128T release notes 5.0.0
128technology/docs pull request #109
Opened 2020-08-14 20:28 UTC by MichaelBaj

2020-09-03 21:52 UTC, ptimmons requested changes

2020-09-03 21:52 UTC, ptimmons commented on docs/cli_reference.md
> +| [`show domain-names`](#show-domain-names) | Display app-id-v2 domain-names used by sessions |
no punctuation

2020-09-03 21:52 UTC, ptimmons commented on docs/cli_reference.md
> +| [`show domain-categories`](#show-domain-categories) | Display app-id-v2 domain-name categories used by sessions |
No punctuation

2020-09-03 21:52 UTC, ptimmons commented on docs/cli_reference.md
> +| device-interface | lte device interface (default: all) |
Should probably capitalize LTE throughout this section.

2020-09-03 21:52 UTC, ptimmons commented on docs/cli_reference.md
> +| router | The name of the router for which to display the RIB summary (default: &lt;current router&gt;) |
inconsistent Capitalization in these rows.

2020-09-03 21:52 UTC, ptimmons commented on docs/cli_reference.md
> +| detail | display session-captures in detail |
Inconsistent capitalization

2020-09-03 21:52 UTC, ptimmons commented on docs/cli_reference.md
> +| force | Skip confirmation prompt. Only required when targeting all routers |
Inconsistent capitalization

2020-09-03 21:52 UTC, ptimmons commented on docs/cli_reference.md
> +| router | the router to request STEP information from |
Initial caps

2020-09-24 13:42 UTC, ptimmons requested changes

2020-09-24 13:42 UTC, ptimmons commented on docs/release_notes_128t_5.0.md
> +- **I95-20757** Displaying alarm history within the PLCI via `show events alarm` now supports relative timestamps
PCLI

2020-09-24 13:42 UTC, ptimmons commented on docs/release_notes_128t_5.0.md
> +- **I95-20718** CLI now produces a warning when creating configuration objects with the keywords ("delete", "force", "move", "clone", "all") as their name
PCLI

2020-09-24 13:42 UTC, ptimmons commented on docs/release_notes_128t_5.0.md
> +- **I95-34624** Remove AP driven install from 128T
I recommend spelling out Automated Provisioner

2020-12-07 21:54 UTC, MichaelBaj commented on docs/about_releases.md
> -| [5.0.0](release_notes_128t_5.0.md#release-5.0)   | October 16, 2020   |                    | April 16, 2021     | October 16, 2021   |
Looks like 5.0.0 was removed.

2020-12-07 21:54 UTC, MichaelBaj commented on docs/release_notes_128t_5.0.md
> +
extra line breaks

2020-12-07 21:54 UTC, MichaelBaj commented on docs/release_notes_128t_5.0.md
> +
Empty description and extra line breaks

2020-12-07 21:54 UTC, MichaelBaj commented on docs/release_notes_128t_5.0.md
> +- **I95-32558 In-line Flow Performance Monitoring:** Inline performance metrics have been enhanced to achieve a finer granularity than what is currently available via BFD. Statistics are now collecte
I believe it is "per path, priority, and traffic class".  Please double check with Scott McCulley.

2020-12-07 21:54 UTC, MichaelBaj commented on docs/release_notes_128t_5.0.md
> +
Extra empty lines

2020-12-07 21:54 UTC, MichaelBaj commented on docs/release_notes_128t_5.0.md
> +
missing line break between entries

2020-12-07 21:54 UTC, MichaelBaj commented on docs/release_notes_128t_5.0.md
> +- **I95-35741 [PCLI plugin service commands](cli_reference.md#manage-plugin-install):** Plugin installation and removal is handled through the PCLI.
Suggested rewording:
Plugin lifecycle management can now be managed through the PCLI.

2020-12-07 21:54 UTC, MichaelBaj commented on sidebars.js
> +
Why was this empty line added?

2020-12-07 21:54 UTC, MichaelBaj commented on sidebars.js
> +
Why was this empty line added?

2020-12-08 16:08 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.0.md
> +- **I95-35741 [PCLI plugin service commands](cli_reference.md#manage-plugin-install):** Plugin installation and removal is handled through the PCLI.
edit made.

2020-12-08 16:09 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.0.md
> +
resolved

2020-12-08 16:10 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.0.md
> +
resolved

2020-12-08 16:18 UTC, Chr1st0ph3rTurn3r commented on docs/about_releases.md
> -| [5.0.0](release_notes_128t_5.0.md#release-5.0)   | October 16, 2020   |                    | April 16, 2021     | October 16, 2021   |
resolved

2020-12-08 16:22 UTC, Chr1st0ph3rTurn3r commented on sidebars.js
> +
I add spaces to keep track of what I have re-organized. The spaces don't show up in the published docs, so if anything it is for readability in the markdown.

2020-12-08 16:22 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.0.md
> +- **I95-32558 In-line Flow Performance Monitoring:** Inline performance metrics have been enhanced to achieve a finer granularity than what is currently available via BFD. Statistics are now collecte
We were both wrong. I got the correct info from Scott and am adding it.

2020-12-08 22:26 UTC, MichaelBaj commented on docs/about_releases.md
> +| [5.0.0](release_notes_128t_5.0.md#release-5.0)   | October 16, 2020   |                    | April 16, 2021     | October 16, 2021   |
Release date needs to be updated to 12/18 (at least that's our current projected date)

2020-12-08 22:26 UTC, MichaelBaj commented on docs/sec_adaptive_encrypt.md
> +On a service where most of the traffic is expected to be encrypted, the goal is to identify and encrypt those few sessions that are not. This eliminates the performance penalty of encrypting traffic
suggest changing "penalty" to "overhead"

2020-12-08 22:26 UTC, MichaelBaj commented on docs/sec_adaptive_encrypt.md
> +leaf adaptive-encryption {
Please swap out the yang with actual configuration example.

2020-12-09 23:14 UTC, robert-patterson commented on docs/howto_tune_bfd.md
> +**Dynamic Damping:** Disabled by default. When enabled and the initial `hold-down-time` and `maximum-hold-down-time` values are configured, the 128T routers dynamically adjust the values to ensure th
`hold-down-time` and `maximum-hold-down-time` have default values, so it is not strictly necessary for the user to configure them for the dynamic adjustment to be applied.

When enabled, the 128T router uses the `hold-down-time` and `maximum-hold-down-time` parameters to dynamically adjust the damping timer to ensure that excessive BFD flaps are not affecting the system negatively.

2020-12-15 23:27 UTC, MichaelBaj commented on docs/concepts_STEP.md
> +- **Pinpoint Service Outages:** STEP stores the service and network information in the STEP Repository, providing a whole view of the network at any given moment. Service outages or heat-map views of
Will need to confirm with Markus and Abilash, but this capability will not be present in the first release of STEP.

2020-12-21 21:05 UTC, closed without merging