Revisions to Installation guide content and layout. Table of Contents rearranged for logical flow, topics added.
128technology/docs pull request #120
Opened 2020-09-08 20:01 UTC by Chr1st0ph3rTurn3r

2020-09-08 21:01 UTC, jeffmart commented on docs/intro_creating_bootable_usb.md
> +128 Technology distributes its software as a set of RPM packages, an ISO, or a container. The ISO is most commonly used to stage a system when it does not have an operating system or if the system is
The software, is really a set of applications.

2020-09-09 12:54 UTC, MichaelBaj requested changes

2020-09-09 12:54 UTC, MichaelBaj commented on docs/intro_creating_bootable_usb.md
> +1. Download the ISO for the software version to be loaded onto the USB. Use the [download instructions](intro_downloading_iso.md). This example uses `128T-OTP-4.2.4-1.el7.x86_64.iso`
In your experience, what is your take on explicit examples? Do you find that most understand them to be examples?  How many people incorrectly simply cut-and-paste without thinking?

2020-09-09 12:54 UTC, MichaelBaj commented on docs/intro_downloading_iso.md
> +128 Technology ISOs are available from our public yum servers located at: `https://yum.128technology.com/isos` to users with an active client certificate.
We are migrating away from using certificates in the near future. These guides will need to be updated to reflect those changes. Would it be okay to change this to "those users with an active account"?

2020-09-09 12:54 UTC, MichaelBaj commented on docs/intro_downloading_iso.md
> +The ISO installation media is hosted at the same location as the 128T software packages, in the isos directory. To acquire the ISO, use the `curl` command. Specify the certificate obtained from 128 T
I believe "ISOs" should be capitalized

2020-09-09 12:54 UTC, MichaelBaj commented on docs/intro_downloading_iso.md
I can't seem to comment on an empty file.  You committed `docs/config_test.md`.  That file should be removed.

2020-09-09 12:54 UTC, MichaelBaj commented on docs/intro_installation.md
> + - Interactive ISO
This can be made into links to the other documents that you broke out (e.g., `[Installing from 128T Installer](intro_installation_installer.md)`)

2020-09-09 12:54 UTC, MichaelBaj commented on docs/intro_installation_bootable_media.md
> +Note: Because not all hardware has video support, booting to console is the default (to account for the fact that a console user may not be able to select an option). The default option is selected a
Suggest using admonitions for notes, etc.

:::note
text
:::

2020-09-09 13:02 UTC, jeffmart requested changes
Minor changes requested.

2020-09-09 15:44 UTC, Chr1st0ph3rTurn3r commented on docs/intro_creating_bootable_usb.md
> +1. Download the ISO for the software version to be loaded onto the USB. Use the [download instructions](intro_downloading_iso.md). This example uses `128T-OTP-4.2.4-1.el7.x86_64.iso`
When an example is provided that is not CLEARLY a dummy link, most people will cut and paste. Unless we want to provide a legitimate example, we should either not provide anything, or make it clear that they need to provide the necessary information, i.e., <link-to-active.release.x86_64.iso>

2020-09-09 15:46 UTC, Chr1st0ph3rTurn3r commented on docs/intro_downloading_iso.md
> +128 Technology ISOs are available from our public yum servers located at: `https://yum.128technology.com/isos` to users with an active client certificate.
I agree with this, and will update accordingly.

2020-09-09 18:34 UTC, Chr1st0ph3rTurn3r commented on docs/intro_downloading_iso.md
> +1. Open the browser and navigate to the Control Panel.
I'll change it to settings for now, and we can open a task to revise the procedure.

2020-09-09 18:36 UTC, Chr1st0ph3rTurn3r commented on docs/intro_downloading_iso.md
> +Your client certificate is provided to you via email, installed on your 128 Technology routers, and allows you to download software updates from our yum servers.
update made.

2020-09-09 18:52 UTC, Chr1st0ph3rTurn3r commented on docs/intro_downloading_iso.md
> +The ISO installation media is hosted at the same location as the 128T software packages, in the isos directory. To acquire the ISO, use the `curl` command. Specify the certificate obtained from 128 T
I capitalized it, but is it the name of the directory? and is the actual name in lower case? If so, then it should be in lower case, but shown in courier font.

2020-09-09 19:31 UTC, MichaelBaj commented on docs/intro_downloading_iso.md
> +The ISO installation media is hosted at the same location as the 128T software packages, in the isos directory. To acquire the ISO, use the `curl` command. Specify the certificate obtained from 128 T
Sorry, I didn't realize it was referring to the directory.  In that case it should remain lowercase.

2020-09-09 20:26 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_bootable_media.md
> +Note: Because not all hardware has video support, booting to console is the default (to account for the fact that a console user may not be able to select an option). The default option is selected a
updated

2020-09-09 20:42 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation.md
> + - Zero Touch Provisioning (ZTP) ISO Image
removed

2020-09-09 20:42 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation.md
> + - Interactive ISO
updates made

2020-09-09 22:39 UTC, MichaelBaj approved these changes

2020-09-10 12:48 UTC, jeffmart approved these changes

2020-09-10 13:01 UTC, merged