Create documentation for new dns-cache feature
128technology/docs pull request #122
Opened 2020-09-15 20:45 UTC by agrawalkaushik

The `redirect-domain` and `block-domain` configuration are added to expose more
of the dns-cache functionality to the end user.

DOCS-150 #time 10m

2020-09-15 20:54 UTC, MichaelBaj submitted a review, later dismissed

2020-09-15 20:54 UTC, MichaelBaj commented on docs/plugin_dns_cache.md
> +                    address  192.168.8.8
Based on the introductory paragraph, this `address` is the address of another DNS server and _not_ the address used in an A record response, correct?

2020-09-16 02:15 UTC, agrawalkaushik commented on docs/plugin_dns_cache.md
> +                    address  192.168.8.8
correct, I made it a `192.168` address to signify a private network

2020-09-16 12:20 UTC, MichaelBaj approved these changes

2020-09-16 13:26 UTC, ptimmons requested changes

2020-09-16 13:26 UTC, ptimmons commented on docs/plugin_dns_cache.md
> +| 1.1.0, 2.1.0 | `dns-cache > redirect-domains` and `dns-cache > block-domains` was introduced |
were introduced

2020-09-16 13:26 UTC, ptimmons commented on docs/plugin_dns_cache.md
> +                redirect-domains  www.some-private-domain.com
recommend you leave off "www" and just leave it as some-private-domain.com

2020-09-16 13:26 UTC, ptimmons commented on docs/plugin_dns_cache.md
> +In some deployments you may want to redirect selected domains to a different upstream DNS server. For example, the `redirect-domains` configuration shown below can be used to redirect private domain
Recommended text:
The DNS cache plugin will send all requests it processes to the list of servers provided in its configuration. Generally, these are configured as public DNS servers. However, many enterprises commonly host their own authoritative name server for their own domain (e.g., some-private-domain.com). The `redirect-domains` configuration lets administrators specify a distinct DNS server for a given domain, and 128T will use this when issuing queries for any host within that domain.

2020-09-16 16:27 UTC, MichaelBaj approved these changes

2020-09-16 17:23 UTC, jeffmart commented on docs/plugin_dns_cache.md
> +
I think we should identify the issue being addressed instead of how we implemented the change for the end user. The end user may not be aware of the implementation but may see that the initial installation of the plugin did not update the configuration. Same would apply for below.

2020-09-16 22:19 UTC, jeffmart approved these changes

2020-09-17 12:57 UTC, MichaelBaj approved these changes

2020-09-17 14:25 UTC, merged