Clarifying how to disable Secure Boot is in the VM
128technology/docs pull request #132
Opened 2020-09-25 02:00 UTC by mendezcirera

Clarifying how to disable Secure Boot is in the VM

2020-09-25 13:01 UTC, MichaelBaj approved these changes

2020-09-25 13:12 UTC, Chr1st0ph3rTurn3r reviewed
Two minor edits in bold. Rather than "uncheck" use "deselect", and capitalize Hardware in "Customize Hardware" - _Unless_ the section in the UI is not capitalized. Callouts should always match what the user sees.

When deploying 128T on VMware ESXi release 6.7 (or newer), Secure Boot must be disabled when the Virtual Machine is created (New Virtual Machine wizard). To disable it, **deselect** "Secure Boot (EFI boot only)" found in the tab "VM Options" within the "Customize **Hardware**" section.

2020-09-25 16:10 UTC, MichaelBaj requested changes
Please address Chris' comments.

2020-09-29 20:41 UTC, mendezcirera commented
> Please address Chris' comments.

I addressed Chris' comments. Let me know if you need anything else.

Thanks!

2020-09-29 20:45 UTC, MichaelBaj approved these changes

2020-10-05 13:41 UTC, Chr1st0ph3rTurn3r approved these changes

2020-10-05 13:51 UTC, merged