Remove references to dynamic nat-pool and destination-nat pools from …
128technology/docs pull request #133
Opened 2020-09-25 15:52 UTC by agrawalkaushik

…documentation

- Those concepts were in the functional spec but only the static source-nat-pool was ever
implemented. The documentation has been corrected to reflect that.

2020-09-25 16:17 UTC, MichaelBaj submitted a review, later dismissed

2020-09-25 16:56 UTC, Chr1st0ph3rTurn3r commented on docs/config_nat.md
> +A static NAT binding can be configured by creating a `authority > router > nat-pool` object and assigning it to a network-interface.  The following rules and constraints will apply to this configurat
...creating an 'authority>router..."

2020-09-25 17:03 UTC, Chr1st0ph3rTurn3r commented on docs/config_nat.md
> +Shared NAT pools provisioned on a HA interface that encounters a failover, the 128T software puts the interface in recovery mode to recover all sessions. At the end of the recovery period, all non-di
**For** shared NAT pools provisioned on **an** HA interface that encounters a failover, the 128T software **will put** the interface **into** recovery mode to recover all sessions. At the end of the recovery period all non-discovered ports **(delete as)** designed as free are returned to the NAT pool.

2020-09-25 17:15 UTC, Chr1st0ph3rTurn3r commented on docs/config_nat.md
> +    * Only the first IP pool is used and hash is applied to create a session. The remainder of the matches are discarded
Combine this with the line above:
If more than one IP pool has a matching tenant, only the first IP pool is used and the hash is applied to create a session. The remainder of the matches are discarded.

2020-09-25 17:17 UTC, Chr1st0ph3rTurn3r commented on docs/config_nat.md
> +The tenant matching rules will apply to sub-tenants as well. For example, if an IP pool allows tenant engineering; traffic with source tenant lab.engineering will also match the pool.
...if an IP pool allows tenant engineering**, then** traffic with source tenant...

2020-09-25 17:22 UTC, Chr1st0ph3rTurn3r requested changes
General Editorial note: For bulleted or numbered lists, they should either all have punctuation or all not have punctuation. So if one bullet has a sentence with a comma, then it should end with a period, and all other items in all the lists should have the appropriate punctuation (period, colon, etc.).

2020-09-27 11:28 UTC, ptimmons submitted a review, later dismissed
Nothing beyond what Chris has already identified.

2020-10-01 12:23 UTC, MichaelBaj approved these changes

2020-10-03 11:50 UTC, ptimmons approved these changes

2020-10-05 13:39 UTC, Chr1st0ph3rTurn3r approved these changes

2020-10-05 13:40 UTC, merged