Add Installer (3.0.0) and Initializer (5.1.0) docs from i95
128technology/docs pull request #135
Opened 2020-09-25 16:39 UTC by ian-h-chamberlain

References: DOCS-120, DOCS-154, IN-264, I95-37431

Includes:
* Initializer 5.1.0 CLI document
* Initializer 5.1.0 preferences schema document
* Installer 3.0.0 CLI document
* Installer 3.0.0 preferences schema document

If it's preferred, I can remove the initializer documents from this PR and add them back once 5.1.0 is closer to release. As it stands, I don't think there are huge (possibly any) differences between the 5.0.0 and 5.1.0 preference schemas, but the infrastructure to generate documentation is only present in 5.1.0. If desired I can probably hack it together to generate 5.0.0 documentation and deliver that instead.

Regarding versioning – should these documents be versioned the same way as release notes are? Or is it acceptable to always document the latest released version, since that is the general recommendation for using the Installer?

Please note the preferences file documents are auto-generated. There is _some_ customization possible but it is more limited.
Both CLI reference documents are hand-written, please review accordingly.

2020-09-25 17:46 UTC, Chr1st0ph3rTurn3r commented on docs/initializer_preferences.md
> +**enum**: the value of this property must be equal to one of the following values:
**The** value... (capitalization)

2020-09-25 18:40 UTC, Chr1st0ph3rTurn3r submitted a review, later dismissed

2020-09-27 11:42 UTC, ptimmons requested changes

2020-09-27 11:42 UTC, ptimmons commented on docs/initializer_cli_reference.md
> +:::note
I don't think it's necessary to make this a :::note. It should just be the preamble of the document.

2020-09-27 11:42 UTC, ptimmons commented on docs/initializer_cli_reference.md
> +```sh
this should either be inline (as `initialize128t`) or the sample text should include the Linux prompt. Probably go with the former.

2020-09-27 11:42 UTC, ptimmons commented on docs/initializer_cli_reference.md
> +`sudo systemctl`:
rather than repeat the info, perhaps just link to: https://docs.128technology.com/docs/intro_installation/#stopping-the-128t-routing-software

2020-09-27 11:42 UTC, ptimmons commented on docs/initializer_cli_reference.md
> +Follow the on-screen prompts to complete the initialization process.
does this complement or replace the information here?
https://docs.128technology.com/docs/intro_installation_installer#initialize-the-128t-node

2020-09-27 11:42 UTC, ptimmons commented on docs/installer_cli_reference.md
> +:::note
Remove :::note and make it document preamble.

2020-09-27 11:42 UTC, ptimmons commented on docs/installer_cli_reference.md
> +### Interactive Mode
Should be consistency checked against: https://docs.128technology.com/docs/intro_installation_installer#install-using-128t-installer

2020-09-28 15:51 UTC, ian-h-chamberlain commented on docs/installer_cli_reference.md
> +### Interactive Mode
Added a link to that section for step-by-step instructions

2020-09-28 15:51 UTC, ian-h-chamberlain commented on docs/initializer_cli_reference.md
> +Follow the on-screen prompts to complete the initialization process.
Added a link to that section for step-by-step instructions

2020-09-28 20:51 UTC, Chr1st0ph3rTurn3r commented on docs/installer_cli_reference.md
> +local repository, after which it will be available for future installation and/or
future installation **and* upgrades... remove the /or.

2020-09-28 20:54 UTC, Chr1st0ph3rTurn3r commented on docs/installer_cli_reference.md
> +128T ISO file, then mount it and save all of its software to the local repository.
With this option, the Installer will attempt **to** search the local filesystem for a 128T ISO file, mount it, and save the contents to the local repository. (delete and, add punctuation, and change text a bit)

2020-09-28 20:57 UTC, Chr1st0ph3rTurn3r requested changes
couple minor text changes.

2020-09-29 20:45 UTC, MichaelBaj approved these changes

2020-10-01 15:27 UTC, ptimmons approved these changes

2020-10-05 13:44 UTC, Chr1st0ph3rTurn3r approved these changes

2020-10-05 14:02 UTC, merged