Docs 153 156
128technology/docs pull request #136
Opened 2020-09-29 20:40 UTC by Chr1st0ph3rTurn3r

Please review: Restructured the Installation section, merged Hardware and OS requirements sections, merged OTP and ZTP sections, added initializer info to Interactive ISO install. 
In the future I will create smaller reviews so not to bury reviewers in work.

2020-09-29 20:50 UTC, MichaelBaj commented
This is the error output from the build.  Looks like you failed to include the `intro_install_initializer_role.png` image.

```
./docs/intro_installation_bootable_media.md
249Error: Image static/img/intro_install_initializer_role.png used in docs/intro_installation_bootable_media.md not found.
250    at async Promise.all (index 2)
251 @ ./.docusaurus/registry.js 1:9537-9607 1:9393-9484
252 @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
253 @ ./.docusaurus/routes.js
254 @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
255 @ multi ./node_modules/@docusaurus/core/lib/client/clientEntry.js./docs/intro_installation_installer.md
```

2020-09-30 00:41 UTC, MichaelBaj requested changes

2020-09-30 00:41 UTC, MichaelBaj commented on sidebars.js
> +      "intro_new_otp_iso_install",
Placeholder name I presume.

2020-09-30 00:41 UTC, MichaelBaj commented on docs/intro_new_otp_iso_install.md
> +---
Because this is embedding javascript, it should have the .mdx extension.  I don't know why as .md seems to work just fine.  It is stated plainly on the Docusaurus website that it should follow that convention. I trust that they put that language there for a reason (because no one _ever_ makes documentation bugs ;) ).

2020-09-30 00:41 UTC, MichaelBaj commented on docs/intro_new_otp_iso_install.md
> +128 Technology has a software-driven framework for rapid and dynamic deployment of network nodes across the enterprise using One Touch Provisioning (OTP). The software was architected from the ground
Suggest removing "from the ground up" as that is an internal reverence as compared to the interactive ISO.

2020-09-30 00:41 UTC, MichaelBaj commented on docs/intro_new_otp_iso_install.md
> +### 5. Reboot
Jeff, I know Tyler is rewriting the QuickStart process to be more efficient and skips several of these unnecessary restarts...

2020-09-30 00:41 UTC, MichaelBaj commented on docs/intro_new_otp_iso_install.md
> +In addition to the above steps, the Bootstrap utility supports executing pre- and post- scriptlets on a USB drive for further customization of the platform. The scriptlets will be executed as the fir
I think this section would benefit from some useful examples of why these scriptlets are useful.

2020-09-30 15:34 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_bootable_media.md
> +7. On the **Anonymous Data Collection** screen, select either **Accept** or **Disable** to enable or disable the RoadRunner process that measures the health of your 128T router and components.
Changed to: "If presented with the **Anonymous Data Collection** screen, select either **Accept** or **Disable** to enable or disable the process that measures the health of your 128T router and components." 
The questions I have are, how old is older? And how often will customers be installing older versions? My guess is rarely. We can remove the statement completely if necessary.

2020-09-30 15:53 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_bootable_media.md
> +5. The **Advanced** button allows you to specify the number of CPU cores to be allocated for running your 128T routing software.
Added info to the exisiting admonition, to prevent "clutter". I'm willing to look at the necessity of creating a second note to draw attention.

2020-09-30 15:55 UTC, Chr1st0ph3rTurn3r commented on sidebars.js
> +      "intro_new_otp_iso_install",
Yes, I'll change it once I know we do not need to go back to the old file for any reason.

2020-09-30 15:56 UTC, Chr1st0ph3rTurn3r commented on docs/intro_new_otp_iso_install.md
> +---
Yeah, and I'm not sure why we need that diagram to be brought in using Javascript. If we move a copy to the images folder, we can source it directly. Is it a flowchart that may change and is used in another publication?

2020-09-30 15:58 UTC, Chr1st0ph3rTurn3r commented on docs/intro_new_otp_iso_install.md
> +128 Technology has a software-driven framework for rapid and dynamic deployment of network nodes across the enterprise using One Touch Provisioning (OTP). The software was architected from the ground
removed.

2020-09-30 15:59 UTC, Chr1st0ph3rTurn3r commented on docs/intro_new_otp_iso_install.md
> +In addition to the above steps, the Bootstrap utility supports executing pre- and post- scriptlets on a USB drive for further customization of the platform. The scriptlets will be executed as the fir
Can you point me at the person to supply this info?

2020-09-30 15:59 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation.md
> +To properly deploy the 128 Technolgy system, you must first install and configure the Conductor. Once the Conductor is installed and configured, the router software can be installed on one or many sy
Yes, changed accordingly.

2020-09-30 16:00 UTC, Chr1st0ph3rTurn3r commented on docs/intro_downloading_iso.md
>  ### Listing Available ISOs from the Command Line
Isn't Artifactory for 5.0? I will make sure it is updated for 5.x.

2020-09-30 16:48 UTC, MichaelBaj approved these changes

2020-09-30 16:48 UTC, MichaelBaj commented on docs/intro_installation_bootable_media.md
> +7. If presented with the **Anonymous Data Collection** screen, select either **Accept** or **Disable** to enable or disable the process that measures the health of your 128T router and components.
Confirmed that RoadRunner was removed in 4.5.0.
I like your new wording. I leave it to you if you want to reference specific versions in this list item.

2020-09-30 16:50 UTC, MichaelBaj commented
You have two broken links to files:

```
Getting links from: http://localhost:34689/docs/intro_creating_bootable_usb
518├─BROKEN─ http://localhost:34689/docs/intro_installation_otp_iso.md (HTTP_404)
519├───OK─── https://rufus.akeo.ie/downloads/
520├───OK─── https://www.pcsteps.com/1461-create-linux-installation-usb-dvd/
521Finished! 196 links found. 193 excluded. 1 broken.
522
523Getting links from: http://localhost:34689/docs/intro_installation_bootable_media
524├─BROKEN─ http://localhost:34689/docs/intro_installation_otp_iso.md (HTTP_404)
```

Are you able to click through the build failure to see these issues yourself?

2020-09-30 18:01 UTC, MichaelBaj approved these changes

2020-10-07 17:03 UTC, MichaelBaj requested changes

2020-10-07 17:03 UTC, MichaelBaj commented on docs/intro_getting_started.md
> +## Service and Topology Exchange Protocol (STEP)
We don't have STEP in product yet. This section should be removed for the time being.

2020-10-07 17:16 UTC, Chr1st0ph3rTurn3r commented on docs/intro_basic_conductor_config.md
> +The 128T Conductor is a 128T instance that is used to manage the 128T Routers you configure within the same Authority. It offers centralized administration, provisioning, monitoring, and analytics.
added.

2020-10-07 17:38 UTC, Chr1st0ph3rTurn3r commented on sidebars.js
> -    "Introduction": [
Hmmm, that wasn't supposed to change. Returned to Introduction.

2020-10-07 18:39 UTC, Chr1st0ph3rTurn3r commented on docs/intro_basic_conductor_config.md
> +### Configure the Web Server as a Service
Can you point me at some documentation or a person to help correct this info?

2020-10-07 18:40 UTC, Chr1st0ph3rTurn3r commented on docs/intro_basic_router_config.md
> +### Configure the Node Interface
I broke out the steps to more clearly identify WAN and LAN procedures.

2020-10-07 18:41 UTC, Chr1st0ph3rTurn3r commented on docs/intro_basic_router_config.md
> + 	Scroll down to the Service Routes and Verify the Service Routes that you have on the seabo1 Router. Why is this blank??
Edited the procedure.

2020-10-07 18:42 UTC, Chr1st0ph3rTurn3r commented on docs/intro_creating_bootable_usb.md
> +### Disk Cloning
resolved.

2020-10-07 18:42 UTC, Chr1st0ph3rTurn3r commented on docs/intro_getting_started.md
> +## Service and Topology Exchange Protocol (STEP)
removed

2020-10-08 19:41 UTC, MichaelBaj approved these changes

2020-10-14 20:22 UTC, ian-h-chamberlain approved these changes

2020-10-14 20:22 UTC, ian-h-chamberlain commented on sidebars.js
> +      "intro_installation_installer",
I assume the Installer installation document is being moved since we want to encourage users to use other processes like ISO and ZTP?

2020-10-14 20:22 UTC, ian-h-chamberlain commented on docs/intro_ztp.md
If you want to prevent it from being rendered this can be a comment like 
```md
<!-- This section will either be absorbed into a different chapter, or removed -->
```

2020-10-15 15:57 UTC, jeffmart commented on docs/intro_getting_started.md
> +The 128T Conductor is a centralized management and policy engine that provides orchestration, administration, zero-touch provisioning, monitoring, and analytics for distributed 128T Session Smart Rou
are we keeping "zero-touch" in?

2020-10-16 16:18 UTC, Chr1st0ph3rTurn3r commented on docs/intro_ztp.md
Topic/file removed from the guide.

2020-10-16 16:19 UTC, Chr1st0ph3rTurn3r commented on docs/intro_getting_started.md
> +The 128T Conductor is a centralized management and policy engine that provides orchestration, administration, zero-touch provisioning, monitoring, and analytics for distributed 128T Session Smart Rou
removed

2020-10-16 18:20 UTC, ian-h-chamberlain submitted a review, later dismissed

2020-10-28 16:27 UTC, ian-h-chamberlain approved these changes

2020-10-29 17:44 UTC, MichaelBaj approved these changes

2020-10-29 18:37 UTC, merged