updated for 4..3.10; new issues 37650, 37660, 37680, and revised desc…
128technology/docs pull request #143
Opened 2020-10-15 19:18 UTC by Chr1st0ph3rTurn3r

…ription of 36927.

2020-10-15 19:26 UTC, MichaelBaj requested changes

2020-10-15 19:26 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +- **I95-37680** nodeMonitor process may fault on shutdown.
`nodeMonitor process may fault on shutdown of 128T`

2020-10-15 19:26 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +- **I95-37650** Clickjacking vulnerability exists if the application allows content to be loaded inside a frame of an attacker-controlled webpage.
`The 128T web UI incorrectly supports being embedded as an iFrame within another page`

2020-10-15 19:45 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37680** nodeMonitor process may fault on shutdown.
changed

2020-10-15 19:45 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37650** Clickjacking vulnerability exists if the application allows content to be loaded inside a frame of an attacker-controlled webpage.
changed

2020-10-15 19:47 UTC, MichaelBaj approved these changes

2020-10-20 13:13 UTC, MichaelBaj submitted a review, later dismissed

2020-10-20 20:05 UTC, jeffmart approved these changes

2020-10-20 20:07 UTC, MichaelBaj approved these changes

2020-10-20 20:08 UTC, merged