Added IN-344, change the 2.6.2 update to define as issues fixed inste…
128technology/docs pull request #144
Opened 2020-10-16 14:28 UTC by jeffmart

Update for the 2.6.3 installer for the rpmdb detection operation.

2020-10-16 14:30 UTC, MichaelBaj approved these changes

2020-10-16 15:05 UTC, ian-h-chamberlain requested changes

2020-10-16 16:22 UTC, Chr1st0ph3rTurn3r approved these changes
I agree with Ian's edits.

2020-10-16 18:16 UTC, jeffmart commented on docs/release_notes_128t_installer_2.6.md
> +- **IN-344** rpmdb corruption detection operation may fail on slower systems resulting in a node asset presisting in a connected state
Corrected typo and added "Unable to repair RPM database" as possible failure output.

2020-10-16 18:16 UTC, jeffmart commented on docs/release_notes_128t_installer_2.6.md
> +  _**Cause:**_ The rpm operation on lower end system may exceed the time defined, resulting in a False negative responce for a corrupted rpm database. An example of a lower end system is a 2 Core 4G
Corrected the typo/cap issues

2020-10-16 18:19 UTC, ian-h-chamberlain approved these changes

2020-10-16 18:46 UTC, Chr1st0ph3rTurn3r approved these changes

2020-10-19 17:50 UTC, MichaelBaj approved these changes

2020-10-19 18:55 UTC, merged