Release notes 4.3.11
128technology/docs pull request #146
Opened 2020-11-05 21:58 UTC by Chr1st0ph3rTurn3r

2020-11-05 22:10 UTC, MichaelBaj requested changes

2020-11-05 22:10 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +- **I95-35567 Weak Password Policy.** New restrictions on password properties have been added to ensure strong passwords.
Is this new styling you are trying to bold more than just the issue id?

2020-11-05 22:10 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +- **I95-37642** 128T GUI does not provide the option for a "User" to change their own password.
Refer to the SIRT announcement for some headline usage on these issues.

2020-11-06 20:39 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-35567 Weak Password Policy.** New restrictions on password properties have been added to ensure strong passwords.
Yes, the intent is to separate the issue and the resolution.

2020-11-09 17:40 UTC, MichaelBaj requested changes
You said you will be adding additional language throughout the docs pages that speaks to the changes that Max noted in his other document. I expected that to be part of this PR as well.

2020-11-09 17:40 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +- **I95-37225 Head End Routers disconnect from their Conductors.** Improved the handling of clock drift between multiple worker cores within the datapath.
"head-end" ?

2020-11-09 17:40 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +- **I95-37643 Vertical Privilege Escalation.** Account privileges have been reviewed and updates have been made to remediate this vulnerability.
Instead of "vertical privilege escalation", "Accounts with the role of 'User' access to plugin REST API resources which should only be available to accounts with the role of 'Administrator'".

2020-11-09 17:40 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +- **I95-37644/I95-37809 SQL Injection Vulnerability.** This vulnerability has been addressed, and fixes put in place to prevent SQL injection attacks.
Instead of "SQL Injection Vulnerability", "Analytics backend requests do not adhere to strict schema"

2020-11-09 17:40 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +- **I95-37642** 128T GUI does not provide the option for a "User" to change their own password.
This one does not have a "bold headline message"

2020-11-09 17:40 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +- **I95-37645 Improper Restriction of excessive authentication attempts.** The user is now locked out after three failed login attempts.
Suggestion, remove "Improper"

2020-11-09 17:40 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +- **I95-37647 Query String Parameter in HTTPS Request.** Any security vulnerability has been addressed.
Suggested replacement: "Server-Sent-Events pass values in the clear for some internal request URIs"

2020-11-09 17:40 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +- **I95-37650 Clickjacking Vulnerability.** The Graphical User Interface has been analyzed and any security vulnerabilities related to clickjacking have been resolved.
Suggested replacement: "128T GUI is allowed to be placed within an i-frame"

2020-11-09 17:40 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +- **I95-37651 Unrestricted File Upload.** Restrictions are in place that make it impossible to import or upload malicious files.
"Restrictions are in place that make it impossible to import or upload files that do not match tar.gz format."

2020-11-10 14:08 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37643 Vertical Privilege Escalation.** Account privileges have been reviewed and updates have been made to remediate this vulnerability.
updated

2020-11-10 14:08 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37644/I95-37809 SQL Injection Vulnerability.** This vulnerability has been addressed, and fixes put in place to prevent SQL injection attacks.
updated

2020-11-10 14:08 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37642** 128T GUI does not provide the option for a "User" to change their own password.
Updated

2020-11-10 14:09 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37645 Improper Restriction of excessive authentication attempts.** The user is now locked out after three failed login attempts.
updated

2020-11-10 14:12 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37647 Query String Parameter in HTTPS Request.** Any security vulnerability has been addressed.
updated

2020-11-10 14:13 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37650 Clickjacking Vulnerability.** The Graphical User Interface has been analyzed and any security vulnerabilities related to clickjacking have been resolved.
updated

2020-11-10 14:14 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37651 Unrestricted File Upload.** Restrictions are in place that make it impossible to import or upload malicious files.
updated

2020-11-10 14:16 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37225 Head End Routers disconnect from their Conductors.** Improved the handling of clock drift between multiple worker cores within the datapath.
Not sure of a replacement for head-end, so I removed it. I assumed the terminology was 128T specific.

2020-11-10 14:20 UTC, MichaelBaj requested changes

2020-11-10 14:20 UTC, MichaelBaj commented on docs/intro_installation.md
> +The examples listed in this guide generally prefer running commands as a non-root user, except as noted, and prepend commands that must be run as a superuser with sudo. The SSH Root login is no longe
I don't believe that last sentence is necessary.
There is a typo in available. (FYI sublime text has spellchecking built in)
If you do intend to keep the sentence, suggest changing to: "SSH root login is not permitted."

2020-11-10 14:20 UTC, MichaelBaj commented on docs/intro_installation.md
> +Requirements for upgrades now include configuring a user with super user (sudo) privileges. The SSH Root login is no longer available. If the existing version allows SSH Root login, it will be disabl
When it comes to user documentation, I tend to write in the tense wherein the situation was alway present as opposed to reading through history (I could be completely wrong here).
"The SSH Root login is no longer available" - should be "SSH root login is not permitted."
"

2020-11-10 14:20 UTC, MichaelBaj commented on docs/intro_upgrading.md
> +Requirements for upgrades now include configuring a user with super user (sudo) privileges. The SSH Root login is no longer available. If the existing version allows SSH Root login, it will be disabl
Same comment as above.

2020-11-10 14:20 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +- **I95-37225 Head End Routers disconnect from their Conductors.** Improved the handling of clock drift between multiple worker cores within the datapath.
head-end is a term used to refer to a routing aggregation point.

2020-11-10 14:37 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation.md
> +The examples listed in this guide generally prefer running commands as a non-root user, except as noted, and prepend commands that must be run as a superuser with sudo. The SSH Root login is no longe
Max was pretty adamant that we need to make sure the users understand they can no longer use SSH Root, so I don't want to remove the information. I have updated it to use your suggestion, which I agree is a better statement.

2020-11-10 14:52 UTC, MichaelBaj approved these changes

2020-11-10 15:46 UTC, migolnikov requested changes

2020-11-10 15:46 UTC, migolnikov commented on docs/intro_installation.md
> +- Have an entry in /etc/sudoers allowing you to execute Linux shell commands as root (via sudo). Failure to do so may result in the loss of management connectivity to the router.
I would add "the loss of **remote** management ...". Root is still available i user connects via a console cable.

2020-11-10 15:46 UTC, migolnikov commented on docs/intro_installation.md
> +[Requirements for upgrades](intro_upgrading.md) include configuring a user with super user (sudo) privileges. **The SSH Root login is not permitted.** If the existing version allows SSH Root login, i
This statement is misleading. Rather then default user is configured with sudo privileges, we should say a "t128" user is installed with sudo privileges

2020-11-10 15:46 UTC, migolnikov commented on docs/intro_upgrading.md
> +Requirements for upgrades now include configuring a user with super user (sudo) privileges. **SSH Root login is not permitted.** If the existing version allows SSH Root login, it will be disabled dur
I would change "Requirements for upgrades" with "Prerequisites for upgrades"

2020-11-10 15:46 UTC, migolnikov commented on docs/release_notes_128t_4.3.md
> +Upon installation, ensure that there is at least one user on each 128T system that has sudo privileges. Failure to do so may result in the loss of management connectivity to the 128T Networking Platf
loss of **remote** management connectivity

2020-11-10 15:46 UTC, migolnikov commented on docs/release_notes_128t_4.3.md
> +- **I95-37642 A user cannot change their password from the 128T GUI.** A user can now change their 128T GUI password from the web application GUI.
remove GUI. "A user can now change their 128T **GUI** password"
The password is not for GUI only

2020-11-10 15:46 UTC, migolnikov commented on docs/release_notes_128t_4.3.md
> +- **I95-37645 Restriction of excessive authentication attempts.** The user is now locked out after three failed login attempts.
We will lock a user out for 1800 seconds (30 min) after 6 failed consecutive login authentication attempts within a 15 minute window.

Also should we caveat that this is not HA?

2020-11-10 15:46 UTC, migolnikov commented on docs/release_notes_128t_4.3.md
> +- **I95-37646 Password Change does not require current password.** The password change process has been strengthened, and now requires the current password.
should we caveat that if a user forgets his password, nothing can be done to recover the account?

2020-11-10 15:46 UTC, migolnikov commented on docs/release_notes_128t_4.3.md
> +- **I95-37651 Unrestricted File Upload.** Restrictions are in place that make it impossible to import or upload files that do not match tar.gz format.
Should we mention the new limits:
- A max file size of 25 MB
- One upload per user every 15 seconds

2020-11-10 15:46 UTC, migolnikov commented on docs/release_notes_128t_4.3.md
> +- **I95-37652 SSH Follows Weak Security Practices.** Several fixes have been put in place to harden SSH access. Please see the warning regarding SSH Root Login at the top of this page.
we should mention 
- SSH Idle Timeout Interval is 5 minutes. Idle ssh sessions will be logged out after 5 minutes
- We will only allow users in “wheel”, “128t”, “128t-admin”, and “128t-user” groups to ssh in.

2020-11-10 15:46 UTC, migolnikov commented on docs/release_notes_128t_4.3.md
> +- **I95-37824 Ensure that AIDE (Advanced Intrusion Detection Evironment) is installed.** The AIDE package is installed and is a 128T dependency.
At 4am every day we will run the linux aide utility to check the for any noteworthy filesystem changes. We will log any irregularities to the system journal.

2020-11-10 15:46 UTC, migolnikov commented on docs/release_notes_128t_4.3.md
> +------
We will not collect core dumps on certain processes with privilege escalation.

2020-11-10 15:46 UTC, migolnikov commented on docs/release_notes_128t_4.3.md
> +- **I95-37843 Require username and password when updating environmental configuration.** The initializer has been updated to require both a username and password when connnecting to an HA Peer to upd
The initializer has been updated to require both a username and password when installing 128T and configuring it to be a second peer in an HA setup.

2020-11-10 15:52 UTC, MichaelBaj commented
@migolnikov I do believe all of your additional notes are needed, but I don't believe they belong in the release notes.  Those are product-specific behaviors (e.g. a user is locked out after 3 consecutive failed attempts within x time for y minutes). We don't expect customers to refer to release notes for product behavior.  @Chr1st0ph3rTurn3r please incorporate Max's notes into new or existing documentation.

2020-11-10 15:52 UTC, MichaelBaj requested changes
Changed my response from `approved` to `request changes` based on Max's comments.

2020-11-10 15:53 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation.md
> +- Have an entry in /etc/sudoers allowing you to execute Linux shell commands as root (via sudo). Failure to do so may result in the loss of management connectivity to the router.
updated

2020-11-10 16:18 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation.md
> +[Requirements for upgrades](intro_upgrading.md) include configuring a user with super user (sudo) privileges. **The SSH Root login is not permitted.** If the existing version allows SSH Root login, i
updated

2020-11-10 16:19 UTC, Chr1st0ph3rTurn3r commented on docs/intro_upgrading.md
> +Requirements for upgrades now include configuring a user with super user (sudo) privileges. **SSH Root login is not permitted.** If the existing version allows SSH Root login, it will be disabled dur
updated

2020-11-10 16:23 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +Upon installation, ensure that there is at least one user on each 128T system that has sudo privileges. Failure to do so may result in the loss of management connectivity to the 128T Networking Platf
updated

2020-11-10 16:23 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37642 A user cannot change their password from the 128T GUI.** A user can now change their 128T GUI password from the web application GUI.
removed

2020-11-10 16:27 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37843 Require username and password when updating environmental configuration.** The initializer has been updated to require both a username and password when connnecting to an HA Peer to upd
updated

2020-11-10 18:37 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37646 Password Change does not require current password.** The password change process has been strengthened, and now requires the current password.
updated

2020-11-11 14:30 UTC, migolnikov approved these changes

2020-11-11 19:26 UTC, MichaelBaj requested changes

2020-11-11 19:26 UTC, MichaelBaj commented on docs/config_access_mgmt.md
> +As part of a security sweep, several SSH features have been limited, and in the case of SSH Root Login, have been disabled.
"Following industry security best practices, SSH features are limited, and in the case of SSH Root Login, have been disabled."

2020-11-11 19:26 UTC, MichaelBaj commented on docs/config_access_mgmt.md
> +To have root access to the 128T system, ensure that there is at least one user configured on each system with super user (sudo) privileges. Failure to do so may result in the loss of management conne
To permit root access...

2020-11-11 19:26 UTC, MichaelBaj commented on docs/config_access_mgmt.md
> +Prerequisites for installation and upgrades now include configuring a super user in etc/sudoers that is allowed to execute Linux shell commands as root (sudo privileges).
there should be a leading `/` in front of etc

2020-11-11 19:26 UTC, MichaelBaj commented on docs/config_access_mgmt.md
> +This is restriction does not apply to High Availability nodes.
Suggested rewording of the note:
User account status is managed independently per node of a HA pair.

2020-11-11 19:26 UTC, MichaelBaj commented on docs/config_access_mgmt.md
> +The `config import` functionality has the following limitations:
Suggest replacing "limitations" with "constraints"

2020-11-11 19:36 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37651 Unrestricted File Upload.** Restrictions are in place that make it impossible to import or upload files that do not match tar.gz format.
added new section linked from the release notes to address this.

2020-11-11 19:36 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37652 SSH Follows Weak Security Practices.** Several fixes have been put in place to harden SSH access. Please see the warning regarding SSH Root Login at the top of this page.
added new section linked from the release notes to address this.

2020-11-11 19:38 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +- **I95-37824 Ensure that AIDE (Advanced Intrusion Detection Evironment) is installed.** The AIDE package is installed and is a 128T dependency.
This seems to be more information than we want to give the user. If it is necessary, I will need some help identifying where to put it.

2020-11-11 19:38 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +------
This seems to be more information than we want to give the user. If it is necessary, I will need some help identifying where to put it.

2020-11-11 19:40 UTC, Chr1st0ph3rTurn3r commented on docs/config_access_mgmt.md
> +The `config import` functionality has the following limitations:
updated

2020-11-11 19:40 UTC, Chr1st0ph3rTurn3r commented on docs/config_access_mgmt.md
> +This is restriction does not apply to High Availability nodes.
updated

2020-11-11 19:40 UTC, Chr1st0ph3rTurn3r commented on docs/config_access_mgmt.md
> +Prerequisites for installation and upgrades now include configuring a super user in etc/sudoers that is allowed to execute Linux shell commands as root (sudo privileges).
updated

2020-11-11 19:40 UTC, Chr1st0ph3rTurn3r commented on docs/config_access_mgmt.md
> +To have root access to the 128T system, ensure that there is at least one user configured on each system with super user (sudo) privileges. Failure to do so may result in the loss of management conne
updated

2020-11-11 19:40 UTC, Chr1st0ph3rTurn3r commented on docs/config_access_mgmt.md
> +As part of a security sweep, several SSH features have been limited, and in the case of SSH Root Login, have been disabled.
updated

2020-11-11 21:12 UTC, MichaelBaj approved these changes

2020-11-12 16:12 UTC, MichaelBaj approved these changes

2020-11-12 17:50 UTC, migolnikov commented on docs/config_access_mgmt.md
> +	- `D`
a and d should be lower case

2020-11-12 17:50 UTC, migolnikov commented on docs/config_access_mgmt.md
> +- Verification of the `*.gz` file format. This does not apply to uploading QuickStart files, Templates, and Custom Charts, as those files are verified before loading.
"This does not apply to uploading QuickStart files, Templates, and Custom Charts, as those files are verified before loading. " should be on a separate line because none of these 3 limitations apply to anything other than config import. Maybe we should even just not even mention it.

2020-11-12 18:42 UTC, Chr1st0ph3rTurn3r commented on docs/config_access_mgmt.md
> +- Verification of the `*.gz` file format. This does not apply to uploading QuickStart files, Templates, and Custom Charts, as those files are verified before loading.
I chose to remove it.

2020-11-12 18:42 UTC, Chr1st0ph3rTurn3r commented on docs/config_access_mgmt.md
> +	- `D`
corrected

2020-11-12 19:26 UTC, MichaelBaj submitted a review, later dismissed

2020-11-12 21:19 UTC, migolnikov approved these changes

2020-11-12 21:48 UTC, MichaelBaj submitted a review, later dismissed

2020-11-13 00:44 UTC, MichaelBaj requested changes

2020-11-13 00:44 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> -- **I95-37643 Accounts with the role of "user" have access to plugin REST API resources.** Account privileges have been reviewed and updates have been made to remediate this vulnerability.
This should not have been removed.

2020-11-13 00:48 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> -- **I95-37643 Accounts with the role of "user" have access to plugin REST API resources.** Account privileges have been reviewed and updates have been made to remediate this vulnerability.
I was wrong.  This should be removed.  This is only applicable to 4.4+

2020-11-13 00:48 UTC, MichaelBaj approved these changes

2020-11-13 14:48 UTC, Chr1st0ph3rTurn3r reviewed
I've made a few editorial changes to the new issues to match the format of the other entries. I'll push those up shortly.

2020-11-13 15:14 UTC, MichaelBaj approved these changes

2020-11-13 16:03 UTC, jeffmart commented on docs/release_notes_128t_4.3.md
> +- **I95-37646 Password Change does not require current password.** The password change process has been strengthened, and now requires the current password.
Addressed in the cli_reference.md section above

2020-11-13 16:03 UTC, jeffmart approved these changes

2020-11-13 16:05 UTC, MichaelBaj approved these changes

2020-11-13 16:24 UTC, merged