Add various DNS app-id enhancements
128technology/docs pull request #147
Opened 2020-11-12 17:38 UTC by agrawalkaushik

Added various enhancements to the `dns-app-id` plugin based on feedback from the field

    - A new toggle for automatically including all builtin applications to keep up-to-date with new apps being added via plugin upgrades.
    - Created a new `dns-app-id` plugin at the authority level to provide means for adding `custom-apps` that apply to all routers in the config with `dns-app-id` enabled.
    - Provide an option to automatically generate services for the configured applications.

DOCS-173 #time 1h

2020-11-12 18:51 UTC, jamesesilvia submitted a review, later dismissed

2020-11-12 19:25 UTC, MichaelBaj requested changes

2020-11-12 19:25 UTC, MichaelBaj commented on docs/plugin_dns_app_id.md
> +The plugin also allow the user to create their own definitions of applications by configuring a set of patterns to be used for matching the application. Each pattern must be a valid regex that will b
Missing 's' in allow: "The plugin also allows ..

2020-11-12 20:02 UTC, Chr1st0ph3rTurn3r requested changes

2020-11-12 20:02 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_dns_app_id.md
> +- **PLUGIN-877** Add support for automatic builtin app inclusion, authority wide custom-apps and automatic service generation
I'm an Oxford comma fan. In a list of items in a sentence, the item before the "and" should have a comma. And there should be a period at the end of the sentence.
"Add support for automatic builtin app inclusion, authority wide custom-apps, and automatic service generation."

2020-11-13 13:46 UTC, MichaelBaj approved these changes

2020-11-13 18:15 UTC, jeffmart approved these changes

2020-11-13 19:00 UTC, Chr1st0ph3rTurn3r approved these changes

2020-11-13 22:19 UTC, merged