First draft of release notes.
128technology/docs pull request #148
Opened 2020-11-16 21:26 UTC by Chr1st0ph3rTurn3r

Mike, can you please run through the resolved issues list to verify it is correct?

2020-11-17 14:14 UTC, MichaelBaj requested changes

2020-11-17 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-34975/I95-34977 CLI changes for `show session`.** The `show session` command has been enhanced to allow the display of a specific session by entering the session-ID. *need to add link to `sho
This is a featurette. It does not need a feature writeup, but a link to a cli_reference with examples is necessary.

2020-11-17 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-35674 Allow Plugin Pages to extend other plugin pages.** You can now use `baseId` to refer to another page that was created by another plugin. *need to add a link to the `baseID` command and
I marked this as exclude from release notes. This is an internal implementation detail.

2020-11-17 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-36490 Provisional Down Interface state.** The `provisional-down` interface state has been added to allow an interface to be brought down for adminstrative purposes. *add CLI command for `prov
This is a feature. This needs a link to cli_reference with examples.

2020-11-17 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-36500 `show-device interface` updates to display provisional status.** Updates made to the show device interface command. *document these in the PCLI sections*
It would be good to provide a link to the existing `show device-interface` (your hyphenation is wrong). Update the example to include provisional status.

2020-11-17 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-37504 Mars returns nothing when expecting values.** (related to 33959?)
I marked this as exclude from release notes

2020-11-17 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-37638 Duplicate Assets showing in CLI.** Resolved an issue where there were duplicate values in the output of `show assets`.
This already exists 4 lines above.  Keep this one.

2020-11-17 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-37842 Inter-router flow move failure for sessoins with same source/dest port (UDP/TCP/ICMP)**
typo in sessions

2020-11-17 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-37855 Configurable Way-point allocation.** **Feature??**
This is a feature. Needs a link to documentation.

2020-11-17 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-37857 Configuration and Value implementation.**
Marked as exclude from release notes

2020-11-17 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +-**I95-37860 Add Closed state to session.**
Marked as exclude from release notes

2020-11-17 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-38075 Make max-way-points dynamically reconfigurable without restarting the 128T.** `max-way-points` is now dynamically configurable. Please see `max way points` for more details.  **Feature?
This is a child of I95-37855.  This one is excluded from release notes.

2020-11-17 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-38139 Remove excessive logging when session is accessed and later deleted(?)**
Marked as exclude from release notes

2020-11-17 14:48 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-37855 Configurable Way-point allocation.** **Feature??**
In discussing with the team on this one, changing the value of this parameter requires a restart of the 128T.  Each node if in a HA pair (does not need to be a simultaneous reboot).

2020-11-19 15:51 UTC, MichaelBaj requested changes

2020-11-19 15:51 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-36122 Provisional Down Interface.** The `provisional-down` interface state has been added to allow an interface to be brought down for adminstrative purposes. *add CLI command for `provisiona
Do you intend on leaving **Feature** in the headline?

2020-11-19 15:51 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-37855 / 38168 Configurable Way-point allocation.** `max-way-points` is now dynamically configurable. Please see `max way points` for more details.  **Feature** requires a reboot after configu
you should remove 38168

2020-11-19 15:51 UTC, MichaelBaj commented on docs/cli_reference.md
> +| by-id| &lt;session-id&gt; |
It would be great to show an example of show session by id.  You can get the example from #field_eng

2020-11-20 13:27 UTC, Chr1st0ph3rTurn3r commented on docs/cli_reference.md
> +| by-id| &lt;session-id&gt; |
updated

2020-11-20 13:27 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +- **I95-37855 / 38168 Configurable Way-point allocation.** `max-way-points` is now dynamically configurable. Please see `max way points` for more details.  **Feature** requires a reboot after configu
removed

2020-11-20 13:27 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +- **I95-36122 Provisional Down Interface.** The `provisional-down` interface state has been added to allow an interface to be brought down for adminstrative purposes. *add CLI command for `provisiona
nope. removed.

2020-11-20 13:27 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +- **I95-38139 Remove excessive logging when session is accessed and later deleted(?)**
done

2020-11-23 21:46 UTC, MichaelBaj requested changes

2020-11-23 21:46 UTC, MichaelBaj commented on docs/api_rest_4.2.0.md
> +`/config/{configStore}/authority/router/{router}/node/{node}/device-interface/{deviceinterface}/provisionalStatus`
Technically these are APIs for 4.5, for which we do not have an API page for.  Those additional API pages need to be added. Unfortunately this API page is out of date.

2020-11-23 21:46 UTC, MichaelBaj commented on docs/config_reference_guide.md
> +The *max-inter-node-way-points* field is configurable at the router level for all inter-node paths. Previously this number was set at 50,000 and was not configurable. Having access to more than 50,00
Suggested rewording:
Having access to more than 50,000 waypoints is useful in cases where the number of concurrent sessions are greater than 50,000 and each of those sessions are required to survive a node failover.

2020-11-23 21:46 UTC, MichaelBaj commented on docs/config_reference_guide.md
> +
Missing table in version history

2020-11-23 21:46 UTC, MichaelBaj commented on docs/config_reference_guide.md
> +The *max-way-points* field is configurable at the adjacency/neighborhood level for each associated inter-router path. Previously this number was set at 50,000 and was not configurable. Having access
Same suggested rewording from above.

2020-11-23 21:46 UTC, MichaelBaj commented on docs/config_reference_guide.md
> +Introduced in version 4.5.3
Missing table in version history.

2020-11-23 22:28 UTC, Chr1st0ph3rTurn3r commented on docs/api_rest_4.2.0.md
> +`/config/{configStore}/authority/router/{router}/node/{node}/device-interface/{deviceinterface}/provisionalStatus`
removed.

2020-11-23 22:37 UTC, Chr1st0ph3rTurn3r commented on docs/config_reference_guide.md
> +The *max-inter-node-way-points* field is configurable at the router level for all inter-node paths. Previously this number was set at 50,000 and was not configurable. Having access to more than 50,00
change made

2020-11-23 22:37 UTC, Chr1st0ph3rTurn3r commented on docs/config_reference_guide.md
> +The *max-way-points* field is configurable at the adjacency/neighborhood level for each associated inter-router path. Previously this number was set at 50,000 and was not configurable. Having access
change made

2020-11-23 22:38 UTC, Chr1st0ph3rTurn3r commented on docs/config_reference_guide.md
> +Introduced in version 4.5.3
Tables are missing throughout the guide. I will add them in 5.0.

2020-11-23 22:38 UTC, Chr1st0ph3rTurn3r commented on docs/config_reference_guide.md
> +
Tables are missing throughout the guide. I will add them in 5.0.

2020-11-23 22:55 UTC, MichaelBaj approved these changes

2020-11-24 17:42 UTC, jeffmart approved these changes

2020-11-25 12:09 UTC, MichaelBaj approved these changes

2020-11-25 13:22 UTC, merged