updating release notes for 4.2.9.
128technology/docs pull request #149
Opened 2020-11-17 16:52 UTC by Chr1st0ph3rTurn3r

2020-11-19 17:48 UTC, MichaelBaj requested changes

2020-11-19 17:48 UTC, MichaelBaj commented on docs/release_notes_128t_4.2.md
> +- **I95-36927 A race condition exists that can cause a fault in the highway process during session setup and configuration changes, that will remove the BGP service route path.** This race condition
Suggested rewording:
A race condition exists that can cause a fault in the highway process during session setup while applying a configuration change that removes BGP over SVR service-route(s).

2020-11-19 20:40 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.2.md
> +- **I95-36927 A race condition exists that can cause a fault in the highway process during session setup and configuration changes, that will remove the BGP service route path.** This race condition
updated.

2020-11-19 20:41 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.2.md
> +
removed

2020-11-19 20:45 UTC, MichaelBaj submitted a review, later dismissed

2020-11-19 21:08 UTC, MichaelBaj submitted a review, later dismissed

2020-11-20 17:52 UTC, jeffmart approved these changes

2020-11-20 17:54 UTC, MichaelBaj approved these changes

2020-11-20 19:14 UTC, merged