Added cloud ha plugin docs
128technology/docs pull request #153
Opened 2020-11-30 15:08 UTC by BenMatase

2020-11-30 17:23 UTC, agrawalkaushik commented on docs/plugin_cloud_ha.md
> + The versions of 128T that support this feature have a `Provides: 128T-device-interface-api(1.0)`, so it can be checked ahead of time by performing a `rpm -q --whatprovides 128T-device-interface-api(
This section should probably be simplified or at least in the trouble shooting section indicate what errors the user will get if the plugin is enabled on a non-compatible version.

2020-12-10 18:06 UTC, BenMatase commented on docs/plugin_cloud_ha.md
> + The versions of 128T that support this feature have a `Provides: 128T-device-interface-api(1.0)`, so it can be checked ahead of time by performing a `rpm -q --whatprovides 128T-device-interface-api(
Let me know if the new approach that I took is better

2020-12-15 14:11 UTC, Chr1st0ph3rTurn3r submitted a review, later dismissed
I made some edits directly to the plugin_cloud_ha.md file. I am fine with other changes to the doc.

2020-12-15 17:29 UTC, agrawalkaushik commented on docs/config_reference_guide.md
> +This section is a reference guide for the elements of the User Interface.
@Chr1st0ph3rTurn3r Not sure if you intended to add this change to this PR. Ideally this should be it's own PR.

2020-12-15 17:37 UTC, Chr1st0ph3rTurn3r commented on docs/config_reference_guide.md
> +This section is a reference guide for the elements of the User Interface.
I believe it was part of an earlier merge with master, not exactly sure how it got pulled into this, but it is fine. It is currently in the 5.0 stream, so it was added a while back.

2020-12-15 18:48 UTC, agrawalkaushik submitted a review, later dismissed

2020-12-15 20:51 UTC, MichaelBaj requested changes

2020-12-15 20:51 UTC, MichaelBaj commented on docs/plugin_cloud_ha.md
> +The 128T-cloud-ha plugin provides High Availability (HA) functionality for the 128T Networking Platform deployed in the cloud. HA for 128T routers in a non-cloud environment uses traditional techniqu
"This plugin utilizes" should be "This plugin uses"

2020-12-15 20:51 UTC, MichaelBaj commented on docs/plugin_cloud_ha.md
> + The router component can only be installed on versions of 128T which support provisional state on device interfaces. This is necessary for the plugin to be able to prevent asymmetrical routing.
Can you provide a link to the documentation for `provisional-state` here?
Since you are referring to the data model construct of "device interfaces" it should be italicized.

2020-12-15 20:51 UTC, MichaelBaj commented on docs/plugin_cloud_ha.md
> +![HA Agent Flow Diagram](/img/cloud-ha-ha-agent-flow-diagram.png)
For future reference I have a module built into the docs repo which supports creating dynamic workflow diagrams. (e.g., https://docs.128technology.com/docs/intro_otp_iso_install#bootstrapping-flow-chart)

2020-12-15 20:51 UTC, MichaelBaj commented on docs/plugin_cloud_ha.md
> +To prevent routing loops, the solution will not update the Azure Route Tables assigned to a subnet that has an activating node's Network Interface.
"Network Interface" should not be capitalized, but should be italicized.

2020-12-15 20:51 UTC, MichaelBaj commented on docs/plugin_cloud_ha.md
> +When the **primary node** becomes unhealthy and the redundant interfaces are operationally down, the Monitoring Agent sends an unhealthy status to the local HA Agent. When the **local node** is deeme
Why are there (??) after "and the local node is healthy"?

2020-12-15 20:51 UTC, MichaelBaj commented on docs/plugin_cloud_ha.md
> +### Split Brain Resolution
Are there any indications/alarms/troubleshooting, etc. to be able to identify a split-brain scenario?

2020-12-15 20:51 UTC, MichaelBaj commented on docs/plugin_cloud_ha.md
> +* Priorities across all members in a group are unique.
This bulleted list would benefit from an introductory sentence.
e.g., The following criteria need to be met in order for the cloud-ha-plugin to take effect:

2020-12-15 20:51 UTC, MichaelBaj commented on docs/plugin_cloud_ha.md
> +* There is at least one functioning forwarding device interface on each of the member nodes.
_device interface_

2020-12-15 20:51 UTC, MichaelBaj commented on docs/plugin_cloud_ha.md
> +Group group1 does not have unique priorities across members: {'BenTestRouter2 test2': '2', 'BenTestRouter test': '2'}
I would scrub this output to have a better example than "BenTestRouter"

2020-12-16 05:56 UTC, BenMatase commented on docs/plugin_cloud_ha.md
> + The router component can only be installed on versions of 128T which support provisional state on device interfaces. This is necessary for the plugin to be able to prevent asymmetrical routing.
I couldn't find any docs section on provisional state, so I linked to the 4.5 release notes section on it. Let me know if that would be better unlinked

2020-12-16 05:57 UTC, BenMatase commented on docs/plugin_cloud_ha.md
> +When the **primary node** becomes unhealthy and the redundant interfaces are operationally down, the Monitoring Agent sends an unhealthy status to the local HA Agent. When the **local node** is deeme
I'm not sure. I think that might be from @Chr1st0ph3rTurn3r . I removed that and cleaned up that part so hopefully it is better

2020-12-16 05:57 UTC, BenMatase commented on docs/plugin_cloud_ha.md
> +### Split Brain Resolution
I added two ways: peer path alarms and state output when both member nodes claim that the remote is unreachable

2020-12-16 05:58 UTC, BenMatase commented on docs/plugin_cloud_ha.md
> +Group group1 does not have unique priorities across members: {'BenTestRouter2 test2': '2', 'BenTestRouter test': '2'}
I removed all references of `ben` in the doc

2020-12-16 18:04 UTC, agrawalkaushik commented on docs/plugin_cloud_ha.md
> + The router component can only be installed on versions of 128T which support provisional state on device interfaces. This is necessary for the plugin to be able to prevent asymmetrical routing.
I think we're missing docs for provisional state. I'll follow with Ryan and TJ and get one written and we can link it at that point.

2020-12-16 19:03 UTC, BenMatase commented on docs/plugin_cloud_ha.md
> + The router component can only be installed on versions of 128T which support provisional state on device interfaces. This is necessary for the plugin to be able to prevent asymmetrical routing.
I removed the release note link in the meantime

2020-12-16 19:32 UTC, agrawalkaushik submitted a review, later dismissed

2020-12-16 20:41 UTC, MichaelBaj approved these changes

2020-12-16 20:43 UTC, Chr1st0ph3rTurn3r approved these changes

2020-12-16 20:43 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_cloud_ha.md
spelling: secondary

2020-12-16 20:46 UTC, MichaelBaj approved these changes

2020-12-16 20:52 UTC, agrawalkaushik approved these changes

2020-12-17 00:43 UTC, jeffmart approved these changes

2020-12-17 02:53 UTC, merged