Added wireguard v1.2.0 release notes
128technology/docs pull request #155
Opened 2020-12-16 03:57 UTC by salegria8

Description

Added release notes for wireguard plugin version 1.2.0. The changes allow wireguard to work with 128T versions 4.3.0 through 4.3.11, 4.5.0 through 4.5.3, and 5.0.0.

JIRA

DOCS-179 #time 10m

2020-12-16 15:31 UTC, agrawalkaushik requested changes

2020-12-16 15:31 UTC, agrawalkaushik commented on docs/plugin_wireguard.md
> +- **PLUGIN-922** Wireguard works with 128T versions 4.3.0 through 4.3.11, 4.5.0 through 4.5.3, and 5.0.0 which install one of the following kernel versions: `3.10.0-1062.9.1`, `3.10.0-1127.18.2`, `3.
We should'nt call out specific releases as otherwise the notes will become stale very quickly. Let's say this instead

```
128T Wireguard solution will now be compatible with multiple kernel versions which cover a majority of 128T releases. The enhancement currently supports the following kernel versions: <fill in the rest>.
```

2020-12-21 21:04 UTC, MichaelBaj requested changes

2020-12-21 21:04 UTC, MichaelBaj commented on docs/plugin_wireguard.md
> +In some upgrade and rollback scenarios, its possible that an older version of module is installed on the router but that version is not compatible. Typically in such scenarios, a new version will be
I believe you are missing "the" between `of` and `module`.

2020-12-21 21:04 UTC, MichaelBaj commented on docs/plugin_wireguard.md
> +  - Before rolling back 128T version, remove all references to `wireguard-profile` from `authority > router > device-interface > network-interface > address`. Once these changes are committed, the wi
missing "the" between `back` and `128T`

2020-12-21 21:12 UTC, MichaelBaj submitted a review, later dismissed

2020-12-21 21:54 UTC, Chr1st0ph3rTurn3r approved these changes

2020-12-21 21:54 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_wireguard.md
> +In some cases, its possible that the version of 128T router is not compatible with wireguard. In such a case you will see the log messages like below in the journal
In some cases, **it is possible**... 
(or it's possible)

2020-12-21 21:54 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_wireguard.md
> +In some upgrade and rollback scenarios, its possible that an older version of the module is installed on the router but that version is not compatible. Typically in such scenarios, a new version will
"In some upgrade and rollback scenarios, **its** possible that an older..." Should be **it is possible**...

2020-12-21 21:54 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_wireguard.md
> +- **PLUGIN-987** The 128T wireguard plugin might cause the 128T rollback to when kernel version changes are incompatible. The following procedure can be applied to work around this limitation
This paragraph is confusing. Is it Plugin 987 that may cause a rollback issue? If so, I suggest stating. "Plugin-987 may cause..." 
Also, "...cause the 128T **to** rollback to **an incompatible kernel version**. The following procedure **may be used to work around this issue.**"

2020-12-21 21:54 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_wireguard.md
> +The process below will cause the wireguard tunnels to be torn down and the peers to disconnect. Please perform the operations during maintainance window only.
Spelling and missing article: "during **a maintenance** window only."

2020-12-21 21:54 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_wireguard.md
> +  - Restore the backup created in the first step. Once the chances are commited, the correct wireguard rpm's will be installed on the router.
Spelling; "Once the **changes** are **committed**...

2020-12-21 23:47 UTC, agrawalkaushik commented on docs/plugin_wireguard.md
> +- **PLUGIN-987** The 128T wireguard plugin might cause the 128T rollback to when kernel version changes are incompatible. The following procedure can be applied to work around this limitation
No the `PLUGIN-287` is the bug to track the rollback issue. The bug will be fixed in a future version and we'll remove the caveat.

2020-12-22 13:46 UTC, MichaelBaj approved these changes

2020-12-22 17:38 UTC, MichaelBaj approved these changes

2020-12-22 17:39 UTC, agrawalkaushik approved these changes

2020-12-22 20:43 UTC, jeffmart approved these changes

2020-12-22 20:43 UTC, merged