Release 5.0 documentation
128technology/docs pull request #156
Opened 2020-12-16 18:30 UTC by Chr1st0ph3rTurn3r

2020-12-16 18:38 UTC, MichaelBaj requested changes

2020-12-16 18:38 UTC, MichaelBaj commented on docs/sec_adaptive_encrypt.md
> +leaf adaptive-encryption {
My suggestion from before was to have this snippet reflect the configuration in the PCLI, not the yang model. We have not been referencing yang in our docs.

2020-12-17 23:15 UTC, Chr1st0ph3rTurn3r commented on docs/sec_adaptive_encrypt.md
> +leaf adaptive-encryption {
updated.

2020-12-18 14:30 UTC, MichaelBaj approved these changes

2020-12-18 14:30 UTC, MichaelBaj commented on docs/about_releases.md
>  | [5.0.0](release_notes_128t_5.0.md#release-5.0)   | December 18, 2020   |                    | April 16, 2021     | October 16, 2021   |
Extra space after 2020

2020-12-18 21:32 UTC, MichaelBaj approved these changes

2020-12-22 18:03 UTC, jeffmart approved these changes

2020-12-22 18:17 UTC, MichaelBaj approved these changes

2020-12-22 19:24 UTC, merged