Add set-hostname doc
128technology/docs pull request #166
Opened 2021-01-15 21:52 UTC by jamesesilvia

Document set-hostname plugin.

2021-01-15 22:15 UTC, Chr1st0ph3rTurn3r submitted a review, later dismissed

2021-01-19 14:02 UTC, MichaelBaj commented on docs/plugin_set_hostname.md
> +Set the system hostname of a 128T node to the default value of `node.router` or define a custom name.
Do you literally mean `node`.`router`? Or is it the representation of {node}.{router}? If it is the latter, can you add the additional sentence to the introduction:

Where `node` and `router` are set to the respective values defined in the configuration

2021-01-19 14:13 UTC, jeffmart submitted a review, later dismissed

2021-01-19 14:28 UTC, MichaelBaj approved these changes

2021-01-19 15:34 UTC, jeffmart approved these changes

2021-01-19 20:34 UTC, agrawalkaushik requested changes

2021-01-19 20:34 UTC, agrawalkaushik commented on docs/plugin_set_hostname.md
> +The plugin confiugration is managed at the node level. If `enabled` is set the hostname will be set to `node.router`, but if `name` is configured, it will be set as the hostname. If `name` is not set
This can benefit from some screen grabs of what the configuration looks like. We've also started including a table showing the config, their defaults etc. Take a look at some of the other plugins for examples.

2021-01-26 16:29 UTC, jamesesilvia commented on docs/plugin_set_hostname.md
> +The plugin confiugration is managed at the node level. If `enabled` is set the hostname will be set to `node.router`, but if `name` is configured, it will be set as the hostname. If `name` is not set
done

2021-01-26 20:53 UTC, MichaelBaj approved these changes

2021-01-28 17:28 UTC, agrawalkaushik approved these changes

2021-01-28 17:36 UTC, merged