test: Bgp vrf
128technology/docs pull request #184
Opened 2021-02-04 15:36 UTC by hadrielk

2021-02-04 16:53 UTC, MichaelBaj requested changes

2021-02-04 16:53 UTC, MichaelBaj commented on docs/concepts_learning_VRF_routes.md
> +Static routes are configured in the respective VRF instance, using the static-route command. For configuration information, see Configuring VRF Static Routes.
"Configuring VRF Static Routes" should be a hyperlink to the other document.

2021-02-04 16:53 UTC, MichaelBaj commented on docs/concepts_learning_VRF_routes.md
> +- In order to exchange VRF routes via BGP, each VRF needs a separate BGP protocol instance and BGP session. This may result in scaling problems when there is a large number of VRFs.
"This may result in scaling problems" is a scary, ill-defined statement. Please get the author of this to quantify the behavior.  e.g., greater than 50 VRFs will require X platform.

2021-02-04 16:53 UTC, MichaelBaj commented on docs/config_vrf_learning.md
> +                    		neighbor-as       3000
Formatting appears incorrect.

2021-02-04 16:53 UTC, MichaelBaj commented on docs/config_vrf_learning.md
> +Need procedure here.
- [ ] Need procedure here.

2021-02-04 16:53 UTC, MichaelBaj commented on docs/config_vrf_learning.md
> +Each Service prefix is matched against the routing table that corresponds to the tenant (using the vrf tenant-name mapping config). If no VRF tenant mapping exists for the tenant, the service prefix
VRF should be capitalized

2021-02-04 19:28 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_learning_VRF_routes.md
> +- In order to exchange VRF routes via BGP, each VRF needs a separate BGP protocol instance and BGP session. This may result in scaling problems when there is a large number of VRFs.
removed statement

2021-02-04 19:28 UTC, Chr1st0ph3rTurn3r commented on docs/config_vrf_learning.md
> +                    		neighbor-as       3000
reformatted

2021-02-04 19:28 UTC, Chr1st0ph3rTurn3r commented on docs/config_vrf_learning.md
> +Need procedure here.
procedure added

2021-02-04 19:28 UTC, Chr1st0ph3rTurn3r commented on docs/config_vrf_learning.md
> +Each Service prefix is matched against the routing table that corresponds to the tenant (using the vrf tenant-name mapping config). If no VRF tenant mapping exists for the tenant, the service prefix
done

2021-02-12 17:43 UTC, MichaelBaj approved these changes

2021-02-12 20:42 UTC, MarkusJork commented on docs/concepts_learning_VRF_routes.md
> +sidebar_lable: Learning VRF routes Via BGP
sidebar_label

2021-02-12 20:42 UTC, MarkusJork commented on docs/config_vrf_learning.md
> +sidebar_lable: VRF Learning via BGP
label

2021-02-12 20:42 UTC, MarkusJork commented on docs/ts_troubleshooting_vrf.md
> +sidebar_lable: Troubleshooting VRF
label

2021-02-12 20:50 UTC, MarkusJork commented on docs/config_vrf_learning.md
> +                    neighbor-as       3000
indentation doesn't look right

2021-02-12 21:26 UTC, Chr1st0ph3rTurn3r commented on docs/config_vrf_learning.md
> +                    neighbor-as       3000
That's odd - in the file neighbor lines up with router-id, and it looks correct in my local build. Not sure why it looks that way in Git.

2021-02-12 21:27 UTC, Chr1st0ph3rTurn3r commented on docs/ts_troubleshooting_vrf.md
> +sidebar_lable: Troubleshooting VRF
Wow three times... I must have been tired.

2021-02-12 21:27 UTC, Chr1st0ph3rTurn3r commented on docs/config_vrf_learning.md
> +sidebar_lable: VRF Learning via BGP
fixed

2021-02-12 21:27 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_learning_VRF_routes.md
> +sidebar_lable: Learning VRF routes Via BGP
fixed.

2021-02-12 21:35 UTC, MarkusJork commented on docs/config_vrf_learning.md
> +                    neighbor-as       3000
There are TAB characters in some of the lines which throw things off

2021-02-16 16:49 UTC, merged