Updated 4.5 release notes with 4.5.5, I95-38833.
128technology/docs pull request #185
Opened 2021-02-05 17:23 UTC by Chr1st0ph3rTurn3r

2021-02-05 17:31 UTC, MichaelBaj requested changes

2021-02-05 17:31 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-38833 BGP is not coming up on a WAN interface with Q-in-Q enabled:** Resolved an issue where a WAN interface with Q-in-Q enabled was incorrectly reading the VLAN tag from the outer VLAN heade
BGP was just a coincidence of the failure mode.  The actual issue has to do with DSCP marking affecting our parser.  The BGP packets were marked with a non-zero DSCP value which meant that we could not properly identify the Q-in-Q packets. Suggested rewording:
I95-38833 Q-in-Q packets are not recognized when packets have non-zero DSCP value.
- you can keep the additional text as is.

2021-02-05 18:14 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +- **I95-38833 BGP is not coming up on a WAN interface with Q-in-Q enabled:** Resolved an issue where a WAN interface with Q-in-Q enabled was incorrectly reading the VLAN tag from the outer VLAN heade
Updated.

2021-02-05 18:16 UTC, MichaelBaj approved these changes

2021-02-08 20:58 UTC, jeffmart approved these changes

2021-02-10 03:22 UTC, merged