Show commands services
128technology/docs pull request #187
Opened 2021-02-12 20:13 UTC by Chr1st0ph3rTurn3r

Please review, especially the command arguments and keywords.

2021-02-16 17:05 UTC, lliu5374 commented on docs/cli_reference.md
> +| 5.1.0   | Detail fields added: Next-hop, Peer, Path-Metrics, Index, Meets-SLA, Reachability-Probes |
same for the two fields here, which should only be in 5.2

2021-02-19 20:16 UTC, lliu5374 approved these changes

2021-02-23 14:43 UTC, cmain approved these changes

2021-02-23 15:03 UTC, jacobbogdanov requested changes

2021-02-23 22:11 UTC, Chr1st0ph3rTurn3r commented on docs/cli_reference.md
> +## `generate config`
changes made

2021-02-23 22:11 UTC, Chr1st0ph3rTurn3r commented on docs/cli_reference.md
> +show config exports [<name>] [verbose] [flat]
removed verbose and the explanation.

2021-02-23 22:11 UTC, Chr1st0ph3rTurn3r commented on docs/cli_reference.md
> +compare config [<old>] [<new>] [<name>]
removed the name argument and clarified.

2021-02-23 22:12 UTC, jacobbogdanov approved these changes

2021-02-24 17:43 UTC, merged