RBAC
128technology/docs pull request #188
Opened 2021-02-19 20:07 UTC by Chr1st0ph3rTurn3r

2021-02-22 14:52 UTC, ian-h-chamberlain approved these changes

2021-02-22 14:52 UTC, ian-h-chamberlain commented on docs/config_RBAC.md
> +The default Administrator role has access to all configuration options, and cannot be removed. From this account, all roles and access are assigned.
Might be worth mentioning the config name for this role is `admin`, unless that's covered somewhere else

2021-02-23 18:47 UTC, migolnikov requested changes

2021-02-23 18:47 UTC, migolnikov commented on docs/config_RBAC.md
> +Role-Based Access Control provides a mechanism for an Administrator to create Access Management Roles that allow specific access to 128T resources such as routers, tenants, and services.
as routers, tenants and services along with other authority level config objects.

2021-02-23 18:47 UTC, migolnikov commented on docs/config_RBAC.md
> +	Resource groups can be assigned to a top-level resource (Authority level) such as a router, a tenant, or a service. The process for assigning a resource group to a service is slightly different than
service and service-policy

2021-02-23 18:47 UTC, migolnikov commented on docs/config_RBAC.md
> +	A Resource Group identifies a set of resources. One or more Resource Groups are assigned to an Access Management Role.
maybe change "a set of resources' to "a set of associated resources"?

2021-02-23 18:47 UTC, migolnikov commented on docs/config_RBAC.md
> +	An Access Management Role identifies the type of user - administrator or user. Roles are assigned capabilities or actions they can perform; read, write, and provision. Provisioning allows users to p
we should go away from concept of user and admin. I would rewrite it as:

An Access Management Role identifies capabilities or actions a user can perform; config read, config write, and provision. Provisioning allows users to perform software lifecycle management duties, such as download software, upgrade existing installations, etc.

2021-02-23 18:47 UTC, migolnikov commented on docs/config_RBAC.md
> +2. Select a resource; a router or a tenant.
not just router or tenant

2021-02-23 18:47 UTC, migolnikov commented on docs/config_RBAC.md
> +7. Assign the Access Management Role to a Resource Group or groups. In the Resource Groups panel, click ADD and select the Resource Group from the drop down.
The logic is reversed. Assign Resource Group(s) to the Access Management Role.

2021-02-23 18:47 UTC, migolnikov commented on docs/config_RBAC.md
> +6. Assign the capabilities for each role. In the Capabilities panel, click ADD and select the capability from the drop down. For example, user roles may only have read access to the resource, where a
Assign capabilities to Access Management Role

2021-02-23 18:47 UTC, migolnikov commented on docs/config_RBAC.md
> +8. Select the specific resources accessible by the Access Management Role. In the Resources panel, click ADD and select resources from the drop down.
This should be marked as Advanced. We do not know how often this will be used, so it's hard for me to say if we should just exclude this from documentation.

2021-02-23 18:47 UTC, migolnikov commented on docs/config_RBAC.md
> +3. On the New Users panel, enter the following:
you should mention that a User can have multiple roles.

2021-02-23 23:52 UTC, Chr1st0ph3rTurn3r commented on docs/config_RBAC.md
> +The default Administrator role has access to all configuration options, and cannot be removed. From this account, all roles and access are assigned.
added

2021-02-23 23:52 UTC, Chr1st0ph3rTurn3r commented on docs/config_RBAC.md
> +Role-Based Access Control provides a mechanism for an Administrator to create Access Management Roles that allow specific access to 128T resources such as routers, tenants, and services.
...resources such as routers, tenants, and services, as well as other Authority-level configuration objects.

2021-02-23 23:56 UTC, Chr1st0ph3rTurn3r commented on docs/config_RBAC.md
> +	Resource groups can be assigned to a top-level resource (Authority level) such as a router, a tenant, or a service. The process for assigning a resource group to a service is slightly different than
done

2021-02-23 23:57 UTC, Chr1st0ph3rTurn3r commented on docs/config_RBAC.md
> +	A Resource Group identifies a set of resources. One or more Resource Groups are assigned to an Access Management Role.
I like that. Done.

2021-02-23 23:59 UTC, Chr1st0ph3rTurn3r commented on docs/config_RBAC.md
> +	An Access Management Role identifies the type of user - administrator or user. Roles are assigned capabilities or actions they can perform; read, write, and provision. Provisioning allows users to p
Done.

2021-02-24 00:01 UTC, Chr1st0ph3rTurn3r commented on docs/config_RBAC.md
> +2. Select a resource; a router or a tenant.
Select an Authority-level resource; for example, a router or a tenant.

2021-02-24 00:05 UTC, Chr1st0ph3rTurn3r commented on docs/config_RBAC.md
> +7. Assign the Access Management Role to a Resource Group or groups. In the Resource Groups panel, click ADD and select the Resource Group from the drop down.
fixed.

2021-02-24 00:06 UTC, Chr1st0ph3rTurn3r commented on docs/config_RBAC.md
> +6. Assign the capabilities for each role. In the Capabilities panel, click ADD and select the capability from the drop down. For example, user roles may only have read access to the resource, where a
done

2021-02-24 00:09 UTC, Chr1st0ph3rTurn3r commented on docs/config_RBAC.md
> +8. Select the specific resources accessible by the Access Management Role. In the Resources panel, click ADD and select resources from the drop down.
reworded to indicate that it is an optional setting. 
"In some cases you may choose to make specific resources accessible to an Access Management Role. This is an optional setting. In the Resources panel, click ADD and select resources from the drop down. "

2021-02-24 00:10 UTC, Chr1st0ph3rTurn3r commented on docs/config_RBAC.md
> +3. On the New Users panel, enter the following:
done

2021-02-24 17:08 UTC, migolnikov approved these changes

2021-02-24 17:08 UTC, migolnikov commented on docs/config_RBAC.md
> +The default Administrator role (`admin`) has access to all configuration options, and cannot be removed. From this account, all roles and access are assigned.
It's important to note that it does not have to be done from "admin" account, but rather from an account of type "admin". So I would reword "From this account, all .." to "From this built in access role, all ..."

2021-02-24 17:36 UTC, Chr1st0ph3rTurn3r commented on docs/config_RBAC.md
> +The default Administrator role (`admin`) has access to all configuration options, and cannot be removed. From this account, all roles and access are assigned.
change made

2021-02-24 17:42 UTC, merged