Documentation 5.1
128technology/docs pull request #191
Opened 2021-02-25 02:17 UTC by Chr1st0ph3rTurn3r

This branch contains several updates for 5.1, most have had preliminary reviews. The current PR is to review the first draft of the release notes.

2021-02-25 15:20 UTC, chaoz0312 commented on docs/howto_config_PPPoE.md
> +        password exit33
`password1` instead of `exit33` since this doc to available to the public?

2021-02-25 16:50 UTC, Chr1st0ph3rTurn3r commented on docs/howto_config_PPPoE.md
> +        password exit33
done

2021-02-25 16:51 UTC, Chr1st0ph3rTurn3r commented on docs/howto_config_PPPoE.md
> +In the event of a disconnection, the `failure` section of `show device-interface` displays the exit code the ppd-exit-reason. The example below shows an authentication failure.
done

2021-02-25 16:51 UTC, Chr1st0ph3rTurn3r commented on docs/howto_config_PPPoE.md
> +        password exit33
done

2021-02-25 16:52 UTC, Chr1st0ph3rTurn3r commented on docs/howto_config_PPPoE.md
> +In situations where there are several connection attempts (for example, consecutive authenication failures), logic is used to back off the reconnect attempts. Failure codes and the intervals between
done

2021-02-25 17:02 UTC, chaoz0312 submitted a review, later dismissed
I have only reviewed `howto_config_PPPoE.md`.

2021-02-25 21:07 UTC, agrawalkaushik requested changes

2021-02-25 21:07 UTC, agrawalkaushik commented on docs/release_notes_128t_5.1.md
> +- **I95-27678 [Send Audit Events to a SYSLOG Server](howto_send_audit_events.md):** Audit and alarm events can now be pushed to syslog and other services via the Monitoring Agent.
The EPIC was called this but I think from release notes perspective its not as interesting. I think we should re-word it as follows:

```
- **I95-27678 [Configurable Audit Events](howto_configure_audit_events.md):** Audit events such as traffic, admin and system can be be configured with the features and also allows the persistence of those events be configurable.
```

2021-02-25 21:07 UTC, agrawalkaushik commented on docs/howto_send_audit_events.md
> +---
This should be re-worked to document how to make the various audit events configurable and control its persistence. We can then use some pieces of this document to show an example of how to send traffic events to a syslog server. I'll re-work this and add a commit to this PR.

2021-02-25 21:44 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-37699 Save tech support on scaled setup has corrupted zip file:** Added a Limit Argument To PCLI show events and Tech Support to resolve this issue.
"**I95-37699 `save tech-support-info` may generate a corrupted zip file on systems that have greater than 10K alarms:** Added a Limit Argument To PCLI show events and Tech Support to resolve this issue. "

2021-02-25 21:44 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-37770 CVE Obfuscator consumes password as a command line argument:** This issue has been resolved.
Instead of "CVE Obfuscator", "Password obfuscator..."

2021-02-25 21:44 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-37826 CIS Compliance: Ensure permissions on bootloader config are configured:** Appropriate permissions are set on bootloader config files.
Drop "CIS Compliance:"

2021-02-25 21:44 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-37848 Properly handle jumbo UDP packet from LTE network:** Resolved an issue where UDP packets larger than interface(network) MTU will cause Rx Error on the LTE interface.
This is a duplicate of I95-37848.  As per my comment above, we should not be documenting duplicates.

2021-02-25 21:44 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-38393 Minions Cannot Get Past Connected State:** Resolved an issue where assets could become stuck in Connected state.
I refrain from using the term "minion" unless specifically referring to salt-minion.  In this case, the customer would only know that the router is not in the correct state.  suggested rewording.
"Router cannot get passed connected state..."

2021-02-25 21:44 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-38458 Handle PCLI model files on the upgrade:** Resolved an issue where caching errors prevented 128T from starting.
"PCLI fails to start after upgrade...."

2021-02-25 21:44 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-38500 CVE Medium: binutils (CESA-2018:3032), binutils (CESA-2019:2075):** Added binutils to deprecated packages.
I see now regarding the CVE severity. I think I like providing the severity, but the CVE is valuable as well for the customer to know how important it is to them.

2021-02-25 21:44 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-38768 Advance DPDK submodule to pick up VMXNet3 Fix:** A fix has been applied to the ip header checksum and is now calculated via hardware offload.
"VMXNet3 driver not functional: ..."

2021-02-25 21:44 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-38830 Fix when statement for device interface identifier:** Resolved a configuration problem wherein vmbus-uuid could not be configured unless forwarding was explicitly configured.
"Validation error when device-interface type is set to `vmbus-uuid` and forwarding is disabled..."

2021-02-25 21:44 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-38832 NETCONF Ending Deliminator Can Appear Over Buffer Packets:** Resolved an issue that resulted in unresponsive web and command line interfaces caused by certain configuration sizes.
"Intermittent PCLI command failure when issues queries against managed routers:..."

2021-02-25 21:44 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-39011 AP using almost 300% CPU, show assets plci command stuck after upgrade:** Resolved by increasing the timeout for local rpm queries.
"AutomatedProvisioner process consuming 300%..."

2021-02-25 23:00 UTC, MarkusJork commented on docs/config_vrf_learning.md
> +title: VRF Learning via BGP
VRF is a concept / capability. By using BGP to exchange VRF routes, one can "learn" VRF routes.
Elsewhere the documentation talks about "VRF route learning" which would be a correct term.
Just "VRF learning" doesn't really make sense, so the above should say "VRF Route Learning".

2021-02-26 04:27 UTC, agrawalkaushik approved these changes

2021-02-26 13:20 UTC, amenon128t commented on docs/cli_reference.md
> -show fib [rows <rows>] [force] [node <node>] router <router>
This fib command is not there in 5.1. This was in the document, but will only come in 5.2

2021-02-26 13:24 UTC, amenon128t commented on docs/concepts_learning_VRF_routes.md
> +- BGP over SVR is not supported for the VRF BGP instances.
We should also mention that multiprotocol bgp over SVR is not supported

2021-02-26 13:25 UTC, amenon128t commented on docs/config_vrf_learning.md
> +Need procedure here.
please add config for  adding the tenant to vrf asociation.

2021-02-26 13:32 UTC, amenon128t commented on docs/config_vrf_learning.md
> +title: VRF Learning via BGP
The wording  is not quite right. VRF is a routing table and is locally relevant. VRF  can be advertised using route distinguish to advertise routes to another bgp neighbor. So we could rename this to learning vrf routes.

2021-02-26 13:34 UTC, amenon128t commented on docs/ts_troubleshooting_vrf.md
> +title: Troubleshooting VRF
This can take the commands from the vrf section above and indicate that the routes will be empty in case there are not vrf routes being advertised. The bgp commands can indicate if the bgp connection is up/

2021-02-26 14:15 UTC, MarkusJork commented on docs/cli_reference.md
> -show fib [rows <rows>] [force] [node <node>] router <router>
The new `tenant` and `vrf` arguments are in 5.1 though

2021-02-26 14:19 UTC, MarkusJork commented on docs/cli_reference.md
> +## `show service`
I'm not seeing this in 5.1 at the moment. Does the above comment from @amenon128t apply here too that this will only come in 5.2?

2021-02-26 14:24 UTC, MarkusJork commented on docs/cli_reference.md
> +show vrf <vrf-name>
This command does not take a vrf-name as argument. Instead:
`admin@node1.Gateway# show vrf
usage: vrf [<verbosity>]

Show VRF name, tenants, and interfaces

positional arguments:
verbosity    detail | summary (default: summary)
`

2021-02-26 14:38 UTC, MarkusJork commented on docs/config_vrf_learning.md
> +                    neighbor-as       3000
I already commented in a previous PR that the indentation is off here. That's because some lines have a mix of blanks and TAB characters. The TABs throw things off depending on whether they get interpreted as four or eight blank characters.
I suggest you remove any TABs from the beginning of lines and replace them with blanks.

2021-02-26 14:41 UTC, MarkusJork commented on docs/config_vrf_learning.md
> +[`show vrf`](cli_reference.md#show-vrf)
This command does not have a `vrf-name` argument. It always displays all configured VRFs.

2021-03-01 15:53 UTC, Chr1st0ph3rTurn3r commented on docs/config_RBAC.md
> +	![Service Applies To](/img/config_RBAC_ARGSstep3.png)
No. I reshot the capture.

2021-03-01 15:54 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_learning_VRF_routes.md
> +128T uses the concept of Tenancy to provide L3 network segmentation. With the 5.1 release, support for learning VRF routes through BGP and the associated routing tables has been added.
done

2021-03-01 16:00 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_learning_VRF_routes.md
> +- BGP over SVR is not currently supported for the VRF BGP instances.
Moved both Caveats to the appropriate section of the 5.1 release notes.

2021-03-01 18:49 UTC, Chr1st0ph3rTurn3r commented on docs/config_vrf_learning.md
> +title: VRF Learning via BGP
Removed "via BGP". Learning VRF Routes and VRF Route Learning, from my perspective as the writer, are really two ways of saying the same thing, it just depends on the context. I will likely use them interchangeably.

2021-03-01 21:02 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +:::warning
I don't really know how long to leave it in. Jeff mentioned 5.0, and I'm okay with removing it. Your thoughts?

2021-03-02 13:12 UTC, amenon128t commented on docs/cli_reference.md
> +## `show service`
This will also come only in 5.2

2021-03-02 13:14 UTC, amenon128t commented on docs/cli_reference.md
> -show fib [rows <rows>] [force] [node <node>] router <router>
The entire show fib command below is not there in 5.1. The tenant and vrf variations are there for bgp over vrf support as Markus has mentioned. That needs to be captured.

2021-03-03 13:39 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +:::warning
REmoved after a conversation with Jeff.

2021-03-03 13:41 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **[I95-19132 Role-Based Access Control](config_RBAC.md):** Role-Based Access Control provides a mechanism for an Administrator to create Access Management Roles that allow specific access to 128T r
added.

2021-03-03 13:43 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-38212 Conductor should have a "reboot" button in GUI:** Added a Restart button on each node page. Clicking the button opens a dialog which asks the user to confirm the (full system) restart.
Need to validate whether it is Reboot or Restart on the button, but will change text as above.

2021-03-03 13:45 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-30812 kicked out of pcli with session timeout when actively running commands:** PCLI sessions now recognize all activity.
done

2021-03-03 14:38 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-35405 BGP over VLAN (non-SVR) not working:** This issue has been resolved as part of I95-36341.
removed.

2021-03-03 14:39 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-36053 High number of System Events on 128T Config chnages:** Added a filter to audit logs of type SERVICE-START and SERVICE-STOP based on service to filter just the required services.
done

2021-03-03 14:41 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-36761 PCLI configure bgp default-route-distance:** All three BGP default distances (ebgp, ibgp, and local) now have default settings.
done

2021-03-03 14:59 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-37181 LTE Modem denied from network with 128T Service Running:** Resolved an issue where UDP packets larger than interface(network) MTU will cause Rx Error on the LTE interface, and resulted
edited as below:
**I95-37181 LTE Modem denied from network with 128T Service Running:** Resolved an issue where UDP packets larger than the network-interface MTU causes Rx Error on the LTE interface, resulting in denial of the LTE modem.

2021-03-03 15:01 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-37699 Save tech support on scaled setup has corrupted zip file:** Added a Limit Argument To PCLI show events and Tech Support to resolve this issue.
done

2021-03-03 15:01 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-37770 CVE Obfuscator consumes password as a command line argument:** This issue has been resolved.
done

2021-03-03 15:02 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-37826 CIS Compliance: Ensure permissions on bootloader config are configured:** Appropriate permissions are set on bootloader config files.
done

2021-03-03 15:03 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-37848 Properly handle jumbo UDP packet from LTE network:** Resolved an issue where UDP packets larger than interface(network) MTU will cause Rx Error on the LTE interface.
Duplicate of 37181. Removed 37848.

2021-03-03 15:04 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-38393 Minions Cannot Get Past Connected State:** Resolved an issue where assets could become stuck in Connected state.
got it - fixed.

2021-03-03 15:10 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-38830 Fix when statement for device interface identifier:** Resolved a configuration problem wherein vmbus-uuid could not be configured unless forwarding was explicitly configured.
I'm going to assume this is a replacement for the issue title? Replaced the title.

2021-03-03 15:11 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-38832 NETCONF Ending Deliminator Can Appear Over Buffer Packets:** Resolved an issue that resulted in unresponsive web and command line interfaces caused by certain configuration sizes.
I'm going to assume this is a replacement for the issue title? Replaced the title.

2021-03-03 15:12 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-39011 AP using almost 300% CPU, show assets plci command stuck after upgrade:** Resolved by increasing the timeout for local rpm queries.
done

2021-03-03 15:16 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_learning_VRF_routes.md
> +- BGP over SVR is not supported for the VRF BGP instances.
moved to Caveats section of the Release notes.

2021-03-03 15:28 UTC, Chr1st0ph3rTurn3r commented on docs/cli_reference.md
> -show fib [rows <rows>] [force] [node <node>] router <router>
I'm sorry, but you guys are not being clear. The show fib command has been in the product since version 1, according to the version history. I also updated this command for 5.1 for next hop details and the ability to filter by: service-name, hierarchy-service-name, contains-service-name, prefix, source-address, source-interface, and tenant. The vrf support is also listed. I don't understand what you are saying is not in this command. Please clarify.

2021-03-03 15:34 UTC, Chr1st0ph3rTurn3r commented on docs/config_vrf_learning.md
> +Need procedure here.
done

2021-03-03 15:37 UTC, Chr1st0ph3rTurn3r commented on docs/cli_reference.md
> +## `show service`
deleted

2021-03-03 15:41 UTC, Chr1st0ph3rTurn3r commented on docs/cli_reference.md
> +show vrf <vrf-name>
done

2021-03-03 15:49 UTC, Chr1st0ph3rTurn3r commented on docs/config_vrf_learning.md
> +                    neighbor-as       3000
Educate me - in the doc output it looks and reads correctly, and tabs are preferred in documentation. If it shows incorrectly in git, but generates correctly in the output, is there an issue? I replaced the tabs with a gazillion individual spaces to align as you requested thinking there must be a reason. Please let me know.

2021-03-03 16:05 UTC, Chr1st0ph3rTurn3r commented on docs/config_vrf_learning.md
> +[`show vrf`](cli_reference.md#show-vrf)
removed the -name and will address individual commands in the cli guide.

2021-03-03 21:41 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-34919 Show Commands for Services:** The [`show service`](cli_reference.md#show-service), [`show service path`](cli_reference.md#show-service-path), and [`show fib`](cli_reference.md#show-fib)
Is `show service` present in cli_reference.md? I may have missed it.

2021-03-04 01:54 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-36509 SSC drops validate message if managed router disconnects while message is in-flight:** This issue has been resolved.
done

2021-03-07 15:05 UTC, jeffmart commented on docs/config_RBAC.md
> +	![Resources](/img/config_RBAC_ARGtoResS2.png)
I think showing the actual resource selected would be better that the top level screen shot that is here. If you read quickly through this, this flow does not look any different than just adding the resource group at the top level.

2021-03-07 15:57 UTC, jeffmart commented on docs/config_RBAC.md
> +### Assign a Resource Group to a Service:
Add Service-Policy here as well.

2021-03-08 15:13 UTC, MarkusJork commented on docs/ts_troubleshooting_vrf.md
> +title: Troubleshooting VRF
Here is my suggestion for some extra content in this troubleshooting section. It would be the start of this section:

The `show rib vrf` command can be used to check for the presence of VRF route entries.
If expected VRF route entries are not present, the following steps may be used to troubleshoot the problem:
- The `show vrf` command will display all the VRFs that were created based on the running configuration. A missing or incorrect VRF entry is likely due to a configuration issue.
- The `show bgp summary vrf` command displays an overview of the status of the BGP VRF peering sessions. Any non-established session can then be investigated further.
- The `show network-interface` command can be used to check all interfaces associated with the VRF (via their tenant assignment). The BGP VRF peering might not be able to become established due to a down interface.

2021-03-08 19:34 UTC, Chr1st0ph3rTurn3r commented on docs/config_RBAC.md
> +	![Resources](/img/config_RBAC_ARGtoResS2.png)
done

2021-03-08 19:34 UTC, Chr1st0ph3rTurn3r commented on docs/config_RBAC.md
> +### Assign a Resource Group to a Service:
done

2021-03-10 21:41 UTC, MichaelBaj submitted a review, later dismissed

2021-03-11 15:29 UTC, agrawalkaushik submitted a review, later dismissed
Reviewed the new edits to the conifg_audit_events and looks good!

2021-03-12 13:55 UTC, MichaelBaj submitted a review, later dismissed

2021-03-15 19:12 UTC, MichaelBaj requested changes

2021-03-15 19:12 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **39483 Validate/Commit and Diff Endpoints not Filtered by RBAC:** In some cases, Role-Based Access Configuration (RBAC) may not filter errors and warnings generated during the Validate operation.
Missing "I95-" as part of the issue id.
Also, I don't think it benefits our customers to caveat this issue. I recommend it be removed. We can add it back in when it is addressed in the next patch.

2021-03-15 19:12 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +	- In order to exchange VRF routes via BGP, each VRF needs a separate BGP protocol instance and BGP session.
This seems less like a caveat and more like an implementation detail. This is already captured in the configuration guide for VRF.
Caveats suggest that it is an issue that will be addressed at a later point.

2021-03-15 20:21 UTC, MichaelBaj approved these changes

2021-03-16 00:25 UTC, merged