WIP: Update all plugin docs for api-2.0 changes
128technology/docs pull request #192
Opened 2021-02-26 22:27 UTC by salegria8

# Description

The following plugins are available in `api-2.0` but have no docs currently. I wanted to make sure changes are necessary before adding anything.
- Application Modules
- AWS TGW
- Syslog Server

The following plugins have docs but I'll need some help making additional changes:
- Monitoring Agent
- Cloud HA? (we added supported solutions)
- DNS Cache? (there was a TTL advertising bug fix that I don't understand)
- Wireguard? (v3.0.0 is ready but it won't work with 5.1.0, not sure how to phrase that nicely)

2021-02-26 22:30 UTC, agrawalkaushik commented
> The following plugins are available in api-2.0 but have no docs currently. I wanted to make sure changes are necessary before adding anything.

    Application Modules
    AWS TGW
    Syslog Server

These are not released yet so you can just skip them from the notes and from the publishing task.

2021-02-26 22:34 UTC, agrawalkaushik commented
>    Monitoring Agent

Greg is working on this already. This is the actual monitoring agent and there is no plugin for it yet. We just put it under plugins because it falls in the same bucket.

    Cloud HA? (we added supported solutions)

> We did - you should just skip the documentation for that. Either Ben or Francisco will update the notes at a later time.

    DNS Cache? (there was a TTL advertising bug fix that I don't understand)

> Can you slack me the link to the bug and I can provide context.

    Wireguard? (v3.0.0 is ready but it won't work with 5.1.0, not sure how to phrase that nicely)

> For now don't do anything - lets wait till the dust settles on that. Likely that will be captured through a different release notes in the product and we'll link to that release note from the plugins doc.

2021-02-26 22:38 UTC, agrawalkaushik commented on docs/plugin_dns_app_id.md
> +- **PLUGIN-768** Support the DNS App ID plugin in 128T versions `5.1.0` and greater.
@salegria8 we also add plugin state support for a whole bunch of plugins like DNS App Id, GRE, IPSec, ICMP etc. We should include a blurb about that as well against PLUGIN-611 EPIC.

2021-02-26 22:38 UTC, agrawalkaushik requested changes
see comments above

2021-03-01 17:21 UTC, MichaelBaj approved these changes

2021-03-01 19:13 UTC, jamesesilvia commented on docs/plugin_dns_app_id.md
> +- **PLUGIN-768** Support the DNS App ID plugin in 128T versions `5.1.0` and greater.
I think a new section should be added to the Plugin Introduction that discusses the new addition of plugin-state. I can help if needed.

2021-03-01 19:14 UTC, jamesesilvia submitted a review, later dismissed

2021-03-01 21:15 UTC, agrawalkaushik commented on docs/plugin_dns_app_id.md
> +- **PLUGIN-768** Support the DNS App ID plugin in 128T versions `5.1.0` and greater.
@jamesesilvia if you're doing that than also add the plugin PCLI commands for managing the plugins. I have a DOC task open for that for a while now (just never go to it).

2021-03-01 21:20 UTC, agrawalkaushik approved these changes

2021-03-01 21:20 UTC, agrawalkaushik commented
Looks like you're missing wireguard @salegria8

2021-03-02 15:34 UTC, BenMatase requested changes
Looks good overall, just some things I'd like to see tweaked

2021-03-02 15:34 UTC, BenMatase commented on docs/plugin_intro.md
> +Show the current state of a plugin using `show plugins state [router <router>] [node <node>] [{detail | summmary}] name <plugin-name>`. The verbosity of the state output can be set to `detail` or `su
I'm not sure if we want to keep a running list of state supporting plugins here. It is definitely useful, but I know it will get out of date quickly. Maybe just change `and for the following plugins...` to say something about how plugins aren't required to support this, so not all plugins will have meaningful output from this command?

2021-03-02 15:34 UTC, BenMatase commented on docs/plugin_intro.md
> +Install a plugin using `manage plugin install [node <node>] [name <plugin-name>]`
IIRC doesn't this also upgrade and downgrade an existing plugin?

2021-03-02 15:34 UTC, BenMatase commented on docs/plugin_wireguard.md
> +- **PLUGIN-611** Add a plugin state endpoint with summary and detail verbosity. State information can be accessed on the PCLI using `show plugins state [router <router>] [node <node>] [{detail | summ
plugin state endpoint is too implementation specific. Maybe `Added support for plugin state. Plugin state information can be accessed ...`?

2021-03-02 15:34 UTC, BenMatase commented on docs/plugin_gre.md
> +- **PLUGIN-611** Add a plugin state endpoint with summary and detail verbosity. State information can be accessed on the PCLI using `show plugins state [router <router>] [node <node>] [{detail | summ
Similar comment on all of these as wireguard's. First sentence is implementation details

2021-03-02 15:54 UTC, salegria8 commented on docs/plugin_intro.md
> +Install a plugin using `manage plugin install [node <node>] [name <plugin-name>]`
Going off `PluginService.robot` it wasn't clear. @jamesesilvia can I add upgrade/downgrade to this description?

2021-03-02 16:06 UTC, jamesesilvia commented on docs/plugin_intro.md
> +Install a plugin using `manage plugin install [node <node>] [name <plugin-name>]`
install/remove. (install could be an upgrade)

2021-03-02 16:09 UTC, jamesesilvia approved these changes

2021-03-02 20:50 UTC, jamesesilvia approved these changes

2021-03-02 21:56 UTC, BenMatase submitted a review, later dismissed

2021-03-03 23:19 UTC, agrawalkaushik commented on docs/plugin_intro.md
> +### Plugin Management
This is a good addition - thanks for adding this @salegria8

2021-03-03 23:19 UTC, agrawalkaushik requested changes

2021-03-03 23:19 UTC, agrawalkaushik commented on docs/plugin_wireguard.md
> +- **I95-38622** The plugin is not yet supported on routers running 128T versions `5.1.0` and greater.
Can you remove the `and greater` part. We'll look for fix this in a subsequent version so the statement wont be true at that point.

2021-03-04 13:57 UTC, BenMatase approved these changes

2021-03-05 05:41 UTC, agrawalkaushik approved these changes

2021-03-15 18:14 UTC, MichaelBaj approved these changes

2021-03-16 00:08 UTC, merged