OTP ISO install
128technology/docs pull request #197
Opened 2021-03-02 22:18 UTC by Chr1st0ph3rTurn3r

2021-03-03 22:04 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
>  Not all hardware has video support, therefore booting to console is the default (a console user may not be able to select an option). The default option is selected after a 30 second timeout.
I would like to have this section updated. The serial console access should normally work. The Serial console default size expected is 80x25. If the terminal being used to connect to the console is less than this row(80) X column(25), the display may appear to the console user that they are unable to select the entries or the display does not repaint correctly. Also in the initial bootup, of the console is disconnected, there is no repaint capability, the arrow up and down buttons should be used to show the available selections. Maybe re-word something like:

"Not all hardware has video support, therefore booting to the serial console is the default and will be automatically selected after 30 seconds. When using the serial console, the terminal size is 80x25 (anything smaller may result in abnormal navigation behavior."

2021-03-03 22:05 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
> +However, the procedure that follows here is the Interactive install on the VGA Console.
Remove "However,"

2021-03-03 22:08 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
> +Selecting the wrong type of console (Serial or VGA) may result in garbage characters being displayed and the install hanging. If this is the case, reboot the target system and select the correct line
The system actually does not hang, and if left will continue to load the OS to it's compleation. However the kernel default console will be set wrong so the the above resolution is still the recommended solution.

2021-03-03 22:12 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
>  Not all hardware has video support, therefore booting to console is the default (a console user may not be able to select an option). The default option is selected after a 30 second timeout.
I did not see the section below calling out the serial console until after I wrote the above, do we move the NOTE to the section below or add the last sentence above to below? (either works for me).

2021-03-03 22:24 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
> +In order to avoid SSH session timeout during installation, it is strongly recommended to use the **Screen** utility when performing an installation. The serial screen size must be a minimum of 80x25,
I think we should change this section. The serial console access and behavior is really dependant on the host OS and utilities. For example I have never seen issues when using Windows with putty on screen display corruption (so using screen and ssh in this case does not apply). However I have seen different issues based on the different hardware using the serial console with OSX/screen, and these are different from hardware platform to hardware platform being imaged. With that said, I think we can reword this to be something like this:

Reiterate the terminal window size of 80x25, "if this is not the minumum size the console navigation may have unintended consequences or may not appear to navigate at all."

"When performing an installation via the serial console, some systems do not interpret control characters that may be passed on the serial console line. For example, the following may be seen during the installation process: [keep the png that you have there]"

2021-03-03 22:26 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
> +5. Type: `^l` (Ctrl-l) (lower case L) to repaint the screen.
Add a sub note here stating that the repaint operation does not work on the initial boot screen to image a system so if the serial console is disconnected, it is recommended to restart the system and imaging process again.

2021-03-03 22:28 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
> +   | user | 128Tuser | 128T user PCLI account |
nit change "128T user PCLI account" to "128T PCLI user account" I may have provided the initial wrong content :)

2021-03-03 22:29 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
> +   | user | 128Tuser | 128T user PCLI account |
actually, thinking about this more, it is PCLI and UI so remove the PCLI completely for both and use "128T admin account" and "128T user account"

2021-03-03 22:33 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
>  3. When asked _What kind of Router node is this?_, select from the following options:
We might want to update this to reference the screen disaply. The text says router the screen shot has Conductor, maybe do "_What kind of Conductor/Route node is this?_

2021-03-03 23:19 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
>  - **1st HA Node:** This router is the first node of a high availability pair. You will be prompted for the High Availability address of this node. Note: The address _must_ be reachable by the 2nd HA 
There has been some confustion on this in the past. While we are in here, please update with the following:
"**1st HA Node:** This router is the first node of a high availability pair. You will be prompted to provide the local IP address for this node. The 2nd HA node will contact this node at the address provided to synchronize state. Note: The 1st Node IP address _must_ be reachable by the 2nd HA Node."

2021-03-03 23:20 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
>  - **2nd HA Node:** This router is the second node of a high availability pair, where the first node has been initialized. You will be prompted for the High Availability address of the first node.
Update this with:
"**2nd HA Node:** This router is the second node of a high availability pair, where the first node has been initialized. You will be prompted to provide the 1st Node IP address for this 2nd node that will be used to synchronize state. Note: The 2nd Node IP address _must_ be reachable by the 1st HA Node."

2021-03-03 23:55 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
> +Please note that Serial and UEFI consoles display differently. The following is the  installation screen when booting to a Serial console:
Change "Serial and UEFI" to "Legacy and UEFI". Serial is not directly related as the difference are also similar in VGA installations for Legacy and UEFI. It will be obvious when someone performs the installation on different systems.

2021-03-03 23:55 UTC, jeffmart requested changes
Please see individual comments below

2021-03-04 00:26 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
>  - **Node Name:** The unique name of the system within your 128T Router or Conductor, for example _labsystem1_. By default this field uses the Linux system's hostname.
While this is not specifically part of this changed we are changing the screen shots so this gives us the opertunity to also provide cascading examples. With the screen shots I provided out of band we should change the context of the nodeName.router/conductorName to match the screen shots which would be:

conductor-node1.conductor

so labsystem1 which be changed to "conductor-node1" and the router/conductorName would be changed to "conductor" to match the screen shot.

2021-03-04 14:39 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_bootable_media.md
> +5. Type: `^l` (Ctrl-l) (lower case L) to repaint the screen.
done

2021-03-04 14:39 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_bootable_media.md
> +In order to avoid SSH session timeout during installation, it is strongly recommended to use the **Screen** utility when performing an installation. The serial screen size must be a minimum of 80x25,
done

2021-03-04 14:43 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_bootable_media.md
> +However, the procedure that follows here is the Interactive install on the VGA Console.
done

2021-03-04 14:45 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_bootable_media.md
>  Not all hardware has video support, therefore booting to console is the default (a console user may not be able to select an option). The default option is selected after a 30 second timeout.
done

2021-03-04 14:45 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_bootable_media.md
> +   | user | 128Tuser | 128T user PCLI account |
done

2021-03-04 15:02 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_bootable_media.md
> +Please note that Serial and UEFI consoles display differently. The following is the  installation screen when booting to a Serial console:
done

2021-03-04 15:03 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_bootable_media.md
>  3. When asked _What kind of Router node is this?_, select from the following options:
done

2021-03-04 15:08 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_bootable_media.md
>  - **2nd HA Node:** This router is the second node of a high availability pair, where the first node has been initialized. You will be prompted for the High Availability address of the first node.
done

2021-03-04 15:08 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_bootable_media.md
>  - **1st HA Node:** This router is the first node of a high availability pair. You will be prompted for the High Availability address of this node. Note: The address _must_ be reachable by the 2nd HA 
done

2021-03-04 16:59 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_bootable_media.md
>  - **Node Name:** The unique name of the system within your 128T Router or Conductor, for example _labsystem1_. By default this field uses the Linux system's hostname.
done

2021-03-04 21:00 UTC, jeffmart submitted a review, later dismissed

2021-03-04 23:01 UTC, MichaelBaj requested changes

2021-03-04 23:01 UTC, MichaelBaj commented on docs/intro_installation_bootable_media.md
> +- The serial screen size **must** be a minimum of 80x25, otherwise the output may not be readable, and the console navigation may have unintended consequences or may not appear to navigate at all.
The disclaimer is present again. If there is an internal link above to this one, I'm not sure so many references are necessary.  My 2c

2021-03-04 23:54 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
> +Selecting the wrong type of console (Serial or VGA) may result in garbage characters being displayed, and if left to continue will result in an incorrect installation. If the wrong console is selecte
corrected

2021-03-04 23:55 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
> +- The serial screen size **must** be a minimum of 80x25, otherwise the output may not be readable, and the console navigation may have unintended consequences or may not appear to navigate at all.
removed

2021-03-04 23:57 UTC, jeffmart commented on docs/intro_installation_bootable_media.md
> +The expected Serial console default size is 80x25. If the terminal being used to connect to the console is less than row (80) X column (25), the display may appear that the user is unable to select t
removed

2021-03-05 00:03 UTC, MichaelBaj approved these changes

2021-03-05 02:19 UTC, merged