DNS App Id improvements
128technology/docs pull request #198
Opened 2021-03-04 18:41 UTC by jamesesilvia

## Description
Update docs for unreleased versions of 128T-dns-app-id plugin that improves UX while configuring the plugin.

## TODO
- [Publish RPMs]

2021-03-04 18:53 UTC, BenMatase requested changes

2021-03-04 18:53 UTC, BenMatase commented on docs/plugin_dns_app_id.md
> +| custom-apps > domin-name | string | A wildcard expression (POSIX.2 fnmatch) to match DNS requests that 128T processes. |
typo, should be domain-name

2021-03-04 18:53 UTC, BenMatase commented on docs/plugin_dns_app_id.md
> +By enabling the `include-all-builtin-apps` configuration, the plugin will automatically include all the available apps. This allows for new apps to be automatically included as new builtin apps are a
youube typo

2021-03-04 18:53 UTC, BenMatase commented on docs/plugin_dns_app_id.md
> +| 1.3.0, 2.3.0 | deprecate `pattterns` in favor of `domain-name` for custom-apps |
Three `t`s in patterns

2021-03-04 18:53 UTC, BenMatase commented on docs/plugin_dns_app_id.md
> +- Add youtube to builtins
jira id associations for these two bullet points

2021-03-04 18:58 UTC, jamesesilvia commented on docs/plugin_dns_app_id.md
> +- Add youtube to builtins
HA. I didn't do the work against a specific new JIRA. Plus -- what's the point? Aren't these customer facing? Does PLUGIN-1990000: Add youtube mean anything to a consumer of these docs?

2021-03-04 19:37 UTC, ptimmons requested changes

2021-03-04 19:37 UTC, ptimmons commented on docs/plugin_dns_app_id.md
> +                    domain-name .*.cnn.com
This is a confusing example. What's with the initial '.'?

2021-03-04 19:37 UTC, ptimmons commented on docs/plugin_dns_app_id.md
> +The plugin contains built in application patterns for Gmail, Google Drive, Youtube, and Windows Update. The patterns were generated from the following published documents:
YouTube

2021-03-04 19:37 UTC, ptimmons commented on docs/plugin_dns_app_id.md
> +| Youtube   | [link](https://www.netify.ai/resources/applications/youtube) |
YouTube

2021-03-04 19:46 UTC, salegria8 commented on docs/plugin_dns_app_id.md
> +- Add youtube to builtins
The JIRA comes in handy when cross referencing plugin changelogs with docs. It helped me quickly find if a change had already been documented

2021-03-04 20:14 UTC, jamesesilvia commented on docs/plugin_dns_app_id.md
> +- Add youtube to builtins
will create/update when addressing more comments

2021-03-04 20:17 UTC, jamesesilvia commented on docs/plugin_dns_app_id.md
> +                    domain-name .*.cnn.com
will remove

2021-03-04 21:15 UTC, agrawalkaushik commented on docs/plugin_dns_app_id.md
> +- Add youtube to builtins
@jamesesilvia Access is not the problem here - process is. Please create a JIRA EPIC for this and we need to document the identifier here.

2021-03-04 21:27 UTC, agrawalkaushik requested changes

2021-03-04 21:27 UTC, agrawalkaushik commented on docs/plugin_dns_app_id.md
> +The latest version is backwards compatabile with the `patterns` functionality however it is much more natural to use `domain-name`. Future releases will likely obsolete the `patterns` configuration f
> Future releases will likely obsolete the `patterns` configuration field!

We should re-word it (and drop that exclamation at the end)

::: note
The `patterns` configuration has been deprecated and replaced with `domain-name`. Please see the release notes for more details
:::

(And link to the release notes below).

2021-03-04 21:27 UTC, agrawalkaushik commented on docs/plugin_dns_app_id.md
> +The `.` character bears special meaning within regular expressions, and matches *any single character*. Because hostnames contain literal `.` characters, in order to explicitly reference a dot separa
Since we are deprecating the `patterns` I dont think we should add this node to try and clarify how to use the deperecated field.

2021-03-04 21:27 UTC, agrawalkaushik commented on docs/plugin_dns_app_id.md
> +
we should add a section for caveat and document that here. Something like this (You can look at format for caveats in other docs - wireguard has on I think)
```
### Caveats
The regex format for the `pattern` configuration has been difficult to configure and is being replaced with a new field called `domain-name` with a more natural <insert-type-here> instead


```

2021-03-08 13:35 UTC, jamesesilvia commented on docs/plugin_dns_app_id.md
> +The `.` character bears special meaning within regular expressions, and matches *any single character*. Because hostnames contain literal `.` characters, in order to explicitly reference a dot separa
Until its removed -- there is a chance people could be using the old plugin and I don't want to remove the description that people could need to reference.

2021-03-08 13:38 UTC, jamesesilvia commented on docs/plugin_dns_app_id.md
> +The latest version is backwards compatabile with the `patterns` functionality however it is much more natural to use `domain-name`. Future releases will likely obsolete the `patterns` configuration f
re-worded

2021-03-08 16:26 UTC, agrawalkaushik submitted a review, later dismissed

2021-03-10 20:54 UTC, MichaelBaj submitted a review, later dismissed

2021-03-10 21:07 UTC, ptimmons submitted a review, later dismissed

2021-03-18 14:15 UTC, agrawalkaushik commented on docs/plugin_dns_app_id.md
> +| custom-apps > domin-name | string | A wildcard expression (POSIX.2 fnmatch) to match DNS requests that 128T processes. |
seems to be fixed now

2021-03-29 19:30 UTC, agrawalkaushik approved these changes

2021-03-29 20:43 UTC, salegria8 approved these changes

2021-03-30 01:48 UTC, agrawalkaushik approved these changes

2021-03-30 12:59 UTC, BenMatase submitted a review, later dismissed

2021-03-30 15:53 UTC, MichaelBaj commented on docs/plugin_dns_app_id.md
> +### Release 1.3.0, 2.3.0, 3.1.0
Is this correct? It states 3.1.0 here, but there inly exists a 3.0.0 heading below.

2021-03-30 16:41 UTC, jeffmart requested changes

2021-03-30 16:41 UTC, jeffmart commented on docs/plugin_dns_app_id.md
> +### Release 1.3.0, 2.3.0, 3.1.0
Looks like these need to be synced. The 3.0.0 was added for the 5.1.0 release only. Also the section above is missing the 1.3.0 reference as well

2021-03-30 16:41 UTC, jeffmart commented on docs/plugin_dns_app_id.md
> +| 1.3.0, 2.3.0 | Add `YouTube` as builtin pattern |
Is this also in 3.1.0?

2021-03-30 16:41 UTC, jeffmart commented on docs/plugin_dns_app_id.md
> +| 1.3.0, 2.3.0, 3.1.0 | deprecate `patterns` in favor of `domain-name` for custom-apps |
We seem to be missing the 3.0.0 reference when we shipped 5.1.0

2021-03-30 16:41 UTC, jeffmart commented on docs/plugin_dns_app_id.md
> +| 2.3.0, 3.0.0 | The generate-as-hierarchical-services capability was introduced |
Is this also in 1.3.0?

2021-03-30 16:45 UTC, agrawalkaushik commented on docs/plugin_dns_app_id.md
> +### Release 1.3.0, 2.3.0, 3.1.0
For plugins, this is the model we've been following @MichaelBaj since the same change tends to apply to several versions at once. This helps keeps the notes concise.

The 3.0.0 was released as part of 128T-5.1.0 and the new version has newer features/bug fixes since then.

2021-03-30 16:50 UTC, MichaelBaj approved these changes

2021-03-30 18:01 UTC, jeffmart commented on docs/plugin_dns_app_id.md
> +| 2.3.0, 3.0.0 | The generate-as-hierarchical-services capability was introduced |
It is not in 1.3.0

2021-03-30 18:03 UTC, jeffmart commented on docs/plugin_dns_app_id.md
> +| 1.3.0, 2.3.0, 3.1.0 | deprecate `patterns` in favor of `domain-name` for custom-apps |
This is not part of 3.0.0

2021-03-30 18:07 UTC, jeffmart approved these changes

2021-03-30 18:26 UTC, merged

2021-03-30 20:12 UTC, agrawalkaushik commented on docs/plugin_dns_app_id.md
> +| 1.3.0, 2.3.0, 3.1.0 | deprecate `patterns` in favor of `domain-name` for custom-apps |
when we shipped 5.1.0, the focus was purely on bonsai compatibility. The new `3.1.0` is where the new feature gets added for the first time.