Updating for the 4.5.6 Release.
128technology/docs pull request #205
Opened 2021-03-18 19:51 UTC by Chr1st0ph3rTurn3r

2021-03-18 20:11 UTC, robert-patterson commented on docs/release_notes_128t_4.5.md
> +- **I95-39106 DHCP alarms are not cleared when config is changed to static:** We now handle the resulting empty string in alarm code after an interface is made static.
The empty string is an implementation detail.

**I95-39106 DHCP alarms are not cleared when config is changed to static:** Clear stale alarms from unresolved DHCP enabled interfaces when reconfigured to use static address.

2021-03-18 20:15 UTC, tjbresnahan commented on docs/release_notes_128t_4.5.md
> +- **I95-38815 Set Adjacency Hostnames as DPU on Config** Dynamic peer hostnames shared via DPU are now properly handled internally and no longer produce DNS queries.
This is specifically for unresolved hostnames, which were not properly handled previously.

`Unresolved dynamic peer hostnames are now properly handled via DPU and no longer produce DNS queries.`

2021-03-18 20:15 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-39378 5.1 Container Conductor failed resulting in an un-usable PCLI and missing system stats:** This issue has been resolved.
Rename title to "PCLI may return partial or empty results from some commands"

2021-03-22 13:53 UTC, tjbresnahan approved these changes

2021-03-22 14:22 UTC, robert-patterson submitted a review, later dismissed

2021-03-23 17:23 UTC, MichaelBaj requested changes

2021-03-23 17:23 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **[I95-35051 Provide a way to generate & stage all auto-generated configuration](cli_reference.md#create-config-autogenerated):** The `create-config autogenerated` command has been added, which for
Was the reference to `create-config-autogenerated` carried over from the 5.1 release notes? I only see the one file changed in this PR.
On another note, you will need to update the `about_releases.md` file to update the release date of 4.5.6

2021-03-23 17:47 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +- **[I95-35051 Provide a way to generate & stage all auto-generated configuration](cli_reference.md#create-config-autogenerated):** The `create-config autogenerated` command has been added, which for
Yes it was carried over from the 5.1 release notes.

2021-03-23 17:55 UTC, MichaelBaj submitted a review, later dismissed

2021-03-26 15:38 UTC, MichaelBaj requested changes

2021-03-26 15:38 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-39069 Highway crash in one thread when another thread is being modified:** This issue has been resolved.
Change statement to:
"**I95-39069 Highway crash when committing configuration:** Multi-threading race condition when processing multicast"

2021-03-26 15:38 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-39248 Session Migration failed due to Session Modification:** The update logic has been modified to handle a metadate update during the migration process.
typo. metadate should be metadata

2021-03-26 16:05 UTC, jeffmart commented on docs/release_notes_128t_4.5.md
> +- **[I95-35051 Provide a way to generate & stage all auto-generated configuration](cli_reference.md#create-config-autogenerated):** The `create-config autogenerated` command has been added, which for
I believe this is addressed so resolving conversation.

2021-03-26 16:06 UTC, jeffmart commented on docs/release_notes_128t_4.5.md
> +- **I95-39106 DHCP alarms are not cleared when config is changed to static:** We now handle the resulting empty string in alarm code after an interface is made static.
This looks to be resolved.

2021-03-26 16:07 UTC, jeffmart commented on docs/release_notes_128t_4.5.md
> +- **I95-38815 Set Adjacency Hostnames as DPU on Config** Dynamic peer hostnames shared via DPU are now properly handled internally and no longer produce DNS queries.
This looks to be resolved.

2021-03-26 16:08 UTC, jeffmart commented on docs/release_notes_128t_4.5.md
> +- **I95-38378 Salt-minion config broken after enabling asset connection resiliency:** The salt-minion configuration file now loads at the time of a migration operation, to ensure the latest version o
This looks to be resolved.

2021-03-26 16:08 UTC, jeffmart commented on docs/release_notes_128t_4.5.md
> +- **I95-37368 Allow Reset of Asset ID Field:** An asset-id can be reset from the Asset ID field in the GUI.
This looks to be resolved.

2021-03-26 16:09 UTC, jeffmart commented on docs/release_notes_128t_4.5.md
> +- **I95-38815 Set Adjacency Hostnames as DPU on Config** Dynamic peer hostnames shared via DPU are now properly handled internally and no longer produce DNS queries.
This looks to be resolved.

2021-03-26 16:10 UTC, jeffmart commented on docs/release_notes_128t_4.5.md
> +- **I95-39378 5.1 Container Conductor failed resulting in an un-usable PCLI and missing system stats:** This issue has been resolved.
This looks resolved.

2021-03-26 16:33 UTC, jeffmart commented on docs/release_notes_128t_4.5.md
> +- **I95-39248 Session Migration failed due to Session Modification:** The update logic has been modified to handle a metadate update during the migration process.
Looks to be resolved with the latest changes

2021-03-26 16:34 UTC, jeffmart commented on docs/release_notes_128t_4.5.md
> +- **I95-39069 Highway crash in one thread when another thread is being modified:** This issue has been resolved.
This looks to be resolved with the latest update

2021-03-26 16:35 UTC, jeffmart approved these changes

2021-03-26 16:40 UTC, MichaelBaj approved these changes

2021-03-26 16:48 UTC, merged