Removal of container references. Please review carefully - Suggested edits placed in documents, and I would like your feedback.
128technology/docs pull request #214
Opened 2021-04-01 16:20 UTC by Chr1st0ph3rTurn3r

2021-04-01 16:32 UTC, MichaelBaj requested changes

2021-04-01 16:32 UTC, MichaelBaj commented on docs/concepts_metadata.md
> +**Suggested Change: The term workload mobility refers to the migration of a workload from one location in a network to another;**
This sentence does not need to change because in this context, we are not referring to the SSR as a container, but the service or application as a container.

2021-04-01 16:32 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +  **Suggested Change: Symptom: The 128T will fail to initialize when running on Ubuntu distributions.**
This is tricky. This issue is specifically talking about an issue with the 128T as a container so the wording is correct. Alternatively, strip this entirely from the release notes since most all customers would never encounter this.

2021-04-01 16:32 UTC, MichaelBaj commented on docs/release_notes_128t_4.4.md
> +  **Suggested Change: Symptom: The 128T will fail to initialize when running on Ubuntu distributions.**
This is tricky. This issue is specifically talking about an issue with the 128T as a container so the wording is correct. Alternatively, strip this entirely from the release notes since most all customers would never encounter this.

2021-04-01 16:32 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +  **Suggested Change: Symptom: The 128T will fail to initialize when running on Ubuntu distributions.**
This is tricky. This issue is specifically talking about an issue with the 128T as a container so the wording is correct. Alternatively, strip this entirely from the release notes since most all customers would never encounter this.

2021-04-01 17:14 UTC, migolnikov commented on docs/release_notes_128t_4.5.md
> +  **Suggested Change: Symptom: The 128T will fail to initialize when running on Ubuntu distributions.**
Is this Ubuntu thing for cloud deployments?

2021-04-01 19:02 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +  **Suggested Change: Symptom: The 128T will fail to initialize when running on Ubuntu distributions.**
To the best of my knowledge, this is for one of our customers in the oil and gas sector deploying the 128T router

2021-04-28 13:45 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_metadata.md
> +**Suggested Change: The term workload mobility refers to the migration of a workload from one location in a network to another;**
Done

2021-04-28 13:48 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.3.md
> +  **Suggested Change: Symptom: The 128T will fail to initialize when running on Ubuntu distributions.**
Removed from 4.3.9 Release Notes.

2021-04-28 13:50 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.4.md
> +  **Suggested Change: Symptom: The 128T will fail to initialize when running on Ubuntu distributions.**
Removed from the 4.4.2 Release notes.

2021-04-28 13:52 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +  **Suggested Change: Symptom: The 128T will fail to initialize when running on Ubuntu distributions.**
Removed from the 4.5.1 release notes

2021-05-05 14:31 UTC, MichaelBaj approved these changes

2021-05-05 16:27 UTC, merged