added informational note about release order.
128technology/docs pull request #215
Opened 2021-04-01 21:35 UTC by Chr1st0ph3rTurn3r

2021-04-01 21:36 UTC, MichaelBaj approved these changes

2021-04-01 21:49 UTC, jeffmart requested changes

2021-04-01 21:49 UTC, jeffmart commented on docs/about_releases.md
> +However, issues resolved in `4.3.12`, which was released on 3/12/2021 are not addressed in `4.5.5` because `4.5.5` was released on 2/10/2021, even though `4.5.5` is lexicographically higher than `4.3
Do we add to the end of this:
though `4.5.5` is lexicographically higher than `4.3.12`, `4.5.5` is chronologically older than `4.3.12`.

Yes it seems obvious but might be missed.

2021-04-01 21:51 UTC, MichaelBaj commented on docs/about_releases.md
> +However, issues resolved in `4.3.12`, which was released on 3/12/2021 are not addressed in `4.5.5` because `4.5.5` was released on 2/10/2021, even though `4.5.5` is lexicographically higher than `4.3
I think being blunt about this is important. I am in favor of adopting this addition.

2021-04-01 22:05 UTC, MichaelBaj submitted a review, later dismissed

2021-04-02 13:27 UTC, reidstidolph reviewed
Looks good, would just suggest breaking up the long sentence into shorter ones for better readability.

2021-04-02 13:27 UTC, reidstidolph commented on docs/about_releases.md
> +However, issues resolved in `4.3.12`, which was released on 3/12/2021 are not addressed in `4.5.5` because `4.5.5` was released on 2/10/2021, even though `4.5.5` is lexicographically higher than `4.3
This is a bit of a run on sentence. Consider breaking into two sentences?

2021-04-02 14:03 UTC, MichaelBaj approved these changes

2021-04-02 14:08 UTC, Chr1st0ph3rTurn3r commented on docs/about_releases.md
> +However, issues resolved in `4.3.12`, which was released on 3/12/2021 are not addressed in `4.5.5` because `4.5.5` was released on 2/10/2021, even though `4.5.5` is lexicographically higher than `4.3
done

2021-04-02 14:25 UTC, jeffmart approved these changes

2021-04-02 14:27 UTC, merged