Add docs for monitoring agent plugin
128technology/docs pull request #218
Opened 2021-04-08 04:19 UTC by agrawalkaushik

- The monitoring agent document has been updated to capture the new plugin based installation and management

DOCS-209 #time 1d

2021-04-08 14:35 UTC, gregschrock requested changes
Just a couple minor things.

2021-04-08 14:35 UTC, gregschrock commented on docs/plugin_monitoring_agent.md
> +| broker | list | List of kafka broker to communicate with                            |
kafka broker`s` to ...

2021-04-08 14:35 UTC, gregschrock commented on docs/plugin_monitoring_agent.md
> +| admin | boolean  | true     | Include admin events generated by the system                 |
We should probably note that these depend on the events being enabled (but not necessarily persisted) on the router itself.

2021-04-08 14:35 UTC, gregschrock commented on docs/plugin_monitoring_agent.md
> +| track-index | boolean | true | Track event indexes such that it allows each event to be produced once when monitoring is restarted |
"produced once when monitoring" reads a bit odd. After a second read, I understand and I'm not sure how to improve it. Just thought I'd point it out in case others have suggestions.

2021-04-08 14:35 UTC, gregschrock commented on docs/plugin_monitoring_agent.md
> +The input type of `top-sessions` can be used to enable the top-sessions configuration. An example of such configuration is as follows
This may be a reference thing, but it bothers me that there are a bunch of full sentences that end in `follows` with no punctuation. They're full, valid sentences. So they should end in a period; or a colon could be used to transition to the example.

2021-04-08 14:35 UTC, gregschrock commented on docs/plugin_monitoring_agent.md
> +| application-filter | string | - | Filter for only including specific applications in the collection |
It took me a couple tries to understand this filter description. Maybe `Restrict the applications to be included in the collection`?

2021-04-08 14:35 UTC, gregschrock commented on docs/plugin_monitoring_agent.md
> +| extract-field > name | string | The name of the collection |
I know it's a reused grouping, but here I'd call out the specific `The name of the field` and `The name of the tag` rather than using the generic `collection`.

2021-04-08 14:35 UTC, gregschrock commented on docs/plugin_monitoring_agent.md
> +## Monitoring Agent Release Notes
Are we going to have separate plugin and agent release notes sections?

2021-04-08 14:35 UTC, gregschrock commented on docs/plugin_monitoring_agent.md
> +                    filter              service
Do we provide a way to itemize by a parameter without filtering it? I hadn't thought about that till now.

2021-04-08 14:37 UTC, agrawalkaushik commented on docs/plugin_monitoring_agent.md
> +For deployments running 128T version `5.1.0` or greater on the conductor should install the monitoring agent plugin for configuration management.
not sure I see the nuance of your comment. This is a plugin which needs to be installed on top of the existing 5.1.0 software. If you share a full line of what you intend this to read like it will be easier.

2021-04-08 14:42 UTC, agrawalkaushik commented on docs/plugin_monitoring_agent.md
> +| track-index | boolean | true | Track event indexes such that it allows each event to be produced once when monitoring is restarted |
this is lifted from the yang description - I'm open to other suggestions.

2021-04-08 14:43 UTC, agrawalkaushik commented on docs/plugin_monitoring_agent.md
> +| application-filter | string | - | Filter for only including specific applications in the collection |
Its not a collection filter but thats probably a subtle nuance we dont care about. I'll see what I can re-word it.

2021-04-08 14:46 UTC, agrawalkaushik commented on docs/plugin_monitoring_agent.md
> +## Monitoring Agent Release Notes
Eventually yeah, that was the idea - hence the reword. We typically don't document the "first" version but I can add a blurb here for clarity.

2021-04-08 15:09 UTC, BenMatase approved these changes

2021-04-08 15:11 UTC, gregschrock commented on docs/plugin_monitoring_agent.md
> +## Monitoring Agent Release Notes
No need for a reword. I just wanted to understand.

2021-04-08 15:19 UTC, agrawalkaushik commented on docs/plugin_monitoring_agent.md
> +                    filter              service
itemization is our default for the metrics collector https://github.com/128technology/telegraf/blob/06288994995f8017ed8be7e8d8a9bd020951bbcc/plugins/inputs/t128_metrics/retriever.go#L215

2021-04-08 15:32 UTC, agrawalkaushik commented on docs/plugin_monitoring_agent.md
> +| track-index | boolean | true | Track event indexes such that it allows each event to be produced once when monitoring is restarted |
how about `Enable best effort tracking of events generated while the output cannot be reached`

2021-04-08 15:34 UTC, agrawalkaushik commented on docs/plugin_monitoring_agent.md
> +| application-filter | string | - | Filter for only including specific applications in the collection |
done

2021-04-08 15:55 UTC, BenMatase approved these changes

2021-04-09 13:50 UTC, MichaelBaj approved these changes

2021-04-09 15:00 UTC, merged