updates for Installer 3.0 release. This does not yet contain ANY of the installer-3.0-updates.
128technology/docs pull request #221
Opened 2021-04-09 20:58 UTC by Chr1st0ph3rTurn3r

Installer 3.0 updates will be merged after that branch is released.

2021-04-09 21:08 UTC, MichaelBaj approved these changes

2021-04-12 11:39 UTC, jeffmart requested changes

2021-04-12 11:39 UTC, jeffmart commented on docs/release_notes_128t_4.5.md
> +- **I95-39649/BEL-42 Routers not going to running state when no release.pem (certificate).** Routers using token-based software access for installation or upgrade no longer look for both the certific
Lets reword this, the token suport is new so does not really apply from an end user perspective. Lets consider something like:

**I95-39649/BEL-42 Conductors/Routers on initial deployment not going to running state ** Conductors/Routers on initial deployment would not transition to a running state until a certificate was added.

2021-04-12 11:39 UTC, jeffmart commented on docs/release_notes_128t_5.0.md
> +- **I95-39649/BEL-42 Routers not going to running state when no release.pem (certificate).** Routers using token-based software access for installation or upgrade no longer look for both the certific
Same as above

2021-04-12 11:39 UTC, jeffmart commented on docs/release_notes_128t_5.1.md
> +- **I95-39649/BEL-42 Routers not going to running state when no release.pem (certificate).** Routers using token-based software access for installation or upgrade no longer look for both the certific
Same as above

2021-04-12 12:39 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +- **I95-39649/BEL-42 Routers not going to running state when no release.pem (certificate).** Routers using token-based software access for installation or upgrade no longer look for both the certific
done

2021-04-12 12:39 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.0.md
> +- **I95-39649/BEL-42 Routers not going to running state when no release.pem (certificate).** Routers using token-based software access for installation or upgrade no longer look for both the certific
done

2021-04-12 12:39 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-39649/BEL-42 Routers not going to running state when no release.pem (certificate).** Routers using token-based software access for installation or upgrade no longer look for both the certific
done

2021-04-12 13:56 UTC, jeffmart approved these changes

2021-04-12 14:13 UTC, MichaelBaj approved these changes

2021-04-12 14:34 UTC, merged