Update CLI reference for show application names
128technology/docs pull request #225
Opened 2021-04-15 01:36 UTC by agrawalkaushik

2021-04-15 07:27 UTC, ptimmons requested changes
Small nits.

2021-04-15 07:27 UTC, ptimmons commented on docs/cli_reference.md
> +| Ip Tuple Count | The number of address and ports associated with the application. |
s/address/addresses

2021-04-15 07:27 UTC, ptimmons commented on docs/cli_reference.md
> +| Date Discovered | The time at which the router first learned this application. Restarting the router or deletion of the application will reset the time.  |
Restarting the router or deleting the application

2021-04-15 13:28 UTC, MichaelBaj approved these changes

2021-04-15 14:22 UTC, robert-patterson submitted a review, later dismissed

2021-04-15 15:51 UTC, agrawalkaushik commented on docs/cli_reference.md
> +| Ip Tuple Count | The number of address and ports associated with the application. |
done

2021-04-15 15:51 UTC, agrawalkaushik commented on docs/cli_reference.md
> +| Date Discovered | The time at which the router first learned this application. Restarting the router or deletion of the application will reset the time.  |
done

2021-04-15 15:52 UTC, ptimmons approved these changes

2021-04-16 19:55 UTC, MichaelBaj approved these changes

2021-04-16 19:55 UTC, merged