Write procedure for troubleshooting duplicate asset IDs
128technology/docs pull request #226
Opened 2021-04-20 23:13 UTC by tcarroll25

Write procedure for troubleshooting duplicate asset IDs and add that procedure to the troubleshooting section

2021-04-21 12:12 UTC, Chr1st0ph3rTurn3r approved these changes

2021-04-21 12:12 UTC, Chr1st0ph3rTurn3r commented on docs/ts_ap_duplicate_assets.md
> +An asset whose has a duplicate asset ID error can be seen from the conductor CLI using the `show assets` command with a provided asset-id. For example:
"An asset that has..."

2021-04-21 12:26 UTC, tcarroll25 commented on docs/ts_ap_duplicate_assets.md
> +An asset whose has a duplicate asset ID error can be seen from the conductor CLI using the `show assets` command with a provided asset-id. For example:
Fixed

2021-04-21 12:39 UTC, jeffmart commented on docs/ts_ap_duplicate_assets.md
> +The user needs to drop to the Linux shell and delete the accepted and denied keys with the same asset ID using the `t128-salt-key -d <asset-id>` command. For example:
While those that are familiar with Linux might recognize that the shell is for the root user (see #) might be good to call this out. I would not expect the t128-salt-key command to work as a non-root user.

2021-04-21 12:40 UTC, jeffmart requested changes

2021-04-21 12:40 UTC, jeffmart commented on docs/ts_ap_duplicate_assets.md
> +The terms "salt-master" and "conductor" are used interchangeably throughout this document. "Salt-master" refers to the salt-master process running on conductor, which orchestrates tasks for AP.  Also
nit: "process running on conductor" might flow better with "process running on the conductor"

2021-04-21 13:15 UTC, MichaelBaj requested changes

2021-04-21 13:15 UTC, MichaelBaj commented on docs/ts_ap_duplicate_assets.md
> +This document describes the process for troubleshooting the duplicate asset ID error with Automated Provisioning (AP).
This introduction would benefit from an explanation of the situations that would result in a duplicate asset ID.
e.g., A duplicate Asset ID may be the cause of 128T SSRs being cloned from staging and have not properly completed their initialization to obtain a unique ID.

2021-04-21 13:15 UTC, MichaelBaj commented on docs/ts_ap_duplicate_assets.md
> +If the root cause was indeed a salt-minion that regenerated new keys and not two different salt-minions with the same ID, then this procedure will solve your problem and the asset will reconnect prop
Is this statement implying that it is possible for two minions to generate the same key? Shouldn't the odds of this be astronomically low? Have you seen this happen?

2021-04-21 13:15 UTC, MichaelBaj commented on docs/ts_ap_duplicate_assets.md
> +Tracking down the asset with the duplicate ID is not always easy. Since the salt-master automatically denies the authentication attempt from this bad actor, the conductor has no insight into the IP a
This troubleshooting guide should point out the case where a bad actor may be attempting to connect to the Conductor by cloning an existing 128T SSR. I would add a section that goes through some validation steps to connect to the currently connected router to ensure its authenticity.

IMO, the right course of action is to deny both duplicate minions until the systems are authenticated. Once authenticated, regenerate a new minion ID and keys for the authentic minion and keep the other system denied until it can be claimed.

2021-04-21 14:31 UTC, ian-h-chamberlain approved these changes

2021-04-21 14:31 UTC, ian-h-chamberlain commented on docs/ts_ap_duplicate_assets.md
> +It is not always clear which situation is causing the duplicate asset ID error. If an asset is in the disconnected state and has a duplicate asset ID error then the conductor is unable to distinguish
This paragraph was a bit tough to follow for me, I might just simplify it to say something like


> There are multiple situations that may cause a duplicate asset ID error.
> 
> * A single salt-minion disconnected, had its key regenerated, and reconnected
>   * In this case, the asset may show as `disconnected`
> * Two salt-minions with the same ID attempted to connect
>   * In this case, either the `connected` asset or the denied minion may be the correct one

2021-04-21 15:21 UTC, tcarroll25 commented on docs/ts_ap_duplicate_assets.md
> +The terms "salt-master" and "conductor" are used interchangeably throughout this document. "Salt-master" refers to the salt-master process running on conductor, which orchestrates tasks for AP.  Also
I copy and pasted this from another doc, ill fix it in both places

2021-04-21 15:22 UTC, tcarroll25 commented on docs/ts_ap_duplicate_assets.md
> +The user needs to drop to the Linux shell and delete the accepted and denied keys with the same asset ID using the `t128-salt-key -d <asset-id>` command. For example:
Added a note at the first instance of `t128-salt-key` in the document

2021-04-21 15:26 UTC, tcarroll25 commented on docs/ts_ap_duplicate_assets.md
> +It is not always clear which situation is causing the duplicate asset ID error. If an asset is in the disconnected state and has a duplicate asset ID error then the conductor is unable to distinguish
Good call, fixed

2021-04-21 17:57 UTC, tcarroll25 commented on docs/ts_ap_duplicate_assets.md
> +This document describes the process for troubleshooting the duplicate asset ID error with Automated Provisioning (AP).
Good call, added that example and a few more

2021-04-21 18:01 UTC, tcarroll25 commented on docs/ts_ap_duplicate_assets.md
> +If the root cause was indeed a salt-minion that regenerated new keys and not two different salt-minions with the same ID, then this procedure will solve your problem and the asset will reconnect prop
No thats not what I meant, I will clarify it. I meant two minions with the same ID and different keys.

2021-04-21 18:28 UTC, tcarroll25 commented on docs/ts_ap_duplicate_assets.md
> +Tracking down the asset with the duplicate ID is not always easy. Since the salt-master automatically denies the authentication attempt from this bad actor, the conductor has no insight into the IP a
@MichaelBaj `IMO, the right course of action is to deny both duplicate minions`: The only problem here is then we can't learn anything about either system. I think most people who want this document dont know where the hell all these duplicate asset IDs are and want help finding them, *cough* AAP. I'll try to add some more debugging options then end with delete both keys and hope you find the systems.

2021-04-22 14:40 UTC, MichaelBaj requested changes

2021-04-22 14:40 UTC, MichaelBaj commented on docs/ts_ap_duplicate_assets.md
> +* 128T SSRs being cloned from staging and have not properly completed their initialization to obtain a unique ID
Minor rewording suggestion:
* 128T SSR has been cloned from staging and has not completed the initialization procedure, creating a unique ID

2021-04-22 14:40 UTC, MichaelBaj commented on docs/ts_ap_duplicate_assets.md
> +1. Two salt-minions with the same ID attempted to connect
This should be 2.

2021-04-22 14:40 UTC, MichaelBaj commented on docs/ts_ap_duplicate_assets.md
> +1. There are two salt-minions trying to authenticate with the same salt-minion ID.
This should be 2.

2021-04-22 14:40 UTC, MichaelBaj commented on docs/ts_ap_duplicate_assets.md
> +1. Delete both the accepted and denied salt-keys on the conductor(s) with `t128-salt-key` as stated above
I believe markdown expects that numbered lists increment sequentially (https://www.markdownguide.org/basic-syntax#ordered-lists)

2021-04-22 14:50 UTC, tcarroll25 commented on docs/ts_ap_duplicate_assets.md
> +1. Delete both the accepted and denied salt-keys on the conductor(s) with `t128-salt-key` as stated above
From the best practices doc: "The numbers don’t have to be in numerical order, but the list should start with the number one.". The second row shows the list rendered correctly even with all 1s. I like it because I don't have to manually reorder all the numbers if I add new steps, markdown will always render it properly:

![Screen Shot 2021-04-22 at 10 47 10 AM](https://user-images.githubusercontent.com/1236357/115735443-7b89a580-a358-11eb-9267-f70e3478ae2b.png)

2021-04-22 14:52 UTC, tcarroll25 commented on docs/ts_ap_duplicate_assets.md
> +* 128T SSRs being cloned from staging and have not properly completed their initialization to obtain a unique ID
done

2021-04-22 14:52 UTC, MichaelBaj commented on docs/ts_ap_duplicate_assets.md
> +1. Delete both the accepted and denied salt-keys on the conductor(s) with `t128-salt-key` as stated above
![image](https://user-images.githubusercontent.com/5543991/115735875-d0c5b700-a358-11eb-964b-2378e5d3f25e.png)

awesome

2021-04-22 14:53 UTC, tcarroll25 commented on docs/ts_ap_duplicate_assets.md
> +1. There are two salt-minions trying to authenticate with the same salt-minion ID.
Markdown still renders properly per later comment

2021-04-22 14:53 UTC, tcarroll25 commented on docs/ts_ap_duplicate_assets.md
> +1. Two salt-minions with the same ID attempted to connect
Markdown still renders properly per later comment

2021-04-22 14:56 UTC, MichaelBaj approved these changes

2021-04-22 14:57 UTC, ian-h-chamberlain approved these changes

2021-04-23 15:56 UTC, jeffmart approved these changes

2021-04-23 16:08 UTC, merged