Release notes 4.5.8
128technology/docs pull request #229
Opened 2021-04-22 15:50 UTC by Chr1st0ph3rTurn3r

2021-04-22 21:18 UTC, MichaelBaj requested changes

2021-04-22 21:18 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +- **I95-39798 Token update and available version update stuck on GPG key access:** The upgrade check has been modified to verify the token update.
**I95-39798 Version update check may get stuck on GPG key access when using an access token:** The software upgrade version check has been modified to support access tokens."

2021-04-23 13:14 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +- **I95-38758 Validate management-over-forwarding and default-route:** A missing default-route prevents the ifcfg from generating. A validation check has been put in place to verify that when managem
done

2021-04-23 13:20 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +- **I95-39544 Non-persistent template fields:** Fields filled in by a user are no longer persisted with the template. When a template is re-opened, the fields are blank and ready for new values.
Created a New Features section and added this, along with the suggested edit.

2021-04-23 13:26 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +- **I95-39580 Reference Candidate Config Values in a Template:** Using the `refconfig` tag in Advanced Mode allows you to reference a value from a running configuration.
Moved to new features and edited.

2021-04-23 13:34 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +- **I95-39632 Power Saver using stale data:** Resolved an issue with the power saver using stale data after the device-type changes between locked and lockless.
edited

2021-04-23 13:34 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +- **I95-39788 Inconsistent services after modifying certain service configs:** Changes made to properly handle service modifications for special services.
edited

2021-04-23 13:35 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +- **I95-39798 Token update and available version update stuck on GPG key access:** The upgrade check has been modified to verify the token update.
edited

2021-04-23 17:11 UTC, MichaelBaj submitted a review, later dismissed

2021-04-27 17:15 UTC, jeffmart commented on docs/about_releases.md
> +| [5.1.2](release_notes_128t_5.1.md#release-512)   | April 30, 2021     |                    | Not Applicable*    | October 16, 2021   |
Do we want this in for this release right now? (I expect that 5.1.2 will require its own update.)

2021-04-28 12:39 UTC, MichaelBaj approved these changes

2021-04-28 14:34 UTC, merged