adding 512 release notes. Waiting on additional info for 2 issues.
128technology/docs pull request #230
Opened 2021-04-22 19:24 UTC by Chr1st0ph3rTurn3r

2021-04-23 15:24 UTC, MichaelBaj requested changes

2021-04-23 15:24 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-39639 Packet transmit fails when traffic-eng is enabled with multiple worker cores:**
did you mean to add some more detailed text to follow the heading, such as "this issue has now been resolved"

2021-04-23 15:24 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95- Remote router login ignores 'User' selection:**
did you mean to add some more detailed text to follow the heading, such as "this issue has now been resolved"

2021-04-23 15:24 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-39764 Per Adjacency Traffic Eng Crashing For Multiple Paths on Configuration:** Resolved an issue when receiving adjacencies with out of order path-indexes.
Eng should be expanded to engineering

2021-04-23 15:24 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-39798 Token update and available version update stuck on GPG key access:** The upgrade check has been modified to verify the token update.
See my comments from 4.5.8 release notes

2021-04-23 17:30 UTC, MichaelBaj approved these changes

2021-04-30 21:10 UTC, jeffmart approved these changes

2021-04-30 21:21 UTC, MichaelBaj approved these changes

2021-04-30 22:08 UTC, merged