Locating defects in documentation
128technology/docs pull request #235
Opened 2021-05-04 19:30 UTC by Chr1st0ph3rTurn3r

…. Added language describing the process and providing links to earlier releases.

2021-05-04 20:59 UTC, jeffmart requested changes

2021-05-04 20:59 UTC, jeffmart commented on docs/release_notes_128t_4.5.md
> +**Includes changes from:** [Version 4.5.7](release_notes_128t_4.5.md#release-457) and [Version 4.5.6](release_notes_128t_4.5.md#release-456).
This is redundant and should be removed. The latest software on the same Major.Minor version will have the fixes in the previous release.

2021-05-04 20:59 UTC, jeffmart commented on docs/release_notes_128t_4.5.md
> +**Includes changes from:** Only includes support for Installer 3.0.
Redundant because the next line states when this version has, and because the latest  Major.Minor version has the previos version release fixes (aka 4.5.6 fixes are in 4.5.7) this is all in the same release notes.

2021-05-04 20:59 UTC, jeffmart commented on docs/release_notes_128t_5.1.md
> +**Includes changes from:** [Version 4.5.8 April 28, 2021](release_notes_128t_4.5.md#release-458) and [Version 5.1.1 April 12, 2021](release_notes_128t_5.1.md#release-511).
Can remove the 5.1.1 reference above because it is right below and is in the same Major.Minor version fixes.

2021-05-04 20:59 UTC, jeffmart commented on docs/release_notes_128t_5.1.md
> +**Includes changes from:** [Version 5.1.0 March 15, 2012](release_notes_128t_5.1.md#release-5.1)
Remove this as this is redundant and the 5.1.0 release notes are below in this same page.

2021-05-04 20:59 UTC, jeffmart commented on docs/release_notes_128t_5.1.md
need to add to the 5.1.0 section to point to the 4.5.5 release as this is chronologically AND numerically after 4.5.5

2021-05-04 21:39 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +**Includes changes from:** [Version 4.5.7](release_notes_128t_4.5.md#release-457) and [Version 4.5.6](release_notes_128t_4.5.md#release-456).
removed.

2021-05-04 21:39 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_4.5.md
> +**Includes changes from:** Only includes support for Installer 3.0.
removed.

2021-05-04 21:40 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
added

2021-05-04 21:40 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +**Includes changes from:** [Version 5.1.0 March 15, 2012](release_notes_128t_5.1.md#release-5.1)
removed.

2021-05-04 21:40 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +**Includes changes from:** [Version 4.5.8 April 28, 2021](release_notes_128t_4.5.md#release-458) and [Version 5.1.1 April 12, 2021](release_notes_128t_5.1.md#release-511).
removed.

2021-05-04 21:53 UTC, jeffmart approved these changes

2021-05-05 13:48 UTC, MichaelBaj approved these changes

2021-05-05 14:14 UTC, ptimmons approved these changes

2021-05-05 14:58 UTC, merged