Creating 513 release notes and updating the release list.
128technology/docs pull request #237
Opened 2021-05-12 15:29 UTC by Chr1st0ph3rTurn3r

2021-05-13 17:45 UTC, MarkusJork commented on docs/config_bgp.md
>  admin@branchoffice1.seattlesite1 (routing-protocol[type=bgp])# local-as 100 admin@branchoffice1.seattlesite1 (routing-protocol[type=bgp])# router-id 1.1.1.128
These should be two separate lines. The first line ends right after `local-as 100`

2021-05-13 17:48 UTC, MarkusJork commented on docs/config_bgp.md
> +3. Configure the `address-family` using `ipv4-unicast`. At least one `address-family`must be configured, and typically is set as `ipv4-unicast`. If your deployment uses other address families (e.g.,
This statement is not wrong. But at the moment we have only implemented support for the `ipv4-unicast` address family in our config data model.

2021-05-13 18:28 UTC, MarkusJork commented on docs/config_bgp.md
> +When VRFs have overlapping address space, the conductor needs additional information to determine which two BGP instances are meant to peer with each other. By explicitly disabling the auto-generatio
The first sentence in this paragraph explains a problem with establishing BGP over VRF across different VRFs.
So I suggest removing it here and adding the info below.

2021-05-13 18:28 UTC, MarkusJork commented on docs/config_bgp.md
> +In this example, the BGP instance configured in the default VRF on a CPE router needs to establish a session with a VRF BGP instance in the VPN provider’s router. To enable the generation of appropri
After this add a sentence:
"The reason is that the VRFs may have overlapping address space."

2021-05-13 18:28 UTC, MarkusJork commented on docs/config_bgp.md
> +For a BGP neighbor residing in the default VRF, the generated BGP service remains the same, and the tenant associated with this BGP neighbor in the default VRF is named `bgp_speaker`.
This sentence is lifted from the funcspec which compares the pre-5.1.3 behavior to 5.1.3. That's why it says "remains the same".
I'm not sure we want that language in the configuration guide. Maybe just say:

For a BGP neighbor residing in the default VRF, the generated BGP service is named `_bgp_<router-name>_<routing-interface-name>`, and the tenant associated with this BGP neighbor in the default VRF is named `_bgp_speaker_`.

2021-05-13 18:28 UTC, MarkusJork commented on docs/config_bgp.md
> +For a BGP neighbor residing in a non-default VRF, the generated BGP service is named `bgp_<router-name>_<vrf-name>_<vrf-routing-interface-name>`. The associated tenant is named `_<vrf-name>._vrf_bgp_
The service name starts with `_bgp_` and not jus `bgp_`.

2021-05-13 18:40 UTC, Chr1st0ph3rTurn3r commented on docs/config_bgp.md
>  admin@branchoffice1.seattlesite1 (routing-protocol[type=bgp])# local-as 100 admin@branchoffice1.seattlesite1 (routing-protocol[type=bgp])# router-id 1.1.1.128
done

2021-05-13 18:41 UTC, Chr1st0ph3rTurn3r commented on docs/config_bgp.md
> +3. Configure the `address-family` using `ipv4-unicast`. At least one `address-family`must be configured, and typically is set as `ipv4-unicast`. If your deployment uses other address families (e.g.,
I'm going to leave it as is. This content has been in the guide since this topic was written.

2021-05-13 18:45 UTC, Chr1st0ph3rTurn3r commented on docs/config_bgp.md
> +When VRFs have overlapping address space, the conductor needs additional information to determine which two BGP instances are meant to peer with each other. By explicitly disabling the auto-generatio
Removed "When VRFs have overlapping address space, the conductor needs additional information to determine which two BGP instances are meant to peer with each other."

2021-05-13 18:51 UTC, Chr1st0ph3rTurn3r commented on docs/config_bgp.md
> +In this example, the BGP instance configured in the default VRF on a CPE router needs to establish a session with a VRF BGP instance in the VPN provider’s router. To enable the generation of appropri
Edited it as below:
"To enable the generation of appropriate BGP service and service-route configuration objects, and in cases where the VRF's have overlapping address space, some additional BGP neighbor configuration is required."

2021-05-13 18:54 UTC, Chr1st0ph3rTurn3r commented on docs/config_bgp.md
> +For a BGP neighbor residing in the default VRF, the generated BGP service remains the same, and the tenant associated with this BGP neighbor in the default VRF is named `bgp_speaker`.
done.

2021-05-13 18:55 UTC, Chr1st0ph3rTurn3r commented on docs/config_bgp.md
> +For a BGP neighbor residing in a non-default VRF, the generated BGP service is named `bgp_<router-name>_<vrf-name>_<vrf-routing-interface-name>`. The associated tenant is named `_<vrf-name>._vrf_bgp_
Fixed

2021-05-13 19:06 UTC, MarkusJork approved these changes

2021-05-17 13:15 UTC, MichaelBaj requested changes

2021-05-17 13:15 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +**Includes changes from:** [Version 5.2 May 10, 2021](release_notes_128t_5.2.md).
This reference may be misleading as it suggests that the features from 5.2 would be included in the 5.1.3 release, which is not the case.

2021-05-17 13:15 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-39854 Mgmt over DHCP interface no active after 128T shutdown:** Resolved an issue where on 128T shutdown the management interface over forwarding dhcp is not started.
"no" should be "not"

2021-05-17 13:15 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-40000 LTE Module Reset overwrites the LTE interface MTU:** The LTE target interface MTU is now persisted at 90000.
I believe this is only for the internal KNI interface. I don't believe the end user will know about this setting. Please check with @chaoz0312 for the correct wording.

2021-05-17 14:13 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +**Includes changes from:** [Version 5.2 May 10, 2021](release_notes_128t_5.2.md).
removed

2021-05-17 14:15 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-39854 Mgmt over DHCP interface no active after 128T shutdown:** Resolved an issue where on 128T shutdown the management interface over forwarding dhcp is not started.
edited

2021-05-17 14:46 UTC, MichaelBaj approved these changes

2021-05-17 14:48 UTC, merged