Documentation 5.3
128technology/docs pull request #242
Opened 2021-05-21 16:05 UTC by Chr1st0ph3rTurn3r

2021-05-25 04:10 UTC, migolnikov commented on docs/bcp_tenants.mdx
> +By adding an `access-policy` allowing (or denying) `_internal_` on your service, you can selectively permit processes running in Linux outbound network access. This is commonplace for "host originate
ToDo: we need to double check if this applies to port 443 and thus REST. It probably does, but I want to be extra sure

2021-05-25 04:10 UTC, migolnikov commented on docs/bcp_conductor_deployment.md
> +>>> The `netconf` configuration is not applicable to version 5.3 and later. NETCONF controls have been replaced with REST API controls, with no loss of functionality.
This is factually correct but we may want to add "have been replaced with REST API controls **in versions 5.1 and later**".  It may be tmi, lets discuss.

2021-05-25 04:10 UTC, migolnikov commented on docs/config_snmp.md
> +The 128T implementation of SNMP relies on the *snmpd* process running within the host operating system. All configuration for SNMP, however, is done within the 128T's data model via its administrativ
GUI is REST, so this would work: (e.g., PCLI, GUI, etc.). P.S. PCLI in 5.1+ uses REST exclusively.

2021-05-25 04:10 UTC, migolnikov commented on docs/config_transport_encryption.md
> +---
is this new in 5.3? I don't think so

2021-05-26 14:29 UTC, Chr1st0ph3rTurn3r commented on docs/config_snmp.md
> +The 128T implementation of SNMP relies on the *snmpd* process running within the host operating system. All configuration for SNMP, however, is done within the 128T's data model via its administrativ
Removed REST reference, as indicated.

2021-05-26 14:29 UTC, Chr1st0ph3rTurn3r commented on docs/config_transport_encryption.md
> +---
Removed.

2021-05-27 16:29 UTC, dfitzpatrick128 commented on docs/bcp_conductor_deployment.md
> +>>> The `netconf` configuration is not applicable to version 5.3 and later. NETCONF controls have been replaced with REST API controls, with no loss of functionality.
I agree I think we should include it.

2021-05-27 16:32 UTC, dfitzpatrick128 commented on docs/intro_system_reqs.md
> +Each Ethernet interface within a Linux system has a unique PCI address. This PCI address is used to bind the 128T router's configuration to the underlying hardware. Session Smart Routing (SSR) functi
connection may be confusing or not if it was me i would use "interface changes" not "connection changes"

2021-05-27 16:34 UTC, dfitzpatrick128 commented on docs/intro_system_reqs.md
> +Connect to a PCI slot:
Believe this should be "Connect an additional PCI card (if possible)"

2021-05-27 16:53 UTC, dfitzpatrick128 requested changes
a few changes to verbiage but looks great. ideally the additions to  docs/intro_system_reqs.md  would be in the current docs too

2021-05-27 17:23 UTC, Chr1st0ph3rTurn3r commented on docs/intro_system_reqs.md
> +Connect to a PCI slot:
done

2021-05-27 17:23 UTC, Chr1st0ph3rTurn3r commented on docs/intro_system_reqs.md
> +Each Ethernet interface within a Linux system has a unique PCI address. This PCI address is used to bind the 128T router's configuration to the underlying hardware. Session Smart Routing (SSR) functi
change made

2021-05-27 17:25 UTC, dfitzpatrick128 submitted a review, later dismissed

2021-05-29 11:01 UTC, ptimmons commented on docs/intro_system_reqs.md
> +Interfaces on host systems running as a 128T router, either baremetal or virtual deployment environments, are assigned for packet forwarding. At least one dedicated interface is required for packet f
"baremetal" isn't a word, this should remain as "bare metal" (or alternatively "bare-metal"). https://en.wikipedia.org/wiki/Bare-metal_server

2021-05-29 11:02 UTC, ptimmons commented on docs/config_snmp.md
> +Each row of the metrics table is keyed by two objects, the t128MetricAlias and the t128MetricIndex. The t128MetricAlias is an arbitrary string of up to 64 characters long that represents a descriptio
This should remain as-is... it's not a punctuation error, the suffix on this metric is actually `_0`.

2021-06-01 15:30 UTC, Chr1st0ph3rTurn3r commented on docs/intro_system_reqs.md
> +Interfaces on host systems running as a 128T router, either baremetal or virtual deployment environments, are assigned for packet forwarding. At least one dedicated interface is required for packet f
done - thank you.

2021-06-01 15:30 UTC, Chr1st0ph3rTurn3r commented on docs/config_snmp.md
> +Each row of the metrics table is keyed by two objects, the t128MetricAlias and the t128MetricIndex. The t128MetricAlias is an arbitrary string of up to 64 characters long that represents a descriptio
change made

2021-06-03 19:13 UTC, MichaelBaj requested changes

2021-06-03 19:13 UTC, MichaelBaj commented on docs/config_ha.md
> +![Edit HA Configuration](/img/config_HA_interactive.gif)
This should be removed now that you created the other PR

2021-06-24 21:00 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +Domain-Based Web Filtering is the ability to categorize internet traffic based on the domain name or domain-name-category. This provides the option for users to create generic services for a broad ra
`Domain-Based` -> `Domain Based`

2021-06-24 21:04 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +Domain-Based Web Filtering is the ability to categorize internet traffic based on the domain name or domain-name-category. This provides the option for users to create generic services for a broad ra
I know the config is called `domain-name-category` but in this context it seems out of place. Can we just call it `category` instead.

2021-06-24 21:05 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +Domain-Based Web Filtering is the ability to categorize internet traffic based on the domain name or domain-name-category. This provides the option for users to create generic services for a broad ra
ESPN.com, NFL.com, NHL.com should all be `espn.com, nfl.com, nhl.com` etc.

2021-06-24 21:07 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +Domain-Based Web Filtering is the ability to categorize internet traffic based on the domain name or domain-name-category. This provides the option for users to create generic services for a broad ra
`Domain-learning` -> `domain learning`

2021-06-24 21:08 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +Domain-Based Web Filtering is the ability to categorize internet traffic based on the domain name or domain-name-category. This provides the option for users to create generic services for a broad ra
`or add new categories if necessary` - though true in the current implementation, this is currently under a bit of a re-review if you will. Can we remove this line for now - we can add it later once we do the work in 5.4.0 time frame.

2021-06-24 21:21 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +Categories can be assigned to services, providing the ability to filter content based on an entire category; for example, denying access to all domains in the Adult category. Services can also be ass
> Categories can be assigned to services, providing the ability to filter content based on an entire category;

I think this statement is a bit confusing. Can we re-word it do be something like `Services can be defined based on categories to filter a broad set of related domains`

2021-06-25 01:42 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +## Configuring Domain-Based Web Filtering from the User Interface
Instead of saying `User Interface` in each spot - can we just call it GUI or UI? it sounds out of place the way written here...

2021-06-25 01:44 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +title: Configuring Domain-Based Web Filtering
`Web Filtering` to me implies denying traffic. Here and throughout the document can we instead use the work `Domain based routing` instead of `Domain-Based web filtering`.

2021-06-25 01:47 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +The domain name category field is pre-populated with a default list of categories. Select from the existing categories for each service, or configure specific categories and add domains manually.
> The domain name category field is pre-populated with a default list of categories.

This is actually not the case - there is no such pre population that I see or know of on the GUI

> select from the existing categories for each service

which makes this impossible

> configure specific categories and add domains manually.

This is true but can be easily collapsed with the paragraph above.

2021-06-25 01:48 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +**How does this process work? I have 5.2 installed and did not see the default categories. I created categories, but even after adding them, they do not show up in the drop down to be used for other
I'm not sure if you got the information from the FS or somewhere else but its not the case. I'll include this in the App ID UX improvement EPIC but lets remove the reference to this for now.

2021-06-25 01:50 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +To allow the dynamic learning of domain categories, enable the feature on the Basic Information screen for the service.
The statement here does not line up with teh graphic below. The `Generate Application Identification Categories` simply allows a set of pre determined categories based child services to be generated. So I would just say something about that instead - its not really related to dynamic learning.

2021-06-25 01:51 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +The procedure to configure domain-based web filtering is provided below.
Configuration should come before the show commands and rest of the sections isntead of saying its provided below.

2021-06-25 01:51 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +- reate a child service to filter
typo `reate` -> `Create`

2021-06-25 01:52 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +- reate a child service to filter
`reate a child service to filter` -> `Create a child service for domain based routing `

2021-06-25 01:54 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +The child service classifies the traffic and provides the option to filter different domains and categories. We will create two services, one of which will be filtered out (denied).
`option to filter different` -> `option to route different`

So far in the document I think the `will be filtered out` is the only correct way to use the term filtering for this feature IMO.

2021-06-25 01:55 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +4.	Set Scope to **public**.
IMO this is generally not recommended as it provides open access. Besides the child services inherit its scope from the parent so best to remove this step altogether.

2021-06-25 01:56 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +6.	Set generate application identification categories to **true**.
This step is at the wrong spot. This toggle is meant for the parent service rather than a child service like the on you're building here

2021-06-25 01:56 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +5.	Set share service routes to **true**.
step 5 and 6 here should be removed

2021-06-25 01:58 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +### Configure the Tenant
This whole step seems out of place to me. Typically at this point in the configuration the tenant configuration is already done. I'd vote for removing this `Configure the Tenant` section altogether.

2021-06-25 02:00 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +Create an access policy on a service to deny (filter) traffic from the indicated domain or category.
This break in the flow is confusing and un-necessary. You should just collapse the `access-policy` configuration with teh `#### Create the second service, the one to be filtered ` section. Something like

8. Configure the access-policy to deny the relevant tenants. For example `office-wifi` tenant could be denied access to the `netflix.internet` service

2021-06-25 02:01 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +![Select Applications Seen](/img/dbwf_appl_seen.png)
The `Applications Seen` section should be circled or highlighted in this graphic

2021-06-25 02:02 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +*Where are the Learning Mode statistics/information available?*
That's basically the show commands section - just move it here.

2021-06-25 02:03 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +*Need examples of the show commands and descriptions of what is displayed.*
Please sanitize as appropriate but here are the outputs

```
admin@node1.kaushik-home# show domain-names
Thu 2021-06-24 22:03:28 EDT

Retrieving from 'node1.kaushik-home'...
Node: node1.kaushik-home Page 1

=================================== =============== ================= =====================
 Domain                              Session Count   Category          Last Updated
=================================== =============== ================= =====================
 ps16.pndsn.com                                 44   <Uncategorized>   2021-06-24 21:37:52
 ps17.pndsn.com                                 40   <Uncategorized>   2021-06-24 21:37:52
 ps9.pndsn.com                                  39   <Uncategorized>   2021-06-24 21:37:53
 ps3.pndsn.com                                  36   <Uncategorized>   2021-06-24 21:37:52
 ps14.pndsn.com                                 36   <Uncategorized>   2021-06-24 21:37:52
 ps6.pndsn.com                                  30   <Uncategorized>   2021-06-24 21:37:52
 ps7.pndsn.com                                  20   <Uncategorized>   2021-06-24 22:01:26
 ps4.pndsn.com                                  20   <Uncategorized>   2021-06-24 21:37:52
 ps15.pndsn.com                                 20   <Uncategorized>   2021-06-24 21:37:52
 ps1.pndsn.com                                  20   <Uncategorized>   2021-06-24 21:37:52
 ps2.pndsn.com                                  10   <Uncategorized>   2021-06-24 21:37:52
 ps18.pndsn.com                                 10   <Uncategorized>   2021-06-24 21:38:15
 ps13.pndsn.com                                 10   <Uncategorized>   2021-06-24 21:38:06
 api-ws.mistsys.com                              3   Technology        2021-06-24 21:37:54
 wss-primary.slack.com                           2   Business          2021-06-24 21:37:53
 mtalk.google.com                                2   Conferencing      2021-06-24 07:49:11
 ep-terminator-staging.mistsys.net               2   Technology        2021-06-24 20:44:12
 mistsys.atlassian.net                           2   Technology        2021-06-24 21:37:53
 beacons.gvt2.com                                1   Business          2021-06-24 22:01:15
 *.immedia-semi.com                              1   DeviceIoT         2021-06-23 09:29:52
 status-integration.mistsys.com                  1   Technology        2021-06-24 21:37:55
 ssl.gstatic.com                                 1   Business          2021-06-24 22:00:21
 slackb.com                                      1   Business          2021-06-24 22:00:21
 slack.com                                       1   Business          2021-06-24 21:38:21
 skydrive.wns.windows.com                        1   Business          2021-06-24 21:38:08
 push.services.mozilla.com                       1   Business          2021-06-24 21:37:59
 addon-juniper.goskope.com                       1   <Uncategorized>   2021-06-24 21:37:55
 alive.github.com                                1   Technology        2021-06-24 21:37:54
 beacons.gcp.gvt2.com                            1   Business          2021-06-24 22:00:21
 beacons3.gvt2.com                               1   Business          2021-06-24 22:03:15
 beacons4.gvt2.com                               1   Business          2021-06-24 22:02:15
 courier.push.apple.com                          1   Business          2021-06-24 21:37:53
 gateway-juniper.goskope.com                     1   <Uncategorized>   2021-06-24 21:38:01
 github.com                                      1   Computers         2021-06-24 21:38:32
 gs-loc.apple.com                                1   Business          2021-06-24 21:38:37
 ibm.lakesidesoftware.com                        1   <Uncategorized>   2021-06-24 21:41:54
 lp-push-server-770.lastpass.com                 1   Business          2021-06-24 21:37:57

Completed in 0.09 seconds
admin@node1.kaushik-home#
```

and 

```
admin@node1.kaushik-home# show domain-categories
Thu 2021-06-24 22:03:45 EDT
✔ Retrieving domain-name categories...

Node: node1
================= =============== ===================
 Category          Session Count   Domain-name Count
================= =============== ===================
 <Uncategorized>             403                  16
 Advertiser                    0                   0
 Arts                          0                   0
 Business                     14                  13
 CDN                           0                   0
 Computers                     1                   1
 Conferencing                  2                   1
 Cybersecurity                 0                   0
 DeviceIoT                     1                   1
 FileSharing                   0                   0
 Hosting                       0                   0
 Mail                          0                   0
 Recreation                    0                   0
 Reference                     0                   0
 Search                        0                   0
 SocialMedia                   0                   0
 SoftwareUpdates               0                   0
 StreamingMedia                0                   0
 Technology                   13                   6

Completed in 0.08 seconds
admin@node1.kaushik-home#

```

2021-06-25 02:04 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +If Learning Mode is not enabled, statistics are only gathered for categories/domains that are identified in an access-policy.
`in an access-policy` -> `in a service`

2021-06-30 18:09 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +Domain-Based Web Filtering is the ability to categorize internet traffic based on the domain name or domain-name-category. This provides the option for users to create generic services for a broad ra
I changed domain-name-category to domain category, and will refer to it as category elsewhere in the doc. 
As far as Domain-Based vs. Domain Based, I checked the Microsoft Style guide, and they recommend using the hyphen. 
"Hyphenate two or more words that precede and modify a noun as a unit if:
One of the words is a past or present participle (a verb form ending in -ed or -ing and used as an adjective or noun).
Examples:
left-aligned text
free-flowing form
well-defined schema"

2021-06-30 18:27 UTC, agrawalkaushik requested changes
Comments above!

2021-06-30 18:30 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +The domain name category field is pre-populated with a default list of categories. Select from the existing categories for each service, or configure specific categories and add domains manually.
So there is no list of domains? I got that info from the spec. Then the user needs to configure all their own domains and categories?

2021-06-30 18:32 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +**How does this process work? I have 5.2 installed and did not see the default categories. I created categories, but even after adding them, they do not show up in the drop down to be used for other
I did. So in order to use the feature, the user has to configure all their own domains and categories, correct?

2021-06-30 18:35 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +To allow the dynamic learning of domain categories, enable the feature on the Basic Information screen for the service.
This is confusing. Where is this set of "pre-determined categories" coming from if there are no default categories? What is the purpose of dynamic learning? What is the benefit of using the Generate Application Identification Categories? How does that work?

2021-06-30 18:42 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +*Need examples of the show commands and descriptions of what is displayed.*
So the user can run a show command to see a list of categories, but they cannot choose from that list in the UI?

2021-06-30 18:43 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +If Learning Mode is not enabled, statistics are only gathered for categories/domains that are identified in an access-policy.
done

2021-06-30 18:46 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +![Select Applications Seen](/img/dbwf_appl_seen.png)
done

2021-06-30 18:54 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +title: Configuring Domain-Based Web Filtering
Reid had suggested the name Domain-based Web Filtering. I will reach out to him for his input.

2021-06-30 18:55 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +The procedure to configure domain-based web filtering is provided below.
Sure, that makes sense.

2021-06-30 20:17 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +The child service classifies the traffic and provides the option to filter different domains and categories. We will create two services, one of which will be filtered out (denied).
But you are blocking traffic from the domain, you are not routing the domain. Maybe you are using routing to classify the traffic on the router, but I don't see how you can route a domain.

2021-06-30 20:21 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +4.	Set Scope to **public**.
done

2021-07-01 14:54 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +Categories can be assigned to services, providing the ability to filter content based on an entire category; for example, denying access to all domains in the Adult category. Services can also be ass
done

2021-07-07 13:45 UTC, Chr1st0ph3rTurn3r commented on docs/bcp_conductor_deployment.md
> +>>> The `netconf` configuration is not applicable to version 5.3 and later. NETCONF controls have been replaced with REST API controls, with no loss of functionality.
added the bold info.

2021-07-07 13:50 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +**How does this process work? I have 5.2 installed and did not see the default categories. I created categories, but even after adding them, they do not show up in the drop down to be used for other
They do but unfortunately there is no drop down for the available categories

2021-07-07 13:53 UTC, Chr1st0ph3rTurn3r commented on docs/config_ha.md
> +![Edit HA Configuration](/img/config_HA_interactive.gif)
done

2021-07-07 13:54 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +To allow the dynamic learning of domain categories, enable the feature on the Basic Information screen for the service.
Think of the `pre-determined categories` being present in the code but are not exposed to the user in a good way right now. 

> What is the benefit of using the Generate Application Identification Categories? How does that work?

This simply creates a set of child services one for each category.

2021-07-07 13:55 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +The child service classifies the traffic and provides the option to filter different domains and categories. We will create two services, one of which will be filtered out (denied).
You're focussing on just the blocking part but the feature does more than that. You route a domain by defining where the parent service goes

2021-07-07 13:56 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +*Need examples of the show commands and descriptions of what is displayed.*
yes

2021-07-12 13:22 UTC, reidstidolph commented on docs/config_domain-based_web_filter.md
> +title: Configuring Domain-Based Web Filtering
I'd consider domain based web filtering to be the use case we support with the feature. I believe filtering and prioritization are the only use cases we support with this currently, and "routing" based on these domains is actually something we can't do today.

2021-07-12 14:51 UTC, ptimmons commented on docs/config_domain-based_web_filter.md
> +title: Configuring Domain-Based Web Filtering
Maybe it's splitting hairs/semantics, but we can kinda sorta consider the existing implementation as doing some routing. A child service can have more strict or more liberal service policy enforcement than a parent, which could cause it to migrate ("route") to an alternate path in the event of peer path impairment.

2021-07-12 16:56 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +title: Configuring Domain-Based Web Filtering
Routing here is more to indicate that we can process and make forwarding decissions and also process and deny traffic. The filtering refers to me refers to the latter but if the routing verbiage is a sticking point than I'm okay with keeping the current terms. The doc, however, should cover both those cases for these features and not solely focus on denying traffic as its a limited use case IMO.

2021-07-12 19:14 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +6.	Set generate application identification categories to **true**.
done

2021-07-12 19:14 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +5.	Set share service routes to **true**.
done

2021-07-12 19:40 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +*Need examples of the show commands and descriptions of what is displayed.*
That is not going to make for a good user experience.

2021-07-14 20:08 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +**How does this process work? I have 5.2 installed and did not see the default categories. I created categories, but even after adding them, they do not show up in the drop down to be used for other
reorganized.

2021-07-14 20:08 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +The domain name category field is pre-populated with a default list of categories. Select from the existing categories for each service, or configure specific categories and add domains manually.
reorganized.

2021-07-14 20:13 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +To allow the dynamic learning of domain categories, enable the feature on the Basic Information screen for the service.
revised.

2021-07-14 20:24 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +The child service classifies the traffic and provides the option to filter different domains and categories. We will create two services, one of which will be filtered out (denied).
I need a little more information on this. Will ping you directly.

2021-07-14 20:29 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +### Configure the Tenant
Added a note with a link to the Tenant configuration process.

2021-07-14 20:40 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +Create an access policy on a service to deny (filter) traffic from the indicated domain or category.
After removing the Tenant steps, I revised the description and left the procedure. Adding 9 steps to the 5 existing in that section would have made the procedure too long (10 should be the max).

2021-07-14 20:40 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +*Where are the Learning Mode statistics/information available?*
done

2021-07-14 20:40 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +*Need examples of the show commands and descriptions of what is displayed.*
done.

2021-07-19 18:22 UTC, Chr1st0ph3rTurn3r commented on docs/bcp_tenants.mdx
> +By adding an `access-policy` allowing (or denying) `_internal_` on your service, you can selectively permit processes running in Linux outbound network access. This is commonplace for "host originate
This was verified correct.

2021-07-20 21:08 UTC, jeffmart commented on docs/release_notes_128t_5.3.md
> +- **I95-412166 Candidate configuration is not synced between nodes and is not stored on disk:** Configuration changes are made to a “candidate” configuration. In releases prior to 5.3.0 the candidate
Typo here, I think the jira is: I95-41266

2021-07-20 21:14 UTC, ecarson commented on docs/bcp_conductor_deployment.md
> +When deploying a conductor behind a firewall, open 930/TCP (used for NETCONF in versions prior to 5.3) and 4505-4506/TCP (used for salt) to allow a conductor to communicate to managed routers. Open 4
This is not correct, 830 is netconf. We still want 930 open for ssh tunnels.

2021-07-20 21:14 UTC, jeffmart commented on docs/release_notes_128t_5.3.md
> +Additionally, the candidate configuration is no longer synchronized between HA nodes. In release 5.3.0 only the running configuration is synchronized between nodes.
Per IM, this will need to go to the core user doc and that the candidate should be exported regularly if the configuration would will not be commited right away.

2021-07-20 21:16 UTC, ecarson commented on docs/bcp_conductor_deployment.md
> +- The head end fronting the conductor must perform NAT/NAPT to forward 4505-4506/TCP (used for salt), and 930/TCP (used for NETCONF in versions prior to 5.3) to the conductor on the data center LAN.
Same comment as above regarding 830 (netconf over ssh) vs 930 (ssh)

2021-07-20 21:24 UTC, ecarson commented on docs/release_notes_128t_5.3.md
> +- **I95-39457 ServiceSecurityCheck validator should check for next-peer in service-route:** A missing validation check on `next-peer` service routes allows the configuration to be committed without p
This might go better under caveats. It is similar to I95-41076

2021-07-22 19:23 UTC, migolnikov commented on docs/intro_upgrade_considerations.md
> +#### The Candidate configuration is not synced between nodes and is not stored on disk:
This is a major functionality change and in my mind could controversial. On one hand I want to avoid controversy, but on the other hand we need to educate the users. Bottom line is we do not persist or HA candidate config, thus
1) All not yet committed changes are lost on 128T restart (more specifically Config Director process restart)
2) For HA: only the node with the active Config Director is aware of the candidate changes and those changes will be lost on loss of leadership.

2021-07-22 19:23 UTC, migolnikov commented on docs/release_notes_128t_5.3.md
> +## Release 5.3.0
Is there mention anywhere that the RBAC feature added in 5.1.0 is not present in 5.3.0? Since this is for CVS conductor only, this is not something they use or rely on. This is again a potentially controversial subject. We need to decide if this caveat is to be included.

2021-07-23 13:49 UTC, Chr1st0ph3rTurn3r commented on docs/bcp_conductor_deployment.md
> +- The head end fronting the conductor must perform NAT/NAPT to forward 4505-4506/TCP (used for salt), and 930/TCP (used for NETCONF in versions prior to 5.3) to the conductor on the data center LAN.
fixed.

2021-07-23 13:50 UTC, Chr1st0ph3rTurn3r commented on docs/bcp_conductor_deployment.md
> +When deploying a conductor behind a firewall, open 930/TCP (used for NETCONF in versions prior to 5.3) and 4505-4506/TCP (used for salt) to allow a conductor to communicate to managed routers. Open 4
fixed

2021-07-23 13:50 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.3.md
> +- **I95-412166 Candidate configuration is not synced between nodes and is not stored on disk:** Configuration changes are made to a “candidate” configuration. In releases prior to 5.3.0 the candidate
fixed.

2021-07-23 14:35 UTC, Chr1st0ph3rTurn3r commented on docs/intro_upgrade_considerations.md
> +#### The Candidate configuration is not synced between nodes and is not stored on disk:
The blanket statement on this will be to save (export) the config often, and will be added here and to the overall documentation.

2021-07-23 14:37 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.3.md
> +## Release 5.3.0
Since this is going to be a very limited release, and RBAC is slated to come back in 5.3.1, I recommend leaving it out (CVS does not use RBAC). We can provide an internal communication for any SEs that might download and install 5.3 (Max's suggestion).

2021-07-23 14:39 UTC, ptimmons commented on docs/about_releases.md
> +| Version | GA Version | GA Date |
Perhaps change "GA Version" with "Initial GA Version" to imply that later patches are ALSO GA?

2021-07-23 14:39 UTC, ptimmons commented on docs/intro_upgrade_considerations.md
> +Stricter validations have been added to enforce the requirement that a profile must be configured when `performance-monitoring` is enabled on a neighborhood. This requirement was loosely enforced pri
Inconsistent capitalization (version 5.3.0 vs. Version 5.3). Per my comment below, references to 5.3.0 should be replaced with 5.3 throughout this section.

2021-07-23 14:39 UTC, ptimmons commented on docs/intro_upgrade_considerations.md
> +Stricter validations have been added to enforce the requirement that a profile must be configured when `performance-monitoring` is enabled on a neighborhood. This requirement was loosely enforced pri
I don't think the bit about "redundant interfaces during failover" applies to performance-monitoring configuration, this appears to be a copy/paste artifact.

2021-07-23 14:39 UTC, ptimmons commented on docs/intro_upgrade_considerations.md
> +#### A mismatched global_id on redundant interfaces generates an "Error: Candidate configuration is invalid" message.
global-id, not global_id

2021-07-23 14:39 UTC, ptimmons commented on docs/intro_upgrade_considerations.md
> +#### Stricter validations have been added to InterfaceRedundancyCheck:
This seems like a more general case that is a superset of the "global-id" case above. Recommend removing the global-id comment, since it's covered here.

2021-07-23 14:39 UTC, ptimmons commented on docs/intro_upgrading.md
> +If you are upgrading to version 5.3.0 of the SSR/128T software, please refer to the [5.3.0 Upgrade Considerations](intro_upgrade_considerations.md) before proceeding.
Throughout this section I recommend replacing "5.3.0" with "5.3". The 5.3.0 software will be limited availability and not all customers will have access to it. The first exposure to 5.3 for most customers will be some future patch. All of the text in this section of the documentation will apply to future customers upgrading from older versions to 5.3.x versions, and we don't want to make it seem like it's strictly 5.3.0 that has these restrictions/new caveats.

2021-07-23 19:00 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.3.md
> +Additionally, the candidate configuration is no longer synchronized between HA nodes. In release 5.3.0 only the running configuration is synchronized between nodes.
Updated in the Upgrade considerations doc, the config basics and config ha docs.

2021-07-23 19:03 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.3.md
> +- **I95-39457 ServiceSecurityCheck validator should check for next-peer in service-route:** A missing validation check on `next-peer` service routes allows the configuration to be committed without p
Leaving based on a comment from Jeff - It was a known issue/caveat in older releases, but is now fixed.

2021-07-23 19:05 UTC, Chr1st0ph3rTurn3r commented on docs/intro_upgrade_considerations.md
> +Stricter validations have been added to enforce the requirement that a profile must be configured when `performance-monitoring` is enabled on a neighborhood. This requirement was loosely enforced pri
Both have been addressed.

2021-07-23 19:06 UTC, Chr1st0ph3rTurn3r commented on docs/intro_upgrade_considerations.md
> +#### A mismatched global_id on redundant interfaces generates an "Error: Candidate configuration is invalid" message.
fixed

2021-07-23 19:14 UTC, Chr1st0ph3rTurn3r commented on docs/intro_upgrade_considerations.md
> +#### Stricter validations have been added to InterfaceRedundancyCheck:
I combined some of the wording and removed the global-id issue: #### A mismatched global_id on redundant interfaces generates an "Error: Candidate configuration is invalid" message.

2021-07-23 19:15 UTC, Chr1st0ph3rTurn3r commented on docs/intro_upgrading.md
> +If you are upgrading to version 5.3.0 of the SSR/128T software, please refer to the [5.3.0 Upgrade Considerations](intro_upgrade_considerations.md) before proceeding.
done

2021-07-23 19:23 UTC, Chr1st0ph3rTurn3r commented on docs/about_releases.md
> +| Version | GA Version | GA Date |
Done

2021-08-04 12:46 UTC, MichaelBaj commented on docs/about_releases.md
> +| [5.3.0](release_notes_128t_5.3.md#release-5.3)   | August 5, 2021     |                    | Not Applicable*    | Not Applicable*    |
Looking more like August 6th. Need to confirm with Jeff.

2021-08-04 12:46 UTC, MichaelBaj commented on docs/bcp_conductor_deployment.md
> +When deploying a conductor behind a firewall, open 830/TCP (used for NETCONF in versions prior to 5.3) and 4505-4506/TCP (used for salt) to allow a conductor to communicate to managed routers. Open 4
This should be 930, not 830 (unless I'm wrong).

2021-08-04 12:46 UTC, MichaelBaj commented on docs/bcp_conductor_deployment.md
> +- The head end fronting the conductor must perform NAT/NAPT to forward 4505-4506/TCP (used for salt), and 830/TCP (used for NETCONF in versions prior to 5.3) to the conductor on the data center LAN.
Same as above.

2021-08-04 15:14 UTC, Chr1st0ph3rTurn3r commented on docs/bcp_conductor_deployment.md
> +When deploying a conductor behind a firewall, open 830/TCP (used for NETCONF in versions prior to 5.3) and 4505-4506/TCP (used for salt) to allow a conductor to communicate to managed routers. Open 4
Made changes to clarify the NETCONF port use for pre- and post-5.3.

2021-08-04 15:14 UTC, Chr1st0ph3rTurn3r commented on docs/bcp_conductor_deployment.md
> +- The head end fronting the conductor must perform NAT/NAPT to forward 4505-4506/TCP (used for salt), and 830/TCP (used for NETCONF in versions prior to 5.3) to the conductor on the data center LAN.
Made changes to clarify the NETCONF port use for pre- and post-5.3.

2021-08-04 20:03 UTC, MichaelBaj submitted a review, later dismissed

2021-08-04 21:48 UTC, ptimmons commented on docs/release_notes_128t_5.3.md
> +## Release 5.3.0
We control access to pre-GA software, so no customers/prospects will be able to get this software without us knowing. If we get requests on behalf of field teams to provide 5.3 to customers we can communicate this on an as-needed basis. (IMHO)

2021-08-05 12:46 UTC, MichaelBaj approved these changes

2021-08-05 14:14 UTC, agrawalkaushik approved these changes

2021-08-06 20:59 UTC, merged