Added monitoring agent 3.4.2 docs
128technology/docs pull request #243
Opened 2021-05-24 15:22 UTC by BenMatase

2021-05-24 15:24 UTC, BenMatase commented on docs/plugin_monitoring_agent.md
> +- **WAN-116** Allow any topic in the events input
It is a little weird to have `WAN` and `I95` projects here, but that is what the work was done against. We could create duplicate `MON` tasks/bugs to make it consistent with the other sections...

2021-05-24 16:16 UTC, Chr1st0ph3rTurn3r approved these changes

2021-05-24 16:16 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_monitoring_agent.md
> +- **WAN-116** Allow any topic in the events input
Add a period at the end of the sentence.

2021-05-24 16:16 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_monitoring_agent.md
> +- **I95-39979** Monitoring agent sending the same metrics multiple times when using the kafka output
Same here - period at the end of the sentence.

2021-05-24 16:20 UTC, BenMatase commented on docs/plugin_monitoring_agent.md
> +- **WAN-116** Allow any topic in the events input
Fair. I was looking below and there weren't mostly periods at the end of sentences. Will add

2021-05-25 14:25 UTC, BenMatase commented on docs/plugin_monitoring_agent.md
> +#### New Features and Improvements:
@agrawalkaushik I debated adding a blurb about the MWA output, but figured that shouldn't be included in public docs since the other plugin isn't released yet

2021-05-25 16:13 UTC, agrawalkaushik commented on docs/plugin_monitoring_agent.md
> +#### New Features and Improvements:
I think that's fair for now. We can update it later one as needed.

2021-05-27 18:26 UTC, MichaelBaj approved these changes

2021-05-29 11:05 UTC, ptimmons commented on docs/plugin_monitoring_agent.md
> +  _**Resolution**_ The kafka output was enhanced to include a batch retry mechanism where it will try up to `max_batch_retry` times to push the buffered metrics during the push interval. The kafka ou
The default for `max_batch_retry` should be indicated here.

2021-06-01 13:36 UTC, Chr1st0ph3rTurn3r requested changes

2021-06-01 13:36 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_monitoring_agent.md
> +  _**Resolution**_ The kafka output was enhanced to include a batch retry mechanism where it will try up to `max_batch_retry` times to push the buffered metrics during the push interval. The kafka ou
I agree with PT - just simply adding "(default is X)" to indicate what the value is would be helpful.

2021-06-01 14:05 UTC, Chr1st0ph3rTurn3r approved these changes

2021-06-01 14:21 UTC, jeffmart approved these changes

2021-06-01 16:54 UTC, MichaelBaj approved these changes

2021-06-01 16:56 UTC, agrawalkaushik approved these changes

2021-06-01 16:56 UTC, merged