Update docs for monitoring agent 3.5.0 release
128technology/docs pull request #255
Opened 2021-06-17 12:51 UTC by salegria8

# Description
Release 3.5.0 will include a few bug fixes and a few new features. See changes below for more info.

2021-06-18 11:38 UTC, BenMatase commented on docs/plugin_monitoring_agent.md
> +| extract-field > value | string | The graphQL query path from which to extract the value. The path can be relative to the entry-point or absolute. If the path is abolute, it cannot diverge from the
typo `absolute` in here

2021-06-18 11:40 UTC, BenMatase commented on docs/plugin_monitoring_agent.md
> +| extract-tag > value | string | The graphQL query path from which to extract the value. The path can be relative to the entry-point or absolute. If the path is abolute, it cannot diverge from the en
What does it mean to diverge? Because the example below feels a little bit like diverging since it goes into the name

2021-06-18 11:41 UTC, BenMatase commented on docs/plugin_monitoring_agent.md
> +| extract-tag > value | string | The graphQL query path from which to extract the value. The path can be relative to the entry-point or absolute. If the path is abolute, it cannot diverge from the en
The same `abolute` typo is here as well

2021-06-18 11:44 UTC, BenMatase commented on docs/plugin_monitoring_agent.md
> +  Paths, absolute or relative to the `entry_point`, from which fields should be created. Each value MUST point to a leaf in the graph. If the path is absolute, it MUST NOT diverge from the `entry_poi
`MUST exclude graphQL arguments`?

2021-06-18 11:57 UTC, BenMatase requested changes
Just the typos

2021-06-18 17:22 UTC, gregschrock commented on docs/plugin_monitoring_agent.md
> +| extract-field > value | string | The graphQL query path from which to extract the value. The path can be relative to the entry-point or absolute. If the path is abolute, it cannot diverge from the
done

2021-06-18 17:22 UTC, gregschrock commented on docs/plugin_monitoring_agent.md
> +| extract-tag > value | string | The graphQL query path from which to extract the value. The path can be relative to the entry-point or absolute. If the path is abolute, it cannot diverge from the en
fixed `abolute`, but I'm not exactly sure about the question of diverging...

2021-06-22 18:49 UTC, agrawalkaushik commented on docs/plugin_monitoring_agent.md
> +                        value  allRouters/nodes/nodes/nodes/deviceInterfaces/totalCount
technically this should just be `totalCount`, correct? Are you showing it like this as an alternate example? If so, I think its a bit confusing and consider removing it.

2021-06-22 18:53 UTC, agrawalkaushik approved these changes

2021-06-22 19:01 UTC, salegria8 commented on docs/plugin_monitoring_agent.md
> +                        value  allRouters/nodes/nodes/nodes/deviceInterfaces/totalCount
`totalCount` for the path? if the path is just `totalCount` the collector will expect a leaf at `allRouters/nodes/node/nodes/deviceInterfaces/nodes/totalCount` which isn't right because of the `nodes` before `totalCount`

2021-06-23 12:48 UTC, agrawalkaushik commented on docs/plugin_monitoring_agent.md
> +                        value  allRouters/nodes/nodes/nodes/deviceInterfaces/totalCount
that's fair - I didn't spot the missing `nodes` in the parent path - good point!

2021-06-23 13:25 UTC, BenMatase requested changes
Of course the one time I do comments as part of a review I forget to submit. I guess the typo is the only thing I'd like to see changed

2021-06-23 15:54 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_monitoring_agent.md
> +| extract-tag > value | string | The graphQL query path from which to extract the value. The path can be relative to the entry-point or absolute. If the path is abolute, it cannot diverge from the en
From Dictionary.com: (of a road, route, or line) separate from another route, especially a main one, and go in a different direction.

2021-06-23 16:25 UTC, Chr1st0ph3rTurn3r submitted a review, later dismissed

2021-06-23 16:25 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_monitoring_agent.md
> +For this diff case, the transform will compute the delta from a "counter" field. No delta can be computed from a single point, so it will wait till the second observed value to produce the diff. If n
"till" is not really a word. It's a contraction of "until" usually written as 'til. However, it shouldn't be used here. My suggestion: ...so the transform waits until the second observed value...
Also, try not to use contractions in documentation; "hadn't". My suggestion: If no values are observed for more than thirty seconds, the transform will begin computing again.

2021-06-23 16:25 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_monitoring_agent.md
> +Processors are not currently exposed explicitly in the plugin config, but they can be achieved through an input's [additional config](plugin_monitoring_agent.md#input-configuration). Here are some ex
examples of... (plural)

2021-06-23 16:25 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_monitoring_agent.md
> +The processors operates on fields separately for series that passes through it. For example, there may be multiple metrics passing through with a `value` field. The processor will distinguish between
This paragraph is a little confusing not because of the content, but the grammar. My suggestion:
The processor operates on each field separately. For example, multiple metrics may pass through with a `value`field. The processor will distinguish between the metrics using the tags and measurement name.

2021-06-23 16:25 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_monitoring_agent.md
> +When there is no value to produce, the processor will exclude the field. If the field name matches its source field, that field is removed. This can be a way of dropping lines as Telegraf will remove
Suggested wording for clarity:
When there is no value to produce, the processor excludes the field. If the field name matches the source field, the field is removed. If a line is not valid, for example, if it has no fields, Telegraf will remove it, effectively dropping the line. When watching for state changes on lines that have a single field, the original line will be dropped. In this way, a polling mechanism can be turned into a means of notification.

2021-06-25 17:24 UTC, gregschrock commented on docs/plugin_monitoring_agent.md
> +| 3.5.0   | `state-change` transform option was introduced |
Just curious if you have an example of this. I find it cleaner to have each change on a separate line. Often I want to know what version has a feature more than I want to know what features are in a version. It's subtle but seems easier to me as separate lines.

2021-06-25 19:20 UTC, MichaelBaj submitted a review, later dismissed

2021-07-06 16:21 UTC, BenMatase commented on docs/plugin_monitoring_agent.md
> +| 3.5.0   | `state-change` transform option was introduced |
That is fine

2021-07-06 16:23 UTC, BenMatase approved these changes

2021-11-19 17:12 UTC, MichaelBaj commented on docs/plugin_monitoring_agent.md
> +The monitoring agent `session-records` input can be used to session records generated by the system.
This sentence does not appear to be grammatically correct.

The monitoring agent `session-records` input can be used to generate session records by the system.

2021-11-19 17:20 UTC, Chr1st0ph3rTurn3r requested changes

2021-11-19 17:20 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_monitoring_agent.md
> +  ## Fields work the same was a fields and can be included in the same condition.
Wording is not clear; "Fields work the same way and can be..."

2021-11-19 20:20 UTC, salegria8 commented on docs/plugin_monitoring_agent.md
> +The monitoring agent `session-records` input can be used to session records generated by the system.
fixed

2021-11-19 20:20 UTC, salegria8 commented on docs/plugin_monitoring_agent.md
> +  ## Fields work the same was a fields and can be included in the same condition.
fixed

2021-11-19 20:33 UTC, Chr1st0ph3rTurn3r approved these changes

2021-11-22 13:33 UTC, gregschrock approved these changes

2021-11-22 13:43 UTC, BenMatase approved these changes

2021-11-22 19:21 UTC, MichaelBaj approved these changes

2021-11-22 19:37 UTC, merged