Release notes 5.1.4
128technology/docs pull request #256
Opened 2021-06-22 20:59 UTC by Chr1st0ph3rTurn3r

2021-06-22 21:30 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-38445 GUI Session Capture:** Added pages to the user interface that allow you to view and configure capture information.
consider providing a link to https://docs.128technology.com/docs/ts_packet_capture/#selective-packet-capture

2021-06-22 21:30 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-40144 EoSVR with outbound only sessions showing errors:** Resolved an issue where EoSVR with outbound only sessions may show errors when fpm is turned on, and will not contribute to fpm data.
FPM should be capitalized.

2021-06-22 21:30 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-40334 `show service-path` shows bgposvr for an EoSVR interface:** Resolved the issue where ethernet-over-svr routes would be displayed as bgp-over-svr in the output.
should be BGPoSVR

2021-06-22 21:30 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-40380 RoutersPage facet selector doesn't work without a search value present:** Removed a condition causing the facets to be ignored when the search bar is empty.
Should be "Routers Page".
I don't believe we use contractions

2021-06-22 21:30 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-40682 the GUI login page keeps focus on whichever element was last selected:** Login page will now focus username field after invalid login.
The should be capitalized

2021-06-23 15:04 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-40682 the GUI login page keeps focus on whichever element was last selected:** Login page will now focus username field after invalid login.
done

2021-06-23 15:04 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-40380 RoutersPage facet selector doesn't work without a search value present:** Removed a condition causing the facets to be ignored when the search bar is empty.
fixed

2021-06-23 15:12 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-40334 `show service-path` shows bgposvr for an EoSVR interface:** Resolved the issue where ethernet-over-svr routes would be displayed as bgp-over-svr in the output.
fixed

2021-06-23 15:12 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-40144 EoSVR with outbound only sessions showing errors:** Resolved an issue where EoSVR with outbound only sessions may show errors when fpm is turned on, and will not contribute to fpm data.
done

2021-06-23 15:12 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-38445 GUI Session Capture:** Added pages to the user interface that allow you to view and configure capture information.
done

2021-06-23 21:16 UTC, MichaelBaj requested changes

2021-06-23 21:16 UTC, MichaelBaj commented on docs/about_releases.md
> +| [5.1.4](release_notes_128t_5.1.md#release-513)   | June 23, 2021      |                    | Not Applicable*    | May 24, 2022       |
The date will need to be updated

2021-06-23 21:16 UTC, MichaelBaj commented on docs/plugin_intro.md
> +![Plugin Commands Tab](/img/plugin_commands_tab.png)
The Mist Agent plugin is not currently distributed and is currently under development. We should showcase some of our standard plugin offerings. @agrawalkaushik should be able to provide a relevant image

2021-06-25 17:18 UTC, Chr1st0ph3rTurn3r commented on docs/about_releases.md
> +| [5.1.4](release_notes_128t_5.1.md#release-513)   | June 23, 2021      |                    | Not Applicable*    | May 24, 2022       |
Date has been updated per today's staff meeting.

2021-06-25 17:19 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_intro.md
> +![Plugin Commands Tab](/img/plugin_commands_tab.png)
messaged with Kaushik, and have removed the graphic.

2021-06-25 19:19 UTC, MichaelBaj submitted a review, later dismissed

2021-06-29 21:57 UTC, MichaelBaj approved these changes

2021-06-29 23:16 UTC, agrawalkaushik commented on docs/plugin_intro.md
> +![Plugins State Tab](/img/plugin_state_tab.png)
@Chr1st0ph3rTurn3r This is also showing the state for the MIST plugin. The state is supported for a few other plugins - I would recommend using the `dns-app-id` plugin for this instead. I dont have any setup I can downgrade but maybe someone on field_eng can provide a snapshot for you

2021-06-29 23:17 UTC, agrawalkaushik requested changes
remove the mist-agent state output

2021-07-01 13:28 UTC, MichaelBaj submitted a review, later dismissed

2021-07-01 17:40 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_intro.md
> +![Plugins State Tab](/img/plugin_state_tab.png)
done

2021-07-01 19:24 UTC, MichaelBaj approved these changes

2021-07-01 19:32 UTC, jeffmart submitted a review, later dismissed

2021-07-01 19:35 UTC, agrawalkaushik approved these changes

2021-07-06 21:03 UTC, MichaelBaj approved these changes

2021-07-07 14:56 UTC, merged