Release notes 5.2.1
128technology/docs pull request #263
Opened 2021-06-29 21:48 UTC by Chr1st0ph3rTurn3r

2021-07-08 13:07 UTC, MichaelBaj requested changes

2021-07-08 13:07 UTC, MichaelBaj commented on docs/release_notes_128t_5.2.md
> +- **I95-36244 Handle names in application-id JSON:** The application-module json output common-name object now includes a list of referenced common-names, in addition to the transport-information lis
I95-36244 is actually the defect: error display generated config in the PCLI. Can you correct the issue ID? Also, I'm not sure the description reads correctly.

2021-07-08 13:07 UTC, MichaelBaj commented on docs/release_notes_128t_5.2.md
> +- **I95-40075/I95-40134 Use gateway from service route for interface ping gateway:** the `service-route next-hop gateway-ip` will be used for ICMP ping reachability probe if so configured. If no IP i
Capitalize "The"

2021-07-12 14:06 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.2.md
> +- **I95-35414 Refresh actions now available for individual sections on the Router Page:**The Device interface, Network Interface, and Peer Paths table sections now can be refreshed independently.
added space

2021-07-12 14:13 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.2.md
> +- **I95-36244 Handle names in application-id JSON:** The application-module json output common-name object now includes a list of referenced common-names, in addition to the transport-information lis
corrected the number (36224) and edited the description.

2021-07-12 14:13 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.2.md
> +- **I95-40075/I95-40134 Use gateway from service route for interface ping gateway:** the `service-route next-hop gateway-ip` will be used for ICMP ping reachability probe if so configured. If no IP i
done

2021-07-14 00:48 UTC, MichaelBaj approved these changes

2021-07-19 13:39 UTC, MichaelBaj approved these changes

2021-07-20 12:57 UTC, MichaelBaj approved these changes

2021-07-20 18:55 UTC, jeffmart approved these changes

2021-07-20 18:55 UTC, merged