adding supported drivers info for initial review.
128technology/docs pull request #264
Opened 2021-07-08 17:00 UTC by Chr1st0ph3rTurn3r

2021-07-09 20:26 UTC, MichaelBaj requested changes

2021-07-09 20:26 UTC, MichaelBaj commented on docs/about_supported_drivers.md
> +### Driver: net_bnx2xvf
From here on down, it appears that you still have the old formatting.  These should all be removed.

2021-07-12 12:45 UTC, reidstidolph commented on docs/about_supported_drivers.md
> +| | Unknown Device (54ad) | All |
Is `Unknown Device (54ad)` meaningful information? To me it isn't, but not sure if the `54ad` identifier would be helpful to anyone. If it is not, perhaps we remove these unknown devices.

2021-07-13 19:50 UTC, Chr1st0ph3rTurn3r commented on docs/about_supported_drivers.md
> +### Driver: net_bnx2xvf
Totally reformatted.

2021-07-13 19:50 UTC, Chr1st0ph3rTurn3r commented on docs/about_supported_drivers.md
> +| | Unknown Device (54ad) | All |
removed unknown devices.

2021-07-13 20:07 UTC, MichaelBaj requested changes

2021-07-13 20:07 UTC, MichaelBaj commented on docs/about_supported_drivers.md
> +| Aquantia Corp. (1d6a) | AQC107 NBase-T/IEEE 802.3bz Ethernet Controller [AQtion] (d107) | net_atlantic | 4.5.0 - 5.3.0 |
Rather than having a range for supported 128T version, I suggest that you have a single value for 128T support added, this way we don't have to update this page with each release. In the off case where we drop support for a driver or NIC (this will happen), we can add a column to those rows indicating when support was dropped.

2021-07-15 14:44 UTC, MichaelBaj approved these changes

2021-07-15 15:39 UTC, jeffmart approved these changes

2021-07-15 16:55 UTC, dfitzpatrick128 approved these changes

2021-07-15 17:24 UTC, merged