resolving 5 Jira DOC tasks.
128technology/docs pull request #267
Opened 2021-07-16 19:19 UTC by Chr1st0ph3rTurn3r

2021-07-16 19:49 UTC, MichaelBaj requested changes

2021-07-16 19:49 UTC, MichaelBaj commented on docs/about_supported_platforms.md
> +* Intel x86 processor, single socket
Why did you remove the 4 core requirement?

2021-07-16 19:49 UTC, MichaelBaj commented on docs/about_supported_platforms.md
> +* Intel x86 processor
Why did you remove the 4 core requirement?

2021-07-19 12:32 UTC, Chr1st0ph3rTurn3r commented on docs/about_supported_platforms.md
> +* Intel x86 processor, single socket
In DOCS-236, Dave requested it be changed to "Intel x86 processor". I have never see 4 Core referred to as 4C, and apparently neither had he. I will change it to 4 Core.

2021-07-19 12:32 UTC, Chr1st0ph3rTurn3r commented on docs/about_supported_platforms.md
> +* Intel x86 processor
Same as above.

2021-07-19 12:39 UTC, MichaelBaj approved these changes

2021-07-19 13:29 UTC, merged