5.1.5 docs releasenotes
128technology/docs pull request #269
Opened 2021-08-08 18:17 UTC by Chr1st0ph3rTurn3r

2021-08-09 16:38 UTC, MichaelBaj requested changes

2021-08-09 16:38 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-39617 Add cost (currency) and carrier information to the `network-interface` and `authority`:** Added attributes to the network-interface that reflect the weighted cost for paths. For more in
Replace "the weighted" with "the monetary". We do not want to confuse the dollar value as a influencer of path selection. This feature was added as a means of translating the SVR savings tool into monetary savings.

2021-08-09 16:38 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-40335 Support running KVM on the host:** Addressed deprecated-packages dependency conflicts with kvm, and updated the minimum allowed version of libX11 to address CVE-2020-14363.
The details of why are not pertinent. Recommended rewording:
"KVM packages and corresponding dependencies have been added to the SSR distribution"

2021-08-09 16:38 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-36099 Time range selection for analytics in the GUI is difficult to use:** Now using the native implementation for date-time.
Replace "Now using the native implementation for date-time."
With "Replaced with browser-native date-time selector."

2021-08-09 16:38 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-40016 Adaptive Encryption cause packet drop on HA fabric:** Resolved an `Adaptive encryption out of order` modification error causing packet drop on HA fabric.
Replace "Adaptive Encryption cause packet drop on HA fabric"
with "Flow-migration with adapative-encryption may cause packet drops"

2021-08-09 16:38 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-40894 Firewall pinhole test:** Added an acceptable loss of packets threshold for FirewallPinhole tests.
Replace "I95-40894 Firewall pinhole test:** Added an acceptable loss of packets threshold for FirewallPinhole tests."
with "I95-40894 Firewall pinhole false-positives:** Added an acceptable loss of packets threshold for Firewall Pinhole tests.

2021-08-10 12:20 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-39617 Add cost (currency) and carrier information to the `network-interface` and `authority`:** Added attributes to the network-interface that reflect the weighted cost for paths. For more in
done

2021-08-10 12:20 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-40335 Support running KVM on the host:** Addressed deprecated-packages dependency conflicts with kvm, and updated the minimum allowed version of libX11 to address CVE-2020-14363.
done

2021-08-10 12:20 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-36099 Time range selection for analytics in the GUI is difficult to use:** Now using the native implementation for date-time.
done

2021-08-10 12:21 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-40016 Adaptive Encryption cause packet drop on HA fabric:** Resolved an `Adaptive encryption out of order` modification error causing packet drop on HA fabric.
done

2021-08-10 12:21 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-40894 Firewall pinhole test:** Added an acceptable loss of packets threshold for FirewallPinhole tests.
done

2021-08-10 13:04 UTC, MichaelBaj submitted a review, later dismissed

2021-08-13 18:28 UTC, jeffmart submitted a review, later dismissed

2021-08-13 20:08 UTC, MichaelBaj approved these changes

2021-08-13 20:10 UTC, jeffmart approved these changes

2021-08-13 20:22 UTC, merged