5.4 documentation
128technology/docs pull request #274
Opened 2021-08-18 20:08 UTC by Chr1st0ph3rTurn3r

2021-08-19 11:47 UTC, salegria8 commented on docs/config_wan_assurance.md
> +    *Issue: There is no information about how to create a Site in this doc (or I haven’t found it yet). But it is made clear how important the concept of a site is. I need information about how to cr
Just found this out but site creation is under Organization (left pane) > Site Configuration > Create Site (top right). I've never created a site so can't comment on all the options that appear

2021-08-19 11:54 UTC, salegria8 commented on docs/config_wan_assurance.md
> +(CLARIFICATION FOR ABOVE PLEASE: Is the router using the new keys to send the telemetry info to the MIST cloud? Or is the MIST cloud providing new keys that some other device uses to send additional
The info above seems like an implementation detail. And if we submitted the onboarding process to the patent office I imagine we'd like to present it as a magic black box to customers

2021-08-19 11:54 UTC, salegria8 commented on docs/config_wan_assurance.md
> +For a system that is currently on-board, setting `mist-wan-assurance` to `false` will prevent telemetry data from being sent to the cloud.
on-board -> on-boarded

2021-08-19 11:57 UTC, salegria8 commented on docs/config_wan_assurance.md
> +Once the onboarding process is complete, each router is displayed on the MIST inventory page under **Organization > Inventory**. Select Gateways on the top of the page to see a list of the routers an
nit-picking but site-assignment is also part of onboarding. How about `once the 128T portion of onboarding is complete...`

2021-08-19 12:03 UTC, salegria8 commented on docs/config_wan_assurance.md
> +### Gateway Insights
Forgot to mention that in the url you can also change `manage-staging.mistsys.com` to `integration.mistsys.com` to see some of the unreleased gui features

2021-08-24 18:48 UTC, gregschrock requested changes
Looks good generally. Mostly need to revise the config structure.

2021-08-24 18:48 UTC, gregschrock commented on docs/config_in-memory_metrics.md
>                          retention  long
These retentions are configured separate from the profiles. e.g.
```
router MyRouter 
  system
    metrics
      retention long
        enabled true
        interval 1h
        duration 180d
      exit
    exit
  exit
exit
```
When profiles reference these retentions, the appropriate values will be used as described for each router.

This probably warrants a separate section in the documentation.

2021-08-24 18:48 UTC, gregschrock commented on docs/config_in-memory_metrics.md
> +The current implementation of the **in-memory** retention value is limited.
`in-memory` is still a valid configuration for a profile.

2021-08-24 18:48 UTC, gregschrock commented on docs/config_in-memory_metrics.md
>  #### Example Profile: Native Output
`Native Output` is a discontinued concept. It was never really implemented that way. This should just be `Example Profile`.

2021-08-24 18:48 UTC, gregschrock commented on docs/config_in-memory_metrics.md
> +| short | Enabled: true | 5 seconds | hour
`hour` -> `1 hour`

2021-08-24 18:50 UTC, salegria8 commented on docs/config_in-memory_metrics.md
> +| short | Enabled: true | 5 seconds | hour
Also might be missing `|` at the end

2021-08-24 19:51 UTC, Chr1st0ph3rTurn3r commented on docs/config_in-memory_metrics.md
> +The current implementation of the **in-memory** retention value is limited.
edits made.

2021-08-24 19:51 UTC, Chr1st0ph3rTurn3r commented on docs/config_in-memory_metrics.md
>  #### Example Profile: Native Output
changed.

2021-08-24 19:52 UTC, Chr1st0ph3rTurn3r commented on docs/config_in-memory_metrics.md
> +| short | Enabled: true | 5 seconds | hour
got them both, thank you!

2021-08-24 19:52 UTC, Chr1st0ph3rTurn3r commented on docs/config_in-memory_metrics.md
>                          retention  long
done.

2021-08-24 20:02 UTC, Chr1st0ph3rTurn3r commented on docs/config_wan_assurance.md
> +(CLARIFICATION FOR ABOVE PLEASE: Is the router using the new keys to send the telemetry info to the MIST cloud? Or is the MIST cloud providing new keys that some other device uses to send additional
I removed the majority of the internal info.

2021-08-24 20:43 UTC, gregschrock submitted a review, later dismissed

2021-08-24 20:43 UTC, gregschrock commented on docs/config_in-memory_metrics.md
> +The following example shows metrics retention configured only for short retention with the default values:
We should probably also add a warning that increasing the retention duration and/or decreasing the interval from the defaults has the potential to impact system overhead and should be carefully considered.

2021-08-24 20:43 UTC, gregschrock commented on docs/config_in-memory_metrics.md
> +            router  MyRouter
`name MyRouter` here instead of `router MyRouter`

2021-08-24 20:47 UTC, Chr1st0ph3rTurn3r commented on docs/config_wan_assurance.md
> +    *Issue: There is no information about how to create a Site in this doc (or I haven’t found it yet). But it is made clear how important the concept of a site is. I need information about how to cr
Thank you - I will work through this process and doc it.

2021-08-24 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/config_wan_assurance.md
> +Once the onboarding process is complete, each router is displayed on the MIST inventory page under **Organization > Inventory**. Select Gateways on the top of the page to see a list of the routers an
changed as suggested.

2021-08-24 20:52 UTC, Chr1st0ph3rTurn3r commented on docs/config_in-memory_metrics.md
> +The following example shows metrics retention configured only for short retention with the default values:
done

2021-08-24 20:53 UTC, Chr1st0ph3rTurn3r commented on docs/config_in-memory_metrics.md
> +            router  MyRouter
Change both or just one?

2021-08-24 21:19 UTC, gregschrock commented on docs/config_in-memory_metrics.md
> +            router  MyRouter
just the second one

2021-08-24 22:02 UTC, agrawalkaushik commented on docs/config_wan_assurance.md
> +- Install the MIST WAN Assurance Plugin on the Conductor.
We should remove this step coz the plugin comes pre-installed as part of 5.4

2021-08-24 22:04 UTC, agrawalkaushik commented on docs/config_wan_assurance.md
> +6. Paste the registration code into the PCLI. **(the example below is not clear. Do they paste the reg-code immediately after logging in? Or do they navigate through commands to mist-wan-assurance an
I'm not following the questions @Chr1st0ph3rTurn3r - what part of this is confusing exactly? What command navigation are you looking for exactly

2021-08-24 22:05 UTC, agrawalkaushik commented on docs/config_wan_assurance.md
> +    admin@node1.conductor1# configure authority mist-wan-assurance registration-code eyJ0eX
you should hcange this registration-code to be somehitng bogus coz I believe this is the code for Falcon org. We dont want any one accidentally onboarding to the demo org by copy/pasting...

2021-08-24 22:07 UTC, agrawalkaushik commented on docs/config_wan_assurance.md
> +### Gateway Insights
while that is true we should not be referring to that URL in the document anywhere. The only public URL should be manage.mist.com

2021-08-24 22:08 UTC, agrawalkaushik commented on docs/config_wan_assurance.md
> +There are two steps to moving a router; releasing and re-onboarding. (why would you need to move a router? Where are you moving it from and to?)
this are the steps to move the router to a different org. The steps are actually not all inclusive of what is needed to migrate a router to another conductor. We can sync up on this later on.

2021-08-25 13:53 UTC, Chr1st0ph3rTurn3r commented on docs/config_in-memory_metrics.md
> +            router  MyRouter
done.

2021-08-25 14:14 UTC, gregschrock approved these changes

2021-08-25 15:27 UTC, lliu5374 commented on docs/config_transport_encryption.md
> +- `show peers` shows the encryption status of peers.
This is not true any more. There is original plan of adding a status in `show peers detail` but it seems not needed anymore, since it's just simply showing what is in the config

2021-08-25 15:27 UTC, lliu5374 commented on docs/config_transport_encryption.md
> +Providing a secure transport system for traffic often requires enabling encryption on all links/paths. For traffic already traversing a trusted link, this adds unnecesary processing overhead. Transpo
It seems to be better with "**secured** transport system"

2021-09-08 16:08 UTC, Chr1st0ph3rTurn3r commented on docs/config_transport_encryption.md
> +- `show peers` shows the encryption status of peers.
removed.

2021-09-08 16:10 UTC, Chr1st0ph3rTurn3r commented on docs/config_transport_encryption.md
> +```
done

2021-10-05 13:39 UTC, tjbresnahan requested changes
just a typo and an additional note that I feel is warranted

2021-10-05 13:39 UTC, tjbresnahan commented on docs/config_dscp_steering.md
> +When traffic is tunneled through an encryption tunnel such as IPSec, every flow within that tunnel looks the same. DPSC packet steering allows the classification of traffic based upon the known DSCP
typo `DPSC` -> `DSCP`

2021-10-05 13:39 UTC, tjbresnahan commented on docs/config_dscp_steering.md
> +        End-value   28
`end-value` is all lower-case in the config

2021-10-05 13:39 UTC, tjbresnahan commented on docs/config_dscp_steering.md
> +                start-port 4500
should this config snippet have all the `exit` bookends like the others, for consistency?

2021-10-05 13:39 UTC, tjbresnahan commented on docs/config_dscp_steering.md
> +The `dscp-steering` option is available at the network-interface level. This allows you to enable traffic steering for dscp traffic entering on a specific transport and port range rather than an enti
I think we should add a note here that only traffic matching the `dscp-steering` properties on this interface is steered via DSCP. Basically, I just want it to be clear that you need **both** the hierarchical service configuration and this network-interface configuration for the feature to function - just defining those services alone is not enough to enable steering

2021-10-05 15:40 UTC, Chr1st0ph3rTurn3r commented on docs/config_dscp_steering.md
> +When traffic is tunneled through an encryption tunnel such as IPSec, every flow within that tunnel looks the same. DPSC packet steering allows the classification of traffic based upon the known DSCP
Fixed

2021-10-05 15:41 UTC, Chr1st0ph3rTurn3r commented on docs/config_dscp_steering.md
> +        End-value   28
fixed

2021-10-05 15:43 UTC, Chr1st0ph3rTurn3r commented on docs/config_dscp_steering.md
> +                start-port 4500
done

2021-10-05 16:04 UTC, Chr1st0ph3rTurn3r commented on docs/config_dscp_steering.md
> +The `dscp-steering` option is available at the network-interface level. This allows you to enable traffic steering for dscp traffic entering on a specific transport and port range rather than an enti
Updated

2021-10-05 17:33 UTC, tjbresnahan submitted a review, later dismissed

2021-10-06 21:16 UTC, MichaelBaj commented on docs/config_dual_router_ha.md
> +**With VRRP isn't the above statement (and all references to the lack of a shared interface) incorrect? Doesn't there have to be a shared interface between the two so that state information can be sy
- [ ] This is a comment that must be addressed

2021-10-06 21:17 UTC, MichaelBaj commented on docs/config_dual_router_ha.md
> +**Why don't we require this????**
- [ ] This is a comment that must be addressed

2021-10-06 21:17 UTC, MichaelBaj commented on docs/config_ha.md
> +                        **vrrp
asterisks should be removed.

2021-10-06 21:18 UTC, MichaelBaj commented on docs/config_ha.md
> +                        exit**
asterisks should be removed.

2021-10-06 21:18 UTC, MichaelBaj commented on docs/config_ha.md
> +                        **vrrp
asterisks should be removed.

2021-10-06 21:18 UTC, MichaelBaj commented on docs/config_ha.md
> +                        exit**
asterisks should be removed.

2021-10-06 21:18 UTC, MichaelBaj commented on docs/config_ha.md
> +                        **vrrp
asterisks should be removed.

2021-10-06 21:18 UTC, MichaelBaj commented on docs/config_ha.md
> +                        exit**
asterisks should be removed.

2021-10-06 21:18 UTC, MichaelBaj commented on docs/config_ha.md
> +                        **vrrp
asterisks should be removed.

2021-10-06 21:18 UTC, MichaelBaj commented on docs/config_ha.md
> +                        exit**
asterisks should be removed.

2021-10-06 21:18 UTC, MichaelBaj commented on docs/config_ha.md
> +                    **enable-failover    true**
asterisks should be removed.

2021-10-07 20:28 UTC, Chr1st0ph3rTurn3r commented on docs/bcp_per-adjacency_traffic_engineering.md
> +While traffic loss in a network is inevitable, where it drops can have a major impact on perceived quality of service. Loss due to an entity with configured transmit caps between instances of the SSN
done

2021-10-14 19:39 UTC, laneshields commented on docs/config_vrf_learning_ospf.md
> +In the example above, all routes learned via OSPF will be installed within the VRF table Red.
All routes learned via OSPF on interface "lan" will be installed within the VRF table Red, all routes learned via OSPF on interface "lan2" will be installed within VRF table Blue.

2021-10-15 19:02 UTC, chaoz0312 commented on docs/config_ha_vrrp.md
> +You must also assign a vector to the service route, and then assign a priority to the vector in the service policy. This priority determines the primary and secondary routers in the HA configuration.
This priority determines the preferences of service-routes where traffic is forwarded. service-route with a vector having a higher priority is preferable.

2021-10-15 19:05 UTC, chaoz0312 commented on docs/config_ha_vrrp.md
> +Configuring session resiliency allows the secondary router to fail back to the primary router once service has been restored. The max-loss, max-latency, and max-jitter settings will determine at what
Configuring session resiliency allows the traffic to fail back to the primary service-route once service has been restored and service-route becomes up again.

2021-10-15 19:14 UTC, chaoz0312 commented on docs/config_ha_vrrp.md
> +Activate VRRP on the `wan` and `lan` device interfaces of node1. By configuring the lower priority (97) on the lan and wan interfaces, router-b is identified as the secondary router. It is advised to
On a dual router HA setup, the vrids must be the same on the two redundant/VRRP devices between two routers. e.g. router-a and router-b' lan devices must have the same vrid. router-a and router-b's wan also must have the same vrid.
NOTE: lan devices and wan devices can have the same vrid as they are on different networks/broadcast domains. But it is recommended to use different vrids to avoid confustion.

2021-10-15 19:15 UTC, chaoz0312 commented on docs/config_ha_vrrp.md
> +Assign a vector to the service route, and then assign a priority to the vector in the service policy. The priority determines the primary and secondary routers in the HA configuration.
The priority determines the preference of service-routes the local router uses to forward traffic.

2021-10-15 19:15 UTC, chaoz0312 commented on docs/config_ha_vrrp.md
> +Configuring session resiliency allows the secondary router to fail back to the primary router once service has been restored. The max-loss, max-latency, and max-jitter settings determine at what poin
Configuring session resiliency allows the traffic to fail back to the primary service-route once service has been restored and service-route becomes up again.

2021-10-18 17:53 UTC, Chr1st0ph3rTurn3r commented on docs/config_dual_router_ha.md
> +This document covers dual router high availability - two instances of the SSR software each configured as separate routers. This is characterized by:
done

2021-10-18 17:54 UTC, Chr1st0ph3rTurn3r commented on docs/config_ha_vrrp.md
> +The following sample configuration provides context for using vrrp and enabling service route failover to provide a stateful failover on a dual router high availability configuration.
removed

2021-10-18 18:12 UTC, Chr1st0ph3rTurn3r commented on docs/config_ha_vrrp.md
> +You must also assign a vector to the service route, and then assign a priority to the vector in the service policy. This priority determines the primary and secondary routers in the HA configuration.
fixed

2021-10-18 20:24 UTC, Chr1st0ph3rTurn3r commented on docs/config_ha_vrrp.md
> +Assign a vector to the service route, and then assign a priority to the vector in the service policy. The priority determines the primary and secondary routers in the HA configuration.
done

2021-10-18 20:25 UTC, Chr1st0ph3rTurn3r commented on docs/config_ha_vrrp.md
> +Configuring session resiliency allows the secondary router to fail back to the primary router once service has been restored. The max-loss, max-latency, and max-jitter settings determine at what poin
done

2021-10-18 20:25 UTC, Chr1st0ph3rTurn3r commented on docs/config_ha_vrrp.md
> +Activate VRRP on the `wan` and `lan` device interfaces of node1. By configuring the lower priority (97) on the lan and wan interfaces, router-b is identified as the secondary router. It is advised to
done

2021-10-18 20:26 UTC, Chr1st0ph3rTurn3r commented on docs/config_ha_vrrp.md
> +- far (this is the interrouter communication link)
got it.

2021-10-18 20:26 UTC, Chr1st0ph3rTurn3r commented on docs/config_vrf_learning_ospf.md
> +In the example above, all routes learned via OSPF will be installed within the VRF table Red.
This has been addressed.

2021-11-02 13:30 UTC, Chr1st0ph3rTurn3r commented on docs/config_wan_assurance.md
> +### On-Boarding Routers
done

2021-11-02 13:32 UTC, Chr1st0ph3rTurn3r commented on docs/config_wan_assurance.md
> +A router or routers can be skipped during the Mist On-boarding process. Change *authority > router > mist-wan-assurance > enabled* to `false`. The Conductor will skip the router and associated nodes
done

2021-11-02 14:14 UTC, MichaelBaj requested changes

2021-11-02 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_5.4.md
> +- **I95-26074 Enable Session View:** Added a 'Find Associated Paths' button to each session, which shows another modal listing the relevant routers.
Suggested rewording to "... the relevant routers"
"listing all SSR routers that are along the path for the session"

2021-11-02 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_5.4.md
> +- **I95-35131 Description Field for static DHCP Pool Assignment:** A description field has been added for static DHCP pool assignment.
Suggestion: "... for static DHCP pool assignment. This is helpful to associate the device name with the static assignment"

2021-11-02 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_5.4.md
> +- **I95-38790 Default Templates:** A limited number of pre-set configuration templates have been added to facilitate an easier user experience. For information, please see [Defalt Templates].
[Default Templates] should point to another file. Missing link.

2021-11-02 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_5.4.md
> +- **I95-40436 Updated Application ID Domain Data:** Application Identification can be configured to automatically download updated domain and application datatsets daily, weekly (default), or monthly
Should there be an underscore between Auto and Update?

2021-11-02 21:33 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.4.md
> +- **I95-40436 Updated Application ID Domain Data:** Application Identification can be configured to automatically download updated domain and application datatsets daily, weekly (default), or monthly
nope. removed.

2021-11-02 21:35 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.4.md
> +- **I95-38790 Default Templates:** A limited number of pre-set configuration templates have been added to facilitate an easier user experience. For information, please see [Defalt Templates].
Need to merge that PR. Fixed the spelling though.

2021-11-02 21:36 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.4.md
> +- **I95-35131 Description Field for static DHCP Pool Assignment:** A description field has been added for static DHCP pool assignment.
done

2021-11-02 21:37 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.4.md
> +- **I95-26074 Enable Session View:** Added a 'Find Associated Paths' button to each session, which shows another modal listing the relevant routers.
done

2021-11-02 21:37 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.4.md
> +
Not anymore! ;^)

2021-11-02 21:38 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +Application Identification is configured to automatically download updated domain and application datatsets weekly. The defaults (shown below) can be adjusted as necessary using the Application Data
There is additional information in the graphic, and I added a link to the cli ref doc.

2021-11-04 21:01 UTC, chaoz0312 approved these changes

2021-11-05 20:49 UTC, mansley12 approved these changes

2021-11-05 21:28 UTC, lliu5374 approved these changes

2021-11-11 00:40 UTC, agrawalkaushik commented on docs/config_wan_assurance.md
> +    admin@node1.conductor1# configure authority mist-wan-assurance registration-code eyJ0eX
cartoon character names could be fine 😄

2021-11-11 22:42 UTC, MichaelBaj requested changes

2021-11-11 22:42 UTC, MichaelBaj commented on docs/release_notes_128t_5.4.md
> +- **I95-35068 Not getting past the Starting state when a bad configuration is stored:** This issue has been resoved.
I would add "asset" before "Starting" so it is more clear what this is referring to.

2021-11-11 22:42 UTC, MichaelBaj commented on docs/release_notes_128t_5.4.md
> +- **I95-43083 5.1.6 ISO missing Rescue Boot Image:** Replacing packages that were removed during upgrade.
I believe the point here is that this issue affects both 5.1.6 and 5.4.0. It is not necessary to specify the version here.

2021-11-12 13:27 UTC, Chr1st0ph3rTurn3r commented on docs/intro_upgrade_considerations.md
> +Several modifications have been made to the verification process for configurations. As a result, configurations that were valid in earlier versions of the SSR/128T software may now present configura
changed.

2021-11-12 14:23 UTC, MichaelBaj submitted a review, later dismissed

2021-11-12 15:22 UTC, laneshields submitted a review, later dismissed

2021-11-16 18:29 UTC, MichaelBaj approved these changes

2021-11-18 16:01 UTC, jeffmart commented on docs/about_releases.md
> +| [5.4.0](release_notes_128t_5.4.md#release-5.4)   | November 17, 2021  | May 3, 2021        | November 3, 2022   |
We will need to update this for today

2021-11-18 16:37 UTC, Chr1st0ph3rTurn3r commented on docs/about_releases.md
> +| [5.4.0](release_notes_128t_5.4.md#release-5.4)   | November 17, 2021  | May 3, 2021        | November 3, 2022   |
done

2021-11-18 16:53 UTC, jeffmart requested changes

2021-11-18 16:53 UTC, jeffmart commented on docs/intro_upgrade_considerations.md
> +Upgrading or rolling back a system (conductor, peer, or router) with the interactive installer `install128t`, that is managed by a conductor may result in the system becoming unresponsive. It is high
Need to remove the first comma in this section:
(conductor, peer, or router)

2021-11-18 16:53 UTC, jeffmart commented on docs/release_notes_128t_5.4.md
> +- **I95-43243/IN-460 Upgrade and Rollback:** Upgrading or rolling back a system (conductor, peer, or router) with the interactive installer `install128t`, that is managed by a conductor may result in
Need to remove the first comma here:
"(conductor, peer, or router)"

2021-11-18 16:53 UTC, jeffmart commented on docs/release_notes_128t_5.4.md
> +- **I95-42624 Upgrade Installer:** Before **upgrading to, or installing** version 5.4, update the Installer to version 3.1.0. Failing to upgrade the installer may result in a rollback failure, should
Lets change this to be:
update the Installer to version to at least 3.1.0

2021-11-18 16:53 UTC, jeffmart commented on docs/release_notes_128t_5.4.md
> +- **I95-38729 Unbinding devices:** VMBus devices are now released at startup.
Add I95-41374 to this entry as well.

2021-11-18 18:33 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.4.md
> +- **I95-38729 Unbinding devices:** VMBus devices are now released at startup.
done

2021-11-18 18:33 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.4.md
> +- **I95-42624 Upgrade Installer:** Before **upgrading to, or installing** version 5.4, update the Installer to version 3.1.0. Failing to upgrade the installer may result in a rollback failure, should
done

2021-11-18 18:35 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.4.md
> +- **I95-43243/IN-460 Upgrade and Rollback:** Upgrading or rolling back a system (conductor, peer, or router) with the interactive installer `install128t`, that is managed by a conductor may result in
see above. Done

2021-11-18 18:35 UTC, Chr1st0ph3rTurn3r commented on docs/intro_upgrade_considerations.md
> +Upgrading or rolling back a system (conductor, peer, or router) with the interactive installer `install128t`, that is managed by a conductor may result in the system becoming unresponsive. It is high
actually, if I remove the first comma, the second is unnecessary. Done.

2021-11-18 18:35 UTC, MichaelBaj submitted a review, later dismissed

2021-11-18 19:23 UTC, jeffmart approved these changes

2021-11-18 19:29 UTC, jeffmart approved these changes

2021-11-18 19:32 UTC, MichaelBaj approved these changes

2021-11-18 20:15 UTC, merged