Add release notes for ICMP Rechability Detection 3.0.3
128technology/docs pull request #291
Opened 2021-10-28 02:11 UTC by agrawalkaushik

Release notes for ICMP Reachability detection plugin
DOCS-268 #time 30m

2021-10-28 15:54 UTC, Bhautik submitted a review, later dismissed

2021-11-01 15:26 UTC, Chr1st0ph3rTurn3r requested changes

2021-11-01 15:26 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_icmp_reachability_detection.md
> +:::warning
I will add an Upgrade Consideration to the 5.4 Release Notes.

2021-11-01 15:26 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_icmp_reachability_detection.md
> +:::
Change 128T to SSR

2021-11-08 18:12 UTC, agrawalkaushik commented on docs/plugin_icmp_reachability_detection.md
> +- **PLUGIN-1419** Invalid service config generated for the config director mode
So technically we've had the support for bonsai mode since 5.1.0 which would require an environment variable to be set.

2021-11-08 18:14 UTC, MichaelBaj approved these changes

2021-11-08 18:18 UTC, Chr1st0ph3rTurn3r approved these changes

2021-11-08 19:51 UTC, merged