Add doc for http probe plugin
128technology/docs pull request #294
Opened 2021-11-07 02:59 UTC by agrawalkaushik

2021-11-07 09:01 UTC, ptimmons submitted a review, later dismissed

2021-11-08 15:08 UTC, BenMatase submitted a review, later dismissed

2021-11-16 18:20 UTC, agrawalkaushik commented on docs/plugin_http_probe.md
> +```config {9-14}
the `{9-14}` will highlight those specific lines in the code block. You'll be able to see this better once its published 😉

2021-11-16 18:21 UTC, agrawalkaushik commented on docs/plugin_http_probe.md
> +| probe-type | enumeration | always | For probe based reachability detection to take effect the probe-type must be set to `always`. |
This is 128T config and cannot be renamed.

2021-11-16 18:34 UTC, jeffmart requested changes
MInor change

2021-11-16 18:40 UTC, jeffmart commented
um ... I put up a change and the github display provided it but seems it did not take... not sure why

2021-11-16 18:45 UTC, jeffmart commented
Ok, I cannot seem to submit through the review change process here, my primary item is we have 128T references that are not in the actual configuration per say, for example in the doc sections we state:

"128T router" 

Are we still using this or which these references be changed to SSR?

2021-11-16 18:46 UTC, MichaelBaj requested changes

2021-11-16 18:46 UTC, MichaelBaj commented on docs/plugin_http_probe.md
> +The http-probe plugin is designed to leverage the reachability detection APIs that were introduced in the 128T router as of 5.2.0 version of software. More documentation on the core product feature c
s/128T/SSR/g

2021-11-16 18:46 UTC, MichaelBaj commented on docs/plugin_http_probe.md
> +The plugin leverages the existing 128T reachability detection and enforcement configuration within the service-route on the router.
s/128T/SSR/g

2021-11-16 18:46 UTC, MichaelBaj commented on docs/plugin_http_probe.md
> +Once the profile is created, the next step is to enable the reachability enforcement and probe detection for a non SVR service-route and reference the profile in that config.
Is it true that this plugin is only applicable for non-SVR service-routes? What happens if it is configured for a SVR service-route? If there is a constraint that is not checked via validation, we need to have a note in the documentation.

2021-11-16 18:46 UTC, MichaelBaj commented on docs/plugin_http_probe.md
> +The router should have a distinct path for the probe traffic. It is recommended that the user create dedicated services and service routes for this purpose. At this time, the plugin does not generate
Please reference in the troubleshooting section for what needs to be checked if the services and service-routes are not properly configured.

2021-11-16 18:46 UTC, MichaelBaj commented on docs/plugin_http_probe.md
> +When all the service routes associated with the same service are down, the default system behavior is to operates in a `best-effort` mode in which the physical link and L2 connectivity is used to det
its -> it's

2021-11-16 23:13 UTC, agrawalkaushik commented on docs/plugin_http_probe.md
> +Once the profile is created, the next step is to enable the reachability enforcement and probe detection for a non SVR service-route and reference the profile in that config.
I believe there to be validation for the reachability-enforcement which guarantees that. I'll double check that. Is your ask to include the text for the validation error or something along those lines or just a caveat?

2021-11-16 23:15 UTC, agrawalkaushik commented on docs/plugin_http_probe.md
> +The router should have a distinct path for the probe traffic. It is recommended that the user create dedicated services and service routes for this purpose. At this time, the plugin does not generate
The configuration is at the service-route. There are product validations in place. Is the ask to include all those errors - I think they should be covered by the reachability enforcement feature that was published in 5.2. I'll double check or reference to those.

2021-11-16 23:19 UTC, agrawalkaushik commented on docs/plugin_http_probe.md
> +The http-probe plugin is designed to leverage the reachability detection APIs that were introduced in the 128T router as of 5.2.0 version of software. More documentation on the core product feature c
I've updated the keyword where possible since there are process names etc with 128T in the name.

2021-11-16 23:25 UTC, MichaelBaj commented on docs/plugin_http_probe.md
> +Once the profile is created, the next step is to enable the reachability enforcement and probe detection for a non SVR service-route and reference the profile in that config.
Please add a caveat since this is covered by validation.

2021-11-16 23:26 UTC, MichaelBaj commented on docs/plugin_http_probe.md
> +The router should have a distinct path for the probe traffic. It is recommended that the user create dedicated services and service routes for this purpose. At this time, the plugin does not generate
If validation exists, then additional documentation is not needed.

2021-11-16 23:28 UTC, agrawalkaushik commented on docs/plugin_http_probe.md
> +Once the profile is created, the next step is to enable the reachability enforcement and probe detection for a non SVR service-route and reference the profile in that config.
So this is an "implicit" requirement but there is no validation. I currently don't have the cycles to test the SVR to see if this just works. So my proposal is that we keep this caveat in place and we can update the doc based on additional testing later. @MichaelBaj let me know if that works for you.

2021-11-18 22:27 UTC, jeffmart submitted a review, later dismissed

2021-11-18 22:28 UTC, jeffmart submitted a review, later dismissed

2021-11-23 13:47 UTC, MichaelBaj submitted a review, later dismissed

2021-12-03 22:20 UTC, MichaelBaj approved these changes

2021-12-03 22:29 UTC, merged