Extended support for 5.1 into the end of Janurary since the release of 5.2 has been pushed out
128technology/docs pull request #305
Opened 2021-12-06 16:59 UTC by MichaelBaj

date for 5.2 has been extended

2021-12-06 17:02 UTC, Chr1st0ph3rTurn3r approved these changes

2021-12-06 20:12 UTC, Chr1st0ph3rTurn3r requested changes
The dates are all incorrect - I realized this when I went back in to verify something for the 5.1.7 Release Notes. You changed them all to January 31 of 2021 - should be 2022.

2021-12-06 21:16 UTC, Chr1st0ph3rTurn3r approved these changes

2021-12-08 17:59 UTC, jeffmart approved these changes

2021-12-08 17:59 UTC, merged