5.5 documentation
128technology/docs pull request #309
Opened 2021-12-14 20:46 UTC by Chr1st0ph3rTurn3r

2021-12-20 18:27 UTC, mja9444 requested changes

2021-12-20 18:27 UTC, mja9444 commented on docs/config_forward_error_correction.md
> +### Dynamic Mode:
Dynamic mode is a bit confusing.  How about this, to be a bit more explicit (which should make it more clear)? 
```
In this mode, the behavior of FEC is adjusted for the currently observed packet loss.  
Its behavior is defined according the FEC profile that was configured which is used to calculate 
what dataPacket:parityPacket ratio is desired for a given loss value in the following way:

* [0, low-loss-threshold): Parity disabled, no parity is needed
* [low-loss-threshold, high-loss-threshold]: calculate the ratio needed for a given loss by computing the slope of the line described by (low-loss-threshold, low-loss-ratio) and (high-loss-threshold, high-Loss-ratio).
* (high-loss-threshold, 100]: high-loss-ratio

When parity is disabled, per the profile, FEC will continue to attach the per-packet trailer to each 
data packet, but it will cease to calculate and send parity packets.  This results in a reduced
bandwidth overhead on links with observed loss less than the low-loss-threshold.
```

2021-12-22 20:58 UTC, MichaelBaj commented on docs/config_domain-based_web_filter.md
> +- **module:** The 128T router uses an external module for application classification. The 128T expects classification modules to be installed on the system in /var/etc/128technology/application-modul
Given that modules aren't "automatically" installed or created, please provide a link to how to create or use modules here.

2021-12-22 20:58 UTC, MichaelBaj commented on docs/config_domain-based_web_filter.md
> +By default, Application Identification automatically downloads updated domain and application datatsets weekly. The defaults (shown below) can be adjusted as necessary using the Application Data Upda
It would be very valuable to provide a debugging command here to show when the application signature pack has been last updated.

2021-12-22 20:58 UTC, MichaelBaj commented on docs/config_reference_guide.md
> +This sub-element allows you to automatically generate category-based application identification services under a service.
There should be a corresponding set of `cli_stats_reference.md` that needs to be updated with the new metrics added for FEC and others.

2021-12-22 20:58 UTC, MichaelBaj commented on docs/config_web_filtering.md
> +Web filtering provides technology within SSR that allows administrators to prevent clients within a network access to dangerous, malicious, or inappropriate internet content. While Domain-based routi
Create an internal link to domain-based routing

2021-12-22 20:58 UTC, MichaelBaj commented on docs/config_web_filtering.md
> +The SSR Application Director (AD) maintains a local cache of URLs known to contain threatening content, or that have been configured to be blocked. As clients request various URLs over HTTP, the SSR
"Application Director (AD)" is an internal detail and should be removed. Subsequently the use of AD later on should be replaced with SSR.

2021-12-22 20:58 UTC, MichaelBaj commented on docs/config_web_filtering.md
> +## Using Web Filtering
Intentionally left blank?

2021-12-22 21:06 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +### Dynamic Mode:
Made changes, but I have questions about the bullet points in this description. Will reach out offline.

2021-12-22 21:06 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +### Forward Error Correction Profile
done

2021-12-22 21:06 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +            low-loss-ratio       30
done

2021-12-22 21:06 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +            service-policy  packet-duplication-policy
done

2021-12-22 21:07 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +Forward Error Correction has the following limitations:
done

2021-12-22 21:07 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +        service-policy                    packet-duplication-policy
done

2021-12-22 21:07 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +If a static mode profile is not created, the default value for `low-loss-ratio` (20) is used.
done

2021-12-22 21:07 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +Static mode hides all fields except for `low-loss-ratio`. In this mode, FEC does not change behavior based on loss. Thresholds are implicitly set to 0 (always on) and the `high-loss-ratio` is set to
done

2021-12-22 21:07 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +```
done

2021-12-22 21:07 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +* `high-loss-ratio` - Default 1:2. Defines the number of data packets to transmit before a parity packet is transmitted when loss is high.
done

2021-12-22 21:07 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +* `low-loss-ratio` - Default 1:20. Defines the number of data packets to transmit before a parity packet is transmitted when loss is low.
done

2021-12-23 18:27 UTC, svjaffer commented on docs/config_forward_error_correction.md
> +Forward Error Correction profiles are configured at the authority level, and can be used by any router in the authority. You can create a profile for a particular type of traffic, or even traffic typ
> You can create a profile for a particular type of traffic, or even traffic type and a transport medium

I feel like this is an awkward and potentially misleading way to say that a user can apply any fec-profile to any service in the authority, since the fec-profile doesn't contain any references to traffic types and all of that is determined by the service.

2021-12-28 17:02 UTC, Chr1st0ph3rTurn3r commented on docs/config_web_filtering.md
> +The SSR Application Director (AD) maintains a local cache of URLs known to contain threatening content, or that have been configured to be blocked. As clients request various URLs over HTTP, the SSR
removed.

2021-12-28 17:02 UTC, Chr1st0ph3rTurn3r commented on docs/config_web_filtering.md
> +## Using Web Filtering
for now

2021-12-28 17:02 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +Forward Error Correction profiles are configured at the authority level, and can be used by any router in the authority. You can create a profile for a particular type of traffic, or even traffic typ
Edits made. Removed wording around traffic.

2021-12-28 17:03 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +### Dynamic Mode:
changes made for clarification.

2021-12-28 17:05 UTC, Chr1st0ph3rTurn3r commented on docs/config_web_filtering.md
> +Web filtering provides technology within SSR that allows administrators to prevent clients within a network access to dangerous, malicious, or inappropriate internet content. While Domain-based routi
added link.

2022-01-04 19:31 UTC, mja9444 approved these changes

2022-01-04 19:40 UTC, mja9444 requested changes

2022-01-04 19:40 UTC, mja9444 commented on docs/config_forward_error_correction.md
> +- **Parity-sent:**  A parity packet was successfully sent.
Slight regrouping of the success stats:   
```
success
{
    add
    {
        parity-sent
        trailer-added
    }
    remove
    {
        trailer-removed
        regenerated-packet
        completed-round
        unnecessary-parity
        resync
        out-of-order
    }
}
```

2022-01-04 19:40 UTC, mja9444 commented on docs/config_forward_error_correction.md
> +- **Allocation:** The number of times a packet was dropped because memory for the FEC trailer could not be allocated.
Slight regrouping of the failure stats:
```
failure
{
    add
    {
        allocation
        buffer-expansion
    }
    remove
    {
        completed-round
        out-of-order
        unexpected-parity
        parity-discard
        invalid-payload-length
    }
}
```

2022-01-04 22:07 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +- **Parity-sent:**  A parity packet was successfully sent.
changes made

2022-01-04 22:08 UTC, Chr1st0ph3rTurn3r commented on docs/config_forward_error_correction.md
> +- **Allocation:** The number of times a packet was dropped because memory for the FEC trailer could not be allocated.
changes made

2022-01-07 17:32 UTC, robert-patterson commented on docs/config_domain-based_web_filter.md
> +- The initial request is dropped while the query takes place, and a configurable number of retransmissions takes place to maintain the connection.
Should this specify that it's on the client to retransmit packets to attempt to complete the connection? Something like

While waiting for a response to the categorization query, the SRR will drop packets for the request. Clients will attempt to retransmit the request. If a configurable threshold of retransmissions is hit, the SRR will give up on categorization and continue applying the access-policy of the initial service, either allowing the request through or denying the session.

2022-01-07 17:38 UTC, robert-patterson approved these changes

2022-01-07 18:26 UTC, tjbresnahan commented on docs/config_dscp_steering.md
> +Steering of ESP traffic takes place using the dscp values configured on the service as shown below.
Steering is done using the DSCP values in both cases (NatT and ESP)

2022-01-07 18:26 UTC, tjbresnahan commented on docs/config_dscp_steering.md
> +A DSCP value and range is configured for the Service; this identifies the priority and handling of the traffic at the router. DSCP aware services are configured in a hierarchy; DSCP values are not co
It may be clearer to have the same sort of high-level how-to that the web filtering section does

1. Configure the ingress interface for dscp-steering
2. Configure a parent service which matches the traffic profile of the tunnel
3. Configure a child service which defines the dscp range for which to steer

2022-01-07 18:40 UTC, benbeshel approved these changes
Not much to change, just small typos, otherwise the content is good.

2022-01-07 18:40 UTC, benbeshel commented on docs/how_to_use_app_summary.md
> +Clicking on the down arrow on the left-side of the table expands collapsed rows, showing associated child data when available. Click on the appropriate color coded checkbox to hide the series in the
"can also change the data is being viewed" -> "can also change the data **that** is being viewed"

just need to add "that"

2022-01-07 18:40 UTC, benbeshel commented on docs/how_to_use_app_summary.md
> +Similar to the Custom Reports functionality, a time selector in the top-right of the page  allows you to select a time range (default is 30 minute lookback). To minimize load time and strain on the s
There is an extra space in "page  allows"

2022-01-07 18:59 UTC, robert-patterson commented on docs/config_domain-based_web_filter.md
> +- The initial request is dropped while the query takes place, and a configurable number of retransmissions takes place to maintain the connection.
If a configurable threshold of retransmissions is hit, the SRR will give up on categorization and allow the session.

2022-01-07 21:02 UTC, Chr1st0ph3rTurn3r commented on docs/how_to_use_app_summary.md
> +Clicking on the down arrow on the left-side of the table expands collapsed rows, showing associated child data when available. Click on the appropriate color coded checkbox to hide the series in the
I went with the "less is more" mindset and deleted "is".

2022-01-07 21:02 UTC, Chr1st0ph3rTurn3r commented on docs/how_to_use_app_summary.md
> +Similar to the Custom Reports functionality, a time selector in the top-right of the page  allows you to select a time range (default is 30 minute lookback). To minimize load time and strain on the s
Nice catch!

2022-01-07 21:32 UTC, Chr1st0ph3rTurn3r commented on docs/config_dscp_steering.md
> +Steering of ESP traffic takes place using the dscp values configured on the service as shown below.
change made

2022-01-10 15:53 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +- The initial request is dropped while the query takes place, and a configurable number of retransmissions takes place to maintain the connection.
I went with a combination of the first and second suggestions. Please review to make sure the context and information are correct.

2022-01-10 15:54 UTC, Chr1st0ph3rTurn3r commented on docs/config_dscp_steering.md
> +A DSCP value and range is configured for the Service; this identifies the priority and handling of the traffic at the router. DSCP aware services are configured in a hierarchy; DSCP values are not co
Thank you for pointing that out. I rearranged the section to be more efficient/clear. Please re-review. Thanks.

2022-01-10 16:05 UTC, tjbresnahan requested changes
The DSCP steering section is much clearer now. Thanks for making those changes!

The needs-changes is for the typos. The other comment is fair game for debate

2022-01-10 16:05 UTC, tjbresnahan commented on docs/config_domain-based_web_filter.md
> +- While waiting for a response to the categorization query, the SRR will drop packets for the request. Clients will attempt to retransmit the request. If a configurable threshold of retransmissions i
Possibly nit-picking, but I think rather than
`Clients will attempt to retransmit ...`
we should say
`Clients are expected to retransmit ...`
off the fact that we dont have control / a priori knowledge of the user's client

2022-01-10 16:05 UTC, tjbresnahan commented on docs/config_dscp_steering.md
> +Configure the `network-inerface` for `dcsp-steering`:
typo: `network-inerface` --> `network-interface`

2022-01-10 20:13 UTC, agrawalkaushik commented on docs/config_app_ident.md
> +Application Identification allows the automatic generation of category-based child services under a service. It also will automatically learn, identify, and classify applications processed by the SSR
> Application Identification allows the automatic generation of category-based child services under a service.

This is not a very accurate description or at least not the first line that I was hoping to read about this feature. I would recommend swapping the two lines. The learning, identifying etc is the main function of this feature that we can/should highlight IMO.

2022-01-10 20:19 UTC, agrawalkaushik commented on docs/config_app_ident.md
> +- **tls:** The system inspects X.509 certificates exchanged during the TLS handshake to look for Common Name elements to identify applications.
should mention client certificates in this case? @svjaffer can provide the exact technical wording around this if need be. Please do follow up with Sarah on this.

2022-01-10 20:21 UTC, agrawalkaushik commented on docs/config_app_ident.md
> +By default, Application Identification automatically downloads updated domain and application datatsets weekly. The defaults (shown below) can be adjusted as necessary using the Application Data Upda
nit: In `downloads updated domain` the `updated` part seems redundant IMO. I think saying `By default, the system will automatically download domain and application datatsets weekly.` reads better

Also `Application Idenfification` is a concept. Saying either `system`, `SSR` or `application director` when referring to it in terms of actions performed would be better.

2022-01-10 20:22 UTC, agrawalkaushik commented on docs/config_app_ident.md
> +The Application Summary is available for each router with Application Identification enabled. Use the steps below to configure Application Learning mode for a router that does not have application id
Remove `that does not have application identification enabled` as its confusing and redundant.

2022-01-10 20:22 UTC, agrawalkaushik commented on docs/config_app_ident.md
> +Application learning mode gathers statistics about domains and categories. You can select the type of information to be gathered; Modules, HTTPS, TLS, or All.
`HTTPS` -> `HTTP`

2022-01-10 20:24 UTC, agrawalkaushik commented on docs/config_app_ident.md
> +Application learning mode gathers statistics about domains and categories. You can select the type of information to be gathered; Modules, HTTPS, TLS, or All.
One other point here - (and I would like @reidstidolph and @MichaelBaj feedback on this). There is no good reason to explicitly configure all the various modes. The `all` mode for application-identification should be preferred. To that end maybe the documentation should be simplified to refer to `all` in most places and hide/move the rest of the modes to an "advanced" section or sorts?

2022-01-10 20:30 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
@MichaelBaj thought we do not explicitly require a license for web-filtering, should we put any note/warning etc about acquiring a special license/SKU to use this feature? Since this is a public doc wasn't sure if we want someone to just enable it without realizing they are supposed to get a special SKU for this feature?

2022-01-10 20:30 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +The SSR maintains a cache of the most frequently used URLs. As clients request URLs over HTTP, the SSR compares the request to the cache. If a requested URL is matched to one in the cache, then the i
`frequently used domains and URLs` for completeness

2022-01-10 20:32 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +- The initial request is dropped while the query takes place, and a configurable number of retransmissions takes place to maintain the connection.
how about saying `and a configurable number of client retransmissions` to emphasis on the fact taht we are relying on the client's behavior here.

2022-01-10 21:01 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +- subcategory
might be worth mentioning somewhere that the subcategory only applies/works for routers with web-filtering enabled. Otherwise the service will ignore the configuration at run time.

2022-01-11 19:18 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +The SSR maintains a cache of the most frequently used URLs. As clients request URLs over HTTP, the SSR compares the request to the cache. If a requested URL is matched to one in the cache, then the i
done

2022-01-11 19:19 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
That's important. Will follow up. The answer is yes - I've added a note at the start of the web filtering doc.

2022-01-11 21:38 UTC, agrawalkaushik commented on docs/how_to_use_app_summary.md
> +The Application Summary is accessed by selecting a router from the Authority -> Routers list. The Router page displays a table with current Application Summary statistics. Currently, the list  contai
`last X minutes` is last 1 minute I believe but please double check with @benbeshel

2022-01-11 21:39 UTC, agrawalkaushik commented on docs/how_to_use_app_summary.md
> +By default the table shows all Applications, grouped by Category. This can be changed to view only Applications, or view only Clients (which will show the user a reverse view. The other two views are
> This can be changed to view only Applications, or view only Clients (which will show the user a reverse view. The other two views are top-down, the Client view is bottom-up, where we map each Application to each unique Client).

I found this explanation of the UI very tedious to understand. In this instance a simple screenshot might be better than trying to explain the UI. The picture should be very much self explanatory.

2022-01-11 21:41 UTC, agrawalkaushik commented on docs/how_to_use_app_summary.md
> +The table controls include `Pivot By`, `View By`, and a `Search`. `View By` changes the metric being viewed in the chart - currently it can change between `rx`, `tx`, and `total bytes`. Clicking on t
Maybe a GIF would be better or at least creating step by step bulleted list will be better. I found this section describing the UI very tedious to read and understand without a UI in front of me.

2022-01-11 21:42 UTC, agrawalkaushik commented on docs/how_to_use_app_summary.md
> +Application Summary data currently is only viewed on a node-by-node basis - that is, data viewed comes specifically from one node at a time. Use the **Node** dropdown on the top-right of the page to
> Application Summary data currently is only viewed on a node-by-node basis - that is, data viewed comes specifically from one node at a time. Use the **Node** dropdown on the top-right of the page to change the node being viewed.

Can be simplified to say the following. Intoducing the notion of `node-by-node basis` and having to explain it seems redundant and un-necessary to me!

Application Summary data currently is only viewed one node at a time. Use the **Node** dropdown on the top-right of the page to change the node being viewed.

2022-01-11 21:55 UTC, agrawalkaushik commented on docs/config_domain-based_web_filter.md
> +## Service Matching Order
A common ask seems to be able to deny all internet traffic and only allow certain categories, subcategories etc. I'm working on a configuration for that and will let you know when I have it. I would like to include a section for it in this doc.

2022-01-11 22:30 UTC, benbeshel commented on docs/how_to_use_app_summary.md
> +The Application Summary is accessed by selecting a router from the Authority -> Routers list. The Router page displays a table with current Application Summary statistics. Currently, the list  contai
I would either note what "last X minutes" is, as in, that it's `Write Interval` found in the config, or replace it with "total bytes transferred since the last write interval" - up to you which you feel makes more sense, but because X minutes is configurable I wouldn't want to accidentally mislead anyone.

2022-01-11 22:31 UTC, benbeshel commented on docs/how_to_use_app_summary.md
> +The Application Summary is accessed by selecting a router from the Authority -> Routers list. The Router page displays a table with current Application Summary statistics. Currently, the list  contai
Also there is an extra space in "Currently, the list  contains names of each application"

2022-01-12 20:28 UTC, Chr1st0ph3rTurn3r commented on docs/how_to_use_app_summary.md
> +The Application Summary is accessed by selecting a router from the Authority -> Routers list. The Router page displays a table with current Application Summary statistics. Currently, the list  contai
made it clearer.

2022-01-12 20:29 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +## Service Matching Order
okay, sounds good.

2022-02-03 15:57 UTC, robert-patterson commented on docs/config_domain-based_web_filter.md
> +For example, on the URL: http://www.google.com/doodles/doodle-champion-island-games-september-05, matching will be performed in the following order.
should the url be in a code formatting block like `http://www.google.com/doodles/doodle-champion-island-games-september-05`

2022-02-03 16:01 UTC, robert-patterson commented on docs/how_to_use_app_summary.md
> +To enable the Application Summary for a router that does not have web filtering enabled, go to Configuration -> Authority -> [router name] -> Application Identification Settings and set Summary Track
summary-tracking is an advanced visibility field that defaults to true. Both app-id mode all needs to be enabled and summary-tracking must be true for the feature to be active.

2022-02-03 17:06 UTC, Chr1st0ph3rTurn3r commented on docs/how_to_use_app_summary.md
> +To enable the Application Summary for a router that does not have web filtering enabled, go to Configuration -> Authority -> [router name] -> Application Identification Settings and set Summary Track
Made changes to the topic to be more correct.

2022-02-16 19:38 UTC, Chr1st0ph3rTurn3r commented on docs/config_domain-based_web_filter.md
> +- **module:** The 128T router uses an external module for application classification. The 128T expects classification modules to be installed on the system in /var/etc/128technology/application-modul
This information was moved to the Application Identification page, and a link was added to the concepts topic.

2022-02-22 21:42 UTC, MichaelBaj requested changes
- Missing changes to releases.table.js
- Missing changes to about_releases.mdx
- release_notes_128t_5.5.md is incomplete

2022-02-28 14:58 UTC, MichaelBaj requested changes

2022-02-28 14:58 UTC, MichaelBaj commented on docs/about_releases.mdx
> +| Release 5.4 | [5.5.0](release_notes_128t_5.5.md#) |
Should be "Release 5.5"

2022-02-28 14:58 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +**Release Date:** February 25, 2022
Release date needs to be updated.

2022-02-28 14:58 UTC, MichaelBaj commented on docs/releases.table.js
> +    releaseDate: 'February 25, 2022',
Release date needs to be updated.

2022-02-28 14:58 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-25630 Gateway IP is required:** When creating or changing a service-route with a next-hop of a static IP net-int, a gateway IP is required. If no gateway IP has been specified, the network-in
IMO, while this was a substantive amount of work for the development team (which is why it was classified as an epic), this is a defect by way of omission in the initial requirements. I believe this should be moved to the Resolved Issues section as many of our customers and field team view this as a bug.

2022-02-28 14:58 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-40660 Kernel Upgrade:** The OS kernel has been upgraded to that of CentOS 8.4 to address several CVEs and provide support for Wireguard and Cordoba.
Change "Cordoba" to "Cordoba platform". It would also be great to add the Cordoba platform to our supported hardware page.

2022-02-28 14:58 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-44534 PCAP function in GUI triggering session-capture instead of capture-filter:** This issue has been resolved. The PCAP function now performs correctly.
Rewording needed:
**I95-44534 Session Capture in GUI not working:** Session Capture triggered from GUI will now create a capture for new sessions traversing the same path as this session

2022-03-01 17:08 UTC, MichaelBaj requested changes

2022-03-01 17:08 UTC, MichaelBaj commented on docs/about_releases.mdx
> +| Release 5.5 | [5.5.0](release_notes_128t_5.5.md#) |
link is incorrect. should point to release_notes_128t_5.5.md#release-550-build number when available.

2022-03-07 14:12 UTC, MichaelBaj requested changes

2022-03-07 14:12 UTC, MichaelBaj commented on docs/about_releases.mdx
> +| Release 5.5 | [5.5.0](release_notes_128t_5.5.md#) |
As per our conversation, I like that this points to the heading of the page. However you still need to drop the trailing hash mark.

2022-03-07 14:12 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-44915 Large amounts of Application Identifictation data take a long time to load:** Wait times of up to 1.5 minutes may occur when displaying large amounts of application identification data.
From this caveat, it is unclear as to what specific page may encounter this issue. The reader may think it is every page.

2022-03-07 16:40 UTC, MichaelBaj submitted a review, later dismissed

2022-03-07 17:58 UTC, mja9444 requested changes

2022-03-07 17:58 UTC, mja9444 commented on docs/config_forward_error_correction.md
> +- This feature should not be used when transferring large amounts of data at the MTU size. Similar to metadata, it is possible for this feature to increase the size of the packets beyond the MTU.
It is probably worth mentioning:  We have accounted for this by automatically adjusting for the increase when the Path-MTU feature is enabled.

2022-03-07 18:36 UTC, mja9444 commented on docs/config_forward_error_correction.md
> +- This feature should not be used when transferring large amounts of data at the MTU size. Similar to metadata, it is possible for this feature to increase the size of the packets beyond the MTU.
Update to the MTU issue looks good

2022-03-07 18:37 UTC, mja9444 approved these changes
FEC documentation looks good

2022-03-07 18:58 UTC, tjbresnahan approved these changes

2022-03-07 19:08 UTC, robert-patterson approved these changes

2022-03-07 20:23 UTC, MichaelBaj approved these changes

2022-03-07 21:11 UTC, Bhautik approved these changes

2022-03-07 21:11 UTC, merged