Release notes for 5.4.2
128technology/docs pull request #311
Opened 2021-12-21 18:31 UTC by MichaelBaj

2021-12-21 18:58 UTC, ptimmons requested changes
Two small nits.

2021-12-21 18:58 UTC, ptimmons commented on docs/release_notes_128t_5.4.md
> +- **I95-42467 save-tech-support info does not save verbose configuration:** Corrected save-tech-support manifest to collect necessary configuration.
Two changes:
save tech-support-info
Corrected tech-support-info manifest

2021-12-21 19:20 UTC, ptimmons approved these changes

2021-12-22 14:04 UTC, Chr1st0ph3rTurn3r approved these changes

2021-12-22 22:42 UTC, jeffmart approved these changes

2021-12-22 23:09 UTC, merged