adding 5.4.3 release notes, removed 4.5.11 from the about releases pa…
128technology/docs pull request #315
Opened 2022-01-10 22:00 UTC by Chr1st0ph3rTurn3r

…ge because it is EOS. Also changed references from  128T to SSR in several other docs.

2022-01-10 22:08 UTC, MichaelBaj approved these changes

2022-01-10 22:08 UTC, MichaelBaj commented on docs/release_notes_128t_5.4.md
> +- **I95-42364 `off-subnet-reverse-arp-mac-learning` does not work when `outbound-only` is configured:** The  learned MAC is now saved in the reverse flow placeholder for use when the flow is establis
extra space after "The  "

2022-01-10 22:09 UTC, MichaelBaj requested changes

2022-01-10 22:09 UTC, MichaelBaj commented on docs/release_notes_128t_5.4.md
> +## Release 5.4.3-1
Build number of `5.4.3-3`

2022-01-10 22:32 UTC, MichaelBaj approved these changes

2022-01-11 19:20 UTC, MichaelBaj approved these changes

2022-01-26 22:46 UTC, Bhautik requested changes

2022-01-26 22:46 UTC, Bhautik commented on docs/release_notes_128t_5.4.md
>  ## Release 5.4.3-4
Release will be: 5.4.3-8

2022-01-26 22:46 UTC, Bhautik commented on docs/about_releases.mdx
> +| Release 5.4 | [5.4.3](release_notes_128t_5.4.md#release-543-3) |
Release: 5.4.3-8

2022-01-27 16:36 UTC, Bhautik approved these changes

2022-01-27 16:56 UTC, MichaelBaj approved these changes

2022-01-27 16:59 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.4.md
> +## Release 5.4.3-3
You are looking at an old commit. That was changed in the checkin 2c9c5db.

2022-01-27 18:13 UTC, jeffmart approved these changes

2022-01-27 18:54 UTC, merged