generating 5.1.8 release notes
128technology/docs pull request #318
Opened 2022-01-12 16:47 UTC by Chr1st0ph3rTurn3r

2022-01-12 18:16 UTC, MichaelBaj requested changes

2022-01-12 18:16 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-43066 Issue with database query co-ordinator:** Resolved an issue that when the buffer queue is full, the message is dropped, but the event was not handling the inflight message.
co-ordinator is not hyphenated. The process name within the system is `databaseQueryCoordinator`, not that that matters to customers.
Suggested heading: "Requests for metrics are timing out"

2022-01-12 18:16 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-43389 SALT Minion file truncation:** This issue has been resolved.
salt is not in all caps (https://saltproject.io/)

2022-01-12 18:16 UTC, MichaelBaj commented on docs/release_notes_128t_5.1.md
> +- **I95-43604 NAT keep alive problem:** Resolved an issue where the keep-alive cache entry was being removed when the flow was invalidated.
keepalive in the domain of software algorithms is usually one word or hyphenated.

2022-01-12 18:58 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-43066 Issue with database query co-ordinator:** Resolved an issue that when the buffer queue is full, the message is dropped, but the event was not handling the inflight message.
The first of the cut and paste errors. Updated.

2022-01-12 18:58 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-43389 SALT Minion file truncation:** This issue has been resolved.
Fixed

2022-01-12 18:59 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.1.md
> +- **I95-43604 NAT keep alive problem:** Resolved an issue where the keep-alive cache entry was being removed when the flow was invalidated.
fixed

2022-01-14 13:58 UTC, MichaelBaj approved these changes

2022-01-18 14:09 UTC, jeffmart approved these changes

2022-01-18 14:10 UTC, MichaelBaj approved these changes

2022-01-18 16:19 UTC, merged