Document reachability-detection probe-type
128technology/docs pull request #320
Opened 2022-01-18 17:38 UTC by robert-patterson

- add a step in the enforcement mode checklist for probe-type, which
  controls if probes are considered in the service health check

2022-01-18 17:44 UTC, MichaelBaj submitted a review, later dismissed

2022-01-18 17:53 UTC, avinashbhat80 approved these changes

2022-01-18 18:30 UTC, Chr1st0ph3rTurn3r requested changes

2022-01-18 18:30 UTC, Chr1st0ph3rTurn3r commented on docs/config_service_health.md
> +7. If probes will be used to determine service health, configure `probe-type` as `always`. Otherwise, configure `probe-type` as `disabled` to use only organic traffic as the basis of service health.
Two things with this. First I suggest changing to active voice:
To use a probe to determine service health, configure the `probe-type` as `always`. To use only organic traffic to determine service health, set the `probe-type` to `disabled`.
Second, based on the config example below, it looks like the `probe-type` is configured within the `reachability-detection` config. I think this step should go under step 11 ("In the probe type window, select a probe type from the drop down.")

2022-01-18 19:37 UTC, robert-patterson commented on docs/config_service_health.md
> +7. If probes will be used to determine service health, configure `probe-type` as `always`. Otherwise, configure `probe-type` as `disabled` to use only organic traffic as the basis of service health.
There's two different fields named `probe-type`. One is under reachability-detection (enum of always or disabled). The other is under `Reachability Detection Enforcement Probes`, which is the drop-down.
This new step is adding the `probe-type` under reachability-detection, which is at the same level as `Enforcement Detection Window` (step 5) and `Enforcement Hold-Down time` (step 6), so I think it makes sense to have this new step as 7. That way the user can do all the `Reachability Detection Settings` level settings before moving on to `Reachability Detection Enforcement Probes` in steps 8-11.

2022-01-18 20:36 UTC, Chr1st0ph3rTurn3r commented on docs/config_service_health.md
> +7. If probes will be used to determine service health, configure `probe-type` as `always`. Otherwise, configure `probe-type` as `disabled` to use only organic traffic as the basis of service health.
thank you for explaining that. I'm good with the changes.

2022-01-18 20:37 UTC, Chr1st0ph3rTurn3r approved these changes

2022-01-19 20:57 UTC, lliu5374 approved these changes

2022-01-20 15:38 UTC, MichaelBaj approved these changes

2022-01-20 15:39 UTC, merged