Updated SSN support policy to reflect current implementation
128technology/docs pull request #324
Opened 2022-01-20 17:02 UTC by MichaelBaj

2022-01-20 17:33 UTC, jeffmart submitted a review, later dismissed

2022-01-24 19:51 UTC, ryankoss submitted a review, later dismissed

2022-01-25 18:09 UTC, MichaelBaj commented
Kevin Klett provided updates out of band that are in line with Juniper's support policy. There are some changes to support timelines as well. Please re-review carefully.

2022-01-25 21:41 UTC, ryankoss commented on docs/about_support_policy.md
> +**EOS Date:** EOS Date is the date after which Juniper will not be under obligation to perform support services of any kind for the affected hardware or the embedded operating system software support
This mentions hardware which I think that hardware should be separate.

2022-01-25 21:45 UTC, ryankoss commented on docs/about_support_policy.md
> +**End-of-Life (EOL):** End-of-Life means that the product release in question has reached the end of its “useful lifespan”. After the EOL date, Juniper Networks will no longer provide support service
second line should say "product release" instead of "release of the product"

2022-01-25 21:54 UTC, ryankoss commented on docs/about_support_policy.md
> +**End-of-Life (EOL):** End-of-Life means that the product release in question has reached the end of its “useful lifespan”. After the EOL date, Juniper Networks will no longer provide support service
still have `release of the product` in second sentence

2022-01-25 22:05 UTC, ryankoss approved these changes

2022-01-26 15:02 UTC, Chr1st0ph3rTurn3r requested changes
I'm not positive about the "legalese" of some of the statements, so in places where I suggest removing "will" there may be some kind of contractual language that it should be left as "will".

2022-01-26 15:11 UTC, MichaelBaj commented on docs/about_support_policy.md
> +description: "This document defines the product lifecycle support policy for Juniper Networks’ software products.  The policy includes both software maintenance, software support and end-of-life."
See, I trained that habit out of me as I was conditioned to not add a comma before and

2022-01-26 15:40 UTC, Chr1st0ph3rTurn3r submitted a review, later dismissed

2022-01-26 20:15 UTC, jeffmart commented on docs/about_support_policy.md
> +description: "This document defines the product lifecycle support policy for Juniper Networks’ software products.  The policy includes both software maintenance, software support, and end-of-life."
Do we want Juniper Networks, Inc. instead of just "Juniper Networks'"

2022-01-26 20:17 UTC, jeffmart commented on docs/about_support_policy.md
> +**EOSE - End of Software Engineering support date:** EOSE is the date after which Juniper is no longer committed to furnish Software Engineering level support or “Maintenance” for the SSN Software. T
nit, "EoSE" or "EOSE"

2022-01-26 20:31 UTC, jeffmart approved these changes

2022-01-26 21:04 UTC, merged