updates per DOCS-280. Adding port and protocol info for SVR.
128technology/docs pull request #325
Opened 2022-01-24 21:23 UTC by Chr1st0ph3rTurn3r

Will send offline pdf of the doc to Rob Schumann and Adam Morris unless they miraculously appear in GitHub.

2022-01-24 21:33 UTC, MichaelBaj approved these changes

2022-01-25 14:00 UTC, MichaelBaj approved these changes

2022-01-25 21:34 UTC, laneshields commented on docs/concepts_machine_communication.md
> +The default range of ports used for configuring waypoints with SVR is 16,385 through 65,533.
I believe this range is split in half where the first half is used as an origin port for SVR and the second half is used as the destination port for SVR. This is done to avoid potential collisions. Not sure if it bears mentioning this fact (please confirm with someone in Engineering if so)

2022-01-25 21:36 UTC, laneshields commented on docs/concepts_machine_communication.md
> +Let's say you want to utilize UDP for transport, but do not want to open up all the default ports. To limit the number of ports open on your firewall, you choose to specify a port range of 10,000 to
I find the claim "With each new waypoint, another 1,000,000 active sessions are added" to be dubious here.  If we want to get specific then we can say each individual port open allows for (whatever the number of origin SVR ports as I commented above) new sessions per peer 128T router. Or just many thousands.

2022-01-25 21:37 UTC, laneshields commented on docs/concepts_machine_communication.md
> +Let's say you want to utilize UDP for transport, but do not want to open up all the default ports. To limit the number of ports open on your firewall, you choose to specify a port range of 10,000 to
Also, that math is specific to the number of 1M, so I'd pull that last sentence.

2022-01-25 21:38 UTC, laneshields requested changes
Please amend the specific sentences that claim 1M active sessions as this is dubious and in most cases I don't think the router even supports 1M sessions

2022-01-26 16:07 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_machine_communication.md
> +The default range of ports used for configuring waypoints with SVR is 16,385 through 65,533.
This is covered in the Concepts topic Waypoints and Waypoint Ports. There it says that 
"By default, each 128T will allocate waypoint ports for each of its interfaces using the default range of 16,385 through 65,533, for a total of 49,148 ports. When sending traffic to a peer, the 128T will allocate an even numbered waypoint for itself and an odd numbered waypoint for its peer. (We did this to avoid "glare conditions," the exceedingly unlikely chance that two devices would pick the exact same values in two directions simultaneously)."
I think adding the text: **When sending traffic to a peer, the 128T will allocate an even numbered waypoint for itself and an odd numbered waypoint for its peer.** is useful here.

2022-01-26 16:10 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_machine_communication.md
> +Let's say you want to utilize UDP for transport, but do not want to open up all the default ports. To limit the number of ports open on your firewall, you choose to specify a port range of 10,000 to
As a former co-worker (tech writer) used to say "When in doubt, vague it out". I think going with less specific claims here is a better idea.

2022-01-26 16:17 UTC, laneshields-jnpr approved these changes

2022-01-26 19:28 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_machine_communication.md
> +The default range of ports used for configuring waypoints with SVR is 16,385 through 65,533.
verified with Engineering that this is correct.

2022-01-26 19:38 UTC, laneshields approved these changes

2022-01-27 13:42 UTC, MichaelBaj approved these changes

2022-01-27 14:12 UTC, merged