resolving DOCS-279 and DOCS-171
128technology/docs pull request #326
Opened 2022-01-25 21:12 UTC by Chr1st0ph3rTurn3r

2022-01-25 21:19 UTC, MichaelBaj submitted a review, later dismissed

2022-01-25 21:37 UTC, ptimmons commented on docs/intro_upgrading.md
> +   If you are running an older version of the Installer (prior to version 2.7.0), it is strongly recommended to use the Screen utility when performing an upgrade in interactive mode to avoid SSH sess
First choice should be to upgrade the installer if at all possible. If that is impossible, then `screen` is the best path for versions < 2.7.

2022-01-25 21:38 UTC, ptimmons commented on docs/intro_upgrading.md
> +   If you are running an older version of the Installer (prior to version 2.7.0), it is strongly recommended to use the Screen utility when performing an upgrade in interactive mode to avoid SSH sess
"dnf update 128T-installer"

2022-01-25 21:39 UTC, ptimmons requested changes
Minor suggestions.

2022-01-26 14:14 UTC, Chr1st0ph3rTurn3r commented on docs/intro_upgrading.md
> +   If you are running an older version of the Installer (prior to version 2.7.0), it is strongly recommended to use the Screen utility when performing an upgrade in interactive mode to avoid SSH sess
added both comments.

2022-01-27 13:41 UTC, MichaelBaj approved these changes

2022-01-27 13:55 UTC, ptimmons approved these changes

2022-01-27 15:48 UTC, merged