Troubleshooting latency
128technology/docs pull request #331
Opened 2022-02-07 22:13 UTC by Chr1st0ph3rTurn3r

Reviewers, please see comments inline (Italicized text) with questions/clarification.

2022-02-07 22:46 UTC, ptimmons requested changes

2022-02-07 22:46 UTC, ptimmons commented on docs/ts_applications.md
> +Additionally, use [`show-fib router <router> tenant <tenant>`](cli_reference.md/#show-fib) to gather information about FIB entries at the router.
this is not related to determining the tenant, so it seems out of place.

2022-02-07 22:46 UTC, ptimmons commented on docs/ts_applications.md
> +_REVIEWERS: Need additional details on what is meant by priorities. Is this the priority of what should be fixed first? Is this to determine what the traffic priority is?_
Traffic on the SSR is sent using one of four traffic classes (high/medium/low/best-effort). This is the reference to priority.

2022-02-08 18:59 UTC, mthompson-jnpr commented on docs/ts_applications.md
> +4. On the right side of the information page, click **Debug**.
Starting in 5.1, the GUI item "Debug" was renamed to "Routing Details".

2022-02-08 19:50 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +4. On the right side of the information page, click **Debug**.
done

2022-02-08 19:50 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +_REVIEWERS: Need additional details on what is meant by priorities. Is this the priority of what should be fixed first? Is this to determine what the traffic priority is?_
This has been updated

2022-02-08 19:51 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +Additionally, use [`show-fib router <router> tenant <tenant>`](cli_reference.md/#show-fib) to gather information about FIB entries at the router.
moved to WAN Side Application Latency.

2022-02-08 23:30 UTC, ptimmons requested changes
I don't have any contributions to the short/long session discussion. You may want to bail on that for the time being and we can update it in the future. This page will probably need more attention once we release Mist WAN Assurance anyhow.

2022-02-08 23:30 UTC, ptimmons commented on docs/ts_applications.md
>  admin@node1.router# show tenant members
can you change AAPVA0962P1A to something else? whoooooooooops!

SOLMA0128P1A is a good replacement.

2022-02-10 14:52 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
>  admin@node1.router# show tenant members
addressed this as well as the comment above.

2022-02-10 15:19 UTC, ayungelson commented on docs/ts_applications.md
> +In cases where traffic engineering has been configured, an oversubscribed traffic class may cause the application performance to suffer. Use the following show commands to dig into the application pr
This is wrong. traffic-eng for `internal-application` isn't something that can be configured. it's always there and shows that the router isn't keeping up with the influx of traffic, which is completely different.

2022-02-18 14:46 UTC, ptimmons requested changes

2022-02-18 14:46 UTC, ptimmons commented on docs/ts_applications.md
> +## Application Latency Troubleshooting Steps
In line 6 you mention this is for troubleshooting performance or basic functionality, but here it specifically calls out Application Latency. I suggest you leave this at "troubleshooting steps."

2022-02-18 14:46 UTC, ptimmons commented on docs/ts_applications.md
> +Each of these steps is discussed in more detail in the sections that follow. It is recommended to perform the application troubleshooting steps on both the local router and the remote router.
remote router (if applicable).

2022-02-18 14:46 UTC, ptimmons commented on docs/ts_applications.md
> +- Functions
not sure what Functions is

2022-02-18 14:57 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +Each of these steps is discussed in more detail in the sections that follow. It is recommended to perform the application troubleshooting steps on both the local router and the remote router.
added

2022-02-18 15:00 UTC, ayungelson commented on docs/ts_applications.md
> +
@ptimmons maybe instead of "in addition" should we be just using session captures?

2022-02-18 15:01 UTC, ayungelson commented on docs/ts_applications.md
> +3. If possible, raise the log level on the ingress and egress SSR for the `highway` process. The command is `set log level debug highway` from the router's PCLI. If the router is not busy, you can se
this would not be necessary if session captures are enabled.

2022-02-18 15:02 UTC, ayungelson commented on docs/ts_applications.md
> +1. Enable packet captures as was done previously, but also enable them on the WAN interface(s) of the ingress and egress SSR devices. Use `capture-filter` configuration that limits the traffic to onl
again, wouldn't be necessary, if using session capture...

2022-02-18 18:14 UTC, ptimmons commented on docs/ts_applications.md
> +
yes, 100% agree.

2022-02-18 18:45 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +3. If possible, raise the log level on the ingress and egress SSR for the `highway` process. The command is `set log level debug highway` from the router's PCLI. If the router is not busy, you can se
removed

2022-02-18 18:45 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +1. Enable packet captures as was done previously, but also enable them on the WAN interface(s) of the ingress and egress SSR devices. Use `capture-filter` configuration that limits the traffic to onl
removed

2022-02-18 20:15 UTC, ayungelson commented on docs/ts_applications.md
> +Please refer to the [Selective Packet Capture section](ts_packet_capture.md#selective-packet-capture) to configure this feature.
Minor nit -
"to enable this feature" instead of "to configure this feature"
since it's not actually config?

2022-02-18 20:17 UTC, ayungelson commented on docs/ts_applications.md
> +Use the `show stats traffic-eng device-interface per-traffic-class traffic-class <traffic class>` to display the available success and failure statistics associated with traffic engineering. When exp
how come these stats don't have the nice links that the others do?

2022-02-18 20:20 UTC, ayungelson commented on docs/ts_applications.md
> +2. Prior to testing, enable packet captures on the non-SVR interfaces (typically the LAN) at both the ingress SSR and the egress SSR devices. Use filters that are inclusive, but as narrow as possible
this is where the session capture should be used, not packet capture on the LAN

2022-02-18 20:20 UTC, ayungelson commented on docs/ts_applications.md
> +7. Lower the log levels on all devices, disable packet captures on all devices.
don't need to lower log level if it wasn't explicitly raised

2022-02-18 20:25 UTC, ayungelson commented on docs/ts_applications.md
> +2. Look for these ports in the WAN captures on both the ingress and egress routers. If you see them leaving the ingress router and not arriving at the egress router, then this should be taken to your
it wouldn't be the WAN captures, it would be the "128T_service_<serviceName>.pcap

2022-02-18 20:33 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +Please refer to the [Selective Packet Capture section](ts_packet_capture.md#selective-packet-capture) to configure this feature.
done

2022-02-18 20:34 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +Use the `show stats traffic-eng device-interface per-traffic-class traffic-class <traffic class>` to display the available success and failure statistics associated with traffic engineering. When exp
linking.

2022-02-18 20:41 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +7. Lower the log levels on all devices, disable packet captures on all devices.
noted. should this be session capture as well?

2022-02-18 20:43 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +2. Look for these ports in the WAN captures on both the ingress and egress routers. If you see them leaving the ingress router and not arriving at the egress router, then this should be taken to your
changed

2022-02-18 20:49 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +2. Prior to testing, enable packet captures on the non-SVR interfaces (typically the LAN) at both the ingress SSR and the egress SSR devices. Use filters that are inclusive, but as narrow as possible
changed to read "session capture" and changed packet capture to session capture where applicable.

2022-02-18 20:50 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +10. If the packet captures and logs do not both contain the user's test traffic, change the filter to improve the signal:noise ratio and re-test. **Getting packet captures that correspond to logs tha
I removed it.

2022-02-18 22:23 UTC, MichaelBaj submitted a review, later dismissed

2022-03-06 01:17 UTC, MichaelBaj commented
Is this ready to be re-reviewed by all parties? Is there more work to be done?

2022-03-09 15:54 UTC, ptimmons commented on docs/ts_applications.md
> +As with issues with the ingress router, this is generally due to a configuration problem or a transient network issue (e.g., an interface failure). Look for the `BEGINNING TEST` messages in the logs
typo in the word you changed (sessioin)

2022-03-09 17:14 UTC, ayungelson commented on docs/ts_applications.md
> +2. Prior to testing, enable session captures on the non-SVR interfaces (typically the LAN) at both the ingress SSR and the egress SSR devices. Use filters that are inclusive, but as narrow as possibl
`2.` doesn't make sense - that's not how session capture works...
"Prior to testing, enable session capture on the LAN interface of the ingress router using the service identified in prior steps" or something like that...
No need for the note that talks about filtering, as the session capture takes care of all that...

2022-03-09 17:14 UTC, ayungelson commented on docs/ts_applications.md
> +7. Lower the log levels on all devices (if explicitly raised), and disable session captures on all devices.
session capture propagates itself across routers, so, you only needed to enable it on the ingress router, so should be just "disable session capture"
I personally would skip anything about raised log levels, as we never asked them to raise that?

2022-03-09 17:14 UTC, ayungelson commented on docs/ts_applications.md
> +1. Run the tests as was done previously. Investigate the `highway` logs or the output of the `show sessions` table while the traffic is in progress to see what waypoint allocations were assigned to t
I would suggest "Investigate `highway` and `serviceArea` logs...

2022-03-09 19:21 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +1. Run the tests as was done previously. Investigate the `highway` logs or the output of the `show sessions` table while the traffic is in progress to see what waypoint allocations were assigned to t
done

2022-03-09 19:22 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +7. Lower the log levels on all devices (if explicitly raised), and disable session captures on all devices.
done

2022-03-09 19:22 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +2. Prior to testing, enable session captures on the non-SVR interfaces (typically the LAN) at both the ingress SSR and the egress SSR devices. Use filters that are inclusive, but as narrow as possibl
done

2022-03-09 19:22 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +As with issues with the ingress router, this is generally due to a configuration problem or a transient network issue (e.g., an interface failure). Look for the `BEGINNING TEST` messages in the logs
fixed

2022-03-09 22:32 UTC, ayungelson commented on docs/ts_applications.md
> +2. Prior to testing, enable session captures on the LAN interface of the egress router using the service identified in previous steps. Use filters that are inclusive, but as narrow as possible to kee
I think this is all we need here:
```
2. Prior to testing, enable session captures on the ingress router using the service identified in previous steps. 
```

2022-03-10 14:33 UTC, Chr1st0ph3rTurn3r commented on docs/ts_applications.md
> +2. Prior to testing, enable session captures on the LAN interface of the egress router using the service identified in previous steps. Use filters that are inclusive, but as narrow as possible to kee
update made

2022-03-10 16:32 UTC, ayungelson approved these changes

2022-03-10 17:51 UTC, MichaelBaj approved these changes

2022-03-10 18:22 UTC, merged