Add release notes for dns cache and dns app id plugins
128technology/docs pull request #332
Opened 2022-02-08 03:25 UTC by agrawalkaushik

DOCS-252 #time 20m

2022-02-08 14:04 UTC, BenMatase requested changes

2022-02-08 14:04 UTC, BenMatase commented on docs/plugin_dns_app_id.md
> +- **PLUGIN-1494**  no route being injected into FIB table for dns-app-id custom apps.
Capital N here to start the sentence and remove the period at the end for consistency

2022-02-08 14:04 UTC, BenMatase commented on docs/plugin_dns_app_id.md
> +  _**Resolution:**_ Correctly handle the config generation for routers where the DNS cache plugin is not enabled during bonsai config generation
Capitalize Bonsai or do customers know/care about Bonsai?

2022-02-08 15:21 UTC, MichaelBaj requested changes

2022-02-08 15:21 UTC, MichaelBaj commented on docs/plugin_dns_app_id.md
> +  _**Resolution:**_ Correctly handle the config generation for routers where the DNS cache plugin is not enabled during bonsai config generation
Bonsai should be excluded from the release notes. Instead refer to the release in which Bonsai was introduced. e.g., >= 5.3

2022-02-09 15:15 UTC, BenMatase approved these changes

2022-02-09 15:15 UTC, BenMatase commented on docs/plugin_dns_app_id.md
> +- **PLUGIN-1461**  Config generation for the plugin failing.
We def aren't consistent with the periods at the end of sentences even further below. Dunno if you want to make it consistent or if this is sufficient

2022-02-09 15:37 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_dns_app_id.md
> +- **PLUGIN-1461**  Config generation for the plugin failing.
Honestly, if I chased the list/punctuation issue, I would be making changes to every release notes file all the way back to the beginning. As a writer I notice it (along with the oxford comma) and I know what the usage is supposed to be, but most folks don't pick up on it. You are one of the few that do, Ben. I try to keep the new stuff punctuated correctly.

2022-02-09 16:20 UTC, agrawalkaushik commented
Thanks @Chr1st0ph3rTurn3r for handling the review comments - much appreciated!

2022-02-09 18:40 UTC, MichaelBaj approved these changes

2022-02-09 18:48 UTC, merged