Added ipsec client 3.2.0 docs
128technology/docs pull request #336
Opened 2022-02-22 21:16 UTC by BenMatase

2022-02-22 21:18 UTC, BenMatase commented
BTW @MichaelBaj I tried doing the docker compose to locally test and I was hitting an issue saying that the `node` version needed to be >= 14. then when I tweaked that, it seemed like it was hanging when bringing up the container. Not sure if the process has changed or something, but I couldn't locally verify these changes.

2022-02-23 15:42 UTC, BenMatase commented
Hit some OOM on last run https://github.com/128technology/docs/runs/5305847549?check_suite_focus=true

2022-02-23 21:04 UTC, Chr1st0ph3rTurn3r requested changes

2022-02-23 21:04 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +* `enabled` - Allows you to switch tunnel monitoring on and off for a `remote`
period after remote.

2022-02-23 21:04 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +* `tunnel-monitor-nat-network` - The subnet to originate traffic from. The correspnoding ingress KNI's fourth octet will be used. By default, the subnet `10.128.128.0/28` is used.
The subnet where traffic originates.
The corresponding ingress KNI's fourth octet is used. (corresponding was misspelled, and changed will be to is.)

2022-02-23 22:32 UTC, BenMatase commented
Hit OOM again, so retriggered

2022-02-24 00:26 UTC, agrawalkaushik approved these changes

2022-02-24 01:56 UTC, jeffmart-jnpr approved these changes

2022-02-24 18:30 UTC, Chr1st0ph3rTurn3r approved these changes

2022-02-25 18:15 UTC, MichaelBaj approved these changes

2022-02-25 23:23 UTC, merged