Add documentation for 2.0.5 and 2.0.4 release
128technology/docs pull request #337
Opened 2022-02-23 17:33 UTC by jiangsunan

2022-02-23 17:46 UTC, agrawalkaushik commented on docs/plugin_wireguard.md
> +eth1-net can be configured with DHCP enabled after Release 2.0.5:
@jiangsunan I dont think this is the right place or method to document this change. There is a `Basic Configuration` section where we describe how to configure the profile under address. We should update that section for DHCP. I addition we will need to also add a blurb around version history. I'll ping you offline about the doc.

2022-02-23 17:47 UTC, agrawalkaushik commented on docs/plugin_wireguard.md
> +### Release 2.0.5
This should be a 2.1.0 since there is a new feature. We follow the semantic versioning and only bug fixes warrant a minor patch release.

2022-02-23 17:47 UTC, agrawalkaushik requested changes
Comments above and will follow up offline.

2022-02-23 18:57 UTC, agrawalkaushik commented on docs/plugin_wireguard.md
> +```
The ``` are not needed

2022-02-23 19:26 UTC, jiangsunan commented on docs/plugin_wireguard.md
> +### Release 2.0.5
Updated

2022-02-23 19:27 UTC, jiangsunan commented on docs/plugin_wireguard.md
> +```
I feel note for each configuration is inside '''<comment>'''. Let me try

2022-02-24 12:39 UTC, salegria8 commented on docs/plugin_wireguard.md
> +- **PLUGIN-1469**  Add support for kernel version `4.18.0-305.19.1`.
could be new feature instead of fixed issue

2022-02-24 12:39 UTC, salegria8 approved these changes

2022-02-24 14:16 UTC, jiangsunan commented on docs/plugin_wireguard.md
> +- **PLUGIN-1469**  Add support for kernel version `4.18.0-305.19.1`.
I was looking at the history release note, the 3.10 support goes into issue fixed, trying to be consistent with that.

2022-02-25 13:05 UTC, BenMatase requested changes
Some grammar tweaks

2022-02-25 13:05 UTC, BenMatase commented on docs/plugin_wireguard.md
> +| 2.1.0        | Support for DHCP interface is introduced        |
plurality seems a bit off here: `Support for DHCP interfaces is introduced` maybe?

2022-02-25 13:05 UTC, BenMatase commented on docs/plugin_wireguard.md
> +Wireguard profile can be configured on DHCP enabled network interface:
Same here `Wireguard profile can be configured on DHCP enabled network interfaces:`

2022-02-25 13:05 UTC, BenMatase commented on docs/plugin_wireguard.md
> +If wireguard is hosted on a DHCP enabled interface, `Endpoint` address needs to be configured with latest IP address assigned.
`with latest` -> `with the latest`

2022-02-25 13:05 UTC, BenMatase commented on docs/plugin_wireguard.md
> +If wireguard is hosted on a DHCP enabled interface, `Endpoint` address needs to be configured with latest IP address assigned.
``Endpoint` address` -> `the peer's `Endpoint` address`?

2022-02-25 13:05 UTC, BenMatase commented on docs/plugin_wireguard.md
> +- **PLUGIN-1429**  Support DHCP for wireguard interfaces
`Support wireguard on DHCP interfaces`?

2022-02-25 13:05 UTC, BenMatase commented on docs/plugin_wireguard.md
> +The feature adds support for configuring wireguard profile in network interface level when dhcp is enabled.
`in network interface level` -> `on the network interface level`

and 
`dhcp` -> `DHCP`

2022-02-25 13:05 UTC, BenMatase commented
Also please change the title of the PR to `2.1.0`

2022-02-25 13:48 UTC, jiangsunan commented on docs/plugin_wireguard.md
> +Wireguard profile can be configured on DHCP enabled network interface:
Done

2022-02-25 13:48 UTC, jiangsunan commented on docs/plugin_wireguard.md
> +If wireguard is hosted on a DHCP enabled interface, `Endpoint` address needs to be configured with latest IP address assigned.
Done

2022-02-25 13:48 UTC, jiangsunan commented on docs/plugin_wireguard.md
> +If wireguard is hosted on a DHCP enabled interface, `Endpoint` address needs to be configured with latest IP address assigned.
Fixed

2022-02-25 13:48 UTC, jiangsunan commented on docs/plugin_wireguard.md
> +- **PLUGIN-1429**  Support DHCP for wireguard interfaces
Fixed

2022-02-25 13:48 UTC, jiangsunan commented on docs/plugin_wireguard.md
> +The feature adds support for configuring wireguard profile in network interface level when dhcp is enabled.
Fixed

2022-02-25 13:49 UTC, jiangsunan commented
> Also please change the title of the PR to `2.1.0`

Done

2022-02-25 14:20 UTC, BenMatase approved these changes

2022-02-28 18:37 UTC, agrawalkaushik submitted a review, later dismissed

2022-03-04 01:17 UTC, agrawalkaushik commented on docs/plugin_wireguard.md
> +### Release 2.0.2, 1.2.2
This line seems extra/misplaced. Might be a copy/paste error

2022-03-04 13:56 UTC, MichaelBaj submitted a review, later dismissed

2022-03-04 14:46 UTC, BenMatase requested changes
I think Kaushik is right about the extra line

2022-03-04 15:52 UTC, agrawalkaushik approved these changes

2022-03-04 15:53 UTC, BenMatase approved these changes

2022-03-04 21:58 UTC, MichaelBaj approved these changes

2022-03-04 22:34 UTC, merged