I95 41561 eosvr active standby
128technology/docs pull request #356
Opened 2022-03-23 19:05 UTC by Chr1st0ph3rTurn3r

2022-03-23 19:14 UTC, Newmz commented on docs/config_EthoSVR_activestandby.md
> +
there are a couple of places with these comments - do you want to discuss them here or have they been answered?

2022-03-23 19:18 UTC, Chr1st0ph3rTurn3r commented on docs/config_EthoSVR_activestandby.md
> +
No, I need answers. Information here is good, that way others can chime in as well if necessary

2022-03-23 19:29 UTC, MichaelBaj requested changes

2022-03-23 19:29 UTC, MichaelBaj commented on docs/config_EthoSVR_activestandby.md
> +title: Configuring Ethernet Over SVR for Active/Standby
This document does not exist in `sidebars.js` (not strictly necessary), but is also not linked from any other document and therefore is not reachable.

2022-03-23 19:29 UTC, MichaelBaj commented on docs/config_EthoSVR_activestandby.md
> +For example, in a network deployment where there are no loop detection mechanisms available, the EoSVR Active Standby configuration gives you the ability to configure two different endpoints on the P
Consider rewording "can be reached from any of the two Headends" to "can be reached from either head-ends".

2022-03-23 19:29 UTC, MichaelBaj commented on docs/config_EthoSVR_activestandby.md
> +![Ethernet over SVR Active Standby](/img/ethosvr_active-standby.png)
It would be preferred to use standard icons for network diagrams throughout our docs site.

2022-03-23 19:29 UTC, MichaelBaj commented on docs/config_EthoSVR_activestandby.md
> +In this example, VLAN A needs to be extended so that End Device 2 can be reached from any of the two Headends, typically deployed in two different datacenters.
Consider rewording "can be reached from any of the two Headends" to "can be reached from either head-ends".

2022-03-23 19:29 UTC, MichaelBaj commented on docs/config_EthoSVR_activestandby.md
> +*does this show the full configuration? In other words, can I just configure this and have it work?*
- [ ] Remove note prior to delivery

2022-03-23 19:29 UTC, MichaelBaj commented on docs/config_EthoSVR_activestandby.md
> +![ARP Traffic](/img/ethosvr_activestandby_ARP.png)
It would be preferred to use standard icons for network diagrams throughout our docs site.

2022-03-23 19:29 UTC, MichaelBaj commented on docs/config_EthoSVR_activestandby.md
> +- Both Headends have their respective EoSVR bridges configured with the same IP address in the network interface and in the peer with the branch EoSVR bridge. *(not clear on what is being configured
- [ ] remove note prior to delivering

2022-03-23 19:29 UTC, MichaelBaj commented on docs/config_EthoSVR_activestandby.md
> +- The branch EoSVR bridge peering is configured with the IP address used in both Headends. Any of the Headend routers can be selected (*this doesn't make sense - can you clarify what you mean by any
- [ ] remove note prior to delivering

2022-03-23 19:29 UTC, MichaelBaj commented on docs/config_EthoSVR_activestandby.md
> +In order to control which service is active and which is standby, two different neighborhoods are defined. On the branch side both (*neighborhoods?*) are applied on each Headend. (*For the?*) Site, o
- [ ] remove note prior to delivering

2022-03-23 19:29 UTC, MichaelBaj commented on docs/config_EthoSVR_activestandby.md
> +If you are not familiar with configuring L2 and L3 services, please refer to [Create a Service for Ethernet Over SVR](config_EthoSVR.md#create-a-service-for-ethernet-over-svr). *(that documentation d
- [ ] remove note prior to delivering

2022-03-23 19:29 UTC, MichaelBaj commented on docs/config_EthoSVR_activestandby.md
> +
It is recommended to add a troubleshooting section to this document as well so as to determine how to diagnose typical failure scenarios. I'm certain that @Newmz encountered several of these when going through the initial tests.

2022-03-23 21:01 UTC, Newmz commented on docs/config_EthoSVR_activestandby.md
> +
this sentence says that the bridge IPs on the headends should match both each other and the peer IP on the branch, but something else is not clear to me.

This explanation does not seem to match the provided config above this. traffic flows from each of the headends to the branch, but the branch only responds over one service at a time according to which vector has priority. From this explanation the headends should have matching IP addresses or there should also be a peer from the branch to HE1, but the config has branch and HE1 both peering to HE2, and HE2 to branch - all with different bridge IPs.

2022-03-23 21:04 UTC, Newmz commented on docs/config_EthoSVR_activestandby.md
> +- The branch EoSVR bridge peering is configured with the IP address used in both Headends. Any of the Headend routers can be selected (*this doesn't make sense - can you clarify what you mean by any
My understanding is not spot-on here, but I think that the vectors inside the service-policy that the eosvr services use provide a heirarchy for which route/service the packets will take - whether that is HE1 or HE2. From the perspective of the branch, it is not aware of which headend is actually being used. clarification for my comment above would clear this up, I think.

2022-03-28 17:22 UTC, abilash128 commented on docs/config_EthoSVR_activestandby.md
> +
This is how it works. Let's say there are 2 routers R1 and R2. Consider that eosvr is configured on the LAN of R1 and R2. Also consider that there is WAN connection between R1 and R2 and they communicate via SVR.  Since eosvr is configured on the LAN of R1 and R2, they both act as a virtual LAN. The configuration of eosvr and services are already covered as part of eosvr docs and hence not going into the details. But in short, there are 2 services which will be configured (for encapsulate all mode) . One is a service from R1 to R2 so that L2 and IP packets can go from R1 to R2.  This service will have the IP address of the interface with eosvr enabled on R2 and the service route on R2 will be eosvr bridge (in docs already). Similarly a service will be configured for packets from R2 to R1 where the service address will be the IP of the eosvr interface on R2. This is just to illustrate the basics.

In this new case, all of the above holds true, but we now have R1 talking to H1 and H2.(which are headend 1 and headend 2).  Consider now 2 cases -  R1 to H1  and R1 to H2 independently and  follow the steps above (R1 ro R2). This means there will be one service for H1's eosvr interface IP, one service for H2's eosrv interface ip and one service for R1's eosvr IP (if you did this independently, you would have had 4 services, but the 3rd and 4th service is the same - which is R1's service). In this eosvr HA case, the IP address if the H1 eosvr interface and H2 eosvr interface is the same. So overall you will only have 2 services.  Service1 (H1-H2 service) with the IP address of eosvr interface on the headend (for packets from R1 to H1 or H2). Service 2 (R1 service) with the IP address of eosvr interface on R1( for packets from either H1 or H2 to R1).

Now for HA, let's say you want to prefer H1 for all packets from R1 to headend. Only if H1 fails or all paths to h1 fails, will we want to send packets to H2. In this case, lets say there are 2 paths to H1 from R1 and 2 paths to H2 from R1. At this point, just configure the neighborhood and the vectors  and for the service towards headend (H1-H2 service - remember there is only one service as explained above), set the vector values such you prefer the paths to H1 and then to H2. Lets sat there are 4 neighborhoods- 2 towards H1 and 2 towards H2.  Lets add 4 vectors V1, V2 (for paths from R1 to h1) and V3, V4 (for paths from R2 to h2). Create a service policy and attach to this H1-H2 service. the service policy will have the following
a) failover - revertible
b) vectors   (ordered)
      V1, V2, V3, V4
or you can give a cost if you desire.

All packets from R1 will flow to H1 as long as paths P1 and P2(with vectors V1 and V2) are up. If they all fail, then the next best path being P3(with vector V3), will be chosen which goes to headend H2. The same rules for vectors and failover applies here.

For packets towards R1, off the packet reaches H1, it will use the R1 service to get to R1 and similarly, if the packet reaches H2, it will use the same R1 service to reach R1.  These are typically L2 packets being sent. R1 nevertheless will send all packets via the preferred paths and hence ensures affinity towards one headend.

2022-04-19 13:44 UTC, Chr1st0ph3rTurn3r commented on docs/config_EthoSVR_activestandby.md
> +title: Configuring Ethernet Over SVR for Active/Standby
added

2022-04-19 13:44 UTC, Chr1st0ph3rTurn3r commented on docs/config_EthoSVR_activestandby.md
> +For example, in a network deployment where there are no loop detection mechanisms available, the EoSVR Active Standby configuration gives you the ability to configure two different endpoints on the P
done

2022-04-19 13:44 UTC, Chr1st0ph3rTurn3r commented on docs/config_EthoSVR_activestandby.md
> +In this example, VLAN A needs to be extended so that End Device 2 can be reached from any of the two Headends, typically deployed in two different datacenters.
done

2022-04-19 13:44 UTC, Chr1st0ph3rTurn3r commented on docs/config_EthoSVR_activestandby.md
> +- Both Headends have their respective EoSVR bridges configured with the same IP address in the network interface and in the peer with the branch EoSVR bridge. *(not clear on what is being configured
done

2022-04-19 13:45 UTC, Chr1st0ph3rTurn3r commented on docs/config_EthoSVR_activestandby.md
> +- The branch EoSVR bridge peering is configured with the IP address used in both Headends. Any of the Headend routers can be selected (*this doesn't make sense - can you clarify what you mean by any
removed

2022-04-19 13:45 UTC, Chr1st0ph3rTurn3r commented on docs/config_EthoSVR_activestandby.md
> +In order to control which service is active and which is standby, two different neighborhoods are defined. On the branch side both (*neighborhoods?*) are applied on each Headend. (*For the?*) Site, o
removed

2022-04-19 13:45 UTC, Chr1st0ph3rTurn3r commented on docs/config_EthoSVR_activestandby.md
> +If you are not familiar with configuring L2 and L3 services, please refer to [Create a Service for Ethernet Over SVR](config_EthoSVR.md#create-a-service-for-ethernet-over-svr). *(that documentation d
removed

2022-04-19 13:49 UTC, Chr1st0ph3rTurn3r commented on docs/config_EthoSVR_activestandby.md
> +
I now need the doc re-reviewed and verified that any changes I made to the text match this configuration. Documents I received from Diego were the same as the original information given to me, and did not show any changes to the config after Abilash worked with the test team to resolve issues. *If the config is appropriate for the text, please let me know.* I will reach out to Abilash and Tim for additional verification.

2022-04-19 13:51 UTC, Chr1st0ph3rTurn3r commented on docs/config_EthoSVR_activestandby.md
> +
Requested, but none provided.

2022-08-09 14:56 UTC, abilash128 commented on docs/config_EthoSVR_activestandby.md
> +*DOES THIS SHOW THE FULL CONFIGURATION? CAN I JUST CONFIGURE THIS AND HAVE IT WORK??*
This is showing some of the manual peer configuration. The peer configuration gets generated. I wasn't  sure if this was intentional or not.

2022-08-09 15:00 UTC, abilash128 approved these changes

2022-08-09 15:52 UTC, mendezcirera approved these changes

2022-08-09 16:28 UTC, Chr1st0ph3rTurn3r commented on docs/config_EthoSVR_activestandby.md
> +*DOES THIS SHOW THE FULL CONFIGURATION? CAN I JUST CONFIGURE THIS AND HAVE IT WORK??*
resolved and removed the note.

2022-08-09 16:29 UTC, MichaelBaj approved these changes

2022-08-11 15:07 UTC, merged