Docs release 5.6
128technology/docs pull request #363
Opened 2022-03-30 17:06 UTC by Chr1st0ph3rTurn3r

2022-03-30 18:46 UTC, tcarroll25 commented on docs/config_basics.md
> +Each user makes edits locally to a candidate configuration. When they have completed their edits locally, they commit the config to the conductor, and it is merged into the running configuration. Whe
> When other users complete and commit their changes, the updated running configuration is pulled down to the system making the changes (rebased), and compared for conflicts.

I'm questioning if we should mention the term rebase at all in our documents because I don't think most users will understand what that means. Maybe we should say something like

When other users complete and commit their changes, their local edits are reapplied on top of the current running configuration. If an edit cannot reapplied then a conflict has occurred and that edit will be dropped. If a conflict occurs the SSR will continue tryinging to reapply all edits. At the end of the operation if a conflict occurred then all the edits which were dropped will be displayed to the user and commit does not take place. If no conflicts exist, the local changes are committed to the running configuration on the conductor.

2022-03-30 18:47 UTC, tcarroll25 commented on docs/config_basics.md
> +Configuration concurrency was introduced in version 5.6. This feature creates a candidate configuration for each user the first time they edit their configuration, allowing multiple administrators to
The candidate configuration is destroyed upon commit as well, not sure if we want to mention that.

2022-03-30 18:49 UTC, tcarroll25 commented on docs/config_basics.md
> +User B also has one change of their own. User B’s candidate configuration requires a rebase before a commit to the conductor is completed. The rebase operation is part of the commit operation, and ta
Same comment about using the term rebase. Perhaps we should try to describe that the user's edits are reapplied on top of the current running configuration

2022-03-30 18:49 UTC, tcarroll25 commented on docs/config_basics.md
> +If the validation operation encouters conflicts, an error message containing details is displayed for each conflict. Conflicts are not committed, and are deleted from the candiate config. Other chang
Maybe mention that a commit does not occur if there is a conflict?

2022-03-30 18:50 UTC, tcarroll25 commented on docs/config_basics.md
> +Similar to copying and pasting the output of `compare config candidate running` into the PCLI, there is a specific command for reverting the entire candidate configuration back to the running configu
Not sure if this is worth mentioning but with config concurrency performing a `restore config running` delete's the users candidate

2022-03-30 18:52 UTC, tcarroll25 commented
Overall looks good to me. There are some differences in the config concurrency experience when using the PCLI vs the GUI that we should document. I will point them out in our demo tomorrow.

2022-03-30 18:53 UTC, tcarroll25 requested changes
Marking request changes because we need to add the PCLI vs GUI differences that I will point out tomorrow

2022-04-05 18:59 UTC, Chr1st0ph3rTurn3r commented on docs/config_basics.md
> +Similar to copying and pasting the output of `compare config candidate running` into the PCLI, there is a specific command for reverting the entire candidate configuration back to the running configu
added

2022-04-05 18:59 UTC, Chr1st0ph3rTurn3r commented on docs/config_basics.md
> +If the validation operation encouters conflicts, an error message containing details is displayed for each conflict. Conflicts are not committed, and are deleted from the candiate config. Other chang
I think I got this...

2022-04-05 19:00 UTC, Chr1st0ph3rTurn3r commented on docs/config_basics.md
> +User B also has one change of their own. User B’s candidate configuration requires a rebase before a commit to the conductor is completed. The rebase operation is part of the commit operation, and ta
change made

2022-04-05 19:00 UTC, Chr1st0ph3rTurn3r commented on docs/config_basics.md
> +Configuration concurrency was introduced in version 5.6. This feature creates a candidate configuration for each user the first time they edit their configuration, allowing multiple administrators to
edited

2022-04-05 19:00 UTC, Chr1st0ph3rTurn3r commented on docs/config_basics.md
> +Each user makes edits locally to a candidate configuration. When they have completed their edits locally, they commit the config to the conductor, and it is merged into the running configuration. Whe
edits made

2022-04-06 13:13 UTC, MichaelBaj commented on docs/config_basics.md
> +When User B commits their change, the peer, name, and description are verified to be added back into the configuration. The deleted authority-name and router-name are not found as part of the change,
This description is great. It would be best to conclude with what would be the expected remediation efforts to follow. Likely in this case, to unwind the change as another administrator had determined the configuration object is not necessary. In the case that it needs to be "reconstructed" they would need to look at the event log to see the details of the object that was removed.

Also, "fakerouter" should be changed to be something more realistic.

2022-04-06 14:00 UTC, tcarroll25 approved these changes

2022-04-06 17:43 UTC, Chr1st0ph3rTurn3r commented on docs/config_basics.md
> +When User B commits their change, the peer, name, and description are verified to be added back into the configuration. The deleted authority-name and router-name are not found as part of the change,
updates made

2022-04-07 12:47 UTC, MichaelBaj submitted a review, later dismissed

2022-04-18 12:18 UTC, jpetersonssr approved these changes

2022-04-20 18:43 UTC, MichaelBaj requested changes

2022-04-20 18:43 UTC, MichaelBaj commented on docs/config_bfd.md
> +title: Bidirectional Forwarding Detection (BFD)
This title may be confusing if it doesn't also contain information about BFD for non-routing protocol use, as it exists today in product between SVR peers.

Rather than changing the title, it would be good to document base BFD behavior. Lane Shields should have this documented in his BCP guide.

2022-04-20 18:43 UTC, MichaelBaj commented on docs/config_bfd.md
> +This section provides information about using BFD with BGP and OSPF protocols on the Session Smart Networking Platform, and how to configure your SSR to take advantage of the Free Range Routing (FRR)
I don't believe we highlight FRR in our docs. I'm not sure specifying our internal technology has external value. My suggestion is to remove.

2022-04-20 18:43 UTC, MichaelBaj commented on docs/config_bfd.md
> +The show commands available in FRR are also available through the SSR PCLI. Additionally, the  BFD status is available in the GUI.
another reference to FRR that should be removed.

2022-04-20 18:43 UTC, MichaelBaj commented on docs/config_step_ha.md
> +STEP can be used in a High Availability configuration, but must be configured on both the routers and the conductors.
This introduction is confusing. STEP client runs on the router. The STEP repo can run on the conductor, head-end or a standalone system. There is ambiguity in this statement. Does HA need to be configured on both the router and conductor? Does STEP need to be configured on both? Do both need to be configured on both?

2022-04-20 18:43 UTC, MichaelBaj commented on docs/howto_STEP_GUI.md
> +The tabs across the top of the pane - LSDB, Routes, Client, Server, and Documents - displpay STEP related tables. All tables are configurable; select the columns icon to show / hide columns.
typo: "display"

2022-04-20 18:43 UTC, MichaelBaj commented on docs/howto_STEP_GUI.md
> +    - Select the Icon next to Summary and choose a router from the dropdown to see all the local information that the originating router has on the selected router. *(need to determine whether this i
Icon should not be capitalized.

2022-04-20 18:43 UTC, MichaelBaj commented on docs/howto_STEP_GUI.md
> +    - Select the Icon next to Summary and choose a router from the dropdown to see all the local information that the originating router has on the selected router. *(need to determine whether this i
- [ ] resolve and remove note

2022-04-20 18:43 UTC, MichaelBaj commented on docs/ts_step.md
> +The following show commands provide a view into the STEP functionality.
These commands as they are can very well be in the cli_reference document. It is the intent of troubleshooting guides to steer customers to typical failure modes, what commands to execute in order to diagnose them and what actions to take in order to remediate.

2022-04-20 18:59 UTC, migolnikov commented on docs/config_radius.md
> +With the release of version 5.6, the SSR will authenticate all user logins using Radius first. If remote authentication fails, then local authentication will be attempted.
this statement is inaccurate. We will only attempt to authenticate users marked as "remote" with the Radius server. If a user is a radius server is not available, that use will not be able to log in

2022-04-20 18:59 UTC, migolnikov commented on docs/config_radius.md
> +
we should note that on the same system we can have either ldap enabled or radius enabled, not both

2022-04-25 13:55 UTC, Chr1st0ph3rTurn3r commented on docs/config_bfd.md
> +This section provides information about using BFD with BGP and OSPF protocols on the Session Smart Networking Platform, and how to configure your SSR to take advantage of the Free Range Routing (FRR)
removed

2022-04-25 14:03 UTC, Chr1st0ph3rTurn3r commented on docs/howto_STEP_GUI.md
> +The tabs across the top of the pane - LSDB, Routes, Client, Server, and Documents - displpay STEP related tables. All tables are configurable; select the columns icon to show / hide columns.
fixed

2022-04-25 14:03 UTC, Chr1st0ph3rTurn3r commented on docs/howto_STEP_GUI.md
> +    - Select the Icon next to Summary and choose a router from the dropdown to see all the local information that the originating router has on the selected router. *(need to determine whether this i
fixed

2022-04-25 15:54 UTC, ravimurthy2012 commented on docs/config_radius.md
> +Password: <not echoed to screen>
Missing a prompt for 'Authentication Type' which will be local here for local users..

2022-04-25 18:03 UTC, MarkusJork commented on docs/config_step_ha.md
> +STEP can be used in a High Availability configuration, but must be configured on both the routers and the conductors.
Agreed, this is confusing. The one user choice / configuration consideration is whether or not to provide HA for the STEP repo. If that is desired, then the conductor needs to be placed in an HA configuration and a little bit extra STEP configuration is required (as detailed in the next section).

Any routers in the authority may be operated in a standalone configuration or as HA routers. Either way they will now be supported by STEP without any additional STEP specific configuration.

2022-04-25 18:25 UTC, MarkusJork commented on docs/ts_step.md
> +The following show commands provide a view into the STEP functionality.
Those commands are the ones I'd use for troubleshooting. To provide some intuition for how to go about using them:

If a router is missing the expected STEP provided forwarding state (FIB entries and service-path entries) for some service:
1. Check that the router is connected to the STEP repository (using `show step clients`)
2. Check the router's view of the LSDB (via the `show step lsdb` command) to verify the destination router is known and is advertising the service in its STEP document
3. Check the result of the STEP path computation for the service (via `show step routes`)

2022-04-25 18:37 UTC, Chr1st0ph3rTurn3r commented on docs/config_step_ha.md
> +STEP can be used in a High Availability configuration, but must be configured on both the routers and the conductors.
I removed line 11. It was the simplest solution.

2022-04-25 18:39 UTC, Chr1st0ph3rTurn3r commented on docs/config_radius.md
> +
Ravi tested and found this is not the case. Made updates accordingly.

2022-04-25 18:48 UTC, Chr1st0ph3rTurn3r commented on docs/config_radius.md
> +Password: <not echoed to screen>
added

2022-04-25 19:17 UTC, Chr1st0ph3rTurn3r commented on docs/ts_step.md
> +The following show commands provide a view into the STEP functionality.
information added

2022-05-03 14:51 UTC, MarkusJork commented on docs/config_STEP.md
> +Use the following command to enable the STEP repository on the Conductor.
Maybe also add a cross-reference to the `STEP Repository High Availability` chapter here to point out that an HA conductor would need two `step-repo` configured.

2022-05-03 15:11 UTC, MarkusJork commented on docs/howto_STEP_GUI.md
> +**Client:** Step client details for the selected router based upon the STEP router documents.
This doesn't seem very clear. How about:

STEP client details for the selected router, providing information about the connection to the one or two STEP repositories in the authority.

2022-05-03 15:26 UTC, MarkusJork commented on docs/howto_STEP_GUI.md
> +**Server:** The server residing on the conductor. Displays the server connections to each router, including session state, and status. The STEP router document can be downloaded from this location as
Instead of "The STEP router document can be downloaded from this location as well.":

Any STEP router documents received by the server can be downloaded from this location as well.

2022-05-03 15:47 UTC, Chr1st0ph3rTurn3r commented on docs/howto_STEP_GUI.md
> +**Server:** The server residing on the conductor. Displays the server connections to each router, including session state, and status. The STEP router document can be downloaded from this location as
I like that much better, thanks!

2022-05-03 15:47 UTC, Chr1st0ph3rTurn3r commented on docs/howto_STEP_GUI.md
> +**Client:** Step client details for the selected router based upon the STEP router documents.
done

2022-05-03 15:47 UTC, Chr1st0ph3rTurn3r commented on docs/howto_STEP_GUI.md
> +
added

2022-05-03 15:48 UTC, Chr1st0ph3rTurn3r commented on docs/config_STEP.md
> +Use the following command to enable the STEP repository on the Conductor.
Added cross references to each topic.

2022-05-03 17:14 UTC, MarkusJork submitted a review, later dismissed

2022-05-04 14:58 UTC, ecarson approved these changes

2022-05-05 13:25 UTC, MichaelBaj requested changes

2022-05-05 13:25 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-43243/IN-460 Upgrade and Rollback:** Upgrading or rolling back a system (conductor peer or router) with the interactive installer `install128t`, that is managed by a conductor may result in t
I'm not sure what is meant by "conductor peer". I believe parenthetically this should read "(conductor or router)"

2022-05-05 13:25 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-42624 Upgrade Installer:** Before **upgrading to, or installing** version 5.4 and above, update the Installer to at least version 3.1.0. Failing to upgrade the installer may result in a rollb
Please provide instructions for how to upgrade the installer (it should be automatic through the GUI).

2022-05-05 13:25 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-37648 JITC: Configurable Password Policy:** The SSR password policies have been updated to provide a more secure experience. See [Password Policies](config_password_policies.md) for additiona
Drop "JITC" in each of the JITC related features.

2022-05-05 13:25 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-41449 JITC: NTP Authentication with SHA1 or better:** Support for NTP authentication provides options for external NTP server authentication. See [NTP Authentication](config_ntp_auth.md) for
Drop JITC

2022-05-05 13:25 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-42887 JITC: Real-time alerts for Audit failure events:** A service has been added a service that warns all logged in users if auditd fails to start and audit logging capability is impacted. S
Drop JITC

2022-05-05 13:25 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-42888 JITC: Logout mechanism for administrator-initiated communication sessions:** A PCLI command and audit log are available to verify session closure.
Drop JITC

2022-05-05 13:25 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-45162 Improve download/upgrade error message if arouter name does not exist:** In situations where a router does not exist, the download and upgrade message now indicates that the router does
space needed between "arouter"

2022-05-05 13:25 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +The active `automatedProvisioner` can be determined by running the command `show system processes`. Once the upgrade begins on the old node, the newly upgraded conductor takes over. Upon completion o
Statement is incomplete. It ends with "Upon completion of the upgrade..."

2022-05-05 15:34 UTC, MichaelBaj approved these changes

2022-05-12 18:45 UTC, MarkusJork submitted a review, later dismissed

2022-05-20 16:17 UTC, MichaelBaj submitted a review, later dismissed

2022-05-20 16:19 UTC, Bhautik commented on docs/release_notes_128t_5.6.md
> +## Release 5.6.0-1
we are releasing 5.6.0-44. We need to update this

2022-05-20 18:54 UTC, Bhautik submitted a review, later dismissed

2022-05-20 19:05 UTC, MichaelBaj approved these changes

2022-05-20 19:28 UTC, MichaelBaj approved these changes

2022-05-20 19:31 UTC, merged