Create wan-assurance 3.3.1 release notes
128technology/docs pull request #366
Opened 2022-04-06 21:41 UTC by agrawalkaushik

DOCS-292 #time 1d

2022-04-06 22:01 UTC, MichaelBaj requested changes

2022-04-06 22:01 UTC, MichaelBaj commented on docs/release_notes_wan_assurance_plugin_3.3.1.md
> +sidebar_label: '3.3.1'
per my comment in sidebar_label.js, this document should be `3.3`

2022-04-06 22:07 UTC, MichaelBaj commented on sidebars.js
> +          "release_notes_wan_assurance_plugin_3.3"
Did you also make sure to change the file name? If not, it won't find it.

2022-04-06 22:51 UTC, MichaelBaj approved these changes

2022-04-07 03:18 UTC, agrawalkaushik commented on sidebars.js
> +          "release_notes_wan_assurance_plugin_3.3"
Yup - I renamed the file name as well!

2022-04-07 03:19 UTC, agrawalkaushik commented on sidebars.js
> +          "release_notes_wan_assurance_plugin_3.3"
I've also verified the changes by running local npm server.

2022-04-07 12:31 UTC, salegria8 approved these changes

2022-04-07 13:04 UTC, Chr1st0ph3rTurn3r requested changes

2022-04-07 13:04 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.3.md
> +- **WAN-618 Releasing SSR from one org to another can result in errors** The device will auto-detect a transition from one org to another eliminating the need to explicitly release and un-release the
The device auto-detects a transition from one organization to another, eliminating...

The device, however, remains in the inventory of the original organization, which...

2022-04-07 13:04 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.3.md
> +- **MIST-59532 Peer down alerts are not being reported for HA routers:** Correct device-interface name is being used to populate the events for HA router to prevent the events from being discarded.
The correct device-interface name...

...events for an HA router...

2022-04-07 13:04 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.3.md
> +- **I95-45173 Newly on-boarded routers were reported as dummy-router in the MIST inventory:** The initial registration process is now delayed until conductor completes the full reinitialization of th
**I95-45173 Newly on-boarded routers were reported as a dummy-router...

...until the conductor completes...

2022-04-07 14:08 UTC, Bhautik submitted a review, later dismissed

2022-04-07 15:20 UTC, agrawalkaushik commented on docs/release_notes_wan_assurance_plugin_3.3.md
> +- **I95-45173 Newly on-boarded routers were reported as dummy-router in the MIST inventory:** The initial registration process is now delayed until conductor completes the full reinitialization of th
@Chr1st0ph3rTurn3r a neat trick with Github is that you can hit <Cmd+g> and it will let you make suggetions. This way I just have to click accept suggestion and it auto creates a commit. Would save us both some time 😉

2022-04-07 15:28 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.3.md
> +- **I95-45173 Newly on-boarded routers were reported as dummy-router in the MIST inventory:** The initial registration process is now delayed until conductor completes the full reinitialization of th
did not know that!

2022-04-07 23:51 UTC, MichaelBaj approved these changes

2022-04-08 00:03 UTC, merged