Release notes for ipsec-client 3.3.0
128technology/docs pull request #374
Opened 2022-04-21 16:54 UTC by agrawalkaushik

2022-04-21 17:03 UTC, MichaelBaj approved these changes

2022-04-21 17:16 UTC, Chr1st0ph3rTurn3r requested changes

2022-04-21 17:16 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +The `custom-option` are added to the libreswan config file and any invalid option could prevent the application from starting up.
```suggestion
The `custom-option` is added to the libreswan config file; any invalid option could prevent the application from starting up.
```

2022-04-21 17:16 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +| `address` | The IP or hostname where traffic is sent. This address must be reachable after traversing the  |tunnel.
```suggestion
| `address` | The IP or hostname where traffic is sent. This address must be reachable after traversing the  tunnel. |
```

2022-04-21 17:16 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +| `timeout` | Duration (in seconds) within which to reach the destination. Each attempt will be made in this  |duration / `max-retries` interval.
```suggestion
| `timeout` | Duration (in seconds) within which to reach the destination. Each attempt will be made in this duration / `max-retries` interval. |
```

2022-04-21 17:16 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +| `max-retries` | Number of consecutive missed ICMP ping responses from the destination within the interval  |before deciding that the tunnel is unhealthy.
```suggestion
| `max-retries` | Number of consecutive missed ICMP ping responses from the destination within the interval before deciding that the tunnel is unhealthy. |
```

2022-04-21 17:16 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +| `tunnel-monitor-nat-network` | The subnet where traffic originates. The corresponding ingress KNI's fourth  |octet is used. By default, the subnet `10.128.128.0/28` is used.
```suggestion
| `tunnel-monitor-nat-network` | The subnet where traffic originates. The corresponding ingress KNI's fourth octet is used. By default, the subnet `10.128.128.0/28` is used. |
```

2022-04-21 17:16 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +- **PLUGIN-1591** Add cpu, memory & status tracking for ipsec services
```suggestion
- **PLUGIN-1591** Add cpu, memory, and  status tracking for ipsec services.
```

2022-04-21 17:16 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +  _**Resolution**_ The auto configuration was updated to use the right script path.
```suggestion
  _**Resolution**_ The auto configuration was updated to use the correct script path.
```

2022-04-21 18:03 UTC, BenMatase requested changes

2022-04-21 18:03 UTC, BenMatase commented on docs/plugin_ipsec_client.md
> +- **PLUGIN-1598** - Support custom options for obscure libreswan config pieces
`pieces` -> `fields`?

2022-04-21 18:03 UTC, BenMatase commented on docs/plugin_ipsec_client.md
> +| 3.3.0    | `profile > custom-option` introduced |
Add the version history to new command?

2022-04-25 15:49 UTC, agrawalkaushik commented on docs/plugin_ipsec_client.md
> +The `restart ipsec tunnel` command can be used to restart an individual IPSec tunnel via the conductor PCLI and UI.
```suggestion
The `restart ipsec remote` command can be used to restart an individual IPSec tunnel via the conductor PCLI and UI.
```

2022-04-25 17:46 UTC, Chr1st0ph3rTurn3r submitted a review, later dismissed

2022-04-27 15:16 UTC, Chr1st0ph3rTurn3r approved these changes

2022-04-27 15:31 UTC, Chr1st0ph3rTurn3r approved these changes

2022-04-27 15:51 UTC, merged