generating 551 release notes, and editing similar issues in the 5.6 r…
128technology/docs pull request #395
Opened 2022-05-25 19:54 UTC by Chr1st0ph3rTurn3r

…elease notes.

2022-05-25 21:48 UTC, MichaelBaj requested changes

2022-05-25 21:48 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-45374 Router Dropping SIP traffic:** A warning is displayed if users configure a service-class to rate-limit but don't set max-flow-burst/max-flow-rate values (default is set to 0).
Heading should read: "Service-class with a rate-limit of 0 will drop traffic"

2022-05-26 14:03 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.5.md
> +- **I95-45767 Verify RBAC handles spaces and escaped characters correctly:** Both spaces and escaped characters are properly handled.
I think this is one that probably does not need to go into the release notes. The Jira issue was to verify that it indeed did handle them correctly, not that it didn't and there was a problem. I'm going to remove it from the R/Ns.

2022-05-26 14:05 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.5.md
> +- **I95-45842 PCLI `show events` does not paginate correctly:** This issue has been resolved.
done

2022-05-26 14:15 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.5.md
> +- **I95-45348: Update salt master and minion to 3002.8:** When upgrading an HA pair to version 5.5.1, please be aware of the following: While updating the conductors in an HA pair, the upgraded condu
Added the appropriate info

2022-05-27 12:58 UTC, MichaelBaj submitted a review, later dismissed

2022-06-01 21:31 UTC, jeffmart-jnpr approved these changes

2022-06-01 21:41 UTC, MichaelBaj approved these changes

2022-06-01 21:41 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-44443 NTP Server config not always picked up:** Resolved an issue where NTP configuration was changed but the backend would not take action on those changes.
This could be made more succinct by stating ntp server configuration is not dynamically reconfigurable.

2022-06-01 23:30 UTC, merged