Guide to deploy SSR on Equinix Metal
128technology/docs pull request #399
Opened 2022-06-03 19:35 UTC by mendezcirera

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r requested changes

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +* The network type of the server is configured as "Hybrid Unbounded".
```suggestion
* Configure the server network type as "Hybrid Unbounded".
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +* For the forwarding data plane specific Layer 2 VLANs are created.
```suggestion
* Create specific Layer 2 VLANs for the forwarding data plane.
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +  * For example, one `Internet VLAN` for data plane Internet access. A second `Peering VLAN` to forward traffic destined to other Equinix Metal regions, to Public Cloud Providers, etc.
```suggestion
  * For example, create one `Internet VLAN` for data plane Internet access, and a second `Peering VLAN` to forward traffic destined for other Equinix Metal regions, or to Public Cloud Providers, etc.
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +* For those type of servers that only have 2 ports (network interfaces), the recommendation is:
```suggestion
* For servers that only have 2 ports (network interfaces):
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +  * The first port is dedicated for management purposes only. The port must have access to the Internet, so that the SSR is reachable for SSH for administration purposes. In additionn, if Conductor i
```suggestion
  * The first port is dedicated to management functions only. The port must have access to the Internet, allowing the SSR to be reachable by SSH for administration activities. In addition, if the Conductor is hosted in the Internet, connectivity to Conductor must be provided via this network interface.
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +Proceed to the next sections to implement the recommended design in Equinix Metal.
```suggestion
The next sections implement the recommended design in Equinix Metal.
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +Repeat the steps described above to create as many L2 VLANs as needed to meet your specific requirements. For example:
```suggestion
Repeat the steps above to create as many L2 VLANs as necessary to meet your specific requirements. For example:
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +
All the procedures need numbered steps: 
Creating L2 Networks
Deploying a Metal Gateway
SSR Deployment

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +
The code above needs to be inside a code window:
```
yum install wget -y
wget ftp://ftp.pbone.net/mirror/vault.centos.org/7.5.1804/updates/x86_64/Packages/centos-release-7-5.1804.1.el7.centos.x86_64.rpm
yum downgrade centos-release-7-5.1804.1.el7.centos.x86_64.rpm -y
reboot
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +
Code window:
```
sudo yum install --enablerepo=* http://yum.128technology.com/installer/repo.rpm -y
sudo yum install dnf -y
sudo dnf remove tmux -y
sudo dnf install 128T-installer -y
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +
```
sudo useradd -s /bin/bash t128
sudo usermod -a -G wheel t128 
sudo passwd t128
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +Lastly, launch the installer with the following command:
```suggestion
Launch the installer using the following command:
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +sudo install128t
```suggestion
`sudo install128t`
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +At the end of the installation process the server will restart. Login to the Conductor GUI and proceed to the next section to configure the device interfaces of the Session Smart Router.
```suggestion
The server restarts at the end of the installation process. Login to the Conductor GUI and use the procedure below (Attaching the L2 Networks to the Server) to configure the Session Smart Router device interfaces.
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +
Number the steps in this procedure.

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +Repeat these last two steps to add all the VLANs required. For example, `Internet VLAN` and `Peering VLAN`.
```suggestion
Repeat steps 8 and 9 to add all the required VLANs. For example, `Internet VLAN` and `Peering VLAN`.
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +## Annexes
```suggestion
## Appendix
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +There are times when a server becomes unreachable over SSH due to broken networking, a bad install, misconfiguration, a kernel upgrade, bad firewall rules, etc. Equinix Metal™ offers an out-of-band c
```suggestion
There may be times when a server becomes unreachable over SSH due to broken networking, a bad install, misconfiguration, a kernel upgrade, bad firewall rules, etc. Equinix Metal™ offers an out-of-band console called "SOS" - which stands for Serial Over SSH. Refer to the [SOS - Serial Over SSH](https://metal.equinix.com/developers/docs/resilience-recovery/serial-over-ssh/) documentation for additional information .
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +To complete the installation of the Session Smart Router (SSR) software, continue from the step 4 of the procedure described [here](https://www.juniper.net/documentation/us/en/software/session-smart-
```suggestion
To complete the installation of the Session Smart Router (SSR) software, continue from the step 4 of the [Manual Installation procedure](https://www.juniper.net/documentation/us/en/software/session-smart-router/docs/intro_installation_installer#manually-installing-using-the-128t-installer).
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +Do not proceed to the next step until the password has been updated successfully, the `t128` username will be used to login to the VM for administration purposes when required from now on rather than
```suggestion
Do not proceed to the next step until the password has been updated successfully. The `t128` username and password will now be used to login to the VM for administrative functions, rather than the `root` username.
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +```ssh root@<Public IP address>```
```suggestion
`ssh root@<Public IP address>`
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +Once the reservation request completes the Public IP address of the management interface of the server will be accessible. The Public IP address of the server is displayed in the Equinix Metal Consol
```suggestion
Once the reservation request completes, the Public IP address of the management interface of the server will be accessible. The Public IP address of the server is displayed in the Equinix Metal Console.
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +Select the numbers of server you want to reserve, and provide a name to each.
```suggestion
Select the number of servers to reserve, and provide a name for each.
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +Select the desired location where you want to deploy.
```suggestion
Select the desired location for deployment.
```

2022-06-03 20:48 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +Click on one the reservation options available. Select "On Demand" if you do not need to reserve the a server for a committed period of time.
```suggestion
Click on one of the reservation options available. Select "On Demand" if you do not need to reserve the server for a committed period of time.
```

2022-06-06 14:00 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
An Equinix Metal™ Metal Gateway provides a single IPv4 Gateway for a subnet. This allows you to deploy a group of servers in a Metro on the same subnet, and able to connect to each other or the Internet through the Metal Gateway.

2022-06-06 14:03 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
>  Proceed to the next section [Session Smart Router Deployment](#session-smart-router-deployment) to deploy a Session Smart Router.
I think this is unnecessary, and should be reworded as an introduction to the next section.

2022-06-06 14:08 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
Remove the heading ### Deployment

2022-06-06 14:08 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
>  To deploy a Session Smart Router software via the [Equinix Metal Console](https://console.equinix.com/login):
```suggestion
Use the following procedure to deploy a Session Smart Router software via the [Equinix Metal Console](https://console.equinix.com/login):
```

2022-06-06 14:09 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
> +Once the reservation request completes, the Public IP address of the management interface of the server will be accessible. The Public IP address of the server is displayed in the Equinix Metal Conso
```suggestion
After the reservation request is complete, the Public IP address of the management interface of the server is accessible. The Public IP address of the server is displayed in the Equinix Metal Console.
```

2022-06-06 14:11 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
>  ### Attaching the L2 Networks to the server
```suggestion
### Attaching the L2 Networks to the Server
```

2022-06-06 14:11 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_equinix_metal.md
>  ### Console access
```suggestion
### Console Access
```

2022-06-06 18:55 UTC, mendezcirera commented on docs/intro_installation_equinix_metal.md
>  For example: Internet and VLAN ID 128.
The table shows an example of how customers can name their L2 Networks (description) and the VLAN ID. This table represents like a live example throughout the doc, the reference SSR configuration at the end matches these values

2022-06-06 19:08 UTC, Chr1st0ph3rTurn3r submitted a review, later dismissed

2022-06-06 20:40 UTC, MichaelBaj requested changes

2022-06-06 20:40 UTC, MichaelBaj commented on docs/intro_installation_equinix_metal.md
> +To complete the installation of the Session Smart Router (SSR) software, continue from the step 4 of the [Manual Installation procedure](https://www.juniper.net/documentation/us/en/software/session-s
This should always be relative links, not absolute links

2022-06-06 20:40 UTC, MichaelBaj commented on docs/intro_installation_equinix_metal.md
> +1. Deploying a Session Smart Conductor. For a quick deployment you can use the Hourly/PAYG offering available in Azure or AWS. Refer to the [Azure documentation](https://www.juniper.net/documentation
Use relative links, not absolute links. Please follow the guide here: https://github.com/128technology/docs/blob/master/docs/CONTRIBUTING.md#hyperlinks

2022-06-06 21:12 UTC, MichaelBaj approved these changes

2022-06-06 21:13 UTC, merged