First draft of Release Notes.
128technology/docs pull request #405
Opened 2022-06-28 20:31 UTC by Chr1st0ph3rTurn3r

2022-06-29 13:57 UTC, MichaelBaj requested changes

2022-06-29 13:57 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-40195 LDAP does not allow search base to be configured correctly:** This is a new feature. New commands, new config.
Is this a placeholder for documenting how one would go about configuring the feature?

2022-06-29 13:57 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-46562 Allow targeting another router or node when saving
looks like an unnecessary line break is here

2022-06-29 13:57 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-46136 Unused app-id stats not being purged fast enough:** Ressolved an issue where app-id stats tracked per client, per app, per next-hop are not cleaned up when inactive.
Typo: Resolved

2022-06-29 14:11 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.5.md
> +- **I95-46562 Allow targeting another router or node when saving
fixed

2022-06-29 14:11 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.5.md
> +- **I95-46136 Unused app-id stats not being purged fast enough:** Ressolved an issue where app-id stats tracked per client, per app, per next-hop are not cleaned up when inactive.
fixed

2022-06-29 15:56 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.5.md
> +- **I95-40195 LDAP does not allow search base to be configured correctly:** This is a new feature. New commands, new config.
this has been updated and contains the new information and link.

2022-06-29 16:30 UTC, MichaelBaj approved these changes

2022-06-30 12:41 UTC, MichaelBaj approved these changes

2022-06-30 20:05 UTC, MichaelBaj approved these changes

2022-06-30 20:34 UTC, merged