5.6.1 release notes
128technology/docs pull request #409
Opened 2022-07-07 20:54 UTC by Chr1st0ph3rTurn3r

Release Notes are still in draft format.

2022-07-08 20:52 UTC, MichaelBaj requested changes

2022-07-08 20:52 UTC, MichaelBaj commented on docs/config_dscp_preservation.md
> +DSCP values may be changed by applications or hardware at any point while traversing a network. In some situations it is important that the DSCP value received at the router is the same as the origin
This statement isn't correct as the SSR can not guarantee that the DSCP value hasn't been already changed by a downstream router between the client and the SSR. The only thing it can do is ensure that the DSCP markings are preserved as they are received by the SSR and are the same when they leave the SSR fabric.  Suggested rewording:

DSCP values are commonly changed within network boundaries. In some situations it is important that the DSCP value received at the router are preserved through all SVR hops within the network. This feature allows the network administrator to preserve the original DSCP value across SVR hops.

2022-07-08 20:52 UTC, MichaelBaj commented on docs/config_dscp_preservation.md
> +When a new session is created, the DSCP value of the first packet received from the local LAN is recorded and included in the metadata. If DSCP values change within the life of the session, when the
"and included in the metadata." -> "and included in the respective session's metadata."

If DSCP values change within the life of the session, when the packet egresses from SVR the original DSCP value is restored and is used on all subsequent packets. ->
"If DSCP values differ per packet within a session, the DSCP value from the first packet in the session will be used for each packet."

2022-07-08 20:52 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-43785 DSCP Tag Preservation:** When set to `true` the `preserve-dscp` command allows you to preserve dscp values that have been set in a service class or received on a LAN-Interface, over an
DSCP should be capitalized

2022-07-08 20:52 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-44267 NIST FIPS-validated Cryptography:** More to come.
- [ ] Todo: fill in section

2022-07-08 20:52 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-44870 Mist Self-Registration Onboarding:** More to come.
This feature should be removed from 5.6.1. We are not sure why it is included in Jira.

2022-07-08 20:52 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-45670 BGP Conditional Advertisement:** More to come.
- [ ] Todo: fill in section

2022-07-08 20:52 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-43779 DHCP IP Address not releasing appropriately:** Reboot now triggers DHCP-enabled interfaces to send out a DHCP Request for their current IP address.
"Reboot" should be "cable unplug and plug" (or choose your preferred wording)

2022-07-19 19:05 UTC, Chr1st0ph3rTurn3r commented on docs/about_releases.mdx
> +| Release 5.6 | [5.6.0](release_notes_128t_5.6.md#release-561-1) |
fixed

2022-07-19 19:06 UTC, Chr1st0ph3rTurn3r commented on docs/config_dscp_preservation.md
> +DSCP values may be changed by applications or hardware at any point while traversing a network. In some situations it is important that the DSCP value received at the router is the same as the origin
done

2022-07-19 19:06 UTC, Chr1st0ph3rTurn3r commented on docs/config_dscp_preservation.md
> +When a new session is created, the DSCP value of the first packet received from the local LAN is recorded and included in the metadata. If DSCP values change within the life of the session, when the
updated

2022-07-19 19:06 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.6.md
> +- **I95-44870 Mist Self-Registration Onboarding:** More to come.
removed

2022-07-19 19:06 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.6.md
> +- **I95-43779 DHCP IP Address not releasing appropriately:** Reboot now triggers DHCP-enabled interfaces to send out a DHCP Request for their current IP address.
fixed wording

2022-07-19 19:52 UTC, MichaelBaj approved these changes

2022-07-19 19:52 UTC, MichaelBaj commented on docs/releases.table.js
> +    url:'release_notes_128t_5.6#release-561-1',
Still need build number

2022-07-19 19:52 UTC, MichaelBaj requested changes
need to update build number prior to publishing

2022-07-26 13:36 UTC, MarkusJork commented on docs/config_bgp.md
> +            interval-time  15
The `interval-time` attribute is at the top level in the BGP hierarchy, not here under the neighbor. Your "Example Configuration" section further below has it in the right place.

2022-07-26 13:36 UTC, MarkusJork commented on docs/config_bgp.md
> +            interval-time  15
same issue here

2022-07-26 14:21 UTC, Chr1st0ph3rTurn3r commented on docs/config_bgp.md
> +            interval-time  15
Moved it to the top level.

2022-07-26 14:21 UTC, Chr1st0ph3rTurn3r commented on docs/config_bgp.md
> +            interval-time  15
moved it up

2022-07-26 14:28 UTC, MarkusJork approved these changes

2022-07-26 18:28 UTC, MichaelBaj commented on docs/config_ha.md
> +### Session Failover
I'm not sure this needs to be documented. While the scope of work was large, many customers would view this a defect by way of omission. My preference is to not document.

2022-07-26 18:28 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-35610 Session Failover without a Forward Packet:** A keep-alive mechanism has been added for flow moves. When flow move is triggered, the SSR detects inactivity in forward traffic and generat
per my comment above, if you agree, please remove the section starting with: "For additional details ..."

2022-07-26 19:00 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.6.md
> +- **I95-35610 Session Failover without a Forward Packet:** A keep-alive mechanism has been added for flow moves. When flow move is triggered, the SSR detects inactivity in forward traffic and generat
Agree - removed the links.

2022-08-01 20:06 UTC, MichaelBaj approved these changes

2022-08-01 21:23 UTC, merged