Add ipsec-client 3.4.0 release notes
128technology/docs pull request #411
Opened 2022-07-11 19:26 UTC by agrawalkaushik

2022-07-11 19:45 UTC, MichaelBaj commented on docs/plugin_ipsec_client.md
> +**Router Version** 128T-ipsec-2.2.4-2
Router version 2.2.4-2, but release 3.4.0?

2022-07-11 20:28 UTC, Chr1st0ph3rTurn3r requested changes

2022-07-11 20:28 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +  _**Resolution:**_ Trace level logging is not converted appropriately for IPSec configuration to prevent underlying failures.
```suggestion
  _**Resolution:**_ Trace level logging was not converted appropriately for IPSec configuration to prevent underlying failures.
```
or "is now converted" The resolution sounds like a restatement of the problem.

2022-07-12 00:53 UTC, agrawalkaushik commented on docs/plugin_ipsec_client.md
> +**Router Version** 128T-ipsec-2.2.4-2
plugins have separate versions for conductor and router components. So on field demand we document both version in this format now.

2022-07-12 00:54 UTC, agrawalkaushik commented on docs/plugin_ipsec_client.md
> +  _**Resolution:**_ Trace level logging is not converted appropriately for IPSec configuration to prevent underlying failures.
I think I mistyped `now` as `not`. It should've said `logging is now converted`.

2022-07-12 00:58 UTC, agrawalkaushik commented on docs/plugin_ipsec_client.md
> +## Troubleshooting
no change to the troubleshooting section. I just moved all the plugin generated config details to the Appendix section which caused this to get bumped up

2022-07-12 12:38 UTC, Chr1st0ph3rTurn3r submitted a review, later dismissed

2022-07-12 12:38 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +The IPsec plugin setup has the following key parts to the configuration
```suggestion
The IPsec plugin setup has the following key parts to the configuration.
```

2022-07-12 12:38 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +* `ipsec-profile` describing the mechanism with which to connect to the server
```suggestion
* `ipsec-profile` describing the mechanism with which to connect to the server.
```

2022-07-12 12:38 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +* `ipsec-client` represent the remote endpoints or server that the ipsec client communicates with
```suggestion
* `ipsec-client` represent the remote endpoints or server with which the ipsec client communicates.
```

2022-07-12 12:38 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +The `router > ipsec-profile`'s are reusable IPsec settings that can be used across multiple nodes in a router and multiple IPsec endpoint `remote`s. The table below represents the most common configu
```suggestion
The `router > ipsec-profile`'s are reusable IPsec settings that can be used across multiple nodes in a router and multiple IPsec endpoint `remote`s. The table below represents the most common configuration elements for a valid ipsec profile.
```

2022-07-12 12:38 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +| host              | ip-or-fqdn | The address or FQDN of the remote endpoint |
```suggestion
| host              | ip-or-fqdn | The address or FQDN of the remote endpoint. |
```

2022-07-12 12:38 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +| profile           | reference | The name of the profile to be used for this remote endpoint |
```suggestion
| profile           | reference | The name of the profile to be used for this remote endpoint. |
```

2022-07-12 12:38 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +| remote-id         | string    | The optional remote identifier used during authentication |
```suggestion
| remote-id         | string    | The optional remote identifier used during authentication. |
```

2022-07-12 12:38 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +| subnet            | ip-prefix | The remote subnet behind the tunnel |
```suggestion
| subnet            | ip-prefix | The remote subnet behind the tunnel. |
```

2022-07-12 12:38 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +| tunnel-monitor    | container | Properties for monitoring the phase-2 connection. More details [here](plugin_ipsec_client.md#tunnel-monitoring) |
```suggestion
| tunnel-monitor    | container | Properties for monitoring the phase-2 connection. See [Tunnel Monitoring](plugin_ipsec_client.md#tunnel-monitoring) for more information. |
```

2022-07-12 12:38 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +The `ipsec-client > name` cannot start with `ipsec` or `mast`. See notes [here](plugin_ipsec_client.md#release-340)
```suggestion
The `ipsec-client > name` cannot start with `ipsec` or `mast`. See notes [here](plugin_ipsec_client.md#release-340).
```

2022-07-12 12:38 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +The user define up to four `ipsec-client > remote` endpoints per node. In addition, the user has to also define the necessary service and service-routes to route the tunnel traffic over the desired W
```suggestion
The user can define up to four `ipsec-client > remote` endpoints per node. In addition, the user must also define the necessary service and service-routes to route the tunnel traffic over the desired WAN interface.
```

2022-07-12 12:38 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +The `service-route > next-hop > interface` must point to the corresponding `ipsec-client > remote > name`-intf to route the traffic through the tunnel. All the available SSR routing techniques using
```suggestion
The `service-route > next-hop > interface` must point to the corresponding `ipsec-client > remote > name`-intf to route the traffic through the tunnel. All available SSR routing techniques including using vectors, service-policy, etc., can be leveraged to define how the untrusted traffic is sent over the tunnels, and how to route the traffic. The SSR routes the packets through the appropriate IPSec tunnels and manages the failover as per the policy. On the return path, the encrypted traffic is processed, decrypted, and send back to the client that originated the session.
```

2022-07-13 22:56 UTC, jeffmart-jnpr approved these changes

2022-07-14 12:32 UTC, Chr1st0ph3rTurn3r approved these changes

2022-07-14 12:32 UTC, merged