Idp features
128technology/docs pull request #412
Opened 2022-07-12 20:01 UTC by Chr1st0ph3rTurn3r

IDP Draft

2022-07-12 21:35 UTC, MichaelBaj commented on docs/ts_idp.md
> +Alarms
Header syntax

2022-07-12 21:35 UTC, MichaelBaj commented on docs/ts_idp.md
> +Logs
Header markdown syntax

2022-08-15 17:55 UTC, jamesesilvia requested changes
Just few things to round it out. Does a great job summarizing the implementation/configuration.

2022-08-15 17:55 UTC, jamesesilvia commented on docs/concepts_ssr_idp.md
> +Security events are generated any time a vulnerability is detected. These events are stored on the system for up to 24 hours (is this configurable?), and can be viewed on the Security Event History p
Correct, retention is not configurable. 

- [ ] The events are filterable/viewable through both the UI and PCLI.

2022-08-15 17:55 UTC, jamesesilvia commented on docs/concepts_ssr_idp.md
> +- The IDP solution is only designed for use on a spoke router, and for local breakout services.
The most common use case is local breakout.

There is a configuration element at `config > authority > router > idp > mode`. This is an advanced field; the default of `auto` is recommended; however its probably worth mentioning that SVR is supported; and the router can be setup as an SVR-passthrough by setting this field to `hub`. 

- [ ] The options are `auto | disabled | spoke | hub`.

2022-08-15 17:55 UTC, jamesesilvia commented on docs/ts_idp.md
> +admin@node.idp # show idp application status
The PCLI docs are the 🐐 . I'd recommend circling back to the PCLI  docs in a day or two once everything has been merged. (1
```
| command | description |
| ------- | ----------- |
| [`request idp restart`](#request-idp-restart) | Restart Idp Command |
| [`show idp application status`](#show-idp-application-status) | Show underlying IDP application status. |
| [`show idp details`](#show-idp-details) | Show underlying IDP details. |
| [`show idp events`](#show-idp-events) | Show all IDP event |
| [`show idp events by-application`](#show-idp-events-by-application) | Show IDP event by application |
| [`show idp events by-attack`](#show-idp-events-by-attack) | Show IDP event by attack type |
| [`show idp events by-severity`](#show-idp-events-by-severity) | Show IDP event by severity level |
| [`show idp network`](#show-idp-network) | Show underlying IDP application status. |
| [`show idp platform`](#show-idp-platform) | Show underlying IDP platform data. |
| [`show idp security-package`](#show-idp-security-package) | Show underlying IDP security package details |
| [`show stats idp`](STATS.md#show-stats-idp) | Metrics about IDP |
```

2022-08-15 17:55 UTC, jamesesilvia commented on docs/ts_idp.md
> +When IDP is configured on a router, an alarm is generated if the IDP engine is in a failed state. The alarm clears when the IDP engine is operational.
Unfortunately, this isn't part of this release. `show idp application status` is the best place to go find high-level errors. Alarm generation will be done as a near future enhancement.

- [ ] rm alarm

2022-08-15 17:55 UTC, jamesesilvia commented on docs/ts_idp.md
> +The `show tech-support` info contains the relevant logs and journals associated with the IDP engine.
This is correct that the logs will be captured by save-tech-support. If we want to elaborate where the IDP engine logs to its `/var/log/128technology/idp/*`

2022-08-29 18:03 UTC, Chr1st0ph3rTurn3r commented on docs/ts_idp.md
> +**(need more information, better troubleshooting information)**
done

2022-08-29 18:04 UTC, Chr1st0ph3rTurn3r commented on docs/ts_idp.md
> +Alarms
done

2022-08-29 18:04 UTC, Chr1st0ph3rTurn3r commented on docs/ts_idp.md
> +Logs
done

2022-08-29 18:04 UTC, Chr1st0ph3rTurn3r commented on docs/config_idp.md
> +It is also important to control the amount of traffic flowing through the IDP engine, as there are system constraints around performance and bandwidth. Intrusion detection is a resource intensive ope
removed

2022-08-29 18:04 UTC, Chr1st0ph3rTurn3r commented on docs/ts_idp.md
> +admin@node.idp # show idp application status
updated/linked

2022-08-29 18:04 UTC, Chr1st0ph3rTurn3r commented on docs/ts_idp.md
> +The `show tech-support` info contains the relevant logs and journals associated with the IDP engine.
added

2022-08-30 17:38 UTC, MichaelBaj requested changes

2022-08-30 17:38 UTC, MichaelBaj commented on docs/concepts_ssr_idp.md
> +### IDP Actions
To the best of my knowledge a network administrator is not able to configure the actions per matching threat. These actions are influenced by the policy enforcement level. This section is useful to understand the behavior, but may be confusing to the reader as they may believe they can influence the behavior.
@jamesesilvia are these actions configurable?
If not, I recommend adding text in the beginning of the section indicating as such.

2022-08-30 17:38 UTC, MichaelBaj commented on docs/ts_idp.md
> +The `show stats idp` metrics track the number of packets and bytes sent in/out of the IDP engine. Additionally, data is captured by protocol such as UDP, TCP, ICMP etc.
This section needs to be updated once the [PR](https://github.com/Juniper-SSN/ssr/pull/3020) has been merged

2022-08-30 20:54 UTC, jamesesilvia commented on docs/concepts_ssr_idp.md
> +### IDP Actions
Correct. The actions are not currently configuration; but here they are:

`alert` -- `no-action; log-attack`
`standard` -- `recommended;log-attack`
`strict` -- `close-client-and-server;log-attack`

2022-08-30 20:57 UTC, jamesesilvia commented on docs/concepts_ssr_idp.md
> +- IDP Mode: This is set to Auto by default, and automatically determines the status of your SSR for IDP. This is an Advanced administrative setting and it is not recommended to be changed. The option
We went back and forth on this. I do think we want to be clear that this is advanced/get-out-of-jail configuration knob. 99% of cases `auto` is what you need.

2022-08-30 20:58 UTC, jamesesilvia commented on docs/concepts_ssr_idp.md
> +![Show IDP Events in PCLI](/img/idp_show-idp-events.jpg)
Will get @Chr1st0ph3rTurn3r some PCLI output

2022-08-31 16:05 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_ssr_idp.md
> +### IDP Actions
done

2022-08-31 16:05 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_ssr_idp.md
> +![Show IDP Events in PCLI](/img/idp_show-idp-events.jpg)
added

2022-08-31 16:05 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_ssr_idp.md
> +IDP Automatic Updates are defined using the same value configured in the Application Identification **auto-update** setting. If no value is set, the default is weekly.
updated

2022-08-31 16:06 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_ssr_idp.md
> +- IDP Mode: This is set to Auto by default, and automatically determines the status of your SSR for IDP. This is an Advanced administrative setting and it is not recommended to be changed. The option
edits made

2022-08-31 16:06 UTC, Chr1st0ph3rTurn3r commented on docs/config_idp.md
> +## Core Requirements
moved

2022-08-31 16:06 UTC, Chr1st0ph3rTurn3r commented on docs/ts_idp.md
> +The `show stats idp` metrics track the number of packets and bytes sent in/out of the IDP engine. Additionally, data is captured by protocol such as UDP, TCP, ICMP etc.
i made some edits, please review.

2022-08-31 17:41 UTC, jamesesilvia approved these changes

2022-08-31 17:41 UTC, jamesesilvia commented on docs/concepts_ssr_idp.md
> +Security events are generated any time a vulnerability is detected. These events are stored on the system for up to 24 hours, and can be viewed on the Security Event History page on the SSR Conductor
Dashboard is available on the Router as well.

2022-08-31 17:41 UTC, jamesesilvia commented on docs/release_notes_128t_6.0.md
> +- **I95-44533 Intrusion Detection and Prevention:** Using the Juniper IDP Signature Database, IDP is now available on the SSR. For detailed information, see [Intrusion Detection and Prevention](conce
Is it worth noting this is Mist-managed compatible? Not sure if we document any Mist related functionality here.

2022-08-31 17:59 UTC, MichaelBaj requested changes

2022-08-31 17:59 UTC, MichaelBaj commented on docs/cli_stats_reference.md
> +IDP Metrics for bytes
What does this mean to show IDP metrics for bytes? Which bytes in a session? Can you provide a snippet of the output? That will help in crafting a proper description.

2022-08-31 17:59 UTC, MichaelBaj commented on docs/concepts_ssr_idp.md
> +```
you should remove the image uploaded in the previous commit

2022-08-31 17:59 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-47418 Audit Events for Plugins:** A new audit event has been added that tracks when a plugin is installed or uninstalled. This can be viewed on the Audit History page in the GUI or in the PCL
I don't believe the trailing period in the `show events` command is correct. Please confirm with Jacob Bogdanov

2022-08-31 17:59 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-46918 GUI and PCLI out of sync when new configuration elements added/modified:** Resolved an issue where  `show network-interface` and `show config` were not updating properly.
extra space before `show

2022-08-31 17:59 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-47630 Unrecognized mac-address argument:** This issue has been resolved.
This is an issue of found and fixed in development. Marked as exclude from release notes. Please remove.

2022-09-01 14:50 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.0.md
> +- **I95-44533 Intrusion Detection and Prevention:** Using the Juniper IDP Signature Database, IDP is now available on the SSR. For detailed information, see [Intrusion Detection and Prevention](conce
noted

2022-09-01 14:50 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_ssr_idp.md
> +Security events are generated any time a vulnerability is detected. These events are stored on the system for up to 24 hours, and can be viewed on the Security Event History page on the SSR Conductor
noted

2022-09-01 14:50 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_ssr_idp.md
> +```
removed

2022-09-01 14:51 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.0.md
> +- **I95-47418 Audit Events for Plugins:** A new audit event has been added that tracks when a plugin is installed or uninstalled. This can be viewed on the Audit History page in the GUI or in the PCL
my typo - fixed

2022-09-01 14:51 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.0.md
> +- **I95-46918 GUI and PCLI out of sync when new configuration elements added/modified:** Resolved an issue where  `show network-interface` and `show config` were not updating properly.
removed

2022-09-01 14:51 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.0.md
> +- **I95-47630 Unrecognized mac-address argument:** This issue has been resolved.
removed

2022-09-01 15:39 UTC, ravimurthy2012 submitted a review, later dismissed
Syslog section looks good...

2022-09-06 19:28 UTC, migolnikov requested changes

2022-09-06 19:28 UTC, migolnikov commented on docs/release_notes_128t_6.0.md
> +- **I95-46126 Router Status:** In some rare configurations of High Availability where a router is connected to HA Conductor 1, but not directly connected to HA Conductor 2, alarms generated on the ro
this is not a "rare configuration". It's more of an edge condition. While this could happen, this is not a normal mode of operation and should only happen during network connectivity failures

2022-09-06 20:17 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.0.md
> +- **I95-46126 Router Status:** In some rare configurations of High Availability where a router is connected to HA Conductor 1, but not directly connected to HA Conductor 2, alarms generated on the ro
edits made

2022-09-07 03:15 UTC, migolnikov submitted a review, later dismissed

2022-09-09 19:15 UTC, MichaelBaj requested changes

2022-09-09 19:33 UTC, Chr1st0ph3rTurn3r commented on docs/config_audit_event.md
> +        content  (text/plain). <---- contents of the client certificate.
done

2022-09-09 19:34 UTC, Chr1st0ph3rTurn3r commented on docs/config_audit_event.md
> +        client-certificate-name  ABC. <-- client certificate already configured under authority/client-certificate
done

2022-09-09 19:34 UTC, Chr1st0ph3rTurn3r commented on docs/config_audit_event.md
> +Although using TCP guarantees events are transmitted to the destination syslog server, it is not considered secure because the syslog server is clear text.
done

2022-09-12 18:16 UTC, MichaelBaj approved these changes

2022-09-13 01:14 UTC, merged