Wanas getstart 1
128technology/docs pull request #422
Opened 2022-08-02 19:21 UTC by Chr1st0ph3rTurn3r

2022-08-02 20:55 UTC, MichaelBaj requested changes

2022-08-02 20:55 UTC, MichaelBaj commented on docs/wan_staging.md
> +Juniper SSR hardware devices (SSR120/130, SSR1000-1500) include a QR code that when scanned, will automatically adopt your device into your Mist Organization. Scan the code using your Mist AI App, an
Add a link to the Juniper hardware onboarding document.

2022-08-02 20:55 UTC, MichaelBaj commented on docs/wan_onboarding_ssrdevice.md
> +With SSR version 6.0, SSR device onboarding to the Mist cloud is a "zero-touch" process. After powering up the hardware device and connecting to the WAN port, simply use your Mist App to scan the QR
Provide a link to the app: https://apps.apple.com/us/app/mistai/id1215196902

2022-08-02 20:55 UTC, MichaelBaj commented on docs/wan_onboarding_ssrdevice.md
> +For Juniper SSR Devices that have SSR Version 5.4.4 pre-installed, if you wish to upgrade to version 6.0, you must install the software using a USB.
Provide a link to the proper staging document. No need to duplicate content.

2022-08-02 21:15 UTC, agrawalkaushik commented on docs/wan_onboarding_ssrdevice.md
> +With SSR version 6.0, SSR device onboarding to the Mist cloud is a "zero-touch" process. After powering up the hardware device and connecting to the WAN port, simply use your Mist App to scan the QR
Is there an Android version 😄

2022-08-03 16:37 UTC, dfitzpatrick128 commented on docs/wan_onboarding_ssrdevice.md
> +With SSR version 6.0, SSR device onboarding to the Mist cloud is a "zero-touch" process. After powering up the hardware device and connecting to the WAN port, simply use your Mist App to scan the QR
https://play.google.com/store/apps/details?id=com.mist.mistify&hl=en_US&gl=US

is what i could find

2022-08-04 15:57 UTC, Chr1st0ph3rTurn3r commented on docs/wan_onboarding_ssrdevice.md
> +For Juniper SSR Devices that have SSR Version 5.4.4 pre-installed, if you wish to upgrade to version 6.0, you must install the software using a USB.
done

2022-08-04 16:09 UTC, agrawalkaushik commented on docs/wan_onboarding_ssrdevice.md
> +In both onboarding processes, when Mist identifies that the device is conductor-managed from the cloud, it reinitializes to use the factory default configuration with the conductor IP address. During
MIST does not identify this automatically, it requires config. We should document the process of how to configure MIST for conductor redirection.

2022-08-04 16:42 UTC, dfitzpatrick128 commented on docs/config_wan_assurance.md
> +SSR software can run on any certified hardware or virtual machine, however, for software versions prior to SSR Version 6.0, router adoption relies on an on-premise conductor to assist in the onboardi
SSR software can run on any Juniper branded, whitebox hardware (certified or self-evaluated), or virtual environments (virtual machines or cloud instances)?

2022-08-04 16:43 UTC, dfitzpatrick128 commented on docs/config_wan_assurance.md
> +SSR software can run on any certified hardware or virtual machine, however, for software versions prior to SSR Version 6.0, router adoption relies on an on-premise conductor to assist in the onboardi
bringing* not brining

2022-08-04 16:43 UTC, dfitzpatrick128 commented on docs/config_wan_assurance.md
> +SSR software can run on any certified hardware or virtual machine, however, for software versions prior to SSR Version 6.0, router adoption relies on an on-premise conductor to assist in the onboardi
is it mist portal or mist cloud ? idk what the street calls it

2022-08-04 16:45 UTC, dfitzpatrick128 commented on docs/config_wan_assurance.md
> +- Click on the Adopt WAN Edges button in the top right corner. The WAN Edge Adoption dialog appears, displaying the registration code.
does it display the code or the textbox to input the claim code? also i believe it is called a claim code not reg code but we should check this.

2022-08-04 16:46 UTC, dfitzpatrick128 commented on docs/wan_edge_provisioning.md
> +---
leaving this doc alone until it is fleshed out.

2022-08-04 16:48 UTC, dfitzpatrick128 commented on docs/wan_onboarding_ssrdevice.md
> +Juniper SSR hardware devices (SSR120/130, SSR1000-1500) come pre-installed with the version 5.4.4 software. The device includes a QR code that when scanned, automatically adopts your device into your
i would change it to SSR1200/1300/1400/1500 there is no SSR1000 or SSR1005 as of now but the way its written it may cause confusion if we ever come out with one

2022-08-04 16:49 UTC, dfitzpatrick128 commented on docs/wan_onboarding_ssrdevice.md
> +3. Connect to the WAN port.
i would flip 2 and 3 connect wan then power up IMO

2022-08-04 16:49 UTC, dfitzpatrick128 commented on docs/wan_onboarding_ssrdevice.md
> +4. Copy the Claim Code from the QR sticker.
Is this the way PLM dictates this vs claiming the code then powering on?

2022-08-04 16:50 UTC, dfitzpatrick128 commented on docs/wan_staging.md
> +Beginning with version 6.0, WAN Assurance for the SSR is available for users who manage their network using the Mist Cloud. This document describes the process to download an image and onboard a **wh
Mist cloud or MIST WAN assurance ? idk the proper term

2022-08-04 16:51 UTC, dfitzpatrick128 commented on docs/wan_staging.md
> +Beginning with version 6.0, WAN Assurance for the SSR is available for users who manage their network using the Mist Cloud. This document describes the process to download an image and onboard a **wh
or a non-certified but Juniper-compatible device. ---> Juniper approved self-evaluated device.

2022-08-04 16:52 UTC, dfitzpatrick128 requested changes
comments inline

2022-08-04 16:58 UTC, Chr1st0ph3rTurn3r commented on docs/config_wan_assurance.md
> +SSR software can run on any certified hardware or virtual machine, however, for software versions prior to SSR Version 6.0, router adoption relies on an on-premise conductor to assist in the onboardi
it's actually both. The portal is the UI, the cloud is the location of the Mist management

2022-08-04 17:01 UTC, Chr1st0ph3rTurn3r commented on docs/wan_onboarding_ssrdevice.md
> +Juniper SSR hardware devices (SSR120/130, SSR1000-1500) come pre-installed with the version 5.4.4 software. The device includes a QR code that when scanned, automatically adopts your device into your
got it

2022-08-04 17:05 UTC, Chr1st0ph3rTurn3r commented on docs/wan_staging.md
> +Beginning with version 6.0, WAN Assurance for the SSR is available for users who manage their network using the Mist Cloud. This document describes the process to download an image and onboard a **wh
got it

2022-08-04 17:09 UTC, Chr1st0ph3rTurn3r commented on docs/wan_onboarding_ssrdevice.md
> +4. Copy the Claim Code from the QR sticker.
Hmmm, so that would be different than the process for a whitebox, which I believe has to connect through the wan port to mist in order to onboard? At least that is what I understood from the ppt presentation.

2022-08-04 17:10 UTC, Chr1st0ph3rTurn3r commented on docs/config_wan_assurance.md
> +SSR software can run on any certified hardware or virtual machine, however, for software versions prior to SSR Version 6.0, router adoption relies on an on-premise conductor to assist in the onboardi
got it

2022-08-04 17:10 UTC, Chr1st0ph3rTurn3r commented on docs/config_wan_assurance.md
> +SSR software can run on any certified hardware or virtual machine, however, for software versions prior to SSR Version 6.0, router adoption relies on an on-premise conductor to assist in the onboardi
edited

2022-08-04 17:10 UTC, Chr1st0ph3rTurn3r commented on docs/wan_onboarding_ssrdevice.md
> +In both onboarding processes, when Mist identifies that the device is conductor-managed from the cloud, it reinitializes to use the factory default configuration with the conductor IP address. During
updated

2022-08-04 18:47 UTC, MichaelBaj requested changes

2022-08-04 18:47 UTC, MichaelBaj commented on docs/config_wan_assurance.md
> +SSR software can run on Juniper branded appliances, whitebox hardware (certified or self-evaluated), or virtual environments. However, for software versions prior to SSR Version 6.0, router adoption
Bring the conductor into the mist cloud can be misleading. The conductor will still be on-prem. What needs to be configured are the ip addresses of the conductor in the most cloud.

2022-08-08 18:51 UTC, Chr1st0ph3rTurn3r commented on docs/wan_staging.md
> +Juniper SSR hardware devices (SSR120/130, SSR1000-1500) include a QR code that when scanned, will automatically adopt your device into your Mist Organization. Scan the code using your Mist AI App, an
done

2022-08-08 18:51 UTC, Chr1st0ph3rTurn3r commented on docs/wan_onboarding_ssrdevice.md
> +With SSR version 6.0, SSR device onboarding to the Mist cloud is a "zero-touch" process. After powering up the hardware device and connecting to the WAN port, simply use your Mist App to scan the QR
done

2022-08-08 18:51 UTC, Chr1st0ph3rTurn3r commented on docs/wan_onboarding_ssrdevice.md
> +3. Connect to the WAN port.
done

2022-08-08 18:51 UTC, Chr1st0ph3rTurn3r commented on docs/config_wan_assurance.md
> +SSR software can run on Juniper branded appliances, whitebox hardware (certified or self-evaluated), or virtual environments. However, for software versions prior to SSR Version 6.0, router adoption
fixed I think

2022-08-09 12:50 UTC, MichaelBaj requested changes

2022-08-09 12:50 UTC, MichaelBaj commented on docs/config_wan_assurance.md
> +SSR software can run on Juniper branded appliances, whitebox hardware (certified or self-evaluated), or virtual environments. However, for software versions prior to SSR Version 6.0, router adoption
Suggested rewording:
"enabling WAN Assurance telemetry and ZTP for conductor-based deployments."

2022-08-09 12:50 UTC, MichaelBaj commented on docs/wan_edge_provisioning.md
> +- Create a unique site for each physical (or logical) location in the network. For example, the spoke and hub should be onboarded to different sites. Other devices from the Juniper stack such as Mist
suggested rewording:
"assigned to their respective sites".

2022-08-09 12:50 UTC, MichaelBaj commented on docs/wan_edge_provisioning.md
> +Configure and save a basic Internet app.
Suggest add additional wording:
"If you intend to have a catch-all application for all traffic, it is best practice to create an "Internet" application that is represented by a quad 0 (0.0.0.0/0)."

2022-08-09 20:32 UTC, Chr1st0ph3rTurn3r commented on docs/wan_edge_provisioning.md
> +Configure and save a basic Internet app.
added

2022-08-09 20:32 UTC, Chr1st0ph3rTurn3r commented on docs/wan_edge_provisioning.md
> +- Create a unique site for each physical (or logical) location in the network. For example, the spoke and hub should be onboarded to different sites. Other devices from the Juniper stack such as Mist
change made

2022-08-09 20:32 UTC, Chr1st0ph3rTurn3r commented on docs/config_wan_assurance.md
> +SSR software can run on Juniper branded appliances, whitebox hardware (certified or self-evaluated), or virtual environments. However, for software versions prior to SSR Version 6.0, router adoption
change made

2022-08-11 18:15 UTC, MichaelBaj approved these changes

2022-08-11 19:19 UTC, merged