Release notes for WAN Assurance 3.5.0 and 3.5.1
128technology/docs pull request #423
Opened 2022-08-02 21:25 UTC by agrawalkaushik

2022-08-02 21:29 UTC, MichaelBaj approved these changes

2022-08-02 21:32 UTC, Bhautik submitted a review, later dismissed

2022-08-03 11:45 UTC, salegria8 approved these changes

2022-08-03 12:09 UTC, BenMatase approved these changes

2022-08-03 12:55 UTC, Chr1st0ph3rTurn3r requested changes

2022-08-03 12:55 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.5.md
> +  _**Resolution:**_ The WAN Assurance plugin use plugin data files instead of pillar to synchronize data and apply plugin state to speed up the process.
```suggestion
  _**Resolution:**_ The WAN Assurance plugin uses plugin data files instead of pillar to synchronize data and apply plugin state to speed up the process.
```

2022-08-03 12:55 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.5.md
> +For TCP sessions the SSR collects metrics on TCP round-trip time which will be reported via application summary to the MIST cloud.
```suggestion
For TCP sessions the SSR collects metrics on TCP round-trip time which are reported via application summary to the MIST cloud.
```

2022-08-03 12:55 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.5.md
> +When a device is released from the MIST portal, the `show mist details` command provides additional context around the status, registration code being used and other information to assist in re-onboa
```suggestion
When a device is released from the MIST portal, the `show mist details` command provides additional context around the status, registration code being used, and other information to assist in re-onboarding the device.
```

2022-08-03 12:55 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.5.md
> +The `authority > mist-wan-assurance > registration-code` is used for onboarding new routers and has an expiration of one year. A warning is now displayed when using an expired code and the `show mist
```suggestion
The `authority > mist-wan-assurance > registration-code` is used for onboarding new routers and has an expiration of one year. A warning is now displayed when using an expired code. The `show mist details` commands also displays the expiration date for the configured token.
```

2022-08-03 13:55 UTC, Chr1st0ph3rTurn3r requested changes
Sorry - missed that last time.

2022-08-03 13:55 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.5.md
> +After upgrade the device will stop reporting the TCP reset metrics for 128T version 5.6.0 and lower since those metrics were reporting higher than normal error counts.
```suggestion
After upgrade the device will stop reporting the TCP reset metrics for SSR version 5.6.0 and lower since those metrics were reporting higher than normal error counts.
```

2022-08-03 15:00 UTC, Chr1st0ph3rTurn3r approved these changes

2022-08-03 15:38 UTC, merged