547 release notes
128technology/docs pull request #424
Opened 2022-08-03 21:10 UTC by Chr1st0ph3rTurn3r

May need to add a couple more things to the docs.

2022-08-04 11:29 UTC, MichaelBaj approved these changes

2022-08-04 20:14 UTC, Bhautik requested changes

2022-08-04 20:14 UTC, Bhautik commented on docs/release_notes_128t_5.4.md
> +- **I95-46747 Improved the Password user experience:** You now are re-propmpted up to three times for the current password if it is incorrect. If a new password does not meet the strength check, you
Seems like a spelling mistake at re-prompted

2022-08-04 20:21 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.4.md
> +- **I95-46574 Security History Export:** An Export button has been to the Security History page.
done

2022-08-04 20:21 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.4.md
> +- **I95-46747 Improved the Password user experience:** You now are re-propmpted up to three times for the current password if it is incorrect. If a new password does not meet the strength check, you
fixed

2022-08-04 21:16 UTC, Bhautik requested changes

2022-08-04 21:16 UTC, Bhautik commented on docs/intro_downloading_iso.md
> +With release 5.4.7-9 (and greater) a single ISO is provided that supports Installation workflows.
it needs to be 5.4.7-7

2022-08-04 21:16 UTC, Bhautik commented on docs/intro_downloading_iso.md
> +- 128T-5.4.7-5.el7.ISO.v1.x86_64.iso
it needs to be 5.4.7-7

2022-08-04 21:27 UTC, Bhautik approved these changes

2022-08-04 21:36 UTC, jeffmart-jnpr approved these changes

2022-08-05 12:52 UTC, MichaelBaj approved these changes

2022-08-05 12:53 UTC, merged