5.5.3 release notes
128technology/docs pull request #426
Opened 2022-08-09 16:32 UTC by Chr1st0ph3rTurn3r

2022-08-09 17:42 UTC, MichaelBaj submitted a review, later dismissed

2022-08-09 20:29 UTC, MichaelBaj approved these changes

2022-08-10 13:55 UTC, MichaelBaj approved these changes

2022-08-10 18:34 UTC, Bhautik requested changes

2022-08-10 18:34 UTC, Bhautik commented on docs/about_releases.mdx
> +| Release 5.5 | [5.5.2](release_notes_128t_5.5.md#release-553-4) |
should be [5.5.3]

2022-08-10 18:59 UTC, Bhautik approved these changes

2022-08-10 19:00 UTC, MichaelBaj approved these changes

2022-08-11 15:07 UTC, merged