adding release notes, feature info for password policies, and fixing …
128technology/docs pull request #428
Opened 2022-08-12 15:56 UTC by Chr1st0ph3rTurn3r

…a typo in the Config element guide.

2022-08-12 16:15 UTC, MichaelBaj requested changes

2022-08-12 16:15 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-47136 Settings for WAN Link Speed and Duplex:** With this update, the SSR supports the auto-negotiation, disable, and speed/duplex settings configured in Mist on an SSR.
This is a Mist feature. The SSR already has this capability.

2022-08-12 18:35 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.0.md
> +- **I95-47136 Settings for WAN Link Speed and Duplex:** With this update, the SSR supports the auto-negotiation, disable, and speed/duplex settings configured in Mist on an SSR.
Updated.

2022-08-15 15:22 UTC, MichaelBaj submitted a review, later dismissed

2022-08-15 15:42 UTC, MichaelBaj approved these changes

2022-08-15 19:21 UTC, jeffmart-jnpr requested changes
Need the identified changes

2022-08-15 19:52 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.0.md
> +- **I95-46281 Kernel Update:** Update to RHCK 8.6 for the latest security fixes.
removed this

2022-08-15 20:14 UTC, jeffmart-jnpr approved these changes

2022-08-15 20:15 UTC, MichaelBaj approved these changes

2022-08-15 20:37 UTC, merged