Docs 323 mist quickstarts
128technology/docs pull request #435
Opened 2022-08-19 22:47 UTC by reidstidolph

This adds an complete quickstart flow, beginning with SSR120 or SSR130 device pages, and ending with a working standalone device config with LAN -> WAN routing.

Device entry points are unlisted in sidebars, intending to be linked from the Juniper.net docs quickstart page.
- /docs/intro_wa_quickstart_SSR120_onboarding
- /docs/intro_wa_quickstart_SSR130_onboarding

Each one will feed into the workflow.

2022-08-19 23:19 UTC, MichaelBaj requested changes

2022-08-19 23:19 UTC, MichaelBaj commented on docs/intro_wa_quickstart_3_templates.md
> +2. Enter a name the name column, and **click the check** to the right of your entry.
"enter a name in the column" ?

2022-08-19 23:19 UTC, MichaelBaj commented on docs/intro_wa_quickstart_4_siteassign.md
> +* your SSR device in your inventory.
Capitalize first letter in each bulleted list

2022-08-19 23:19 UTC, MichaelBaj commented on docs/intro_wa_quickstart_SSR120_onboarding.md
> +<img src="/img/intro_wa_ssr120_quickstart_1.png" alt="Device Connections" width="500"/>
why not use the standard way to add an image to markdown?

2022-08-19 23:19 UTC, MichaelBaj commented on docs/intro_wa_quickstart_SSR120_onboarding.md
> +Your SSR device uses port 0 (`ge-0`) as a default WAN port to contact Mist for zero-touch provisioning (ZTP). Also you will set up port 3 (`ge-3`) with a LAN network.
is't it `ge-0-0-0` when defined in the mist data model. It should be consistent. Same for `ge-3`

2022-08-19 23:19 UTC, MichaelBaj commented on docs/intro_wa_quickstart_SSR120_onboarding.md
> +<img src="/img/intro_wa_ssr120_quickstart_2.png" alt="Device Connections" width="500"/>
same as above

2022-08-19 23:19 UTC, MichaelBaj commented on docs/intro_wa_quickstart_SSR120_onboarding.md
> +<img src="/img/intro_wa_quickstart_mobile_app.png" alt="MistAI app" width="250"/>
same as above

2022-08-19 23:19 UTC, MichaelBaj commented on docs/intro_wa_quickstart_SSR130_onboarding.md
> +<img src="/img/intro_wa_ssr130_quickstart_1.png" alt="Device Connections" width="500"/>
why not use standard markdown image syntax?

2022-08-19 23:19 UTC, MichaelBaj commented on docs/intro_wa_quickstart_SSR130_onboarding.md
> +Your SSR device uses port 0 (`ge-0`) as a default WAN port to contact Mist for zero-touch provisioning (ZTP). Also you will set up port 3 (`ge-3`) with a LAN network.
same comment as SSR120 page

2022-08-19 23:19 UTC, MichaelBaj commented on docs/intro_wa_quickstart_SSR130_onboarding.md
> +<img src="/img/intro_wa_ssr130_quickstart_2.png" alt="Device Connections" width="500"/>
same

2022-08-19 23:19 UTC, MichaelBaj commented on docs/intro_wa_quickstart_SSR130_onboarding.md
> +<img src="/img/intro_wa_quickstart_mobile_app.png" alt="MistAI app" width="250"/>
same

2022-08-19 23:27 UTC, reidstidolph commented on docs/intro_wa_quickstart_3_templates.md
> +2. Enter a name the name column, and **click the check** to the right of your entry.
hmmm...yeah the column is called "name", and there are multiple columns so I need to call it out. Let me try to re-word that.

2022-08-19 23:32 UTC, reidstidolph commented on docs/intro_wa_quickstart_SSR120_onboarding.md
> +<img src="/img/intro_wa_ssr120_quickstart_1.png" alt="Device Connections" width="500"/>
The issue I was having was that it rendered the images stretched the width of the viewport, and they were far too large. I spent some time trying to figure out how to indicate some better width formatting in markdown...and ultimately everywhere I looked people seemed to just say "use inline HTML".

2022-08-19 23:32 UTC, reidstidolph commented on docs/intro_wa_quickstart_SSR120_onboarding.md
> +Your SSR device uses port 0 (`ge-0`) as a default WAN port to contact Mist for zero-touch provisioning (ZTP). Also you will set up port 3 (`ge-3`) with a LAN network.
Yeah, good call.

2022-08-19 23:35 UTC, reidstidolph commented on docs/intro_wa_quickstart_4_siteassign.md
> +* your SSR device in your inventory.
Fixed.

2022-08-19 23:55 UTC, MichaelBaj submitted a review, later dismissed

2022-08-20 14:05 UTC, Chr1st0ph3rTurn3r requested changes

2022-08-20 14:05 UTC, Chr1st0ph3rTurn3r commented on docs/intro_wa_quickstart_4_siteassign.md
> +Continue reading in the docs for more advanced design use cases, deployment and onboarding scenarios, and AI operations with Mist WAN Assurance!
```suggestion
Continue reading in the Mist documentation for more advanced design use cases, deployment and onboarding scenarios, and AI operations with Mist WAN Assurance!
```
Not sure if you are referring to the Mist or the SSR documentation.

2022-08-20 14:05 UTC, Chr1st0ph3rTurn3r commented on docs/wan_assurance_ssr130_quickstart.md
> +    * Connectivity Internet and Mist
```suggestion
    * Connectivity to the Internet and Mist
```

2022-08-20 14:05 UTC, Chr1st0ph3rTurn3r commented on docs/wan_assurance_ssr130_quickstart.md
> +* enter the claim code in Mist
```suggestion
* Enter the claim code in Mist
```

2022-08-21 15:32 UTC, MichaelBaj approved these changes

2022-08-22 02:05 UTC, Chr1st0ph3rTurn3r approved these changes

2022-08-22 02:05 UTC, merged