adding installer release notes for 3.1.5
128technology/docs pull request #444
Opened 2022-09-08 20:40 UTC by Chr1st0ph3rTurn3r

2022-09-08 20:51 UTC, ian-h-chamberlain approved these changes

2022-09-08 20:51 UTC, ian-h-chamberlain commented on docs/release_notes_128t_installer_3.1.md
> +- **IN-491 Installer Repo uses HTTP instead of HTTPS:** Installer repo now defaults to HTTPS. To install the new repo manually, run yum install https://yum.128technology.com/installer/repo.rpm.
Technically this is not strictly tied to installer 3.1.5, but I don't think we really have a better place for this note than here so it's probably fine.

2022-09-08 20:51 UTC, ian-h-chamberlain commented on docs/release_notes_128t_installer_3.1.md
> +- **IN-502 Improve error message for packagebased install attempt over image-based install:** The package-based installation process will not attempt over an image-based install, and provides relevan
nit: `packagebased` -> `package-based` ?

2022-09-08 20:51 UTC, ian-h-chamberlain commented on docs/release_notes_128t_installer_3.1.md
> +- **IN-505 The `check_url` plugin only checks first `baseurl` location:** The `check_url` plugin now makes requests to all baseurls, allowing downloads if the first encountered repo is down.
For users, `check_url` is kind of an implementation detail, so depending on how technical you want this to be it could even just be something like

> When multiple conductor-hosted repositories are used (`prefer-conductor` or `conductor-only` configuration) with an HA conductor, check for package availability from both Conductors instead of just one.

This technically could apply to other remote repos too but the primary case is for conductor-hosted repos.

2022-09-08 21:02 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_installer_3.1.md
> +- **IN-505 The `check_url` plugin only checks first `baseurl` location:** The `check_url` plugin now makes requests to all baseurls, allowing downloads if the first encountered repo is down.
edited

2022-09-08 21:03 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_installer_3.1.md
> +- **IN-502 Improve error message for packagebased install attempt over image-based install:** The package-based installation process will not attempt over an image-based install, and provides relevan
thank you!

2022-09-09 12:44 UTC, ian-h-chamberlain approved these changes

2022-09-09 17:33 UTC, MichaelBaj requested changes

2022-09-09 17:33 UTC, MichaelBaj commented on docs/release_notes_128t_installer_3.1.md
> +- **IN-505 The `check_url` plugin only checks first `baseurl` location:** When multiple conductor-hosted repositories are used (`prefer-conductor` or `conductor-only` configuration) with an HA conduc
`check_url` is an internal detail that is meaningless to customers. Suggested rewording:
- **IN-505** Installer does not attempt to use subsequent configured repositories:** When multiple conductor-hosted repositories are used (`prefer-conductor` or `conductor-only` configuration) with an HA conductor, package availability is checked on both Conductors instead of just one.

2022-09-09 17:37 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_installer_3.1.md
> +- **IN-505 The `check_url` plugin only checks first `baseurl` location:** When multiple conductor-hosted repositories are used (`prefer-conductor` or `conductor-only` configuration) with an HA conduc
changes made

2022-09-09 17:38 UTC, MichaelBaj approved these changes

2022-09-09 17:45 UTC, ian-h-chamberlain approved these changes

2022-09-09 19:35 UTC, merged