Telemetry breakout
128technology/docs pull request #446
Opened 2022-09-16 15:34 UTC by Chr1st0ph3rTurn3r

2022-09-20 17:24 UTC, MichaelBaj requested changes

2022-09-21 15:52 UTC, agrawalkaushik commented on docs/wan_telemetry_troubleshooting.md
> +`show plugins state router <router name> summary 128T-mist-wan-assurance`
we added a `show mist` command in 6.0.0. The output remains the same. My recommendation would be to add that instead of this command and maybe we can add a footnote about this command for 5.x deployments.

2022-09-21 15:55 UTC, agrawalkaushik commented on docs/wan_telemetry_troubleshooting.md
> +### Releasing a Router
There is a hyperlink to the following [link](https://www.juniper.net/documentation/us/en/software/session-smart-router/docs/config_wan_assurance/#releasing-a-router) from the MIST UI. So we need to either preserve that or re-route the link somehow to this page. 

Here's where the link is on MIST page:
![Screen Shot 2022-09-21 at 11 54 31 AM](https://user-images.githubusercontent.com/60372242/191552705-f0aa04ae-93d2-436b-a546-8d41c0ff9bf1.png)

2022-09-21 15:57 UTC, agrawalkaushik requested changes
Need to figure out the hyperlink before making these changes

2022-09-21 17:04 UTC, Chr1st0ph3rTurn3r commented on docs/wan_telemetry_troubleshooting.md
> +### Releasing a Router
This will be the new link:
https://www.juniper.net/documentation/us/en/software/session-smart-router/docs/wan_telemetry_troubleshooting.md#moving-a-router 
but it won't be active until I publish these changes, so we need to coordinate the two events.

2022-09-21 17:07 UTC, Chr1st0ph3rTurn3r commented on docs/wan_telemetry_troubleshooting.md
> +`show plugins state router <router name> summary 128T-mist-wan-assurance`
I will add that to the SSR 6.x section of the docs. This section in particular deals with onboarding/configuring an SSR running 5.4.4 up to 6.0.

2022-09-22 17:16 UTC, agrawalkaushik commented on docs/wan_telemetry_troubleshooting.md
> +### Releasing a Router
If we intend on updating the link on the MIST UI, we need to do that soon to catch the 09/28 push. Otherwise we will need to wait for this change until the next push. My proposal alternatively, was to redirect the old page to the new link somehow. Maybe @MichaelBaj knows of a way to do that in docusaurus?

2022-09-22 17:43 UTC, MichaelBaj commented on docs/wan_telemetry_troubleshooting.md
> +### Releasing a Router
@agrawalkaushik the link you posted above is of a section within the docs page (WAN Assurance > Conductor Managed WAN Assurance > Releasing a Router).
What page do you want to be redirected? That page has additional content related to releasing a router. Are you referring to the section itself, dynamically loading the content from the "new" link?

2022-09-28 02:41 UTC, agrawalkaushik commented on docs/wan_telemetry_troubleshooting.md
> +### Releasing a Router
This is the link on the MIST UI for release and re-onboarding a conductor managed router
https://www.juniper.net/documentation/us/en/software/session-smart-router/docs/config_wan_assurance/#releasing-a-router

and if we want to re-organize things per Chris's change it will nee to be redirected to
https://www.juniper.net/documentation/us/en/software/session-smart-router/docs/wan_telemetry_troubleshooting.md#moving-a-router

This is to avoid changing the link on the MIST UI.

2022-09-28 19:30 UTC, Chr1st0ph3rTurn3r commented on docs/wan_telemetry_troubleshooting.md
> +### Releasing a Router
Based on the doc changes, the link in the Mist UI will need to change as Kaushik states above. We can coordinate the docs push with the Mist UI push as needed.

2022-09-30 16:01 UTC, MichaelBaj requested changes

2022-09-30 16:01 UTC, MichaelBaj commented on docs/wan_telemetry_site_assign.md
> +4. For conductor-managed routers (SSR Software version 5.4.x to 6.x) Make sure there is **no** checkmark in the **Manage Configuration from Mist** under **Manage Configuration**. The device will reac
no upper bound

2022-09-30 17:51 UTC, Chr1st0ph3rTurn3r commented on docs/wan_telemetry_site_assign.md
> +4. For conductor-managed routers (SSR Software version 5.4.x to 6.x) Make sure there is **no** checkmark in the **Manage Configuration from Mist** under **Manage Configuration**. The device will reac
resolved

2022-09-30 17:51 UTC, Chr1st0ph3rTurn3r commented on docs/intro_wa_quickstart_4_siteassign.md
> +	For conductor-managed routers (SSR Software version 5.4.x to 6.x) Make sure there is **no** checkmark in the **Manage Configuration from Mist** under **Manage Configuration**.
resolved

2022-10-03 14:32 UTC, MichaelBaj submitted a review, later dismissed

2022-10-04 14:20 UTC, agrawalkaushik commented on docs/wan_telemetry_troubleshooting.md
> +   registration-code:                          eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdfaWQiOiIwYzE2MGI3Zi0xMDI3LTRjZDEtOTIzYi03NDQ1MzRjNGIwNzAiLCJzdmMiOiIxMjhyb3V0ZXIiLCJwcm92aWRlciI6ImF3cyIsImV
is this a fake reg-code ?

2022-10-04 14:34 UTC, MichaelBaj approved these changes

2022-10-10 13:25 UTC, agrawalkaushik requested changes

2022-10-10 13:25 UTC, agrawalkaushik commented on docs/wan_overview.md
> +### Onboard a Mist-Managed SSR Device
These sections should be re-organized as they are a mist of MIST managed and conductor managed workflows. I would recommend the following order

* Onboard a Mist-Managed SSR Device
* Adopt a Whitebox Device to be MIST managed
* Adopt a conduct-managed SSR device
    * For this one we no longer include the process of onboarding for non Juniper devices which was previously covered [here](https://docs.128technology.com/docs/config_wan_assurance) - this needs to be restored

2022-10-11 23:00 UTC, agrawalkaushik commented on docs/config_wan_assurance.md
> +- [Features](wan_telemetry_features.md)
When reviewing these changes locally, these links are broken. I think the `.md` needs to be dropped?

2022-10-11 23:03 UTC, agrawalkaushik commented on docs/config_wan_assurance.md
> +- Add the Conductor IP address to the Site.
Might be worth mentioning that this allows a device to ZTP to the conductor via MIST. This is mostly useful for Juniper branded devices such as SSR120, SSR130 etc. It's a pretty powerful feature so we can probably document it separately. I know this PR has been delayed long enough so not going to block it for this.

2022-10-11 23:03 UTC, agrawalkaushik approved these changes

2022-10-11 23:05 UTC, agrawalkaushik commented
@Chr1st0ph3rTurn3r since you're keeping the `config_wan_assurance.md`, you need to create a section for https://www.juniper.net/documentation/us/en/software/session-smart-router/docs/config_wan_assurance/#releasing-a-router which points to https://www.juniper.net/documentation/us/en/software/session-smart-router/docs/wan_telemetry_troubleshooting.md#moving-a-router per our conversation offline.

2022-10-12 13:16 UTC, Chr1st0ph3rTurn3r commented on docs/config_wan_assurance.md
> +- [Features](wan_telemetry_features.md)
I just tested this locally, and it seems to be working. I had a similar issue yesterday when adding different links - it would return a file not found error for no reason that I could find.

2022-10-12 17:06 UTC, MichaelBaj submitted a review, later dismissed

2022-10-12 17:56 UTC, agrawalkaushik submitted a review, later dismissed

2022-10-12 18:58 UTC, MichaelBaj approved these changes

2022-10-12 19:46 UTC, merged