WAN Assurance 3.6.1 and 3.6.2 release notes
128technology/docs pull request #452
Opened 2022-09-28 03:14 UTC by agrawalkaushik

2022-09-28 12:14 UTC, Chr1st0ph3rTurn3r requested changes

2022-09-28 12:14 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.6.md
> +  _**Resolution:**_ The control plane CPU utilization will exclude the data core usage sent to the MIST cloud.
```suggestion
  _**Resolution:**_ The control plane CPU utilization excludes the data core usage sent to the MIST cloud.
```

2022-09-28 12:14 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.6.md
> +When IDP is enabled on the router, the security events will be reported to the MIST cloud.
```suggestion
When IDP is enabled on the router, the security events are reported to the MIST cloud.
```

2022-09-28 16:09 UTC, salegria8 approved these changes

2022-09-29 12:11 UTC, Chr1st0ph3rTurn3r approved these changes

2022-09-29 12:48 UTC, MichaelBaj approved these changes

2022-09-29 20:44 UTC, merged