5.4.8 release notes
128technology/docs pull request #454
Opened 2022-10-05 15:16 UTC by Chr1st0ph3rTurn3r

2022-10-05 17:43 UTC, MichaelBaj submitted a review, later dismissed

2022-10-10 12:58 UTC, MichaelBaj approved these changes

2022-10-11 15:53 UTC, Bhautik requested changes

2022-10-11 15:53 UTC, Bhautik commented on docs/release_notes_128t_5.4.md
>  ## Release 5.4.8-7
Build number is 5.4.8-8

2022-10-11 15:53 UTC, Bhautik commented on docs/releases.table.js
>      url:'release_notes_128t_5.4#release-548-7',
build number 548-8

2022-10-11 15:53 UTC, Bhautik commented on docs/about_releases.mdx
> +| Release 5.4 | [5.4.4](release_notes_128t_5.4.md#release-544-9) | February 18, 2022 | [5.4.8](release_notes_128t_5.4.md#release-548-7) |
Date here should be October 11th

2022-10-11 16:41 UTC, Chr1st0ph3rTurn3r commented on docs/about_releases.mdx
> +| Release 5.4 | [5.4.4](release_notes_128t_5.4.md#release-544-9) | February 18, 2022 | [5.4.8](release_notes_128t_5.4.md#release-548-7) |
this date is the initial GA date, not the current release.

2022-10-11 17:39 UTC, Bhautik approved these changes

2022-10-11 17:40 UTC, Bhautik submitted a review, later dismissed

2022-10-11 17:44 UTC, MichaelBaj approved these changes

2022-10-11 18:52 UTC, MichaelBaj approved these changes

2022-10-11 21:22 UTC, merged