Adding info for Ports to be enabled on the Firewall
128technology/docs pull request #468
Opened 2022-10-31 21:03 UTC by Chr1st0ph3rTurn3r

2022-10-31 21:08 UTC, agrawalkaushik commented on docs/config_firewall_ports.md
> +| Service Type | Global 01 | Global 02 | Global 03 | Global 04 |
The Global 01, 02 etc doesn't apply here

2022-10-31 21:08 UTC, agrawalkaushik commented on docs/config_firewall_ports.md
> +| Service Type | Global 01 | Global 02 | Global 03 | Global 04 |
same here

2022-11-01 13:21 UTC, MichaelBaj requested changes
Please update and address Kaushik's comments.

2022-11-01 13:21 UTC, MichaelBaj commented on docs/config_firewall_ports.md
> +| Service Type | Global 01 | Global 02 | Global 03 | Global 04 |
Is the SSR only available in one region?

2022-11-01 14:54 UTC, agrawalkaushik commented on docs/config_firewall_ports.md
> +| Service Type | Global 01 | Global 02 | Global 03 | Global 04 |
@MichaelBaj this one says SSR to a conductor so I did not interpret this having anything to do with MIST. Hence the comment about removing the Global01, 02 etc as that's a MIST concept.

2022-11-01 15:00 UTC, MichaelBaj commented on docs/config_firewall_ports.md
> +| Service Type | Global 01 | Global 02 | Global 03 | Global 04 |
Thanks, I must need glasses. I thought this was for the Device to Mist table. You are 100% correct. Global <x> has no meaning here.

2022-11-01 18:28 UTC, MichaelBaj submitted a review, later dismissed

2022-11-01 19:33 UTC, agrawalkaushik submitted a review, later dismissed

2022-11-01 20:11 UTC, MichaelBaj approved these changes

2022-11-01 20:13 UTC, merged