creating release notes for 5.5.7, fixed some indents in the 5.5 relea…
128technology/docs pull request #473
Opened 2022-11-09 15:44 UTC by Chr1st0ph3rTurn3r

2022-11-13 13:24 UTC, MichaelBaj requested changes

2022-11-13 13:24 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-48357 CoreDump on Failover with DSCP Steering:** Resolved an issue where DSCP Steering sessions would fail to move a flow under certain circumstances and, when using DSCP value 0, crash.
CoreDump should be "process fault"

2022-11-13 13:24 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-48507 Vlan packets are generated without a valid vlan from the flow-move cache:** Resolved an issue where sessions could be modified incorrectly when vlan is present when session resiliency i
VLAN should be capitalized (Virtual Local Access Network)

2022-11-15 21:43 UTC, MichaelBaj approved these changes

2022-11-15 22:27 UTC, jeffmart-jnpr approved these changes

2022-11-15 22:28 UTC, MichaelBaj approved these changes

2022-11-15 22:51 UTC, merged