6.0.6 release notes
128technology/docs pull request #474
Opened 2022-11-09 19:20 UTC by Chr1st0ph3rTurn3r

2022-11-13 13:55 UTC, MichaelBaj requested changes

2022-11-13 13:55 UTC, MichaelBaj commented on docs/releases.table.js
> +    releaseDate: 'November 13, 2022',
Target date needs to be updated with actual.

2022-11-13 13:55 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +**Release Date:** November 13, 2022
To be updated with actual

2022-11-13 13:55 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-44957 Azure is not able to identify the asset-id of the depolyed conductor and router:** The Azure ID has been modified to a value that can be processed by Azure.
typo: deployed

2022-11-13 13:55 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-48427 BGP ignoring multihop ttl setting leading to invalid nexthop:** Resolved an issue where BGP may temporarily "forget" about the ttl value configured for a neighbor.
ttl should be capitalized (Time To Live)

2022-11-13 13:55 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-48507 Vlan packets are generated without a valid vlan from the flow-move cache:** Resolved an issue where sessions could be modified incorrectly when vlan is present when session resiliency i
VLAN should be capitalized

2022-11-25 12:25 UTC, ptimmons commented on docs/release_notes_128t_6.0.md
> +- **I95-47519 Add First Article of Inspection scan output to Tech Support Info:** Added the output of the FAI (first article of inspection) script to Tech Support Info.
FAI = first article inspection (no "of")

2022-12-01 20:58 UTC, MichaelBaj requested changes

2022-12-01 20:58 UTC, MichaelBaj commented on docs/releases.table.js
> +    url: 'release_notes_128t_6.0#release-607-6',
looks like you will need to rebase from master. These URLs should all have the prefix `/docs/` on them.

2022-12-01 20:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-47929 Missing BGP advertisement after deleting all sessions after an upgrade:** Resolved an issue where FRR BGP update suppress was not removing any pending withdrawls.
Simply remove `FRR` here.

2022-12-01 20:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-48343 Cannot complete Image-based installation if secondary disks are less than 2TB:** Resolved the issue so that image-based installation will complete correctly for systems containing drive
This statement seems contradictory. cannot complete when <2TB. Can complete when > 2TB

2022-12-01 20:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-48579 Application director does not handle overlapping prefixes correctly:** The IP tree has been updated and now handles overlapping prefixes correctly.
"IP tree"? Do you mean "[trie](https://en.wikipedia.org/wiki/Trie)"? I would double check on this.

2022-12-01 20:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-48581 No entry timestamp for s`how app-id cache`:** Additional timing information has been added to `show app-id cache`.
`s` is outside of backquote

2022-12-01 20:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +:::important
Can we call out which issue ID relates to this problem and/or call out the release(s) in which this issue is addressed?

2022-12-01 21:35 UTC, Chr1st0ph3rTurn3r commented on docs/releases.table.js
> +    url: 'release_notes_128t_6.0#release-607-6',
Not sure what you mean. The same file in `master` looks the same.

2022-12-02 13:34 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.0.md
> +- **I95-48579 Application director does not handle overlapping prefixes correctly:** The IP tree has been updated and now handles overlapping prefixes correctly.
James said it is technically a "radix tree", so I changed it to that.

2022-12-02 14:06 UTC, MichaelBaj submitted a review, later dismissed

2022-12-05 22:04 UTC, jeffmart-jnpr approved these changes

2022-12-05 22:08 UTC, MichaelBaj approved these changes

2022-12-05 22:09 UTC, merged