5.6.4 release notes
128technology/docs pull request #478
Opened 2022-11-16 14:09 UTC by Chr1st0ph3rTurn3r

2022-11-16 16:08 UTC, MichaelBaj approved these changes

2022-11-17 13:39 UTC, jeffmart-jnpr commented on docs/release_notes_128t_5.6.md
> +- **I95-48507 VLAN packets are generated without a valid VLAN from the flow-move cache:** Resolved an issue where sessions could be modified incorrectly when a VLAN is present and session resiliency
This fix actually went in 5.6.3, can this be moved to the 5.6.3 section?

2022-11-17 13:45 UTC, jeffmart-jnpr commented on docs/release_notes_128t_5.6.md
> +- **I95-48685 Infinite Proxying Between HA systems:** Updates made to prevent the recursive proxying that occurs between two HA systems when one of the upstream targets is unavailable.
Looks like for the 5.5 release notes this is documented different, this PR should align the definition of the jira for both releases to provide more information on how the customer could observe the issue.

2022-11-17 13:45 UTC, jeffmart-jnpr requested changes
Please update based on individual comments

2022-11-17 14:54 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.6.md
> +- **I95-48685 Infinite Proxying Between HA systems:** Updates made to prevent the recursive proxying that occurs between two HA systems when one of the upstream targets is unavailable.
corrected.

2022-11-17 14:54 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.6.md
> +- **I95-48507 VLAN packets are generated without a valid VLAN from the flow-move cache:** Resolved an issue where sessions could be modified incorrectly when a VLAN is present and session resiliency
moved

2022-11-18 13:49 UTC, MichaelBaj approved these changes

2022-11-18 22:57 UTC, jeffmart-jnpr approved these changes

2022-11-18 22:59 UTC, merged