Conductor installation guide
128technology/docs pull request #484
Opened 2022-11-30 17:58 UTC by Chr1st0ph3rTurn3r

2022-12-01 01:24 UTC, MichaelBaj requested changes

2022-12-01 01:24 UTC, MichaelBaj commented on docs/conductor_conversion.md
> +To stop the SSR, follow the steps shown in the
This section would be a great place to leverage the component merging example I provided https://github.com/128technology/docs/pull/485/files

2022-12-01 01:24 UTC, MichaelBaj commented on docs/conductor_conversion.md
> +   **Result:** The service is listed as _Active (running)_.<br/>If the service is listed as _Inactive_, run the `sudo systemctl start 128T` command. This may take several minutes to fully launch the
I have another comment on this list item. There shouldn't be a case where 128T is not running by default.

2022-12-01 01:24 UTC, MichaelBaj commented on docs/single_conductor_config.md
> +- Non-SSR network configurations imported to the conductor; however these may need to be reviewed and revised to fit SSR conventions.
What does this mean? What type of configuration file is a non-SSR one that the conductor supports?

2022-12-01 01:24 UTC, MichaelBaj commented on docs/single_conductor_config.md
> +## Initial Manual Configuration
This section seems out of place.

2022-12-01 01:24 UTC, MichaelBaj commented on docs/conductor_upgrade.md
> +Your SSR conductor must have internet access to download the latest software packages; for deployments where the SSR does not have internet access, you can use the SSR conductor as a repository (or p
This statement "SSR conductor as a repository (or proxy) to retrieve software images" needs to be reworded as this document is for the conductor.
There is an offline upgrade procedure that Steve Voto has documented. That should be its own complete guide. Please reach out to him as there are customers who need to do this in air-gapped networks.

2022-12-01 01:24 UTC, MichaelBaj commented on docs/conductor_upgrade.md
> +Use this procedure to upgrade the conductor from a linux shell.
I might add the comment:
While the linux shell is available for upgrading the conductor, it is advised to use the GUI. Upgrading through the interactive installer should be used in environments where a GUI is not otherwise accessible.

2022-12-01 01:24 UTC, MichaelBaj commented on docs/conductor_upgrade.md
> +   If you are running an older version of the Installer (prior to version 2.7.0), it is strongly recommended that you first upgrade to the latest version of the Installer. If the upgrade is not possi
I debate whether this section is still needed. 2.7.0 is an old version of the installer. It is possible that some instances are running older versions. I hope not.

2022-12-01 01:24 UTC, MichaelBaj commented on docs/ha_conductor_install.md
> +This process covers the installation of two HA Conductor Nodes, and assumes you have already created a bootable device, either a USB or CD/DVD/Blueray disk. Instructions for downloading and creating
Same as my other comment regarding DVD/Bluray

2022-12-01 01:24 UTC, MichaelBaj commented on docs/ha_conductor_install.md
> +2. For SSR routers, you will be prompted for the IP address(es) of your conductor(s). If you have conductors, enter the administrative addresses and the node will retrieve the configuration from the
"For SSR routers" is not relevant for a conductor upgrade guide. In general this section needs to be reworded since this guide is specifically targeted towards HA installation.

2022-12-01 01:24 UTC, MichaelBaj commented on docs/ha_conductor_install.md
> +- **1st HA Node:** This router/conductor is the first node of a high availability pair. You will be prompted to provide the local IP address for this node. The 2nd HA node will contact this node at t
This "conductor"

2022-12-01 01:24 UTC, MichaelBaj commented on docs/ha_conductor_install.md
> +- **2nd HA Node:** This router/conductor is the second node of a high availability pair, where the first node has been initialized. You will be prompted to provide the 1st Node IP address for this 2n
This "conductor"

2022-12-01 01:24 UTC, MichaelBaj commented on docs/ha_conductor_install.md
> +  :::note
This note should also be relevant for a conductor. Simply state "A reboot will be necessary"

2022-12-01 14:32 UTC, Chr1st0ph3rTurn3r commented on docs/single_conductor_config.md
> +- Non-SSR network configurations imported to the conductor; however these may need to be reviewed and revised to fit SSR conventions.
By this I mean a situation where the SSR is being deployed as a replacement for existing network hardware/software. Rather than reconstructing the network config manually, the network config is exported and saved to another location, and then imported to the Conductor.

2022-12-01 14:39 UTC, Chr1st0ph3rTurn3r commented on docs/single_conductor_config.md
> +## Initial Manual Configuration
You are the second person to say that and I guess I don't understand why a user wouldn't want or need to know how to manually make configuration changes on the Conductor? In the 128T training after installing the conductor, the students are instructed on how to manually configure a simple network so that when the routers are onboarded, they receive a working config. I think that is important.

2022-12-01 14:47 UTC, Chr1st0ph3rTurn3r commented on docs/conductor_upgrade.md
> +Your SSR conductor must have internet access to download the latest software packages; for deployments where the SSR does not have internet access, you can use the SSR conductor as a repository (or p
I can see a need to re-word this to call out the Router, but I thought the routers always got the software images/upgrades from their conductors? If it is a conductor managed deployment, isn't that one of the purposes of the conductor?

2022-12-01 15:13 UTC, Chr1st0ph3rTurn3r commented on docs/ha_conductor_install.md
> +  :::note
done

2022-12-01 15:13 UTC, Chr1st0ph3rTurn3r commented on docs/ha_conductor_install.md
> +- **1st HA Node:** This router/conductor is the first node of a high availability pair. You will be prompted to provide the local IP address for this node. The 2nd HA node will contact this node at t
done

2022-12-01 15:13 UTC, Chr1st0ph3rTurn3r commented on docs/ha_conductor_install.md
> +2. For SSR routers, you will be prompted for the IP address(es) of your conductor(s). If you have conductors, enter the administrative addresses and the node will retrieve the configuration from the
done

2022-12-01 15:13 UTC, Chr1st0ph3rTurn3r commented on docs/ha_conductor_install.md
> +This process covers the installation of two HA Conductor Nodes, and assumes you have already created a bootable device, either a USB or CD/DVD/Blueray disk. Instructions for downloading and creating
done

2022-12-01 15:13 UTC, Chr1st0ph3rTurn3r commented on docs/conductor_upgrade.md
> +Use this procedure to upgrade the conductor from a linux shell.
revised

2022-12-01 15:14 UTC, Chr1st0ph3rTurn3r commented on docs/conductor_conversion.md
> +   **Result:** The service is listed as _Active (running)_.<br/>If the service is listed as _Inactive_, run the `sudo systemctl start 128T` command. This may take several minutes to fully launch the
done

2022-12-01 15:14 UTC, Chr1st0ph3rTurn3r commented on docs/conductor_conversion.md
> +An SSR device (SSR1xx or SSR 1xxx) shipped with SSR 5.4.x Routing software may be reinitialized as a conductor for use in an existing network. The conductor can be used with or without Cloud Telemetr
fixed

2022-12-01 15:15 UTC, Chr1st0ph3rTurn3r commented on docs/single_conductor_install.md
> +  If the service is listed as _Inactive_, run the `sudo systemctl start 128T` command. This may take several minutes to fully launch the service.
revised

2022-12-01 15:15 UTC, Chr1st0ph3rTurn3r commented on docs/single_conductor_install.md
> +This process assumes you have already created a bootable device, either a USB or CD/DVD/Blueray disk. Instructions for downloading and creating a bootable device are available in [Downloading an SSR
removed

2022-12-01 22:03 UTC, MichaelBaj requested changes

2022-12-01 22:03 UTC, MichaelBaj commented on docs/ha_conductor_install.md
> +- **1st HA Node:** This onductor is the first node of a high availability pair. You will be prompted to provide the local IP address for this node. The 2nd HA node will contact this node at the addre
typo: conductor

2022-12-02 15:59 UTC, MichaelBaj approved these changes

2022-12-02 16:00 UTC, merged