Wireguard 2.1.2 release notes
128technology/docs pull request #488
Opened 2022-12-06 03:34 UTC by agrawalkaushik

2022-12-06 14:11 UTC, Chr1st0ph3rTurn3r requested changes

2022-12-06 14:11 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_wireguard.md
> +  _**Resolution:**_ The plugin will validate for the missing configuration and will also prevent failures on one router to impact other routes config.
This isn't clear to me. 
"...prevent failures on one router *that may impact other configured routes*"?
"...that impact the configuration of other routers"?

2022-12-09 15:19 UTC, MichaelBaj approved these changes

2022-12-09 19:26 UTC, jeffmart-jnpr approved these changes

2022-12-09 19:26 UTC, merged