adding SSR onboarding topic
128technology/docs pull request #489
Opened 2022-12-06 19:30 UTC by Chr1st0ph3rTurn3r

2022-12-08 14:30 UTC, MichaelBaj requested changes

2022-12-08 14:30 UTC, MichaelBaj commented on docs/onboard_ssr_to_conductor.md
> +<!--- It's not clear to me what to expect for the asset id value from these SSR devices after Mist points them to conductor (is it the serial number, MAC address, or a UUID on a label on the box?) bu
For SSR Juniper-branded devices - the focus of this guide, it will be a serial number burned into EEPROM.

2022-12-08 14:30 UTC, MichaelBaj commented on docs/onboard_ssr_to_conductor.md
> +<!---- remove the info below, verify it's use in Telemetry
Please add steps to this guide up to verifying a successful onboarding to the conductor.

2022-12-09 18:30 UTC, agrawalkaushik commented on docs/onboard_ssr_to_conductor.md
> +title: Onboard an SSR Device to a Conductor
I suspect this will be confusing - unless the intention is to position this as the primary way of onboarding to the conductor. Maybe it should be called `ZTP an SSR device to Conductor` or something along those lines? I'm on the fence and see value either ways.

2022-12-09 18:31 UTC, agrawalkaushik commented on docs/onboard_ssr_to_conductor.md
> +The steps in this section describe the process of onboarding an SSR device (SSR1x0/1x00) to a Conductor using Mist, but without Cloud Telemetry (WAN Assurance Telemetry) integration. The steps are si
`onboarding an SSR device` -> `onboarding a Juniper branded SSR device`?

2022-12-09 18:32 UTC, agrawalkaushik commented on docs/onboard_ssr_to_conductor.md
> +The steps in this section describe the process of onboarding an SSR device (SSR1x0/1x00) to a Conductor using Mist, but without Cloud Telemetry (WAN Assurance Telemetry) integration. The steps are si
`but without Cloud Telemetry (WAN Assurance Telemetry) integration.` this bit is confusing and out-of-place. I guess what is this trying to warn against?

2022-12-09 18:33 UTC, agrawalkaushik commented on docs/onboard_ssr_to_conductor.md
> +The steps in this section describe the process of onboarding an SSR device (SSR1x0/1x00) to a Conductor using Mist, but without Cloud Telemetry (WAN Assurance Telemetry) integration. The steps are si
@Chr1st0ph3rTurn3r I'd like to think through re-wording this entire paragraph. It comes across as too many "caveats" about its not this but its not that etc ... I find it confusing.

2022-12-12 14:47 UTC, Chr1st0ph3rTurn3r commented on sidebars.js
> +      "bcp_conductor_deployment",
working on that overall process in a different branch - I appreciate the pointer. I'll make sure I capture that.

2022-12-12 17:29 UTC, Chr1st0ph3rTurn3r commented on docs/onboard_ssr_to_conductor.md
> +The steps in this section describe the process of onboarding an SSR device (SSR1x0/1x00) to a Conductor using Mist, but without Cloud Telemetry (WAN Assurance Telemetry) integration. The steps are si
Added

2022-12-12 17:29 UTC, Chr1st0ph3rTurn3r commented on docs/onboard_ssr_to_conductor.md
> +<!--- It's not clear to me what to expect for the asset id value from these SSR devices after Mist points them to conductor (is it the serial number, MAC address, or a UUID on a label on the box?) bu
got it thank you

2022-12-12 17:30 UTC, Chr1st0ph3rTurn3r commented on docs/onboard_ssr_to_conductor.md
> +<!---- remove the info below, verify it's use in Telemetry
done

2022-12-12 17:33 UTC, Chr1st0ph3rTurn3r commented on docs/onboard_ssr_to_conductor.md
> +The steps in this section describe the process of onboarding an SSR device (SSR1x0/1x00) to a Conductor using Mist, but without Cloud Telemetry (WAN Assurance Telemetry) integration. The steps are si
rewritten

2022-12-12 20:02 UTC, MichaelBaj approved these changes

2022-12-12 20:02 UTC, MichaelBaj commented on docs/intro_installation.md
> +The Image-Based Installation process supports Mist WAN Assurance; the Mist-managed WAN Assurance offering. Do not use the image-based installation for conductor-managed WAN Telemetry deployments.
Please keep track of all these admonitions that will later need to be removed once image-based support for conductor has been added.

2022-12-19 15:58 UTC, MichaelBaj approved these changes

2022-12-19 16:14 UTC, merged