Update configuration example for app-id v2 (SSR 5.0) for TLS
128technology/docs pull request #492
Opened 2022-12-13 22:25 UTC by robert-patterson

- in 5.0 and later, TLS no longer creates FIB entries, so hierarhical services and domain-name should be configured

2022-12-13 23:18 UTC, MichaelBaj commented on docs/concepts_appid.md
> +With App-Id v2 (SSR 5.0 and later), a FIB entry is no longer installed as DPI learns domain-name and IP address from TLS. Instead, heirarchical services and `domain-name` is used.
"App ID v2" is not how we've ever marketed this feature. I suggest rewording this to:

"Starting with versions SSR version 5.0, a FIB entry is no longer installed as part of DPI and instead learns domain-names and IP addresses from TLS and maps to hierarchical services using the `domain-name` field.

2022-12-14 15:50 UTC, MichaelBaj submitted a review, later dismissed

2022-12-14 16:49 UTC, avinashbhat80 submitted a review, later dismissed

2022-12-14 21:34 UTC, tjbresnahan commented on docs/concepts_appid.md
> +Starting with versions SSR version 5.0, a FIB entry is no longer installed as part of DPI and instead learns domain-names and IP addresses from TLS and maps to hierarchical services using the `domain
Superfluous `versions` here
```
Starting with SSR version 5.0, ...
```

2022-12-14 21:35 UTC, tjbresnahan commented on docs/concepts_appid.md
> +            description           "www.example.com website"
This should be something else, like `Catch-All Internet` or something

2022-12-16 14:04 UTC, Chr1st0ph3rTurn3r requested changes

2022-12-16 14:04 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_appid.md
> +Starting with versions SSR version 5.0, a FIB entry is no longer installed as part of DPI and instead learns domain-names and IP addresses from TLS and maps to hierarchical services using the `domain
Starting with SSR version 5.0, a FIB entry is no longer installed as part of DPI. Instead, domain-names and IP addresses are learned from TLS and mapped to hierarchical services using the `domain-name` field.

2022-12-16 16:10 UTC, Chr1st0ph3rTurn3r approved these changes

2022-12-16 16:23 UTC, merged