5.6.5 release notes
128technology/docs pull request #494
Opened 2022-12-22 15:03 UTC by Chr1st0ph3rTurn3r

2022-12-22 18:30 UTC, MichaelBaj requested changes

2022-12-22 18:30 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-48163 Only services with load-balanced paths are shown in "show services":** Resolved an issue where services without load-balanced paths weremissing from show services output.
instead of quoting show services, our convention is to use back ticks to indicate a command.

2022-12-27 21:42 UTC, Bhautik commented on docs/release_notes_128t_5.6.md
> +## Release 5.6.5-4
The release which will go out tomorrow is 5.6.5-5

2022-12-28 14:15 UTC, MichaelBaj approved these changes

2022-12-28 14:27 UTC, Bhautik approved these changes

2022-12-28 15:38 UTC, merged