Installer 317 release notes
128technology/docs pull request #497
Opened 2022-12-28 21:39 UTC by Chr1st0ph3rTurn3r

2022-12-28 21:42 UTC, MichaelBaj submitted a review, later dismissed

2022-12-28 21:44 UTC, jeffmart-jnpr commented on docs/release_notes_128t_installer_3.1.md
> +- **IN-508 Prompt user to disable salt-minion:** When the installer is being run manually, the installer now will alert the user that the `salt-minion` is active and ask whether the `salt-minion` sho
@mja9444 is it true that we give the option to disable or not during a manual install?

2022-12-29 13:19 UTC, mja9444 commented on docs/release_notes_128t_installer_3.1.md
> +- **IN-508 Prompt user to disable salt-minion:** When the installer is being run manually, the installer now will alert the user that the `salt-minion` is active and ask whether the `salt-minion` sho
Correct - we present the option to the user

2022-12-29 13:20 UTC, mja9444 approved these changes

2022-12-29 13:37 UTC, jeffmart-jnpr requested changes
While this is not part of the release notes, the section under:
https://docs.128technology.com/docs/intro_upgrade_considerations

Should be updated to say to upgrade to the 3.1.7 installer. This section say to update to 3.1.0 which is missing many fixes.

2022-12-29 13:59 UTC, MichaelBaj approved these changes

2022-12-29 14:28 UTC, jeffmart-jnpr approved these changes

2022-12-29 14:31 UTC, merged