creating release notes
128technology/docs pull request #506
Opened 2023-01-11 21:32 UTC by Chr1st0ph3rTurn3r

2023-01-11 23:00 UTC, MichaelBaj requested changes

2023-01-11 23:00 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **The following internally discovered vulnerabilities have been resolved:** I95-48447, I95-48464.
I believe the way these are written may cause more suspicion. My suggestions:
- **I95-48447 JWTs signing does not meet stringent security standards** Changed how JWTs are signed to increase security posture 
- **I95-48464 Addressed latest CVEs.**

2023-01-12 14:53 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.6.md
> +- **I95-49263 BGP for VRF failing with missing modules:** Resolved an issue where some missing modules were not detected, causing a retry/fail loop.
Tyler's perspective is that this was a fix for a feature that was just added to 5.6.6, so no customer would ever have seen it. Looking for info on that feature now...

2023-01-12 14:53 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.6.md
> +- **The following internally discovered vulnerabilities have been resolved:** I95-48447, I95-48464.
done

2023-01-12 15:20 UTC, MichaelBaj submitted a review, later dismissed

2023-01-18 21:27 UTC, MichaelBaj approved these changes

2023-01-18 21:29 UTC, merged