Release Notes for 5.5.8
128technology/docs pull request #510
Opened 2023-01-24 16:53 UTC by Chr1st0ph3rTurn3r

2023-01-24 20:45 UTC, MichaelBaj requested changes

2023-01-25 16:44 UTC, MichaelBaj approved these changes

2023-02-01 16:44 UTC, MichaelBaj commented
Add the caveat to 5.6.6 to this PR.

2023-02-01 16:44 UTC, MichaelBaj requested changes

2023-02-01 16:44 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-49724 "Resource not found" error in the configuration preview of the Quickstart:** Removed a typo in the API Route for `/config/upload`.
This should be removed for 5.5.8.

2023-02-01 19:27 UTC, MichaelBaj requested changes

2023-02-01 19:27 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-49724 "Resource not found" error in the configuration preview of the Quickstart:** Removed a typo in the API Route for `/config/upload`.
This needs to be removed

2023-02-01 19:51 UTC, MichaelBaj approved these changes

2023-02-01 19:52 UTC, jeffmart-jnpr approved these changes

2023-02-01 19:52 UTC, merged