Remove outdated HA sync, reuse HA Sync Plugin info
128technology/docs pull request #519
Opened 2023-02-14 21:25 UTC by Chr1st0ph3rTurn3r

2023-02-14 21:30 UTC, MichaelBaj approved these changes

2023-02-14 23:25 UTC, tcarroll25 submitted a review, later dismissed

2023-02-14 23:29 UTC, agrawalkaushik commented on docs/plugin_ha_sync_redundancy.mdx
> +---
not sure what the `.mdx` format is for but this plugin is no longer necessary so please feel free to deprecate and remove all the documentation related to this plugin.

2023-02-15 00:37 UTC, MichaelBaj commented on docs/plugin_ha_sync_redundancy.mdx
> +---
`.mdx` file is a markdown file that support javascript. Note the use of the `import` directives in the file.
Kaushik, I think I am missing something significant here. Is the plugin no longer a plugin and now there is native support for HA config without the use of the plugin? Why would the plugin no longer be necessary?

2023-02-15 21:03 UTC, agrawalkaushik commented on docs/plugin_ha_sync_redundancy.mdx
> +---
If my memory serves me right the plugin was used before we had team interfaces. I talked a bit more with Lane and it looks like there are some other alternative use cases at bunch of customers. So please disregard my comment above the plugin not being necessary.

2023-02-15 21:13 UTC, agrawalkaushik commented on docs/plugin_ha_sync_redundancy.mdx
> +<HASyncTroubleshooting/>
```suggestion
<HASyncTroubleshoot/>
```

Without the change, the troubleshooting section is not getting rendered.

2023-02-15 21:14 UTC, agrawalkaushik commented on docs/plugin_ha_sync_redundancy.mdx
> +<HASyncTroubleshooting/>
side note - just like we catch broken links, I wonder if docusaurus will let us catch this!

2023-02-15 21:15 UTC, agrawalkaushik requested changes
lgtm!

Just need to fix the troubleshooting link!

2023-02-15 21:21 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ha_sync_redundancy.mdx
> +<HASyncTroubleshooting/>
Nice catch Kaushik. Docusaurus did not catch that. Nor did I in my local build.

2023-02-15 21:34 UTC, MichaelBaj approved these changes

2023-02-16 14:15 UTC, agrawalkaushik commented on docs/plugin_ha_sync_redundancy.mdx
> +<HASyncTroubleshooting/>
I usually spin up a local build to review doc changes... My click on the Troubleshooting page didn't work 😄

2023-02-16 14:19 UTC, merged