adding traceroute info
128technology/docs pull request #521
Opened 2023-02-22 16:37 UTC by Chr1st0ph3rTurn3r

2023-02-22 17:57 UTC, MichaelBaj requested changes

2023-02-22 17:57 UTC, MichaelBaj commented on docs/ts_traceroute.md
> +
I thought we had a precedent for indicating the version of software a feature was introduced, but I couldn't find any consistency in our docs.
Please add a section at the beginning of this doc indicating the version of software where this was first introduced.

2023-02-22 19:38 UTC, dmontgomeryJuniper commented on docs/config_reference_guide.md
> +| destination-ip | IP address | The destination address for the traceroute command |
destination-ip is now a positional rather than keyword argument

2023-02-22 19:39 UTC, dmontgomeryJuniper commented on docs/ts_traceroute.md
> +Network administrators frequently make use of Linux traceroute as a compliment to ping when isolating intermediate connectivity issues and troubleshooting MTU, and TTL issues. Traceroute provides inf
*complement

2023-02-22 19:41 UTC, dmontgomeryJuniper commented on docs/ts_traceroute.md
> +For service-traceroute and peer-traceroute, ICMP echo requests are the default discovery packets. To support instances where ICMP replies are disabled at the destination or disallowed by firewall rul
we're only doing UDP

2023-02-22 21:39 UTC, MichaelBaj approved these changes

2023-02-23 18:04 UTC, dmontgomeryJuniper commented on docs/config_reference_guide.md
> +authority > router > traceroute
just hit me: this... isn't a config element.  is this the right guide?

2023-02-24 14:00 UTC, MichaelBaj approved these changes

2023-02-24 15:18 UTC, smcculley-juniper approved these changes

2023-02-24 15:30 UTC, dmontgomeryJuniper commented on docs/cli_reference.md
> +| peer-name | The name of the SVR peer to probe |
(default is empty)

2023-02-24 15:31 UTC, dmontgomeryJuniper commented on docs/ts_traceroute.md
> +| peer-name | string | The name of the SVR peer to probe |
add (default is empty)

2023-02-24 16:09 UTC, dmontgomeryJuniper approved these changes

2023-02-28 16:26 UTC, Chr1st0ph3rTurn3r commented
Closing as it has been merged into the 6.1.x branch.

2023-02-28 16:26 UTC, closed without merging