Release notes for ICMP reachability plugin
128technology/docs pull request #524
Opened 2023-02-28 03:52 UTC by agrawalkaushik

DOCS-348 #time 20m

2023-02-28 13:36 UTC, MichaelBaj approved these changes

2023-02-28 14:17 UTC, Chr1st0ph3rTurn3r requested changes

2023-02-28 14:17 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_icmp_reachability_detection.md
> +- **PLUGIN-1480** Large configuration was causing plugin config generation to fail
need period after fail

2023-02-28 14:17 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_icmp_reachability_detection.md
> +  _**Resolution:**_ The config generation logic for the plugin will handle config with long lines correctly
need period after correctly

2023-02-28 15:49 UTC, MichaelBaj approved these changes

2023-02-28 15:51 UTC, Chr1st0ph3rTurn3r approved these changes

2023-03-01 15:18 UTC, Bhautik approved these changes

2023-03-01 17:08 UTC, merged