Add release notes for WAN assurance 3.7.0
128technology/docs pull request #525
Opened 2023-02-28 04:47 UTC by agrawalkaushik

DOCS-349 #time 1h

2023-02-28 13:36 UTC, MichaelBaj requested changes

2023-02-28 13:36 UTC, MichaelBaj commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +  _**Resolution:**_ The mist-agent will ensure that the SPU data is always present in the oc-stats.
SPU should be CPU

2023-02-28 14:14 UTC, Chr1st0ph3rTurn3r requested changes

2023-02-28 14:14 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +  _**Resolution:**_ Upon establishing a new connection to the MIST cloud, the device will immediately send all relevant telemetry information to provide most up-to-date information
period after information.

2023-02-28 14:14 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +  _**Resolution:**_ The cloud-intel agent will process incoming events real time and not cache the events for too long avoid any delays and drops.
_**Resolution:**_ The cloud-intel agent will process incoming events **in** real time and not cache the events for too long **to** avoid any delays and drops.

2023-02-28 14:14 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +- **WAN-1632 SSR devices have been sending bytes data as zero, causing large dips **
remove space after "dips" - the issue title is not showing as bold.

2023-02-28 15:13 UTC, gregschrock commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +- **WAN-1507 The cloud triggered streaming PCAPs do not always report data**
I don't think this was a customer visible issue. But I'd describe the bug as `Cloud triggered streaming PCAPs when the agent restarts`.

2023-02-28 15:13 UTC, gregschrock commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +  _**Resolution:**_ The directory used to store the PCAP command related information will be persisted appropriately across agent and system level restarts.
PCAPs do not and will not persist across system or 128T restarts. There would be unknown data gaps which we could not indicate. We can, however, continue PCAP reporting across an agent restart with a reasonable expectation that data will not be lost. This is fixing a bug in that functionality.

2023-03-02 19:17 UTC, agrawalkaushik commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +  _**Resolution:**_ The directory used to store the PCAP command related information will be persisted appropriately across agent and system level restarts.
I think that gets too technical for external consumption. I'd probably err on the side of caution and remove this from the list in that case.

2023-03-02 19:56 UTC, gregschrock commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +  _**Resolution:**_ The directory used to store the PCAP command related information will be persisted appropriately across agent and system level restarts.
Right, I'm not saying we should put that in here. I just don't think we should say it persists across system level restarts because it won't. I'm suggesting some more conservative wording is all.

2023-03-03 17:30 UTC, Chr1st0ph3rTurn3r approved these changes

2023-03-03 17:37 UTC, gregschrock approved these changes

2023-03-03 19:28 UTC, MichaelBaj approved these changes

2023-03-03 19:45 UTC, merged