Stuck flow recovery
128technology/docs pull request #526
Opened 2023-02-28 20:07 UTC by Chr1st0ph3rTurn3r

2023-02-28 20:25 UTC, MichaelBaj requested changes

2023-02-28 20:25 UTC, MichaelBaj commented on docs/config_session_recovery.md
> +In a Spoke and Hub topology, forward and reverse flows are exchanged between devices. However, in a case where there is a service interruption on a hub and the session no longer exists, the hub can n
While it is true that most of our deployments are hub-and-spoke, this feature pertains to SVR, which would be for any topology that consists of two peering SSR routers running SVR.
I don't see this distinction as important. Looking for @ayungelson to comment.

2023-02-28 20:25 UTC, MichaelBaj commented on docs/config_session_recovery.md
> +In a Spoke and Hub topology, forward and reverse flows are exchanged between devices. However, in a case where there is a service interruption on a hub and the session no longer exists, the hub can n
"which often is flagged as a security issue" - This should be changed to "which may falsely indicate to that the SSR is listening and responding to wayports." (or something similar that doesn't immediate raise security concerns)

2023-02-28 20:25 UTC, MichaelBaj commented on docs/config_session_recovery.md
> +Because this feature uses a request/response mechanism, **all** SSR's must be upgraded before using/enabling this feature.
use :::important::: admonition.

2023-02-28 20:25 UTC, MichaelBaj commented on docs/config_session_recovery.md
> +Info coming
- [ ] todo

2023-02-28 20:25 UTC, MichaelBaj commented on docs/config_session_recovery.md
> +Info coming
- [ ] todo

2023-02-28 20:58 UTC, ayungelson commented on docs/config_reference_guide.md
> +
it's not just reverse, it's opposite... and it's not hub/spoke...
```
When enabled, the originating node will monitor activity on the opposite flow. If no activity is detected for the specified time, it will add an additional metadata attribute called `session-health-check` to the next packet. The `session-health-check` attribute is validated by the receiving node and if the flow on the other node does not exist, it will generate an `enable-metadata` message back to the originator.
```

2023-02-28 20:58 UTC, ayungelson commented on docs/config_session_recovery.md
> +In a Spoke and Hub topology, forward and reverse flows are exchanged between devices. However, in a case where there is a service interruption on a hub and the session no longer exists, the hub can n
Yes, it has nothing to do with hub/spoke, it just applies to SVR.

2023-02-28 20:58 UTC, ayungelson commented on docs/config_session_recovery.md
> +In a Spoke and Hub topology, forward and reverse flows are exchanged between devices. However, in a case where there is a service interruption on a hub and the session no longer exists, the hub can n
> "which often is flagged as a security issue" - This should be changed to "which may falsely indicate to that the SSR is listening and responding to wayports." (or something similar that doesn't immediate raise security concerns)

Yes - I completely agree - Mike's wording is much better.

2023-02-28 22:20 UTC, ayungelson commented
Looks good to me.

2023-03-06 15:52 UTC, MichaelBaj requested changes

2023-04-03 13:48 UTC, closed without merging