6.0.8 release notes
128technology/docs pull request #528
Opened 2023-03-03 16:22 UTC by Chr1st0ph3rTurn3r

2023-03-03 19:28 UTC, MichaelBaj requested changes

2023-03-03 19:28 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-49242 When HMAC is disabled, the automatic MSS adjustment calculation for `enforced-mss = automatic` may be wrong :** The Automatic MSS adjustment calculation has been corrected (expanded).
space after wrong and :

2023-03-03 19:28 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-49454 Error while creating a new Radius user from the GUI:** The create user API will now reject requests that specifies invalid input parameters.
"specifies invalid input" - not sure what this means.
should it instead be "... will now reject requests that have invalid input parameters"?

2023-03-03 19:28 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-49455 Cut and paste from `show flat` generates an error:** Resolved the issue that prevented editing the OSPF list.
incorrect Jira id. https://128technology.atlassian.net/browse/I95-49455 is for RTT stats.
correct jira id is https://128technology.atlassian.net/browse/I95-49655
Also, I believe the wording of this to be incorrect. 
cutting and subsequently pasting the output of `show flat` does not work for OSPF

2023-03-06 15:43 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.0.md
> +- **I95-48869 Failed to identify default IDP policy when it appears to be the first access policy defined in a service:** The default IDP policy is now handled as `IDP off` in all cases.
I had gotten this info from Sunan, but I like your wording better.

2023-03-06 15:49 UTC, MichaelBaj approved these changes

2023-03-07 18:13 UTC, merged