5.6.7 release notes
128technology/docs pull request #530
Opened 2023-03-07 16:34 UTC by Chr1st0ph3rTurn3r

2023-03-07 17:09 UTC, MichaelBaj requested changes

2023-03-07 17:09 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-49655 Cutting and pasting the output of `show flat` does not work for OSPF:** Resolved the issue that prevented editing the OSPF list.
This does not match what was ratified for the 6.0.8 release notes. Please check this and others.

2023-03-07 19:24 UTC, Chr1st0ph3rTurn3r commented on docs/about_releases.mdx
> +| Release 5.6 | [5.6.7](release_notes_128t_5.6.md#release-567-2) |
Dragan requested that I wait until 3/24 to identify this release as GA, so I'm holding off until then.

2023-03-07 19:32 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.6.md
> +- **I95-49655 Cutting and pasting the output of `show flat` does not work for OSPF:** Resolved the issue that prevented editing the OSPF list.
That is what you suggested in the 608 release notes review. It originally read "Cut and paste from `show flat` generates an error:"

2023-03-07 19:56 UTC, Chr1st0ph3rTurn3r commented on docs/releases.table.js
> +    endOfMaintenance: 'February 20, 2023',
Done

2023-03-07 19:56 UTC, Chr1st0ph3rTurn3r commented on docs/about_releases.mdx
> +| Release 5.6 | [5.6.7](release_notes_128t_5.6.md#release-567-2) |
done

2023-03-08 15:58 UTC, MichaelBaj approved these changes

2023-03-08 15:58 UTC, MichaelBaj commented on docs/cli_reference.md
> +## `send command sync`
Please check with @tcarroll25 for when this feature was added so we can include that information in the docs.

2023-03-08 16:56 UTC, MichaelBaj submitted a review, later dismissed

2023-03-13 20:46 UTC, MichaelBaj approved these changes

2023-03-14 00:24 UTC, tcarroll25 commented on docs/cli_reference.md
> +## `send command sync`
Sorry I was out on vacation last week. @Chr1st0ph3rTurn3r this feature was added in 5.6.7 and 6.0.8. It will be present in 5.6.7+, 6.0.8+ and 6.1.0+

2023-03-15 13:15 UTC, MichaelBaj approved these changes

2023-03-15 15:49 UTC, MichaelBaj requested changes

2023-03-15 15:49 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-49633 Static assignment config is in multiple places locations:** This is as designed, however cross-validation has been added to prevent adding different IP addresses.
typo: multiple places locations

Suggested rewording:
- **I95-49633 Validation not strict for static assignment within DHCP server configuration:** Configuration for static addresses within DHCP server exists in multiple locations per design, however cross-validation has been added to prevent adding different IP addresses.

2023-03-15 15:57 UTC, MichaelBaj requested changes

2023-03-15 15:57 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-49633 Validation not strict for static assignment within DHCP server configuration:** Configuration for static addresses within DHCP server exists in multiple locations per design. Cross-vali
I think you meant "configured AND assigned"

2023-03-15 16:01 UTC, MichaelBaj submitted a review, later dismissed

2023-03-16 15:50 UTC, Bhautik requested changes

2023-03-16 15:51 UTC, jeffmart-jnpr approved these changes

2023-03-16 15:57 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.6.md
> +- **The following CVE's have been identified and addressed in this release:** I95-48445, I95-48643, I95-48859, I95-48907, I95-47079, I95-49445, I95-49745, I95-49746, I95-49747, I95-49748.
fixed

2023-03-16 16:02 UTC, jeffmart-jnpr commented on docs/release_notes_128t_5.6.md
> +- **I95-49633 Validation not strict for static assignment within DHCP server configuration:** Configuration for static addresses within DHCP server exists in multiple locations per design. Cross-vali
this has been updated

2023-03-16 16:03 UTC, jeffmart-jnpr approved these changes

2023-03-16 16:17 UTC, merged