Ipsec client 3.5.0 release notes
128technology/docs pull request #532
Opened 2023-03-14 19:24 UTC by BenMatase

2023-03-14 19:34 UTC, MichaelBaj commented on docs/plugin_ipsec_client.md
> +- **PLUGIN-1999** Tunnels failed to come up because of DNS not working at salt application time
"salt application time" has little meaning to customers. Is there a better way to frame this? Suggestion: "Tunnels failed to come up because of unresolvable DNS during startup"

2023-03-14 19:36 UTC, agrawalkaushik commented on docs/plugin_ipsec_client.md
> +- **PLUGIN-1906** Support DNS Proxy integration
This was a bug so can you move to the `Issues Fixed` section

2023-03-14 19:36 UTC, agrawalkaushik commented on docs/plugin_ipsec_client.md
> +- **PLUGIN-1999** Tunnels failed to come up because of DNS not working at salt application time
Also capture the documentation for https://128technology.atlassian.net/browse/PLUGIN-1782 in the Issues Fixed section?

2023-03-14 19:48 UTC, Chr1st0ph3rTurn3r requested changes

2023-03-14 19:48 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +Example output can be found [here](plugin_ipsec_client.md#pcli-enhancements).
`Example output can be found in the [PCLI Enhancements](#pcli-enhancements) section.`

2023-03-14 19:48 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +The plugin now supports `redundancy-enabled` [configuration option](plugin_ipsec_client.md#redundancy) which will ensure that tunnels are only being created by one node at a time. The default behavio
1. You don't have to provide the filename and heading when you link within the same document. So [configuration option] should link to  (#redundancy).
2. Reads better this way:
`The plugin now supports the `redundancy-enabled` [configuration option](#redundancy). This ensures that tunnels are being created by only one node at a time. The default behavior remains active-active.`

2023-03-14 19:48 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +The plugin now supports non-persisted metrics for tunnels. More details and examples can be found [here](plugin_ipsec_client.md#metrics).
Always use the name of the section that you are linking, so the user knows where they are supposed to be going. 
`examples can be found in the [Metrics section.](#metrics).`

2023-03-16 12:52 UTC, MichaelBaj submitted a review, later dismissed

2023-03-16 14:36 UTC, Chr1st0ph3rTurn3r approved these changes

2023-03-17 16:57 UTC, agrawalkaushik commented on docs/plugin_ipsec_client.md
> +**Router Version** 128T-ipsec-2.3.0-3
@BenMatase can you update this version to match the latest and greatest changes

2023-03-17 17:47 UTC, Chr1st0ph3rTurn3r approved these changes

2023-03-17 19:01 UTC, merged