6.1.x documentation
128technology/docs pull request #538
Opened 2023-03-24 19:34 UTC by Chr1st0ph3rTurn3r

2023-03-27 14:40 UTC, MichaelBaj requested changes

2023-03-27 14:40 UTC, MichaelBaj commented on docs/cli_reference.md
> +| [`show idp platform`](#show-idp-platform) | Show IDP platform data. |
inconsistent use of periods at the end of description

2023-03-27 14:40 UTC, MichaelBaj commented on docs/ts_traceroute.md
> +Traceroute is implemented as a troubleshooting tool, allowing you to debug  connectivity from point to point.
extra space after debug

2023-03-27 14:40 UTC, MichaelBaj commented on docs/ts_traceroute.md
> +- `peer traceroute`: Performs traceroute between two adjacent SSRs. Useful for diagnosing peering issues.
Check with @jacobdionne. I thought that 6.1.0 was not going to have peer traceroute and that was coming in 6.1.3

2023-03-27 14:40 UTC, MichaelBaj commented on docs/config_session_recovery.md
> +When SSR routers are peered, forward and reverse flows are exchanged between devices. However, in a case where there is a service interruption on one node and the session no longer exists, that node
Suggested rewording: "When SSR routers peer, forward and reverse flows are established between devices as traffic flows from client to server through SSR routers."

2023-03-27 14:40 UTC, MichaelBaj commented on docs/config_session_recovery.md
> +Because this feature uses a request/response mechanism, **all** SSR's using this feature must be upgraded.
Must be upgraded to a minimum of `6.1.0`

2023-03-30 16:58 UTC, MichaelBaj requested changes

2023-03-30 16:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-45220 Conductor local forwarding parameters not dynamic:** Resolved an issue when transitioning a conductor from standalone to HA the managed routers were not automatically connecting to the
heading "Conductor local forwarding parameters not dynamic" is an implementation detail.
suggested rewording:
"managed routers do not connect to newly added HA conductor"

2023-03-30 16:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-45348: Update salt master and minion to 3002.8:** When upgrading an HA pair to version **5.5.1**, please be aware of the following: While updating the conductors in an HA pair, the upgraded c
@migolnikov is this still relevant for 6.1?

2023-03-30 16:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-45348 Update salt master and minion to 3002.8:** This update resolves several CVE's and requires that the conductor must be running this release containing these fixes **before** upgrading a
@migolnikov I don't believe this is relevant from 6.1.0 and should be removed.

2023-03-30 16:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-45489 `ifcfg` custom options issues:** Resolved an issue where  interface ifcfg option changes were not being processed.
`ifcfg` custom options are not real-time configurable.
Also, there is an extra space after "where  "

2023-03-30 16:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-45643 User created users missing after upgrade:** Resolved an issue where the XML values true/false are also handled as 1/0.
**I95-45643 Users created missing after upgrade:** Resolved a config type conversion issue that caused users to disappear after upgrade"

2023-03-30 16:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-45882 Rare case where an invalid DHCP server configuration generated:** This issue has been resolved.
Please work with @ayungelson to clarify this issue. What was the actual configuration trigger for this issue? What was the result (in this case a crash - that needs to be specified).

2023-03-30 16:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-46230 Highway Crash:** Resolved an issue where uncaught exceptions were causing highway issues.
What was the trigger for the crash? How does a customer know if this will impact them?

2023-03-30 16:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-47362 Monitor Secure Communication Manager:** Implement a watchdog for the SSH tunnels maintained by SCM. If the watchdog detects a dead connection, it will:
Change heading to: "Internal process SSH tunnel watchdog"

2023-03-30 16:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> + - **i95-47750 DHCP client interface info not listed in "show dhcp v4 detail" pcli command output:** The software now expects redundant interfaces with a non-zero vlan to have the vlan at the end of
Capitalize 'I'

2023-03-30 16:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> + - **I95-49340 Crash when the unexpected input of tenant-prefixes with no source-addresses is committed:** Restricting the tenant-prefixes's source-addresses to a minimum of one has resolved this iss
Change description to:
Validation has been added to restrict the tenant-prefixes's source-addresses to a minimum of one.

2023-03-30 16:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-49925 Issue monitoring GRE IP:** The GRE tunnel manager now removes all sessions before adding new ones rather than modifying the existing sessions.
Change heading to
"GRE tunnel health-check not migrating sessions when path is down"

2023-03-30 16:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-50260 `show idp events` does not respect the `router` or `node` arguments:** Resolved an issue where `show idp events` did not respect the `router` and `node` arguments and always executed ag
change "respect" to "honor"

2023-03-30 16:58 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-50331 System fails to synchronize keys on startup:** The SSR now dynamically updates srsync IP host address from the non forwarding HA sync interfaces, and will fall back to the global.init h
I believe srsync should be `rsync`

2023-03-30 17:56 UTC, MichaelBaj requested changes

2023-03-30 17:56 UTC, MichaelBaj commented on docs/releases.table.js
> +    releaseDate: 'March 31, 2023',
April 7th (tentatively)

2023-03-30 17:56 UTC, MichaelBaj commented on docs/releases.table.js
> +    releaseDate: 'March 31, 2023',
Also, this will be a GA release, so it needs to be added to the GA release table.

2023-03-30 17:56 UTC, MichaelBaj commented on docs/about_releases.mdx
> +| Release 6.1 | [6.1.0](release_notes_128t_6.1.md#release-610-39) |
6.1 will be GA, not LA.

2023-03-30 17:56 UTC, MichaelBaj commented on docs/config_bgp.md
> +
introduced in table (6.1.0)

2023-03-31 13:34 UTC, MichaelBaj requested changes

2023-03-31 13:34 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-45882 Rare case where the derived interface is the same as ingress interface for DHCP server causing a crash:** The SSR code has been bolstered to verify the derived interface and ingress int
Perhaps it is just me, but I don't know what a "derived interface" is. How does a customer configure a derived interface?

2023-03-31 13:34 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-46230 portKey exceptions with invalid giid causing a highway crash:** PortKeys containing invalid giid of zero are now caught.
What is a port key from a customer's perspective?  (I don't know what a port key is myself) How would a customer find themselves in this situation?

2023-03-31 19:48 UTC, migolnikov approved these changes

2023-04-04 17:21 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-45348: Update salt master and minion to 3002.8:** When upgrading an HA pair to version **5.5.1**, please be aware of the following: While updating the conductors in an HA pair, the upgraded c
Removed from 6.1 release notes.

2023-04-04 17:21 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-45348 Update salt master and minion to 3002.8:** This update resolves several CVE's and requires that the conductor must be running this release containing these fixes **before** upgrading a
removed

2023-04-04 17:21 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **Plugin Upgrades:** If you are running with plugins, updates are required for some plugins **before** upgrading the conductor to SSR version 5.4.0 or higher. Please review the [Plugin Configuratio
Checked with Kaushik, and yes it is still relevant.

2023-04-04 17:22 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-42624 Upgrade Installer:** Before **upgrading to, or installing** version 5.4 and above, update the Installer to at least version 3.1.0. Failing to upgrade the installer may result in a rollb
Checked with Max and yes it is still relevant.

2023-04-04 17:22 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-42452 Conductor Upgrade Time:** Upgrades to version 5.4 and above can take up to 40 minutes due to the number of rpms being upgraded. Please plan accordingly.
found the correct id, and updated.

2023-04-04 17:23 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-43243/IN-460 Upgrade and Rollback:** Upgrading or rolling back a system (conductor peer or router) with the interactive installer `install128t`, that is managed by a conductor may result in t
Evan responded to this and it is still relevant.

2023-04-04 17:41 UTC, MichaelBaj requested changes

2023-04-04 17:41 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-50286 Node B reboot from Linux in High Availability config breaks routing:** Resolved an issue where a delay in the shutdown process caused a node to take over a VRRP interface, creating rout
"Node B reboot" should be "Rebooting a node of a HA pair from Linux breaks routing"

2023-04-05 17:43 UTC, MichaelBaj approved these changes

2023-04-12 14:54 UTC, MichaelBaj requested changes

2023-04-12 14:54 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-50445 i40e and ice devices reporting malicious descriptor detection events:** Resolved an issue where fragmented packet chains larger than 8 buffers were discarded causing a malicious descrip
The resultant behavior of this MDD condition is that the NIC stops forwarding packets for the affected queue.
Suggested rewording:
**I95-50445 i40e and ice devices enter malicious descriptor detection state, preventing forwarding of traffic:** Resolved an issue where fragmented packet chains larger than 8 buffers were discarded causing a malicious descriptor event.

2023-04-12 14:54 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-50554 Dynamically create symlinks to salt file roots:** Resolved an issue where it was necessary to restart 128T on the Conductor in order for the Conductor to recognize newly added repositor
@tcarroll25 how does this issue impact the customer? Should this be excluded from the release notes? The respective PR has 'n/a' in the release notes section.

2023-04-12 14:54 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-50574 Recurring issue with NodeA in a high availability setup:** Resolved a crash due to a race condition when `service ping icmp-request` is matched against a partially installed flow.
there is no "nodeA" in a HA setup.
50574 is the incorrect issue ID.
Not sure what this should be.

2023-04-13 21:00 UTC, MichaelBaj approved these changes

2023-04-14 19:00 UTC, MichaelBaj approved these changes

2023-04-14 20:54 UTC, merged