WAN Assurance plugin 3.7.1 release notes
128technology/docs pull request #541
Opened 2023-03-30 21:58 UTC by agrawalkaushik

DOCS-354 #time 20m

2023-03-30 22:04 UTC, BenMatase approved these changes

2023-03-30 22:14 UTC, MichaelBaj approved these changes

2023-03-31 12:20 UTC, gregschrock approved these changes

2023-03-31 13:32 UTC, Chr1st0ph3rTurn3r requested changes

2023-03-31 13:32 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +  _**Resolution:**_ Any service with RFC1918 address space will be tagged as custom app in the data that hub sends to MIST cloud.
_**Resolution:**_ Any service with RFC1918 address space will be tagged as a custom app in the data that the hub sends to the MIST cloud.

2023-03-31 13:32 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +- **WAN-1737 De-duplicate peer path down events**
- **WAN-1737 Prevent duplication of peer path down events**

2023-03-31 18:14 UTC, agrawalkaushik commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +  _**Resolution:**_ Any service with RFC1918 address space will be tagged as custom app in the data that hub sends to MIST cloud.
sorry having a hard time spotting the correction in your suggestion @Chr1st0ph3rTurn3r but I'll just take it as is 😄

2023-03-31 19:37 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +  _**Resolution:**_ Any service with RFC1918 address space will be tagged as custom app in the data that hub sends to MIST cloud.
No worries - just missing articles: ...**a** custom app  ...that **the** hub sends to **the** Mist cloud.

2023-04-01 02:18 UTC, merged