SSR 6.0.9 Release Notes
128technology/docs pull request #542
Opened 2023-04-01 11:19 UTC by MichaelBaj

2023-04-01 20:36 UTC, drcosic requested changes
I would not change version yet till we finish all the testing

2023-04-01 20:36 UTC, drcosic commented on docs/release_notes_128t_6.0.md
> +## Release 6.0.9-2
6.0.9-3 is current version

2023-04-01 20:36 UTC, drcosic commented on docs/about_releases.mdx
> +| Release 6.0 | [6.0.9](release_notes_128t_6.0.md#release-609-2) |
this probably needs to be link to -3

2023-04-03 12:41 UTC, Chr1st0ph3rTurn3r submitted a review, later dismissed

2023-04-03 17:15 UTC, Chr1st0ph3rTurn3r approved these changes

2023-04-03 20:35 UTC, drcosic approved these changes

2023-04-03 20:35 UTC, Chr1st0ph3rTurn3r approved these changes

2023-04-03 22:29 UTC, merged