Added information on how to leverage cloud-init to automate SSR deplo…
128technology/docs pull request #544
Opened 2023-04-10 01:38 UTC by laneshields

…yment and how to use NoCloud when cloud-init metadata service not provided by the hypervisor

2023-04-10 18:08 UTC, Chr1st0ph3rTurn3r requested changes

2023-04-10 18:08 UTC, Chr1st0ph3rTurn3r commented on docs/install_qcow2_deployment.md
> +This will case this device's salt-minion to attempt to connect to the Conductor at IP address `10.10.10.10`. The device, by default, will set its asset-id to match the hostname provided by the hyperv
This causes this device's salt-minion to attempt to connect to the Conductor at IP address `10.10.10.10`. By default the devices sets its `asset-id` to match the hostname provided by the hypervisor's cloud-init metadata. 

...and node name, allowing the system to pull the full configuration.

2023-04-10 18:08 UTC, Chr1st0ph3rTurn3r commented on docs/install_qcow2_deployment.md
> +The example above assumes that the system will be able obtain an IP address via DHCP on the first network interface which will provide connectivity to the Conductor. If this is not the case, addition
...the first network interface, which provides connectivity to the Conductor.

However, these details are beyond the scope...

...and the documentation for your particular hypervisor for further guidance.

2023-04-17 02:24 UTC, laneshields commented on docs/install_qcow2_deployment.md
> +    {"node-role": "combo", "node-ip": "127.0.0.1", "node-name": "dummy-node", "router-name": "dummy-router", "admin-password": "$6$W2wtGSOP7lT4vqLj$zG3eYb9/QAWD/0PqiN/I6vVLtDhBzhecx.aBpdweIx4D.0NJzxI
That is just the salted and hashed version of our standard password

2023-04-18 14:44 UTC, Chr1st0ph3rTurn3r approved these changes

2023-04-19 14:33 UTC, merged

2023-05-08 20:40 UTC, iwbarker commented on docs/install_qcow2_deployment.md
> -For successful SSR qcow2 deployment, a cloud-init configuration **must** provide persistent network interface bindings and be run on first boot of the VM; otherwise the SSR will not correlate virtual
@Chr1st0ph3rTurn3r 
In my opinion, this paragraph should not have been removed. 

Because the packer-generated qcow2 does not create persistent ifcfg files on first boot, it is a mandatory requirement for all package-based qcow2 that the cloud-init config fully describes all network interfaces on the VM.  

Without that config, there is nothing to tie the NIC to a particular interface name, and the interfaces can get juggled around on each VM reboot as the probe order is non-deterministic.

The example cloud-init config that Lane added below does not fulfill this requirement, so this is still an open issue to be documented for customer use I think.

[ For image-based qcow2 deployments this is not a problem, as unpacker (not packer) is used to create the qcow2 and ib uses a startup script that does inject the appropriate ifcfg files on first boot of the VM. ]