OTP re imaging doc
128technology/docs pull request #545
Opened 2023-04-11 15:21 UTC by Chr1st0ph3rTurn3r

2023-04-11 16:03 UTC, agrawalkaushik commented on docs/onboard_ssr_device_otp.md
> +The image shipped on the SSR Devices is designed to connect with Mist and Mist WAN Assurance. For use in a conductor-managed environment that does not have access to Mist, re-image the SSR Device wit
> generally available, package-based, OTP-compatible SSR software release

Can we add a link to where they can find said OTP images

2023-04-11 16:04 UTC, agrawalkaushik commented on docs/onboard_ssr_device_otp.md
> +3. Connect the USB end of the cable to your pc/mac using the serial adapter provided with the SSR device.
Is this true - coz I don't believe I had any such adapter in the box I had received. Maybe they were just proto units?

2023-04-11 16:05 UTC, agrawalkaushik commented on docs/onboard_ssr_device_otp.md
> +8. In the terminal window, type `screen` and paste the serial port info
I belive it also needs the baud rate. I typically use `screen /dev/cu.usbserial-14420 115200` - change the port to be whatver they learn from step 6.

2023-04-11 16:06 UTC, agrawalkaushik commented on docs/onboard_ssr_device_otp.md
> +11. Insert your USB with the new ISO image into the serial port of the SSR1x0/0.
I think you mean into the USB port - I dont think you can connect USB to a serial port.

2023-04-11 16:53 UTC, MichaelBaj commented on docs/onboard_ssr_device_otp.md
> +## Re-Imaging Process
@agrawalkaushik Is it true that reimaging is needed? For air-gapped networks, can't a customer still get to a workflow where they can accept a OTP file to configure the device to talk to a conductor?

2023-04-11 16:59 UTC, Chr1st0ph3rTurn3r commented on docs/onboard_ssr_device_otp.md
> +3. Connect the USB end of the cable to your pc/mac using the serial adapter provided with the SSR device.
Just going by what was in the box that I got, although Jeff may have packed those things specifically for me. I will check the packing list with the hardware guide.

2023-04-11 17:03 UTC, Chr1st0ph3rTurn3r commented on docs/onboard_ssr_device_otp.md
> +## Re-Imaging Process
no that's the whole issue that I've been asked to document around.

2023-04-11 18:26 UTC, migolnikov commented on docs/onboard_ssr_device_otp.md
> +10. At the instruction in the terminal window: `Press ESC for the boot menu`, do so.
is it ESC for both Silicom (SSR1xx) and Lanner (SSR1xxx)?

2023-04-13 18:17 UTC, eleung128 commented on docs/onboard_ssr_device_otp.md
> +8. In the terminal window, type `screen` and paste the serial port info
Do we need to note that these instruction doesn't apply to Windows PC since it doesn't have `screen` command in either `Powershell` or `Command Prompt`?  It also has no `/dev`.

2023-04-13 18:24 UTC, eleung128 commented on docs/onboard_ssr_device_otp.md
> +11. Insert your USB with the new ISO image into the serial port of the SSR1x0/0.
I thought the boot menu is not dynamically updated if the USB is inserted after the boot menu is shown.  But I could be wrong.

2023-04-14 03:46 UTC, agrawalkaushik commented on docs/onboard_ssr_device_otp.md
> +## Re-Imaging Process
> @agrawalkaushik Is it true that reimaging is needed? For air-gapped networks, can't a customer still get to a workflow where they can accept a OTP file to configure the device to talk to a conductor?

At the time we decided that MIST based ZTP was acceptable so no, we unfortunately do not have this. At some point, I'd like to get to this so we truly have a single image once and for all
https://128technology.atlassian.net/browse/I95-50572

2023-04-14 12:14 UTC, MichaelBaj commented on docs/onboard_ssr_device_otp.md
> +## Re-Imaging Process
So there is no way for a customer in an air-gapped network to use the manufactured 5.4.4 image on a Juniper-branded SSR platform to connect to a Conductor without a full reimaging?

2023-04-14 12:33 UTC, MichaelBaj submitted a review, later dismissed

2023-04-17 13:34 UTC, MichaelBaj approved these changes

2023-04-17 15:04 UTC, avijitvjuniper commented on docs/config_wan_assurance.md
> +SSR software can run on Juniper branded appliances, whitebox hardware (certified or self-evaluated), or virtual environments. For software versions prior to SSR Version 6.0, router adoption relies on
Can we please change this to 'SSR software can run on Juniper SSR100 and SSR1000 appliances'?

2023-04-18 14:27 UTC, Chr1st0ph3rTurn3r commented on docs/config_wan_assurance.md
> +SSR software can run on Juniper branded appliances, whitebox hardware (certified or self-evaluated), or virtual environments. For software versions prior to SSR Version 6.0, router adoption relies on
done

2023-04-18 14:27 UTC, Chr1st0ph3rTurn3r commented on docs/onboard_ssr_device_otp.md
> +- To retain a valid warranty, the software used to re-image the SSR device must be an [**official Juniper GA Release of the SSR Software**](about_releases.mdx#general-availability).
done

2023-04-18 14:28 UTC, Chr1st0ph3rTurn3r commented on docs/onboard_ssr_device_otp.md
> +- If the SSR device is to be used as a Conductor, it must first be converted into a Conductor. See [Conductor Conversion](conductor_conversion.md) for more information.
revised - will address the documentation where we describe how to convert an SSR1x0/1x00 to a Conductor

2023-04-18 14:40 UTC, migolnikov commented on docs/onboard_ssr_device_otp.md
> +The image shipped on the SSR Devices is designed to connect with Mist and Mist WAN Assurance. For use in a conductor-managed environment that does not have access to Mist, re-image the SSR Device wit
+1 on that. I commonly get asked where ISOs can be downloaded from and how to get credentials. (The latter part may not be an issue for customers though)

2023-04-26 19:44 UTC, migolnikov commented on docs/onboard_ssr_device_otp.md
> +10. At the instruction in the terminal window: `Press ESC for the boot menu`, do so.
I withdraw this request. This will be different on many platforms. To make this generic we should generally advise that boot process should be interrupted by user input

2023-04-26 21:18 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +10. At the instruction in the terminal window: `Press ESC for the boot menu`, do so.
I disagree with Max's withdrawal... we should document how to reinstall on our SSR branded hardware.

For white box customers can figure it out themselves, but for SSR platforms we must provide correct guidance how to replace the 'bad' ZTP image with a 'good' OTP image ready to use with the on-prem conductor.

2023-04-26 21:19 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +10. At the instruction in the terminal window: `Press ESC for the boot menu`, do so.
@Chr1st0ph3rTurn3r I will post screenshots and key sequences here shortly

2023-04-26 21:20 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +10. At the instruction in the terminal window: `Press ESC for the boot menu`, do so.
SSR120 & SSR130
![ssr120](https://user-images.githubusercontent.com/99365208/234705255-dbdde2e9-1a08-45c1-87a8-65394319d2d1.png)

Press ESC when prompted to display the boot menu.
Press the menu character corresponding to the USB stick.

2023-04-26 21:23 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +10. At the instruction in the terminal window: `Press ESC for the boot menu`, do so.
SSR1200
![ssr1x00](https://user-images.githubusercontent.com/99365208/234705632-03158bfa-5545-4b2e-be2a-f5218743aa1b.png)
Press Tab or DEL when prompted to enter setup

![ssr1200](https://user-images.githubusercontent.com/99365208/234705570-c7a2239c-11d3-485e-a53c-7f74c78c3f81.png)
Use Left and Right arrow to navigate to the “Save & Exit” page
Use Up and Down arrow to highlight the USB device in “Boot Override”
Press Enter to confirm boot from the USB device

2023-04-26 21:23 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +10. At the instruction in the terminal window: `Press ESC for the boot menu`, do so.
SSR1300
Same two-screen process as SSR1200 but slightly different setup layout
![ssr1300](https://user-images.githubusercontent.com/99365208/234706033-b67dca18-a534-4f84-9405-272cbf49204d.png)

2023-04-26 21:24 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +10. At the instruction in the terminal window: `Press ESC for the boot menu`, do so.
SSR1500
Same two-screen process as SSR1200 but again slightly different setup layout
![ssr1500](https://user-images.githubusercontent.com/99365208/234706165-503225fb-7b16-4c28-89e1-898ba943189c.png)

2023-04-26 21:25 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +10. At the instruction in the terminal window: `Press ESC for the boot menu`, do so.
Personally I think the above are all close enough to just provide two sets of instructions. 
One example for SSR1xx
Second example for SSR1xxx

2023-04-27 18:55 UTC, migolnikov approved these changes

2023-05-18 15:28 UTC, MichaelBaj commented on docs/onboard_ssr_device_otp.md
> +3. Connect the USB end of the cable to your laptop.
instead of laptop - "computer"

2023-05-18 17:14 UTC, Chr1st0ph3rTurn3r commented on docs/onboard_ssr_device_otp.md
> +3. Connect the USB end of the cable to your laptop.
change made. I've gone through your review copy again, and I don't believe I missed anything. What are you not finding?

2023-05-18 17:28 UTC, MichaelBaj approved these changes
Apologies, I thought you missed adding the link to download PuTTY, but you did add it.

2023-05-22 13:38 UTC, avijitvjuniper commented on docs/config_wan_assurance.md
> +SSR software can run on Juniper SSR1x0 and SSR1x00 appliances, whitebox hardware (certified or self-evaluated), or virtual environments. For software versions prior to SSR Version 6.0, router adoptio
Please change this to Juniper SSR100 and SSR1000 series appliances

2023-05-22 13:38 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +## Re-Imaging Process
> So there is no way for a customer in an air-gapped network to use the manufactured 5.4.4 image on a Juniper-branded SSR platform to connect to a Conductor without a full reimaging?

initiailize128t is still available to be used manually on the ODM image, so installation without re-imaging is definitely possible.

But @jeffmart was concerned that the hardware bootstrapped could interfere with that manual workflow that it would not be reliable without further testing. 

For example, interfaces being renamed to the ZTP 'ge' style instead of OTP 'eno' style etc.

2023-05-22 13:40 UTC, avijitvjuniper commented on docs/onboard_ssr_device_otp.md
> +The steps in this section describe the process of **re-imaging an SSR1x0 or SSR1x00** for onboarding to a Conductor using the OTP process. This process is for SSR devices that **cannot** use Mist for
Please change this to SSR100 and SSR1000 series appliance

2023-05-22 13:53 UTC, avijitvjuniper commented on docs/onboard_ssr_device_otp.md
> +2. Connect the RJ45/USB cable to the console port on the SSR1x0/1x00.
Please change this to SSR100 and SSR1000 series appliance

2023-05-22 13:53 UTC, avijitvjuniper commented on docs/onboard_ssr_device_otp.md
> +4. Connect the power input to the back of the SSR1x0/1x00, but do not power it up.
Please change this to SSR100 and SSR1000 series appliance

2023-05-22 13:54 UTC, avijitvjuniper commented on docs/onboard_ssr_device_otp.md
> +12. Use the instructions below appropriate for your device (SSR1x0 or SSR1x00) to complete the re-imaging process.
Please change this to SSR100 and SSR1000 series appliance

2023-05-22 13:54 UTC, avijitvjuniper commented on docs/onboard_ssr_device_otp.md
> +#### SSR1x0 Devices
Please change this to SSR100 series appliances

2023-05-22 14:04 UTC, avijitvjuniper commented on docs/onboard_ssr_device_otp.md
> +#### SSR1x00 Devices
Please change this to SSR1000 series appliances

2023-05-22 14:05 UTC, avijitvjuniper commented on docs/onboard_ssr_device_otp.md
> +2. Connect the RJ45/USB cable to the console port on the SSR1x0/1x00.
Please change this to SSR100 and SSR1000 series appliance

2023-05-22 14:05 UTC, avijitvjuniper commented on docs/onboard_ssr_device_otp.md
> +4. Connect the power input to the back of the SSR1x0/1x00, but do not power it up.
Please change this to SSR100 and SSR1000 series appliance

2023-05-22 14:06 UTC, avijitvjuniper commented on docs/onboard_ssr_device_otp.md
> +#### SSR1x0 Devices:
Please change this to SSR100 series appliance

2023-05-22 14:06 UTC, avijitvjuniper commented on docs/onboard_ssr_device_otp.md
> +#### SSR1x00 Devices
Please change this to SSR1000 series appliance

2023-05-22 15:33 UTC, avijitvjuniper commented on docs/onboard_ssr_device_otp.md
> +For customers or partners who can access Mist and are not in an "air-gap" network, the easiest way to onboard an SSR device is to configure an account on Mist (this is free), and onboard to a conduct
I believe somewhere we may want to mention as a note that once the SSR device is re-imaged, should the customer want to onboard the device to Mist via Conductor in future, it may not show up as an SSR device but as a whitebox.

2023-05-30 14:16 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +The process varies based on the SSR device, as well as Mac and Windows. Use the following procedures for the serial connection and set up and device specific re-imaging.
Can we change this to:
The process varies based on the SSR target device series, and whether Mac or Windows is used as the re-imaging host.

2023-05-30 14:17 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +3. Connect the USB end of the cable to your computer.
can we say "Mac" instead of "computer" here?

2023-05-30 14:17 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +3. Connect the USB end of the cable to your laptop.
can we say "Windows host" instead of "laptop" here?

2023-05-30 14:21 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +2. From the boot menu, select the USB Boot device and press Enter; or enter the boot device number and press Enter.
why is this an either/or ?

2023-05-30 14:22 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +3. Select the image for your install.
what does "select the image" mean here?

2023-05-30 14:24 UTC, iwbarker requested changes
Final round of comments added

2023-05-30 15:19 UTC, Chr1st0ph3rTurn3r commented on docs/onboard_ssr_device_otp.md
> +3. Select the image for your install.
Again, during my walkthrough with Jeff, there were multiple packages on the USB. You can select the appropriate package. I will add clarification to that line.

2023-05-30 15:57 UTC, migolnikov approved these changes
onboard with changes and Iain's comments

2023-05-30 15:59 UTC, Chr1st0ph3rTurn3r commented on static/img/putty-ssr1x0-boot-menu.png
it is not used. I replaced it as suggested with onboard_otp_boot_device.png.

2023-05-30 16:46 UTC, agrawalkaushik commented on docs/onboard_ssr_device_otp.md
> +For customers or partners who can access Mist and are not in an "air-gap" network, the easiest way to onboard an SSR device is to configure an account on Mist (this is free), and onboard to a conduct
@avijitvjuniper that statement is not factually correct.

2023-05-30 18:00 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +2. From the boot menu, select the USB Boot device and press Enter; or enter the boot device number and press Enter.
I just tried it on an SR130 and there is no cursor control, the only way to select the USB device is to press the corresponding number on the menu.

![Screenshot 2023-05-30 at 1 58 43 PM](https://github.com/128technology/docs/assets/99365208/f98a5cfb-c480-4fd1-9d5b-84686b31a6d3)

2023-05-30 18:01 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +3. Press Enter to confirm boot from the USB device.
When I just tested, there is no 'press enter' to confirm step. 
As soon as I enter '2' at the menu, the USB boots immediately.

2023-05-30 19:37 UTC, avijitvjuniper submitted a review, later dismissed

2023-05-30 19:46 UTC, iwbarker commented on docs/onboard_ssr_device_otp.md
> +2. From the boot menu, enter the boot device number and press Enter.
enter the boot device number _corresponding to the OTP USB_

2023-05-30 19:47 UTC, iwbarker submitted a review, later dismissed

2023-05-30 20:10 UTC, merged