6.1.1 I95-51052 Release Note
128technology/docs pull request #554
Opened 2023-04-25 14:31 UTC by Chr1st0ph3rTurn3r

2023-04-25 14:40 UTC, MichaelBaj requested changes

2023-04-25 14:40 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-51052 `session-scaling` regression generating high number of `wrong-thread` error messages:** The following regression has been resolved: If `outbound-only` or `nat-traversal mode` is used be
Change to:

**I95-51052 NAT changes in network cause sessions to fail:** If `session-scaling` is set to enabled with `outbound-only` or `nat-traversal mode` is used between SSR routers, and a NAT between the routers causes an address and/or port change for existing TCP or UDP sessions between them, the SSR will not automatically recover those sessions if they were idle or had one-way traffic.

The impacted sessions will time out when all packets for the failed sessions stopped. New sessions are not impacted, nor are any pre-existing sessions with regular bi-directional traffic.

2023-04-25 16:02 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-51052 `session-scaling` regression generating high number of `wrong-thread` error messages:** The following regression has been resolved: If `outbound-only` or `nat-traversal mode` is used be
Updated

2023-04-25 16:16 UTC, MichaelBaj submitted a review, later dismissed

2023-04-25 18:52 UTC, hadrielk commented on docs/release_notes_128t_6.1.md
> +- **I95-51052 NAT changes in network cause sessions to fail:** If `session-scaling` is set to `enabled` with `outbound-only` or `nat-traversal` mode used between SSR routers, and a NAT between the ro
Lol, **you** were the one who told me to use that term!

2023-04-25 18:55 UTC, hadrielk requested changes

2023-04-25 18:55 UTC, hadrielk commented on docs/release_notes_128t_6.1.md
> +- **I95-51052 NAT changes in network cause sessions to fail:** If `session-scaling` is set to `enabled` with `outbound-only` or `nat-traversal` mode used between SSR routers, and a NAT between the ro
@Chr1st0ph3rTurn3r in the end, after more analysis internally, I think this wording is a bit too extreme and broad. It takes a specific traffic pattern to hit this issue, an it's not a common one. (I mean, it's common enough that Commerzbank hit it, but it's not like every session has the problem)

2023-04-25 20:59 UTC, ayungelson approved these changes

2023-04-25 22:00 UTC, hadrielk commented
FYI: we're also going to need to release-note this PR: https://github.com/Juniper-SSN/ssr/pull/6640

That's being merged in as well. I added a potential red-note to the PR description, but could use word-smithing.

I'm not sure howe we publicly word fixes for race-condition crashes.

2023-04-26 13:17 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-51093 95-51093 Race condition in `session-scaling` can cause crash/restart:** Resolved an issue when `session-scaling` is set to `enabled` together with `outbound-only`, a race condition can
Missing 'I' in I95 issue ID.

2023-04-26 14:27 UTC, MichaelBaj approved these changes

2023-04-26 16:07 UTC, ayungelson approved these changes

2023-04-26 16:24 UTC, hadrielk approved these changes

2023-04-27 13:29 UTC, MichaelBaj submitted a review, later dismissed

2023-05-01 13:26 UTC, MichaelBaj requested changes

2023-05-01 13:26 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-48965, I95-50070, I95-50086 Highway Crashes:** Resolved an issue where a routing change that affects the `forwarding-table` can incur a race condition with sessions completing and being remov
[I95-50086](https://128technology.atlassian.net/browse/I95-50086) is unrelated from other two items and is NOT in 6.1.1. It is in 6.0.10.

I95-50070 is a duplicate of I95-48965 and should be removed from the release notes.

Headline should be changed to 
**I95-48965 Race condition with routing updates inducing crash in highway process:** ...

2023-05-01 14:05 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-48965, I95-50070, I95-50086 Highway Crashes:** Resolved an issue where a routing change that affects the `forwarding-table` can incur a race condition with sessions completing and being remov
So two things with this. One is that I got the wrong number - it should be 51086, which I'll fix. Two, Jeff asked me to document all three in the release notes. I don't know if CHS and Plusnet are the same customer - but if they are two different customers, and this is a high visibility issue, should they both be in there? And I'll change the Issue name.

2023-05-01 14:36 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-48965, I95-50070, I95-50086 Highway Crashes:** Resolved an issue where a routing change that affects the `forwarding-table` can incur a race condition with sessions completing and being remov
These are two different customers. Therefore you _can_ add both issue IDs for that purpose if you feel that it is valuable.

2023-05-01 17:11 UTC, MichaelBaj submitted a review, later dismissed

2023-05-01 18:09 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.1.md
> +- **I95-51052 NAT changes in network cause sessions to fail:** If `session-scaling` is set to `enabled` with `outbound-only` or `nat-traversal` mode used between SSR routers, and a NAT between the ro
nat-traveral mode section was removed to resolve this comment

2023-05-01 18:09 UTC, ayungelson approved these changes

2023-05-01 18:15 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.1.md
> +- **I95-51052 `session-scaling` regression generating high number of `wrong-thread` error messages:** The following regression has been resolved: If `outbound-only` or `nat-traversal mode` is used be
confirmed + changes requested below.

2023-05-01 18:15 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.1.md
> +- **I95-51052 NAT changes in network cause sessions to fail:** If `session-scaling` is set to `enabled` with `outbound-only` or `nat-traversal` mode used between SSR routers, and a NAT between the ro
confirmed, resolving ...

2023-05-01 18:16 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.1.md
> +- **I95-48965, I95-50070, I95-50086 Highway Crashes:** Resolved an issue where a routing change that affects the `forwarding-table` can incur a race condition with sessions completing and being remov
I do, resolving this section :)

2023-05-01 18:16 UTC, jeffmart-jnpr approved these changes

2023-05-01 18:57 UTC, MichaelBaj approved these changes

2023-05-01 19:09 UTC, merged