6.1.2 release notes
128technology/docs pull request #559
Opened 2023-05-10 18:36 UTC by Chr1st0ph3rTurn3r

2023-05-10 21:07 UTC, MichaelBaj requested changes

2023-05-10 21:07 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-51007 cpusetOrchestrator isolating and pinning cores on the Conductor:** The cpuProperties cores setting in /etc/128technology/local.init was erroneously isolating cores on conductor nodes wh
heading should be: "Conductor is incorrectly honoring core pinning"

2023-05-10 21:07 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +
- [ ] @migolnikov has indicated that we need to add a caveat for the conductor proxy issue.

2023-05-10 21:07 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-51093 Segfault in Highway when using multithreaded ServiceArea:** Resolved an issue when `session-scaling` is set to `enabled` together with `outbound-only`, whereby a race condition can caus
multi-threaded ServiceArea

2023-05-11 15:43 UTC, migolnikov submitted a review, later dismissed

2023-05-11 15:57 UTC, MichaelBaj requested changes

2023-05-11 17:54 UTC, MichaelBaj approved these changes

2023-05-11 18:34 UTC, MichaelBaj approved these changes

2023-05-12 12:31 UTC, MichaelBaj submitted a review, later dismissed

2023-05-12 16:20 UTC, hadrielk commented on docs/release_notes_128t_6.1.md
> +- **I95-51086 Highway Crash on Headend:** Resolved an issue where a routing change that affects the `forwarding-table` can incur a race condition with sessions completing and being removed, which cou
that was fixed in `6.1.1`, and already noted in that part of this release-notes doc.

2023-05-12 16:22 UTC, hadrielk commented on docs/release_notes_128t_6.1.md
> +- **I95-51093 Segfault in Highway when using multi-threaded ServiceArea:** Resolved an issue when `session-scaling` is set to `enabled` together with `outbound-only`, whereby a race condition can cau
this was also fixed in `6.1.1`

2023-05-12 16:23 UTC, hadrielk requested changes
remove the bugs that were fixed previously

2023-05-12 17:26 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-51086 Highway Crash on Headend:** Resolved an issue where a routing change that affects the `forwarding-table` can incur a race condition with sessions completing and being removed, which cou
removed

2023-05-12 17:26 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-51093 Segfault in Highway when using multi-threaded ServiceArea:** Resolved an issue when `session-scaling` is set to `enabled` together with `outbound-only`, whereby a race condition can cau
removed - thanks for catching those.

2023-05-12 17:27 UTC, MichaelBaj submitted a review, later dismissed

2023-05-12 20:12 UTC, hadrielk submitted a review, later dismissed

2023-05-12 20:45 UTC, MichaelBaj approved these changes

2023-05-12 20:55 UTC, merged