5.6.8 Release Notes
128technology/docs pull request #564
Opened 2023-05-15 19:51 UTC by Chr1st0ph3rTurn3r

2023-05-15 21:23 UTC, MichaelBaj requested changes

2023-05-15 21:23 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-50445 i40e and ice devices enter malicious descriptor detection state, preventing forwarding of traffic:** Resolved an issue where fragmented packet chains larger than 8 buffers were discarde
This is a serious issue and should have a log snippet so customers and SEs can be made more knowlegable of the issue.
the following is an example of a log messages see in `dpdk.log` indicating the occurrence of the issue:
```
[DPDK| -- ] ERROR (00007f03ec18e700) i40e_dev_alarm_handler(): ICR0: malicious programming detected
[DPDK| -- ] WARN  (00007f03ec18e700) i40e_handle_mdd_event(): Malicious Driver Detection event 0x02 on TX queue 6 PF number 0x01 VF number 0x00 device 0000:08:00.1
[DPDK| -- ] WARN  (00007f03ec18e700) i40e_handle_mdd_event(): TX driver issue detected on PF
```

2023-05-15 21:23 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-50445 i40e and ice devices enter malicious descriptor detection state, preventing forwarding of traffic:** Resolved an issue where fragmented packet chains larger than 8 buffers were discarde
Also, I do know that I didn't make this comment in 6.1.2 release notes, but I should have.

2023-05-15 21:23 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-51006 Nodes stuck in connected state after upgrade:** On an HA conductor, if the user is performing an upgrade on the first conductor node and that user makes a config commit during the upgra
you have this issue listed twice.

2023-05-16 22:17 UTC, MichaelBaj commented on docs/about_releases.mdx
> +| Release 5.6 | [5.6.7](release_notes_128t_5.6.md#release-567-4) | March 16, 2023 | [5.6.8](release_notes_128t_5.6.md#release-568-8) | June 16, 2024 | December 16, 2024 |
This should be 5.6.8 in the link

2023-05-16 22:17 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-50269 Router clone operation fails:** Implemented checks to prevent cloning obsolete elements and internal lists/containers on legacy versions of the SSR software (SSR Software </= version 4.
I'm not familiar with </= is that a way to escape an equal sign?

2023-05-17 14:18 UTC, MichaelBaj submitted a review, later dismissed

2023-05-18 15:19 UTC, MichaelBaj approved these changes

2023-05-25 15:50 UTC, MichaelBaj submitted a review, later dismissed

2023-05-25 16:56 UTC, MichaelBaj requested changes

2023-05-25 16:56 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
>  	- Added new metrics for tracking utilization of packet pools.
Please add paths for the new metrics

2023-05-25 17:51 UTC, MichaelBaj requested changes

2023-05-25 17:51 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +		- `FastLanePacketPool`
Sorry, I should have been more clear. We need the full path.
e.g., `packet-processing/classifier/received/ipv4-fragmented`
Not sure what the equivalent is for these metrics. That path would be used for both the GUI as well as PCLI.

2023-05-25 18:21 UTC, MichaelBaj approved these changes

2023-05-25 20:35 UTC, jeffmart-jnpr approved these changes

2023-05-25 23:39 UTC, merged