Application Steering topic
128technology/docs pull request #572
Opened 2023-06-09 14:53 UTC by Chr1st0ph3rTurn3r

2023-06-09 15:09 UTC, agrawalkaushik commented on docs/config_application_steering.md
> +The application database is updated on a regular basis/a static database and is updated when the software version is updated. (Or we just say it is periodically updated, or we don't say anything) ---
> The application database is updated on a regular basis

That is the only way to make this feature work. We can clarify but thats pretty much a pre-requisite for this feature. Without this the feature is as good as disabled.

2023-06-09 17:16 UTC, MichaelBaj requested changes

2023-06-09 17:16 UTC, MichaelBaj commented on docs/config_application_steering.md
> +| 6.1.4   | Application Steering introduced |
release `6.1.4-R2`

2023-06-09 17:16 UTC, MichaelBaj commented on docs/config_application_steering.md
> +Application Steering provides the ability to configure unique steering policies for individual applications based on the application name, category, application signatures, URLs, and domains. In addi
This introduction statement doesn't fundamentally explain what application steering does - which is to steer traffic across available paths once it has been classified. This is different from traditional routing which is destination based, application steering is policy that associated with a classified application.

2023-06-09 17:16 UTC, MichaelBaj commented on docs/config_application_steering.md
> +service facebook.internet
Since this is using hierarchical services, provide a link to the hierarchical services doc for reference.

2023-06-09 17:16 UTC, MichaelBaj commented on docs/config_application_steering.md
> +  service-route workday.internet__headend
in the introduction to this section, describe what you are accomplishing with this config:
* above, defined a catch-all service for internet traffic (`0.0.0.0/0`)
* defined a child service for workday.internet
* defined a service route for internet to take both broadband and lte paths
* defined another service route specifically for workday.internet to take SVR path to head-end

2023-06-15 15:12 UTC, tjbresnahan submitted a review, later dismissed
Just needs the updates already requested. Otherwise it's good

2023-06-15 15:34 UTC, reidstidolph-JNPR commented on docs/config_application_steering.md
> +The application database is updated on a regular basis/a static database and is updated when the software version is updated. (Or we just say it is periodically updated, or we don't say anything) ---
We simply could note that apps are periodically updated based on the application-identification settings ( https://www.juniper.net/documentation/us/en/software/session-smart-router/docs/config_reference_guide#application-identification )

2023-06-15 16:58 UTC, Chr1st0ph3rTurn3r commented on docs/config_application_steering.md
> +The application database is updated on a regular basis/a static database and is updated when the software version is updated. (Or we just say it is periodically updated, or we don't say anything) ---
This is confusing - to me at least - because the app-id updates are set as part of the Web Filtering feature, which is a separately purchased feature. So from my understanding, they won't be able to get updates because they can't configure app-id settings. Unless I am misunderstanding how the features interact.

2023-06-20 15:06 UTC, Chr1st0ph3rTurn3r commented on docs/config_application_steering.md
> +During the service configuration, applications are simply identified by name, for example `Facebook`. If the application is not in the application database, an error is generated.
Still working on finding the error info for this.

2023-06-20 15:07 UTC, Chr1st0ph3rTurn3r commented on docs/config_application_steering.md
> +service facebook.internet
done

2023-06-20 15:08 UTC, Chr1st0ph3rTurn3r commented on docs/config_application_steering.md
> +The application database is updated on a regular basis/a static database and is updated when the software version is updated. (Or we just say it is periodically updated, or we don't say anything) ---
resolved this.

2023-06-29 13:49 UTC, Chr1st0ph3rTurn3r commented on docs/config_application_steering.md
> +During the service configuration, applications are simply identified by name, for example `Facebook`. If the application is not in the application database, an error is generated.
Verified that there is no error. Removed the reference.

2023-06-29 20:09 UTC, MichaelBaj approved these changes

2023-06-29 21:43 UTC, closed without merging