LAG, LACP, and LLDP info
128technology/docs pull request #573
Opened 2023-06-09 20:02 UTC by Chr1st0ph3rTurn3r

…formation.

2023-06-09 20:47 UTC, agrawalkaushik commented on docs/config_reference_guide.md
> +#### Version History:
VRRP has been in the product for a while - its not new to 6.1.4

2023-06-09 20:48 UTC, agrawalkaushik commented on docs/config_reference_guide.md
> +## q-in-q
same here - not sure why these are getting picked up now (presumable some scripting?) but this is also not new to 6.1.4

2023-06-12 17:24 UTC, MichaelBaj requested changes

2023-06-12 17:24 UTC, MichaelBaj commented on docs/config_reference_guide.md
> +## q-in-q
Q-in-Q was introduced in 4.5.1

2023-06-12 17:24 UTC, MichaelBaj commented on docs/config_reference_guide.md
> +#### Version History:
VRRP was introduced in `5.4.0`

2023-06-27 18:45 UTC, sjaffer-juniper commented on docs/config_lacp.md
> +LLDP allows other devices in the network to discover the SSR. It is not required for LACP, but when enabled it provides information about the LAG interface in the network. It should be noted that whe
LLDP config, not LLDP command?

2023-06-27 19:11 UTC, jacobdionne commented on docs/config_lacp.md
> +- All members of the `bond` must be of the type `ethernet`.
Another point to document is that all bond members should be of similar speed and support full duplex. Could even say it's preferred that members are of the same NIC model, but it isn't required.

2023-06-27 19:56 UTC, jacobdionne commented on docs/config_lacp.md
> +The LAG is created by configuring a `bond` device interface. It is populated as other device interfaces are configured with the `parent-bond` option identified as the `bond` device interface. Because
Maybe some extra detail in here. Line 2 makes it sound like the `parent-bond` is set on the bond itself. 
`The bond interface is configured with network-interfaces. Members of the bond are configured as an ethernet device interfaces with parent-bond assigned as the bond device it's apart of. Bond members are not allowed to have network-interfaces configured on them`

2023-06-28 17:00 UTC, ayungelson commented on docs/config_lacp.md
> +The LAG is created by configuring a `bond` device interface. It is populated as other device interfaces are configured with the `parent-bond` option identified as the `bond` device interface. Because
The LAG is created by defining a device interface as a `bond`. The bond interface is configured with network-interfaces and other settings. Members of the bond are configured as ethernet device interfaces with `parent-bond` assigned as the bond device it's apart of. Bond members are not allowed to have network-interfaces configured on them.

2023-06-29 02:06 UTC, agrawalkaushik commented on docs/config_lacp.md
> +A Link Aggregation Group (LAG) enables the grouping Ethernet interfaces to form a single link layer interface. LAGs are formed by connecting multiple ports in parallel between two devices. As more li
> Traffic is automatically load-balanced

@jacobdionne is there more info we want to add around this in later sections?

2023-06-29 02:08 UTC, agrawalkaushik commented on docs/config_lacp.md
> +- A `bond` must have at least one member; At least one `device-interface` that references the `bond` as it’s `parent-bond`.
> A `bond` must have at least one member

shouldn't there be at least 2 members? What good is a bond with 1 member?

2023-06-29 02:10 UTC, agrawalkaushik commented on docs/config_lacp.md
> +LLDP allows other devices in the network to discover the SSR. It is not required for LACP, but when enabled it provides information about the LAG interface in the network. It should be noted that whe
I was about to ask whether we got LAG TLVs but I agree if we dont have them working yet we should remove it. Currently LLDP is only mentioned in this one place in our docs I believe.
https://www.juniper.net/documentation/us/en/software/session-smart-router/docs/wan_telemetry_features/#topology-mapping

2023-06-29 02:11 UTC, agrawalkaushik commented on docs/config_lacp.md
> +
Since dynamic reconfig for LLDP doesnt work today, I'd suggest adding a note here saying that 128T restart is required when changing LACP setting.

2023-06-29 02:13 UTC, agrawalkaushik commented on docs/config_lacp.md
> +### Configuration using the GUI
We should add a foot note about user configuring all the normal device-interface config like network-interface, tenants, neighborhood etc on the bond interface and those config not being relevant on the members.

cc: @ayungelson

2023-06-29 02:15 UTC, agrawalkaushik commented on docs/config_lacp.md
> +![Configure LAG devices](/img/config_lacp_dev-inf-parent-bond.png)
This does not seem like the right image for this step. This should instead show the bond member config, no?

2023-06-29 15:39 UTC, Chr1st0ph3rTurn3r commented on docs/config_lacp.md
> +### Configuration using the GUI
done
- The only configuration allowed on the bond-members are `pci-address` and `parent-bond`. All other settings must be configured on the `bond` interface.

2023-06-29 15:39 UTC, Chr1st0ph3rTurn3r commented on docs/config_lacp.md
> +- A `bond` must have at least one member; At least one `device-interface` that references the `bond` as it’s `parent-bond`.
done 
A `bond` must have between 1 and 8 members. Members are device-interface's that reference the `bond` interface as their `parent-bond`.

2023-07-13 13:59 UTC, ayungelson commented on docs/config_lacp.md
> +- A `bond` must have between 1 and 8 members. Members are device-interface's that reference the `bond` interface as their `parent-bond`.
typo? device-interface's?

2023-07-13 13:59 UTC, ayungelson commented on docs/config_lacp.md
> +- A `bond` can have a maximum of 8 members. This is verified during the configuration validation step.
is this bullet point important? we mention 1-8 above, and if we say we validate for max 8, we should also say that 0 is not allowed?

2023-07-13 13:59 UTC, ayungelson commented on docs/config_lacp.md
> +- High Availability has not been fully tested, and may not be fully functional.
HA? isn't that VRRP? so this line is redundant?

2023-07-13 13:59 UTC, ayungelson commented on docs/config_lacp.md
> +Please note that after any configuration changes to LAG or LACP settings, an SSR restart is required.
This may be not true any more?
We support enable/disable of LACP now. Also - maybe it's best to say something like this:
```Please note that after changing LAG configuration an SSR restart may be required. Please refer to the caveats section'```?

2023-07-13 18:27 UTC, ayungelson submitted a review, later dismissed

2023-07-13 18:48 UTC, MichaelBaj requested changes

2023-07-13 18:48 UTC, MichaelBaj commented on docs/config_lacp.md
> +This feature is currently a Beta feature. Some components are not fully tested. Refer to [Caveats](#caveats) for more details.
Please change this statement to:
"This feature is current in Beta. Support for LAG has been added for a limited number of use cases. Please refer to the [Caveats](#caveats) section for details."

2023-07-13 18:48 UTC, MichaelBaj commented on docs/config_lacp.md
> +- Dynamic reconfiguration is supported for changing LACP settings on the `bond` device, however adding or removing bonds and/or bond members from the LAG is not currently supported. Any time these ch
reboot the device or restart the 128T service?

2023-07-13 18:48 UTC, MichaelBaj commented on docs/config_lacp.md
> +    - VRRP with LAG is not supported
@ayungelson I thought there was testing performed with VRRP and LAG?

2023-07-13 18:48 UTC, MichaelBaj commented on docs/config_lacp.md
> +- High Availability has not been fully tested, and may not be fully functional.
Agreed, this line is redundant with VRRP

2023-07-13 18:48 UTC, MichaelBaj commented on docs/config_lacp.md
> +Please note that after any changes to the LAG configuration, it is recommended to reboot the device.
restart 128T instead of reboot?

2023-07-13 18:59 UTC, ayungelson commented on docs/config_lacp.md
> +    - VRRP with LAG is not supported
No testing was done with VRRP.

2023-07-13 19:07 UTC, Chr1st0ph3rTurn3r commented on docs/config_lacp.md
> +- High Availability has not been fully tested, and may not be fully functional.
This section had been changed (not sure how you see the old version) but this is what it says regarding HA:

- High Availability has not been fully tested, and may not be fully functional. 
    - VRRP with LAG is not supported
    - Shared physical addresses are not allowed.

2023-07-13 19:14 UTC, Chr1st0ph3rTurn3r commented on docs/config_lacp.md
> +- High Availability has not been fully tested, and may not be fully functional.
We do support more than one type of HA: Dual Node High Availability, and Dual Router High Availability using VRRP. Just sayin'... ;)

2023-07-13 19:16 UTC, MichaelBaj approved these changes

2023-07-13 19:41 UTC, closed without merging