IDP improvements 6.1.4 r2
128technology/docs pull request #574
Opened 2023-06-14 14:57 UTC by Chr1st0ph3rTurn3r

2023-06-14 15:31 UTC, MichaelBaj commented on docs/config_idp.md
> +**still need PCLI example of configuration, for consistency**
- [ ] TODO: Get PCLI output

2023-06-14 15:31 UTC, MichaelBaj commented on docs/config_idp.md
> +- Security events are triggered because traffic typical for that network configuration is considered a risk.
An example screen capture here would be illustrative

2023-06-14 15:31 UTC, MichaelBaj commented on docs/config_idp.md
> +After creating the custom ruleset, use the `access-policy` as shown in the [Configuration section above](#configuration) to define the IDP policy where this custom ruleset is used.
@agrawalkaushik after making these custom IDP rules changes, does it require a restart of the IDP engine? If so, that would incur some downtime for traffic to start honoring the new rules. If that is the case, that must be indicated here in the docs that this will happen.

2023-06-14 15:34 UTC, agrawalkaushik commented on docs/concepts_ssr_idp.md
> +Starting with SSR 6.1.4-R2, users can customize an existing base IDP policy, adding new or exception-based rules. For example, consider a case where an IDP policy is put in place, but security events
> adding new or exception-based

We cannot add new rules - everything is just exception based. 

```suggestion
Starting with SSR 6.1.4-R2, users can customize an existing base IDP policy, adding exception-based rules. For example, consider a case where an IDP policy is put in place, but security events are triggered because traffic typical for that network is considered a risk. Using an existing IDP policy, you can modify the profile to allow the specific traffic to flow as expected within the network. Changes are implemented from the SSR GUI or PCLI, and validated as part of the existing configuration workflow. 
```

2023-06-14 15:34 UTC, agrawalkaushik commented on docs/config_idp.md
> +- Security events are triggered because traffic typical for that network configuration is considered a risk.
@jamesesilvia can you please provide an example to include here

2023-06-14 15:38 UTC, agrawalkaushik commented on docs/config_idp.md
> +After creating the custom ruleset, use the `access-policy` as shown in the [Configuration section above](#configuration) to define the IDP policy where this custom ruleset is used.
It does not require a restart to enable the new policy changes. It does take some time for the changes to apply but our bypass logic should keep traffic off this policy until the IDP engine is ready (and there is an alarm to pair it up with). 

I see that Chris covered the startup behavior for IDP; @jamesesilvia @Chr1st0ph3rTurn3r I think its a good idea to capture a similar blurb for config changes as well. It's more selective where it only "bypasses" that one service and not the whole thing.

2023-06-14 15:39 UTC, agrawalkaushik approved these changes
overall lgtm!

2023-06-14 20:43 UTC, jamesesilvia commented on docs/config_idp.md
> +- Security events are triggered because traffic typical for that network configuration is considered a risk.
Yeah will get some snippets in a bit.

2023-06-15 12:46 UTC, hadrielk commented on docs/ts_idp.md
> +Beginning with SSR version 6.1.4-R2, traffic destined for IDP will temporarily bypass the IDP engine until it completes the startup process. This will take place at initial start up of the device, up
> An alarm is triggered on the device to indicate this is taking place

seriously?!?

2023-06-15 13:23 UTC, hadrielk commented on docs/ts_idp.md
> +Beginning with SSR version 6.1.4-R2, traffic destined for IDP will temporarily bypass the IDP engine until it completes the startup process. This will take place at initial start up of the device, up
Generate an alarm if and only if the IDP engine does not come up after X amount of time?

I mean that's an actual alarm able event, right? Not "boot up".

2023-06-15 13:42 UTC, Chr1st0ph3rTurn3r commented on docs/ts_idp.md
> +Beginning with SSR version 6.1.4-R2, traffic destined for IDP will temporarily bypass the IDP engine until it completes the startup process. This will take place at initial start up of the device, up
My understanding of how it works is that when the ssr or idp engine starts or restarts, IDP traffic automatically bypasses the IDP engine until it fully boots. During that time and alarm is raised so that the user/admin knows that traffic is NOT going through the IDP. As part of the info provided, we tell the user what traffic is not going through the IDP, and when the IDP engine will be fully booted and passing traffic. All that seems pretty important to me. If you are responsible for your the network security wouldn't you want to know that part of your security configuration is temporarily suspended, and when to expect it back?

2023-06-15 14:06 UTC, hadrielk commented on docs/ts_idp.md
> +Beginning with SSR version 6.1.4-R2, traffic destined for IDP will temporarily bypass the IDP engine until it completes the startup process. This will take place at initial start up of the device, up
> Point being, there may be cases where it does not start at all

Yes, that's I said "Generate an alarm if and only if the IDP engine does not come up after X amount of time?"

Because that's an actual unexpected event that the user not only needs to know about, but needs to do something about/fix.

But anyway, I'm resolving this issue thread.

2023-07-12 16:55 UTC, jamesesilvia requested changes

2023-07-12 16:55 UTC, jamesesilvia commented on docs/config_idp.md
> +- A standard IDP policy is put in place.
nit: wording `standard` is overloaded since its a possible `idp-policy` option and an adjective 😉 

change to: A "strict" `idp-policy` is initially configured for the service below.

2023-07-12 16:55 UTC, jamesesilvia commented on docs/config_idp.md
> +- Use an existing IDP policy to create a custom IDP profile in the Authority Settings configuration that can be referenced in the `access-policy`.
In this case, the User has identified the attack of `HTTP:EXTRA_CONTROL_CHARACTERS` to be of minimal risk to this network and would like to create a rule to change this event to be `alert` only.

2023-07-12 16:55 UTC, jamesesilvia commented on docs/config_idp.md
> +- Modify the profile to allow the specific traffic to flow as expected within the network, for example, modifying the action to alert/allow. Changes are implemented from the SSR GUI or PCLI (in this
Just flow/wording, No changes needed here

2023-07-12 18:17 UTC, MichaelBaj approved these changes

2023-07-12 18:18 UTC, jamesesilvia approved these changes

2023-07-12 19:38 UTC, closed without merging