BGP over SVR interhub steering first draft
128technology/docs pull request #577
Opened 2023-06-21 21:01 UTC by Chr1st0ph3rTurn3r

2023-06-22 21:35 UTC, jpetersonssr commented on docs/config_bgp.md
> +The PCLI command **Need the command** displays the current best peer for each group of peers sharing the same service policy. Information includes the last time the best peer changed for the group, a
The PCLI command is `show bgp path-based-policy`

2023-06-22 21:53 UTC, jpetersonssr commented on docs/config_bgp.md
> +
I would change this slightly to include something like this:

We configure `set-path-based-as-path prepend` to an AS path which is a sequence of AS numbers.  The prepend value is applied to BGP routes matched by the policy, making the BGP route AS path longer and thus less preferred.

2023-06-22 21:55 UTC, jpetersonssr approved these changes

2023-06-26 22:00 UTC, MarkusJork approved these changes

2023-06-27 20:25 UTC, MichaelBaj requested changes

2023-06-27 20:25 UTC, MichaelBaj commented on docs/config_bgp.md
> +The user configures the service-policy which provides the criteria for picking the best path. With this information, the BGP neighbors are prioritized. To ensure that BGP uses the best path, we confi
Is the attribute name correct (`set path based as-path prepend`)? What is in the docs differs from what John put in his comment as well as the example snippets in the config sections.

2023-06-27 20:25 UTC, MichaelBaj commented on docs/config_bgp.md
> +The service policy in the new routing policy path-based action determines the best BGP peer using the adjacency vectors. Per peer routing policies are dynamically modified as the best paths to the BG
I don't believe there should be an 's' at the end of "change".

2023-06-27 20:25 UTC, MichaelBaj commented on docs/config_bgp.md
> +## BGP over SVR Inter-Hub Steering
This is a good introduction paragraph, but it doesn't provide explanation for when it should be used. Under what conditions should this policy be applied?

2023-06-28 13:22 UTC, MarkusJork commented on docs/config_bgp.md
> +```
This needs to say that the above config snippet is an action inside a routing policy.
In context, it would look like this:

    authority
        routing
            policy spoke-to-hub
                name spoke-to-hub

                statement  s0
                    name    s0
                    policy  accept

                    action  set-path-based-as-path
                        type            set-path-based-as-path
                        prepend         65001
                        service-policy  prefer-mpls-hub1
                    exit
                exit
            exit

2023-06-28 13:58 UTC, MarkusJork commented on docs/config_bgp.md
> +## BGP over SVR Inter-Hub Steering
Here is a suggestion for an initial intro text answering that question:

In an SVR hub & spoke topology where a spoke connects to more than one hub router, it may be desirable to align service-policy based peer-path selection (between spoke and the hubs) with the BGP next-hop selection. The BGP next-hop (i.e. hub) that the spoke selects should correspond to the best available peer-path at any time.

2023-06-29 13:13 UTC, MarkusJork commented on docs/config_bgp.md
> +    action set-path-based-as-path
You lost the `statement 1` that you had here before.
This `action` needs to be inside a `statement`.

2023-06-29 13:14 UTC, MarkusJork commented on docs/config_bgp.md
> +    type             set set-path-based-as-path
remove the extra `set `

2023-06-29 14:13 UTC, Chr1st0ph3rTurn3r commented on docs/config_bgp.md
> +    action set-path-based-as-path
done

2023-06-29 14:59 UTC, MarkusJork commented on docs/config_bgp.md
> +3. Configure a routing policy that includes the new routing policy `path-based` action. See [Configuration Commands](#configuration-commands) below for additional information.
this should probably say `set-path-based-as-path` instead of `path-based`

2023-06-29 14:59 UTC, MarkusJork commented on docs/config_bgp.md
> +    action set-path-based-as-path
Now you also need the matching `exit` at the end for the `statement`.
And you might as well adjust the indentation to look like this:

    policy spoke-to-hub
        statement 1
            action set-path-based-as-path
                ...
            exit
        exit
    exit

2023-06-29 17:25 UTC, MarkusJork approved these changes

2023-06-29 18:14 UTC, MichaelBaj approved these changes

2023-06-29 21:42 UTC, closed without merging