6.1.4 r2 release docs
128technology/docs pull request #578
Opened 2023-06-28 23:43 UTC by Chr1st0ph3rTurn3r

2023-06-29 00:08 UTC, hadrielk commented on docs/release_notes_128t_6.1.md
> +  - Provides the ability to walk packet buffer pools, count locations, and display information
That's much too far into the weeds/details of implementation, in my opinion.

But I'll let @MichaelBaj and @ayungelson weigh in.

2023-06-29 00:09 UTC, hadrielk commented on docs/release_notes_128t_6.1.md
> +- **I95-50632 Add Buffer tracking monitoring to lockup detector:** LockupDetector is now able to identify and take corrective action should a network packet pool buffer exhaustion event occur.
that's not a new "customer feature" - it's more of a bug fix or design-bug fix, and shouldn't really be in this section, imo.

2023-06-29 00:11 UTC, hadrielk commented on docs/release_notes_128t_6.1.md
> +- **I95-48792 Encryption on Multicast not working correctly:** Encryption actions have been enhanced on all service paths. (I don't understand how a customer can report an issue with this, when we ha
yeah, remove this

2023-06-29 00:12 UTC, hadrielk commented on docs/release_notes_128t_6.1.md
> +- **I95-48965 Race condition with routing updates inducing crash in highway process:** Resolved an issue where a routing change that affects the `forwarding-table` can incur a race condition with ses
this was fixed in a previously released patch to `6.1` - it's not newly fixed in `6.1.4-r2`, afaik.

2023-06-29 00:13 UTC, hadrielk commented on docs/release_notes_128t_6.1.md
> +  - save packet-buffer snapshot
this was already mentioned above on line 85.

2023-06-29 00:19 UTC, hadrielk commented on docs/release_notes_128t_6.1.md
> +- **I95-51053 ESP session stuck in Incomplete state:** Resolved an issue with DSCP session modification. An exception is no longer thrown if the FIB is not found.
'Exceptions being thrown' does not mean anything to customers - this bug fixed an issue whereby SVR sessions from `network-interface`s with `dscp-steering` `enabled` can be stuck in an incomplete state.

2023-06-29 00:25 UTC, hadrielk commented on docs/release_notes_128t_6.1.md
> +- **I95-51167 Unable to override auto-generated peer service-route:** Updated StepTopology to not override modified auto-generated peer service-route.
`StepTopology` is, as far as I know, only an internal code name.

The fix allows the customer to provision a `service-route` with the same `name` as an automatically-generated one, such that the customer's `service-route` takes precedence and will be used instead of generating one.

2023-06-29 00:30 UTC, hadrielk commented on docs/release_notes_128t_6.1.md
> +- **I95-51203 Update stats retention periods:** Some of the `process/thread/queue` and `process/thread/task` statistics are now recorded for a longer time period, and are available in custom charts a
This was actually partially undone/reverted by [I95-51406](https://128technology.atlassian.net/browse/I95-51406), such that only some of the `process/thread/queue` statistics are recorded for a longer period of time.

So please remove "and `process/thread/task`" from the above.

2023-06-29 00:34 UTC, hadrielk commented
Out of curiosity, is there a reason the bug-fixed section is not in Jira-numeric order? Or does that happen later?

2023-06-29 00:37 UTC, ayungelson commented on docs/release_notes_128t_6.1.md
> +  - Provides the ability to walk packet buffer pools, count locations, and display information
I am totally OK not adding release notes for this instrumentation that we did. I am even OK not documenting the pcli command. I am not expecting customers to ever have to use it.
I wouldn't even call it a new feature, just debugging enhancements.

2023-06-29 00:38 UTC, ayungelson commented on docs/release_notes_128t_6.1.md
> +- **I95-50632 Add Buffer tracking monitoring to lockup detector:** LockupDetector is now able to identify and take corrective action should a network packet pool buffer exhaustion event occur.
Agreed - NOT a new feature, it's an enhancement on the lockup detector.  Bug fix.

2023-06-29 00:43 UTC, ayungelson commented on docs/release_notes_128t_6.1.md
> +- **I95-466 LAG/LACP Support:** Link Aggregation Groups are formed by connecting multiple ports in parallel between two devices. LACP is the protocol that defines how the group of interfaces operates
This feature is not customer ready - @MichaelBaj should this be documented here?

2023-06-29 15:23 UTC, MichaelBaj requested changes

2023-06-29 15:23 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-50338 About this System link on GUI not working:** The link target is no longer valid, and the link has been removed from the GUI.
should "About this System" be in quotes?

2023-06-29 15:23 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-51178 Increase default `juteMaxBufferSize`:** The default `juteMaxBufferSize` has been increased to 10MB.
It is important to explain why this is needed for customers.
The default `juteMaxBufferSize` has been increased to 10MB, which addresses issues where the device is unable to commit very large configurations.

2023-06-29 18:44 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-20864 Support for Multicast:** Multicast over SVR is now supported, and is a “one source, many destinations” method of traffic distribution. For more information, see [Multicast](config_multi
removed the "over SVR" reference. Rather than calling out both "PIM-SM" and SVR in the release notes, it makes more sense to keep that info in the feature doc.

2023-06-29 18:46 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-50973 DSCP Steering with BGP over SVR:** Need clarification from Markus how BGP operates with DSCP steering.
Researched the feature, and no additional documentation is necessary. It just works due to App steering work.

2023-06-29 18:48 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-51039 / I95-50949 Create PCLI commands for buffer tracking tools:** The following PCLI commands have been created for buffer tracking.
done

2023-07-12 23:50 UTC, migolnikov commented on docs/release_notes_128t_6.1.md
> +- **I95-48922 Common Criteria Certification - Network Device Protection Profile:** Waiting for Max's input on this.
I do not see https://128technology.atlassian.net/browse/I95-51105 mentioned. That one was the last one to go in. It is directly related to https://128technology.atlassian.net/browse/IN-533 that was part of 3.2.0 installer.
@ecarson wanted to add a special note on some behavior differences that may be experienced by customers who are importing older ISOs that may not have the needed checksums

- [ ] Check with @ecarson

2023-07-14 14:01 UTC, MichaelBaj requested changes

2023-07-14 14:01 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-51951 Packets not being properly encapsulated in BFD:** PathMetrics drop packets are now properly encapsulated when SVR over BFD feature is enabled.
Internal names such as "PathMetrics" should be converted to customer readable terms, unless the process/code name is material to the point. Just "Path metric drop...."

2023-07-14 14:01 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-52083 Race condition with `application-identification`:** Resolved a race condition on low-end systems running `application-identification` resulting in a failure of packet forwarding.
What is a "low-end" system? We need to be specific about the system type. Is this 4 core 8GB RAM? Is this a SSR120? Need to be specific.

2023-07-14 15:51 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.1.md
> +## Release 6.1.4-23.r2.v1
.v1 to be removed

2023-07-14 15:52 UTC, jeffmart-jnpr commented on docs/about_releases.mdx
> +| Release 6.1 | [6.1.0](release_notes_128t_6.1.md#release-610-55) | April 14, 2023 | [6.1.4](release_notes_128t_6.1.md#release-614-23r2v1) | January 14, 2024 |   July 14, 2024 |
v1 to be removed

2023-07-14 16:08 UTC, ecarson commented on docs/release_notes_128t_6.1.md
> +- **I95-51105 Options added to the import operation to enable or disable checking the signatures of RPMs:** The `import iso` command now optionally verifies the signatures of all imported rpms. This
The problem is for historical ISOs. We discovered to our chagrin that we had been missing signing some of the rpm contents in the ISOs since day 1. This was corrected for only recent ISOs so we need the ability to override.

The behavior is for 6.1.4-r2:
- By default, check for the presence of rpm signatures when importing via UI or API. Optionally, these can be ignored to allow older ISOs to work.
- Pre < 6.1.4-r2 and < 6.0.<next>, rpm signatures will not be checked in any way (current behaviour)

I thinkt he wording is a little confusing here so maybe this is better:
```
- **I95-51105 Options added to the import operation to enable or disable checking the signatures of RPMs:** The `import iso` command now verifies the signatures of all imported rpms. This behavior can be optionally controlled from the PCLI by passing in the `check-rpm-signature {required | allow-unsigned | disabled}` option to require that all rpms are signed and verified, allow importing isos with unsigned rpms but verify those that are signed, or to disable the signature checking altogether.
```

2023-07-14 17:05 UTC, MichaelBaj submitted a review, later dismissed

2023-07-14 18:00 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.1.md
> +- **I95-50810 IDP Custom Rules and Policies:** Users can customize an existing base IDP policy by creating exception-based rules. Using an existing IDP policy, you can modify the profile to allow the
Need to change the jira ID with I95-48014

2023-07-14 18:05 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.1.md
> +- **I95-51105 Options added to the import operation to enable or disable checking the signatures of RPMs:** The `import iso` command now verifies the signatures of all imported RPMs. This is controll
Do we know what the default is for this?  I would expect that it would be "required" but it would be good to just state it so we know.

2023-07-14 18:09 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-51105 Options added to the import operation to enable or disable checking the signatures of RPMs:** The `import iso` command now verifies the signatures of all imported RPMs. This is controll
I'll ask Evan.

2023-07-14 18:53 UTC, jeffmart-jnpr approved these changes
Need to update the Jira and put in

2023-07-14 18:59 UTC, MichaelBaj approved these changes

2023-07-14 19:37 UTC, merged