Release notes for 5.6.9
128technology/docs pull request #582
Opened 2023-07-10 16:37 UTC by Chr1st0ph3rTurn3r

2023-07-10 17:19 UTC, MichaelBaj requested changes

2023-07-10 17:53 UTC, hadrielk commented on docs/release_notes_128t_5.6.md
> +- **I95-48931 Service area Highway crash:** Now prevent crashing in SSR's highway process in unusual race conditions when a session's flow is removed before the session is fully established.
or even "rare"?

2023-07-10 17:54 UTC, hadrielk commented on docs/release_notes_128t_5.6.md
> +- **I95-49587 ICMP session classification improvement:** The application lookup for ICMP sessions has been optimized to accurately identify the correct service.
Lol, that's not _exactly_ "optimized".

How about "fixed".

2023-07-10 17:56 UTC, hadrielk commented on docs/release_notes_128t_5.6.md
> +- **I95-51621 Provide a way for the user to display the history of configuration stored on disk:** Users can now use the `show diskcache` command to retrieve metadata information about the current ru
They named such a command "`show diskcache`"?!?

Ugh.

2023-07-10 18:17 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.6.md
> +- **I95-48931 Service area Highway crash:** Now prevent crashing in SSR's highway process in unusual race conditions when a session's flow is removed before the session is fully established.
I like rare.

2023-07-10 18:29 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.6.md
> +- **I95-51621 Provide a way for the user to display the history of configuration stored on disk:** Users can now use the `show diskcache` command to retrieve metadata information about the current ru
checking...

2023-07-10 20:23 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> -- **I95-51621 Provide a way for the user to display the history of configuration stored on disk:** Users can now use the `show diskcache` command to retrieve metadata information about the current ru
Was this supposed to be removed?

2023-07-10 20:27 UTC, MichaelBaj approved these changes

2023-07-19 12:39 UTC, MichaelBaj approved these changes

2023-07-19 12:43 UTC, hadrielk approved these changes

2023-07-19 15:53 UTC, merged