Removed references from CentOS from docs
128technology/docs pull request #583
Opened 2023-07-10 22:38 UTC by MichaelBaj

Took some creative license with regard to removing mention of CentOS from our docs. Please review carefully and suggest alternatives.

2023-07-10 22:45 UTC, hadrielk submitted a review, later dismissed

2023-07-10 23:05 UTC, reidstidolph-JNPR requested changes
Generally suggesting we remove places where CentOS version numbers are mentioned.

2023-07-10 23:05 UTC, reidstidolph-JNPR commented on docs/release_notes_128t_installer_2.6.md
> +- **IN-261** - Installation using a SSR-OS 7.3 base is no longer supported.
This might actually be a place where referring to CentOS makes sense. Suggest saying:
"Installation using a CentOS base is no longer supported."

2023-07-10 23:54 UTC, reidstidolph-JNPR approved these changes

2023-07-12 12:30 UTC, Chr1st0ph3rTurn3r approved these changes

2023-07-12 12:55 UTC, merged