Added stronger language regarding deploying a conductor behind an SSR
128technology/docs pull request #586
Opened 2023-07-12 18:34 UTC by laneshields

2023-07-12 18:49 UTC, Chr1st0ph3rTurn3r requested changes

2023-07-12 18:49 UTC, Chr1st0ph3rTurn3r commented on docs/bcp_conductor_deployment.md
> +When deploying your conductor behind another SSR at a data center, it opens the question of using Secure Vector Routing to reach the conductor using SVR peer paths between a branch and the data cente
conductor communication... 
(typo)

2023-07-12 20:47 UTC, MichaelBaj submitted a review, later dismissed

2023-07-13 16:03 UTC, MichaelBaj approved these changes

2023-07-13 16:24 UTC, Chr1st0ph3rTurn3r approved these changes

2023-07-13 16:24 UTC, merged