Release notes for 5.5.10
128technology/docs pull request #590
Opened 2023-07-26 13:11 UTC by Chr1st0ph3rTurn3r

2023-07-26 14:04 UTC, MichaelBaj requested changes

2023-07-26 14:04 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-52283 Correct the Domain Matching order:** When using Web-Filtering, the SSR now properly matches against domain-name services if no url-based services are found.
- **I95-52283 Correct the Domain Matching order:** When using web filtering, the SSR now properly enforces the matching order documented [here|https://www.juniper.net/documentation/us/en/software/session-smart-router/docs/config_domain-based_web_filter/#service-matching-order]

2023-07-26 15:10 UTC, MichaelBaj submitted a review, later dismissed

2023-07-31 15:30 UTC, MichaelBaj submitted a review, later dismissed

2023-07-31 16:17 UTC, jeffmart-jnpr approved these changes

2023-07-31 16:28 UTC, hadrielk commented on docs/release_notes_128t_5.5.md
> +	- `save packet-buffer snapshot`
I thought we decided not to document these, no @ayungelson?

2023-07-31 18:09 UTC, merged