Conductor deployment guide
128technology/docs pull request #591
Opened 2023-07-28 17:57 UTC by Chr1st0ph3rTurn3r

2023-08-03 17:59 UTC, MichaelBaj requested changes

2023-08-03 17:59 UTC, MichaelBaj commented on docs/ha_conductor_install.mdx
> +title: High Availability Conductor Installation
All of my comments on `single_conductor_install.mdx` are applicable to this file as well.

2023-08-03 17:59 UTC, MichaelBaj commented on docs/ha_conductor_install.mdx
> +## Install the First Conductor HA Node
It would be beneficial to have a digram of SSR 1300s (acting as conductors) indicating how physical ports should be configured. Since this section discusses management ports, and HA sync ports and reachability, it would be better to provide a blueprint for customers to follow.

2023-08-03 17:59 UTC, MichaelBaj commented on docs/ha_conductor_install.mdx
> +3. Enter the **HA Peer Credentials**. This is a one time operation for the initialization of the second HA Node with the first HA Peer. The `t128` user can be used for this operation.
The `t128` user can be used for this operation.
What other user can be used for this operation? We should be explicit in this step for which user account to use.
Additionally, it should be added as a note that this one time operation has no impact on future changes to users and their passwords. Once HA is established between conductor nodes, security keys are exchanged for secure communication and not passwords.

2023-08-08 17:02 UTC, Chr1st0ph3rTurn3r commented on docs/ha_conductor_install.mdx
> +## Install the First Conductor HA Node
Still working on this diagram. Will include in the next edits/push.

2023-08-10 20:51 UTC, Chr1st0ph3rTurn3r commented on docs/ha_conductor_install.mdx
> +## Install the First Conductor HA Node
Added. Am reaching out to Adam for review - sending him a pdf.

2023-08-11 13:03 UTC, MichaelBaj approved these changes

2023-08-17 13:59 UTC, MichaelBaj requested changes

2023-08-17 13:59 UTC, MichaelBaj commented on docs/_install_verify_conductor_install.md
> +1. Login using the Admin credentials.
recommend changing "Admin" to "admin" because that is how you would enter it on the command line.

2023-08-17 13:59 UTC, MichaelBaj commented on docs/_install_verify_conductor_install.md
> +CentOS Linux 7 (Core)
Not sure why these two lines with "CentOS and Kernel" are here

2023-08-18 19:03 UTC, MichaelBaj approved these changes

2023-08-18 19:31 UTC, merged