5.6.10 release notes
128technology/docs pull request #594
Opened 2023-08-09 16:12 UTC by Chr1st0ph3rTurn3r

2023-08-09 18:28 UTC, MichaelBaj requested changes

2023-08-09 18:28 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-51336 App-ID stats entry leaked in some session building exceptions:** Resolved an issue where the `app-id stats` entry was not added to the `Expiring` list to be cleaned up.
While the Jira talks about "stats entries are being leaked", this really amount to a memory leak.
**I95-51336 App-ID memory leak for some uncommon cases, such a duplicate flow:** Resolved an issue where the `app-id stats` entry was not added to the `Expiring` list to be cleaned up.

2023-08-09 18:28 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I9552208 Queries return incomplete data with FIPS enabled:** Resolved an issue where a FIPS-incompatible hashing function was causing missing or incomplete metrics data.
What queries? Also, missing hyphen
**I95-52208 metrics queries return incomplete data when FIPS is enabled: Resolved an issue where a FIPS-incompatible hashing function was causing missing or incomplete metrics data.

2023-08-09 20:06 UTC, MichaelBaj approved these changes

2023-08-18 19:45 UTC, MichaelBaj requested changes

2023-08-18 19:45 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-41386/I95-52114 HA pair device interface's redundancy status stays non-redundant even though the interface operational status is up:** Resolved an issue where zookeepper enters a leaderless s
Suggested rewording
- **I95-41386/I95-52114 HA pair device interface's redundancy status stays non-redundant even though the interface operational status is up after both nodes simultaneously come online, as in the case of power failures:** Resolved a race condition where zookeepper enters a leaderless state when a disconnection occurs right after an electorate ephemeral node is created, and before running a success callback.

2023-08-18 19:45 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-52650 Create a cache of the common file root hash calculation:** An optimization was made to an internal calculation and improve the speed at which synchronization requests are processed.
Suggested rewording:

- **I95-52650 Asset state transition on conductor is slow for deployments with greater than 250 routers:** An optimization was made to an internal calculation and improve the speed at which synchronization requests are processed.

2023-08-19 02:34 UTC, hadrielk commented on docs/release_notes_128t_5.6.md
> +- **I95-41386/I95-52114 HA pair device interface's redundancy status stays non-redundant even though the interface operational status is up:** Resolved an issue where zookeepper enters a leaderless s
1. "zookeeper" is misspelled as "zookeepper" in both the original and your rewording.
2. Do these internal details about zookeeper and such really mean anything to customers?

2023-08-19 02:36 UTC, hadrielk commented on docs/release_notes_128t_5.6.md
> +- **I95-52198 Handle incoming public keys from peer conductor node:** Added functionality to allow conductor nodes to share the authorized keys of managed routers between each other. If the SSH publi
the word "it's" at the end of the paragraph should be "its".

2023-08-19 02:40 UTC, hadrielk commented on docs/release_notes_128t_5.6.md
> +- **I95-52626 Forwarding plane control message bursts create exception, causing a packet buffer leak:** Resolved a condition where backpressure from fastlane caused the messaging mechanism between hi
again, I'm not sure we should be documenting this level of internal details, which are not meaningful to customers.

2023-08-28 14:54 UTC, MichaelBaj approved these changes

2023-08-28 14:55 UTC, MichaelBaj requested changes
Still need to make requested changes.

2023-08-29 15:56 UTC, hadrielk commented on docs/release_notes_128t_5.6.md
> +- **I95-41386/I95-52114 HA pair device interface's redundancy status stays non-redundant even though the interface operational status is up:** Resolved a race condition where a disconnection occurs r
This resolution isn't meaningful to customers; I suggest it be:

"Resolved a race condition when selecting the active components between HA nodes."

2023-08-29 15:58 UTC, hadrielk commented on docs/release_notes_128t_5.6.md
> +- **I95-52316 Enhancements to Overlapping FIB Services:** When creating FIB entries, we now consider services that match the route update but do not have the best match service address.
I believe this requires setting an authority-wide configuration knob, no?

2023-08-29 15:59 UTC, hadrielk commented on docs/release_notes_128t_5.6.md
> +- **I95-52626 Forwarding plane control message bursts create exception, causing a packet buffer leak:** Resolved a condition where backpressure caused the messaging mechanism to develop buffer leaks.
I would remove the "Additionally, ..." last sentence.

2023-08-29 17:38 UTC, Bhautik approved these changes

2023-08-29 20:02 UTC, hadrielk approved these changes

2023-08-29 20:03 UTC, MichaelBaj approved these changes

2023-08-29 20:22 UTC, merged