adding session optimization documentation
128technology/docs pull request #595
Opened 2023-08-09 20:00 UTC by Chr1st0ph3rTurn3r

2023-08-10 00:24 UTC, reidstidolph-JNPR requested changes
Requesting clarification on what "WAN optimization features that employ flow move or route modify" means, that a typical user without deep implementation knowledge would understand.

2023-08-10 00:24 UTC, reidstidolph-JNPR commented on docs/config_session_optimization.md
> +Because the packets that are stored for this feature cannot be easily backed up and recovered `session-optimization` should not be configured on High Availability nodes, or inline with other WAN opti
"...employ flow move or route modify." Can we put this in terms that a customer would understand? I'm not even sure what situations we are describing here, which should be avoided.

2023-08-11 13:41 UTC, Chr1st0ph3rTurn3r commented on docs/config_session_optimization.md
> +Because the packets that are stored for this feature cannot be easily backed up and recovered `session-optimization` should not be configured on High Availability nodes, or inline with other WAN opti
the section has been revised with input from Don Troshynski.

2023-08-11 19:29 UTC, ayungelson commented on docs/config_session_optimization.md
> +1. Set a [`traffic-engineering transmit-cap`](config_reference_guide.md#traffic-engineering) of 10Mbs (or maybe 25Mbps - checking on this) or lower on the desired device-interface.
the limit in the code now is 30 Mbps

2023-08-11 19:29 UTC, ayungelson commented on docs/config_session_optimization.md
> +Session failover for optimized sessions is not supported in HA configurations.
I am 100% certain that there are more features that are not supported when session opt is enabled. The list of limitations is probably a mile long.  I am guessing that app-id would be severely affected. @svjaffer would be able to comment more. This feature is very limited, and hasn't really been battle tested for many years at this point and for every POC that tried to use it, it fell short.

2023-08-17 13:56 UTC, MichaelBaj requested changes

2023-08-17 13:56 UTC, MichaelBaj commented on docs/config_session_optimization.md
> +Session failover for optimized sessions is not supported in HA configurations.
Recommended proposal. Rather than listing all features that may not work, instead define how this feature is known to work.

Session failover is designed to work in non-HA configurations without other features enabled.

Obviously "other features enabled" is too broad. Need help with clarification.

2023-12-14 15:02 UTC, merged