Release notes for 5.5.11
128technology/docs pull request #596
Opened 2023-08-17 13:18 UTC by Chr1st0ph3rTurn3r

2023-08-17 13:45 UTC, MichaelBaj requested changes

2023-08-17 13:45 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-52626 Ring push exception causing a packet buffer leak:** Resolved a condition where backpressure from fastlane caused the messaging mechanism between highway manager and fastlane to get stuc
Recommended changes:

- **I95-52626 Forwarding plane control message bursts create exception, causing a packet buffer leak:** Resolved a condition where backpressure from fastlane caused the messaging mechanism between highway manager and fastlane to drop mbufs. Proper handling of exception now prevents buffer leaks. Additionally, increased the control buffer capacity to better handle bursts as part of the resolution.

2023-08-18 19:13 UTC, MichaelBaj approved these changes

2023-08-21 15:59 UTC, Bhautik approved these changes

2023-08-21 16:39 UTC, merged