DHCP Relay Best Practices Doc
128technology/docs pull request #597
Opened 2023-08-17 20:37 UTC by Chr1st0ph3rTurn3r

2023-08-28 20:28 UTC, MichaelBaj requested changes

2023-08-28 20:28 UTC, MichaelBaj commented on docs/bcp_dhcp_relay_overview.md
> +The following characteristics define the standard model where DHCP Relay is implemented:
I find this statement confusing. DHCP Relay server can be deployed in any number of locations. I don't believe we can state that the DHCP server location can be standardized.

Isn't this unnumbered list more of an overview of the described topology?

2023-08-28 20:28 UTC, MichaelBaj commented on docs/bcp_dhcp_relay_overview.md
> +A service-route is configured on the Branch1 and Enterprise DC routers referencing the DHCP relay service, with a service-agent next-hop pointing to the real DHCP server.
can "real DHCP server" instead be "IP of the DHCP server". Additionally, it would be beneficial to explain that the `nat-target` in the example below is the address of the DHCP server.

2023-08-28 20:28 UTC, MichaelBaj commented on docs/bcp_dhcp_relay_overview.md
> +On the router identified to relay DHCP requests (Branch 2), the unique tenant created must be applied to the network-interface `lan1`. DHCP requests broadcast here are tagged by the tenant and associ
"On the router processing the DHCP relay requests (Branch 2), ..."

2023-08-28 20:28 UTC, MichaelBaj commented on docs/bcp_dhcp_relay_overview.md
> +                        reverse-arp-mac-learning 				true
I don't believe `reverse-arp-mac-learning` and `off-subnet-reverse-arp-mac-learning` are germane to this example.

2023-08-28 20:28 UTC, MichaelBaj commented on docs/bcp_dhcp_relay_overview.md
> +Building upon the earlier configuration and the information above, all that is needed to add additional DHCP servers is an additional **service-route** for each DHCP server. In our example configurat
need space after closing paren.
Same comment as above, explain the IPs in the config - especially since the IPs are different. The first example has `172.16.3.1`, the second example has `172.16.1.3` and `172.16.1.4` respectively. Typo?

2023-08-28 20:28 UTC, MichaelBaj commented on docs/bcp_dhcp_relay_overview.md
> +By default, the SSR will auto-generate service-routes and services for each DHCP server on the connected branch. This is good for SVR without BGP. To make DHCP relay work for with BGP over SVR, we ne
"To make DHCP relay work for with" - drop the "for".
Additionally, instead of "we need to deviate from" - "we need to make additional changes to the auto generated configuration".

2023-08-28 20:28 UTC, MichaelBaj commented on docs/bcp_dhcp_relay_overview.md
> +````
one extra back tick

2023-08-30 17:14 UTC, mansley12 requested changes

2023-08-30 17:14 UTC, mansley12 commented on docs/bcp_dhcp_relay_overview.md
> +
Add branch 2 here from the above comments.

2023-08-30 17:14 UTC, mansley12 commented on docs/bcp_dhcp_relay_overview.md
> +					tenant				dhcp.demo
change to lan

2023-08-30 17:14 UTC, mansley12 commented on docs/bcp_dhcp_relay_overview.md
> +			router				Branch1
Add router Branch 2 above this. See earlier comments

2023-08-30 17:14 UTC, mansley12 commented on docs/bcp_dhcp_relay_overview.md
> +By default, the SSR will auto-generate service-routes and services for each DHCP server on the connected branch. This is good for SVR without BGP. To make DHCP relay work with BGP over SVR, we need t
" By default, the SSR will auto-generate service-routes and services for each DHCP server on the connected branch." -> " By default, the SSR will auto-generate service-routes and services for each DHCP server."

2023-08-30 20:16 UTC, MichaelBaj requested changes

2023-08-30 20:16 UTC, MichaelBaj commented on docs/bcp_dhcp_relay_overview.md
> +                            gateway 			 172.26.2.2
This should probably be `172.26.2.1` as the gateway is almost always the lowest address in the subnet.

2023-08-30 20:16 UTC, MichaelBaj commented on docs/bcp_dhcp_relay_overview.md
> +                            gateway 			 172.26.2.2
Same here.

2023-08-30 20:16 UTC, MichaelBaj commented on docs/bcp_dhcp_relay_overview.md
> +                            gateway 			 172.26.2.2
same here

2023-08-31 14:13 UTC, MichaelBaj approved these changes

2023-08-31 15:16 UTC, mansley12 requested changes

2023-08-31 15:16 UTC, mansley12 commented on docs/bcp_dhcp_relay_overview.md
> +                        source-nat               true
remove source nat here.

2023-08-31 15:16 UTC, mansley12 commented on docs/bcp_dhcp_relay_overview.md
> +		conductor-address	192.168.1.7
remove conductor address

2023-08-31 15:16 UTC, mansley12 commented on docs/bcp_dhcp_relay_overview.md
> +			router				Branch1
fix indent

2023-08-31 15:16 UTC, mansley12 commented on docs/bcp_dhcp_relay_overview.md
> +		conductor-address	192.168.1.7
remove conductor address

2023-08-31 15:16 UTC, mansley12 commented on docs/bcp_dhcp_relay_overview.md
> +			node		node1
may need to tweak indentation here too if others are fixed.

2023-08-31 15:16 UTC, mansley12 commented on docs/bcp_dhcp_relay_overview.md
> +			node	node1
fix indentation

2023-08-31 16:49 UTC, mansley12 submitted a review, later dismissed

2023-08-31 16:49 UTC, mansley12 commented on docs/bcp_dhcp_relay_overview.md
> +exit
Sent you the format

2023-08-31 16:49 UTC, mansley12 commented on docs/bcp_dhcp_relay_overview.md
> +exit
sent you the format

2023-08-31 18:22 UTC, MichaelBaj approved these changes

2023-08-31 18:56 UTC, merged