Vmware getting started doc
128technology/docs pull request #598
Opened 2023-08-24 16:59 UTC by Chr1st0ph3rTurn3r

2023-08-28 20:46 UTC, MichaelBaj requested changes

2023-08-28 20:46 UTC, MichaelBaj commented on docs/install_vmware_config.mdx
> +- Download the SSR package-based or image-based ISO. Refer to [Downloading ISOs](intro_downloading_iso.md)
As of today I don't believe there is a use case where image-based deployments can work for ESXi since they will be conductor-managed.
@agrawalkaushik could an ESXi be managed as a whitebox in Mist?

2023-08-28 20:46 UTC, MichaelBaj commented on docs/install_vmware_config.mdx
> +In order to perform the configuration and installation of the SSR software, you must have a properly installed and working configuration of VMware ESXi. This documentation references VMware ESXi vers
Typo "Additoinally"

2023-08-28 20:46 UTC, MichaelBaj commented on docs/install_vmware_config.mdx
> +- Download the SSR package-based or image-based ISO. Refer to [Downloading ISOs](intro_downloading_iso.md)
Also, need to confirm from @drcosic if `qcow` should be used for ESXi.
Should (https://www.juniper.net/documentation/us/en/software/session-smart-router/docs/intro_downloading_iso/#downloading-an-iso) be updated?

2023-08-28 20:46 UTC, MichaelBaj commented on docs/install_vmware_config.mdx
> +	- Set the number of CPU’s to at least 4.
You should reference the min specs here as well as reference our scaling guidelines.

2023-08-28 20:46 UTC, MichaelBaj commented on docs/install_vmware_config.mdx
> +	- Set hard disk 1 to a minimum of 26GB.
26GB is lower than our minimum guidelines.

2023-08-28 20:46 UTC, MichaelBaj commented on docs/install_vmware_config.mdx
> +8. Click the **Add network adapter** button two times, so you have a total of three network adapters available.
total of three? I would say, minimum of three. They should define however many they need.

2023-08-28 20:46 UTC, MichaelBaj commented on docs/install_vmware_config.mdx
> +	- Expand each network adapter by clicking the small triangle and set the **Adapter Type** on each network adapter to be **E1000e**.
@jacobdionne I thought we don't recommend `e1000` driver any more. Even for ESXi.

2023-08-28 22:23 UTC, jacobdionne commented on docs/install_vmware_config.mdx
> +	- Expand each network adapter by clicking the small triangle and set the **Adapter Type** on each network adapter to be **E1000e**.
I believe `vmxnet3` should be the best performant (or SR-IOV passthrough actually). However I think `e1000` is what was tested and qualified. There are some Jiras that suggest some issues were hit with vmxnet3. The ESXi version being used could also factor in what works and what doesn't

2023-09-01 19:01 UTC, Chr1st0ph3rTurn3r commented on docs/install_vmware_config.mdx
> +- Download the SSR package-based or image-based ISO. Refer to [Downloading ISOs](intro_downloading_iso.md)
Based on what you say above - ESXi is conductor managed - and qcow is only available for image-based installs, no the qcow cannot be used for ESXi.

2023-10-05 19:33 UTC, MichaelBaj approved these changes
Not having gone through this exercise myself, I can't speak the accuracy, but my comments have now been addressed.

Please note that there is a TODO in here and needs to be addressed prior to publishing.

2023-10-05 21:57 UTC, merged