6.1.5 release notes
128technology/docs pull request #602
Opened 2023-09-06 14:49 UTC by Chr1st0ph3rTurn3r

2023-09-07 15:48 UTC, MichaelBaj requested changes

2023-09-07 15:48 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-50708 Significant decrease in memory usage for the salt_master process:** **NEED INFO FROM DEV ON THIS - STILL WAITING**
After reviewing the defect notes, here is my take:

- **I95-50708 Time series data for memory of the salt_master process periodically significantly decreases:** Incorrect method for polling application memory data; this resulted in dips in application memory being presented.

2023-09-07 15:48 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-51766 Enable TX lockup detector for bond interfaces:** The datapath lockup detection mechanism has been re-enabled to run on bond interfaces.
Suggested rewording:

- **I95-51766 TX lockup detector not enabled for LAG/bonded interfaces:** The datapath lockup detection mechanism has been re-enabled to run on bond interfaces.

2023-09-07 15:48 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-52113 Application Director consumes a full core:** Resolved an overrun bug that was causing the Application Director to enter an endless loop when loading port ranges. This issue has been res
Suggested rewording:

- **I95-52113 Application Identification on the SSR runs at 100% CPU utilization:** Resolved an overrun bug that was causing the SSR to enter a loop when loading port ranges. This issue has been resolved.

2023-09-07 15:48 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-52491 Crash in `metadata propagate egress` with indications that the PacketControlBlock was corrupted:** Resolved an issue when metadata is segmented across two packet buffers, a function use
Suggested rewording:
- **I95-52491 Crash in highway process due to segmented metadata** Resolved an issue processing metadata that is segmented across two packet buffers. The segmented packets are no longer discarded and the dataplane no longer crashes when processing a packet comprised of segmented metadata.

2023-09-07 15:48 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **WAN-2090 Conductor managed SSR Applications in WAN Insights Showing up as Numbers:** Resolved an issue with stats APIs, which were not properly handling some internal service names.
Showing should not be capitalized

2023-09-07 16:31 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-52426 Incorrect behavior when configuring an IDP custom rule definition:** In a case where a user is modifying a rule to **decrease** the action type to an `alert`, alerts for that vulnerabil
The rule generation issue was addressed. There still is an issue with alerts, per James Silvia.

2023-09-07 18:19 UTC, MichaelBaj submitted a review, later dismissed

2023-09-07 18:19 UTC, MichaelBaj commented on docs/bcp_service-policy_defaults.md
> +ne of the most powerful aspects of the SSR data model is the flexibility offered by a `service-policy`. Giving customers the ability to configure thresholds for when traffic should migrate from path
Accidentally removed the 'O'

2023-09-07 18:19 UTC, MichaelBaj commented on docs/config_command_guide.md
> +Authority configuration is the top-most level in the 128T router configuration hierarchy.
This should read SSR configuration, and all instances throughout

2023-09-07 18:21 UTC, hadrielk commented on docs/release_notes_128t_6.1.md
> +- **I95-48174 Expand supported values for DHCP option:** DHCP option 43 is now a supported option, as well as a binary encoded-type (hex/byte) support. Valid examples are `0xabcdef` and `0x123456`.
this is arguably a feature rather than a bug fix.

2023-09-11 19:18 UTC, jamesesilvia submitted a review, later dismissed

2023-09-13 13:55 UTC, MichaelBaj submitted a review, later dismissed

2023-09-13 20:35 UTC, avinashbhat80 approved these changes

2023-09-20 15:36 UTC, ayungelson commented on docs/release_notes_128t_6.1.md
> +- **I95-52279 Prevent VRRP Virtual MACs from being dropped by Bond interface in LACP mode:**  Packets with VRRP virtual dest MACs are now processed by the Bond interface when using LACP.
I think we should remove this as this was only a partial fix and didn't work for x710 NICs. The final fix for VRRP should come in 6.1.6.

2023-09-22 16:15 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.1.md
> +- **I95-52316 Enhancements to Overlapping FIB Services:** The [`fib-service-match`](config_command_guide.md#configure-authority-fib-service-match) command allows you to configure either `best-match-o
@MichaelBaj is this issue resolved?

2023-09-22 17:16 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.1.md
> +- **The following CVEs have been resolved in this release:** I95-51431, I95-51758, I95-52495, I95-52496, I95-52497, I95-52509, I95-52554, I95-52625, I95-52645, I95-52956,
has been updated

2023-09-22 17:17 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.1.md
> +- **I95-50708 Significant decrease in memory usage for the salt_master process:** **NEED INFO FROM DEV ON THIS - STILL WAITING**
Looks like this has been updated.

2023-09-22 17:19 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.1.md
> +- **I95-52279 Prevent VRRP Virtual MACs from being dropped by Bond PMD in LACP mode:**  Packets with VRRP virtual dest MACs are now processed by the Bond PMD when using LACP.
Looks like this is resolved

2023-09-22 17:21 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.1.md
> +- **I95-52491 Crash in `metadata propagate egress` with indications that the PacketControlBlock was corrupted:** Resolved an issue when metadata is segmented across two packet buffers, a function use
Looks to be resolved

2023-09-22 17:39 UTC, MichaelBaj approved these changes

2023-09-22 20:08 UTC, jeffmart-jnpr approved these changes

2023-09-22 20:08 UTC, merged