adding static NAT info
128technology/docs pull request #603
Opened 2023-09-11 19:47 UTC by Chr1st0ph3rTurn3r

2023-09-12 13:04 UTC, MichaelBaj requested changes

2023-09-12 13:04 UTC, MichaelBaj commented on docs/config_nat.md
> +The `spk-lan2` network-interface is not routable (cannot send or receive traffic) in the `Corp` and `Internet` networks. The Client in `spk-lan2` has local IP of `192.168.1.0`, and overlaps with the
The client in `spk-lan2` cannot have the IP of 192.168.1.0 as .0 is reserved and cannot be used.

you can change this sentence to:
"The client in `spk-lan2` has a local IP within the `192.168.1.0/24` subnet and overlaps with another client from `Corp` in `spk-lan1`.

2023-09-12 13:04 UTC, MichaelBaj commented on docs/config_nat.md
> +The same process must be applied to `spk-lan1`, in this example using the remote IP address `172.16.129.0`.
"remote IP address" should be:
"remote IP prefix"

2023-09-12 13:04 UTC, MichaelBaj commented on docs/config_nat.md
> +- On the session ingress node, the `show sessions by-id` output has an Ingress Source NAT field where the source-nat type, NAT’d source address, NAT’d port, and protocol are displayed.
Provide example, highlighting new field.

2023-09-12 13:04 UTC, MichaelBaj commented on docs/config_nat.md
> +- On the session egress node the `show sessions by-id` output has an Ingress Source NAT field where the source-nat type, NAT’d source address, NAT’d port, and protocol are displayed.
Provide example, highlighting new field.

2023-09-12 13:04 UTC, MichaelBaj commented on docs/config_nat.md
> +- The `show sessions` output has `NAT IP` and `NAT Port` columns where the NAT’d source address and NAT’d source port are displayed.
Provide example, highlighting new field.

2023-09-12 13:04 UTC, MichaelBaj commented on docs/config_nat.md
> +- On the session egress node the `show sessions by-id` output shows the NAT’d destination address in the Forward Flow `NextHop` and Reverse Flow `src ip` fields.
Provide example, highlighting new field.

2023-09-12 13:04 UTC, MichaelBaj commented on docs/config_nat.md
> +- The `show sessions` output reverse flow `src ip `column also shows the NAT’d destination address.
Provide example, highlighting new field.

2023-09-12 14:24 UTC, chao-128t commented on docs/config_nat.md
> +SSR supports source NAT pool configurations at interface and service-route level as described in [Static NAT Bindings](#static-nat-bindings). However, this is not always sufficient to enable simple c
To be more accurate, change `on a pool of IP addresses` to `between two same-sized subnets`.

2023-09-12 14:24 UTC, chao-128t commented on docs/config_nat.md
> +Static NAT defines a one-to-one mapping from one IP subnet to another IP subnet. The mapping includes destination IP address translation in one direction and source IP address translation in the reve
Mention source NAT first sounds more natural -> `The mapping includes source IP address translation in one direction and destination IP address translation in the reverse direction.`

2023-09-12 14:24 UTC, chao-128t commented on docs/config_nat.md
> +The `spk-lan2` network-interface is not routable (cannot send or receive traffic) in the `Corp` and `Internet` networks. The Client in `spk-lan2` has local IP of `192.168.1.0`, and overlaps with the
Following the sentence suggested by @MichaelBaj, you can add "By configuring `bidirectional-nat` on `spk-lan1` and `spk-lan2`, those two `192.168.1.0/24` subnets are mapped to `172.16.128.0/24` and `172.16.129.0/24` respectively and differentiate themselves on the `hub` router."

2023-09-12 15:26 UTC, leo-128t-liu commented on docs/config_nat.md
> +![Static Nat Diagram](/img/static_nat_example.png)
Following up with the discussion of `prefix` instead of `address` being used, the diagram need to be updated with remote IP prefix, `192.168.129.0/24` and `192.168.128.0/24` respectively.

2023-09-12 15:29 UTC, leo-128t-liu commented on static/img/static_nat_example.png
Following up with the discussion of prefix instead of address being used, the diagram need to be updated with remote IP prefix, `172.16.129.0/24` and `172.16.128.0/24` respectively.

2023-09-21 14:49 UTC, leo-128t-liu approved these changes

2023-09-21 17:06 UTC, chao-128t approved these changes

2023-09-27 15:32 UTC, Chr1st0ph3rTurn3r commented
This has been merged into 6.2.0-release-docs.

2023-09-28 12:41 UTC, closed without merging