Release Notes Heading Change
128technology/docs pull request #604
Opened 2023-09-13 13:47 UTC by Chr1st0ph3rTurn3r

2023-09-13 13:53 UTC, MichaelBaj requested changes

2023-09-13 13:53 UTC, MichaelBaj commented on docs/release_notes_128t_4.3.md
> +### Resolved Issues Requiring Configuration Changes
ugh, this was at a time when we were actually adding features to patches. This one should stay with New Features

2023-09-13 13:53 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +### Resolved Issues Requiring Configuration Changes and Improvements
Did you mean to leave "and Improvements"?

2023-09-13 13:53 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +### Resolved Issues Requiring Configuration Changes and Improvements
Did you mean to leave "and Improvements"?

2023-09-13 13:53 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +### Resolved Issues Requiring Configuration Changes and Improvements
Did you mean to leave "and Improvements"?

2023-09-13 13:53 UTC, MichaelBaj commented on docs/release_notes_128t_4.5.md
> +### Resolved Issues Requiring Configuration Changes and Improvements
Did you mean to leave "and Improvements"?

2023-09-13 13:53 UTC, MichaelBaj commented on docs/release_notes_128t_5.0.md
> +### Resolved Issues Requiring Configuration Changes and Improvements
Did you mean to leave "and Improvements"?

2023-09-13 13:53 UTC, MichaelBaj commented on docs/release_notes_128t_5.2.md
> +###  Resolved Issues Requiring Configuration Changes and Improvements
Did you mean to leave "and Improvements"?

2023-09-13 19:11 UTC, hadrielk approved these changes

2023-09-14 12:23 UTC, MichaelBaj approved these changes

2023-09-14 13:09 UTC, merged