Adding how to topic for new feature config local-override
128technology/docs pull request #605
Opened 2023-09-13 19:50 UTC by Chr1st0ph3rTurn3r

2023-09-14 12:23 UTC, MichaelBaj requested changes

2023-09-14 12:23 UTC, MichaelBaj commented on docs/how_to_local_config_override.md
> +When local override mode is engaged, copy of the router config is saved at that time and named `at-local-override`. This is saved as a baseline for the original router config.
I don't understand what this statement means. Is `at-local-override` a file? Is it a something within the SSR config model that can be seen? Is this completely hidden from the customer?

2023-09-14 12:23 UTC, MichaelBaj commented on docs/how_to_local_config_override.md
> +Use the command `set config local-override disable` to disable the local override mode. The router fetches the latest configuration from the conductor and applies it to the local configuration. Any c
I believe it is worth noting here that this feature does not sync any local router config back to the conductor and that any changes that were applied locally to the router, should they desired to be saved when local-config-override is disabled, that those changes be made to the conductor as well.

2023-09-14 12:23 UTC, MichaelBaj commented on docs/how_to_local_config_override.md
> +````
extra backtick

2023-09-14 13:25 UTC, tcarroll25 commented on docs/how_to_local_config_override.md
> +When local override mode is engaged, copy of the router config is saved at that time and named `at-local-override`. This is saved as a baseline for the original router config.
`at-local-override` is another exported config which is saved at the time when local override mode is engaged, maybe we should mention explicitly that this is another exported config which can be used to compare against or can be imported. We should also mention that `at-local-override` is deleted when local override mode is disengaged. Some use cases for the two exports `at-local-override` and `last-seen-conductor-config` are:

- `compare config at-local-override running` -> see all changes made on the router while in local override mode if the user wants to apply them to the conductors config
- `compare config at-local-override last-seen-conductor-config` -> see all changes made on the conductor while in local override mode if the user wants to apply them to their local router config
- `import config at-local-override` -> revert back to the original config when local override mode was engaged

I'm not sure if its worth mentioning some of these use cases in the documentation

2023-09-14 13:36 UTC, tcarroll25 requested changes

2023-09-14 13:36 UTC, tcarroll25 commented on docs/how_to_local_config_override.md
> +```
Engaging or disengaging local override mode is done with a PCLI command. Even though we store the local config override state in config, the config is hidden from the user and they are unable to touch the config value directly. The PCLI command can only be targeted towards routers because local override mode is invalid for conductors, but the PCLI command can either be run directly on the router:

Enable on router:
```
admin@combo-east-1.RTR_EAST_COMBO# set config local-override
```

Disable on router:
```
admin@combo-east-1.RTR_EAST_COMBO# set config local-override disabled
```

Or run from conductor nodes targeted at router nodes:

Enable on router from conductor:
```
admin@conductor-east-1.RTR_EAST_CONDUCTOR# set config local-override router RTR_EAST_COMBO
```

Disable on router from conductor:
```
admin@conductor-east-1.RTR_EAST_CONDUCTOR# set config local-override disabled router RTR_EAST_COMBO
```

Running the command targeted at a conductor will return an error

2023-09-14 13:36 UTC, tcarroll25 commented on docs/how_to_local_config_override.md
> +When local override mode is engaged, copy of the router config is saved at that time and named `at-local-override`. This is saved as a baseline for the original router config.
I see these use cases documented below, great!

2023-09-14 13:36 UTC, tcarroll25 commented on docs/how_to_local_config_override.md
> +### Show Commands
I'm not sure if this is worth mentioning in the docs but we have a new warning message if the user tries to edit the router config directly which encourages them to enable local override mode if they want the router config changes to persist:
```
admin@combo-east-1.RTR_EAST_COMBO# configure authority router RTR_EAST_COMBO description hello
% Warning: You are about to make configuration changes to a router that is managed by a Conductor. These changes could be overwritten at
any time by the Conductor. Consider enabling config local override mode to prevent the conductor from overwritting the local changes by
running 'set config local-override'.
Are you sure you want to edit 'description'? [y/N]:
```

2023-09-26 15:32 UTC, tcarroll25 approved these changes

2023-09-26 15:32 UTC, tcarroll25 commented on docs/how_to_local_config_override.md
> +- To compare running config against the last seen conductor config use: `compare config last-seen-conductor-config`.
A third comparison that might be worth mentioning is `compare config at-local-override last-seen-conductor-config`, which is all changes made by the conductor since local override mode was enabled. This would be the best comparison if a user wanted to view any new conductor changes and decide if they wanted to apply them to their local config manually.

2023-09-27 17:43 UTC, tcarroll25 approved these changes

2023-09-27 19:56 UTC, MichaelBaj approved these changes

2023-09-28 12:42 UTC, closed without merging