WAN Assurance plugin 3.7.4 relese notes
128technology/docs pull request #609
Opened 2023-09-16 04:21 UTC by agrawalkaushik

- Captures content and bug fixes for Jun, Jul and Aug pushes

2023-09-18 13:10 UTC, BenMatase commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +  _**Resolution:**_ The log-level configuration setting is correctly propagated to teh cloud-intel-agent.
`teh` -> `the`

2023-09-18 13:10 UTC, BenMatase commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +  _**Resolution:**_ The log-level configuration setting is correctly propagated to teh cloud-intel-agent.
inconsistent reference to cia. In title it is `cloud-intel agent` and here it is `cloud-intel-agent`

2023-09-18 13:10 UTC, BenMatase commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +  _**Resolution:**_ The system will now skip factory reset for a conductor managed greenfield device .
space before period at the end

2023-09-18 13:10 UTC, BenMatase commented on sidebars.js
> +      // "cli_reference",
intentional?

2023-09-18 14:05 UTC, Chr1st0ph3rTurn3r approved these changes
Just Ben's suggestions, otherwise it looks good.

2023-09-18 16:44 UTC, agrawalkaushik commented on sidebars.js
> +      // "cli_reference",
oops - not intentional at all - will remove.

2023-09-19 12:54 UTC, gregschrock approved these changes

2023-09-20 14:39 UTC, Chr1st0ph3rTurn3r approved these changes

2023-09-20 14:40 UTC, BenMatase submitted a review, later dismissed

2023-09-20 14:52 UTC, MichaelBaj requested changes

2023-09-20 14:52 UTC, MichaelBaj commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +**Release Date:** Aug 20, 2023
This should be September 20

2023-09-20 15:47 UTC, MichaelBaj approved these changes

2023-09-20 15:48 UTC, merged