Updating cli docs
128technology/docs pull request #612
Opened 2023-09-20 20:50 UTC by Chr1st0ph3rTurn3r

2023-10-10 19:56 UTC, MichaelBaj requested changes

2023-10-10 19:56 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **95-53000 process highway disconnected messages caused by NIC driver bug:** The DPDK driver code for the Broadcom NICs contained a bug that caused the querying of the extended statistic to fail. T
Missing 'I' in Jira ID

2023-10-10 19:56 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-50071 Lenovo SR650 platform support as a 100G ports solution:** WAITING TO FINALIZE
- [ ] TODO - complete this item

Recommendation:
I95-50071 Lenovo SR650 platform w/100G support: Two 2x100G Mellanox ConnectX-6 Dx NICs supported in SR650 platform.

2023-10-10 19:56 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-47838 SSR does not remove networks on stop:** Resolved an issue where the SSR does not remove networks on stop. This has been corrected and the SSR now will cleanup networks on container stop
Too many internal details on this one. Recommended alternative:
- **I95-47838 SSR strands internal interfaces when enabling and disabling IDP** Resolved an issue where the SSR does not remove internal network interfaces when IDP is disabled.

2023-10-10 19:56 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-52018 Path returned contained ip-address with no escaping:** The Inspector path has been modified with the ability to escape.
I don't understand this description. This defect pertains to IDP, which was introduced in 6.0, but this fix was also delivered to 5.6 as well. The PR does not have a release notes section, unfortunately. Please reach out to the developer and understand the customer-facing impact.

2023-10-10 19:56 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-52178 Reset of SSR IDP does not turn it off:** Resolved an issue when performing a factory reset on SSR IDP did not turn it off properly.
Recommended rewording:

- **I95-52178 factory-reset of SSR config does not does not disable IDP:** Resolved an issue when performing a factory reset on SSR, IDP does not turn it off properly.

2023-10-10 19:56 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +**WAN-1728 SSR1000 series Out of band management improvements:** The following improvements have been made to enhance the management functionality in Mist Managed environments:
new feature?

2023-10-10 19:56 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **WAN-1735 Set log levels on SSR:** Added new `log_level` and `log_category` fields in the `root_override` section of the intent config.
New FEature?

2023-10-24 16:44 UTC, MichaelBaj requested changes

2023-10-24 16:44 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-50539 Common Criteria - SSR not handling and logging Multicast packets correctly:** Per Common Criteria guidelines, the SSR now filters and drops packets if the source address is a multicast
Drop "Common Criteria".

- **I95-50539 SSR not handling and logging Multicast packets correctly:** Per security best practices, the SSR now filters and drops packets if the source address is a multicast source IP address.

2023-10-24 16:44 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-52414 User seeing other user's FIB entries and messages:** Resolved an issue where `show fib` included entries that the current user did not have permission to view.
Suggested rewording:

- **I95-52414 RBAC not being honored for `show fib` output:** Resolved an issue where `show fib` included entries that the current user did not have permission to view.

2023-10-24 16:44 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-52889 Highway crash caused by a false negative waypoint exhaustion check:** Waypoint ports reinitialization that is triggered by a false negative exhaustion check can lead to duplicate waypoi
need space after "two sessions"

2023-10-24 16:44 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-53009 Common Criteria - RPM Verification:** Compliance verification for all ISO RPMs has been added.
Suggested rewording:

- **I95-53009 RPM signature verification missing for all artifacts:** Verification for all ISO RPMs has been added.

2023-10-24 16:44 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-53393 Common Criteria - Allow empty password attempts via SSH:** The SSR counts login attempts with an empty password as failed login attempts. These  contribute to locking a user account if
Suggested rewording:

- **Empty password attempts not counting towards user lockout:** The SSR now counts login attempts with an empty password as failed login attempts. These contribute to locking a user account if they reach the threshold (the value configured in `configure authority password-policy deny`,) within a short time window.

2023-10-24 18:22 UTC, MichaelBaj requested changes

2023-10-24 18:22 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-50071 Lenovo SR650 platform support as a 100G ports solution: WAITING TO FINALIZE
- [ ] Complete this item

2023-10-30 17:46 UTC, MichaelBaj requested changes

2023-10-30 17:46 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-53777 Multicast traffic not passing after HA Failover:** This feature is currently in Beta; High Availability with Multicast has not been fully tested and may not be fully functional. Drop or
Suggested rewording to match LAG caveats:
- **I95-53777 Multicast traffic not passing after HA Failover:** High Availability with Multicast is not fully supported. Drop or complete loss of traffic may be seen when the primary node resumes traffic after a node failure and failover.

2023-10-30 17:46 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **The following CVEs have been resolved in this release:** CVE-2023-2828, CVE-2022-42896, CVE-2023-1281, CVE-2023-1829, CVE-2023-2124, CVE-2023-2194, CVE-2023-2235, CVE-2023-20569, CVE-2023-20593,
Per the internal email thread, I believe these need to follow a specific format with a brief description and CVSS.

2023-10-30 17:46 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-20864 Support for Multicast:** Multicast is a “one source, many destinations” method of traffic distribution. For more information, see [Multicast](config_multicast.md). The previous implemen
I don't recall Multicast being in Beta.

2023-10-30 17:46 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-20864 Support for Multicast:** Multicast is a “one source, many destinations” method of traffic distribution. For more information, see [Multicast](config_multicast.md). The previous implemen
Remove newly added sentence.

2023-10-30 17:46 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-53777 Multicast traffic not passing after HA Failover:** This feature is currently in Beta; High Availability with Multicast has not been fully tested and may not be fully functional. Drop or
See my wording in the 6.2 release notes section.

2023-10-30 17:46 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-51544 Add the option to use the physical source MAC on VRRP interfaces:** The coommand [`use-physical-address`](config_command_guide.md#configure-authority-router-node-device-interface-vrrp-u
Typo "coomand"

2023-10-31 13:02 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **The following CVEs have been resolved in this release:** CVE-2023-2828, CVE-2022-42896, CVE-2023-1281, CVE-2023-1829, CVE-2023-2124, CVE-2023-2194, CVE-2023-2235, CVE-2023-20569, CVE-2023-20593,
Looks like a list of CVEs is sufficient. Let's start with this approach. Thank you.

2023-11-16 15:13 UTC, Bhautik commented on docs/release_notes_128t_6.2.md
> +- **I95-51544 Add the option to use the physical source MAC on VRRP interfaces:** The coommand [`use-physical-address`](config_command_guide.md#configure-authority-router-node-device-interface-vrrp-u
Release version is 6.2.0-39 and date is November 16th

2023-11-16 19:54 UTC, Bhautik approved these changes

2023-11-16 20:07 UTC, MichaelBaj requested changes

2023-11-16 20:07 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-53894 DNS cache-service does not start:** Resolved an issue that resulted in a stack trace in the logs which starts with message `No TimeoutQueue:`.
The release notes section in the PR is not accurate.
Resolved a race condition causes the dns process to fail to start. The log message `No TimeoutQueue:` can be seen in the logs during this condition.

2023-11-16 20:46 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.0.md
> +- **The following issues have been identified during penetration testing and addressed in this release:** I95-48445, I95-48448, I95-49456, I95-49912, I95-49913, I95-49914.
I have called out the issues that were not identified in Pen testing; the two that remain look to be significant and if given public visibility could be bad.

2023-11-16 21:20 UTC, MichaelBaj requested changes

2023-11-16 21:20 UTC, MichaelBaj commented on docs/release_notes_128t_6.0.md
> +- **I95-49914 List of cryptographic algorithms does not match:** A discrepancy between algorithms claimed and those offered was found. This issue has been addressed and the list of claimed and offere
This is marked as Exclude from Release Notes. Please remove.

2023-11-16 21:24 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.0.md
> +- **I95-49914 List of cryptographic algorithms does not match:** A discrepancy between algorithms claimed and those offered was found. This issue has been addressed and the list of claimed and offere
done

2023-11-16 21:27 UTC, MichaelBaj approved these changes

2023-11-16 21:37 UTC, merged