MSDP and RPs in 6.2.0
128technology/docs pull request #613
Opened 2023-09-21 15:35 UTC by Chr1st0ph3rTurn3r

2023-09-21 15:44 UTC, MichaelBaj requested changes

2023-09-21 15:44 UTC, MichaelBaj commented on docs/cli_stats_reference.md
> +For more information regarding in-memory metrics, please refer to this retention document - https://www.juniper.net/documentation/us/en/software/session-smart-router/docs/config_in-memory_metrics/
Why is this pointing to an external absolute reference rather than a relative referenece?
True here and throughout.

2023-09-26 17:04 UTC, robertkebler approved these changes

2023-09-27 19:54 UTC, MichaelBaj approved these changes

2023-09-28 12:45 UTC, closed without merging