5.6.11 release notes
128technology/docs pull request #616
Opened 2023-09-25 17:22 UTC by Chr1st0ph3rTurn3r

2023-09-25 20:12 UTC, MichaelBaj requested changes

2023-09-25 20:12 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-52859 ENCS issue moving MPLS cable between chassis:** When swapping physical cable from active node to standby node, the customer experienced low rate packet loss on traffic-engineering enabl
ENCS happens to be the specific problem where this issue was encountered, but this is more generically applicable to hypervisor platforms. Suggested heading:
Issue moving interface between chassis of hypervisor platforms running SSR (e.g., ENCS):

2023-09-25 20:15 UTC, hadrielk commented on docs/release_notes_128t_5.6.md
> +- **I95-52406 Add ability to download MIBs from GUI:** A button has been added to the GUI, in the Documentation pane of the About Page, to download the SNMP MIB definitions for SSR.
how/why as this added to `5.6.11`?!? that sounds like a feature, tbh.

2023-09-25 20:21 UTC, hadrielk commented on docs/release_notes_128t_5.6.md
> +- **I95-53002 NTP setup check fails on startup:** Resolved an issue in the exec startup script `ntpSetupCheck.sh`. It had the incorrect path for the NTP configuration template.
the script name doesn't mean anything to anyone. Just make this:

"Resolved an issue in the NTP startup sequence, due to an incorrect path for the NTP configuration."

2023-09-25 20:24 UTC, hadrielk commented on docs/release_notes_128t_5.6.md
> +- **I95-53000 process highway disconnected messages caused by NIC driver bug:** The DPDK driver code for the Broadcom NICs had a bug which caused the querying of the extended statistic to fail, in no
This info is too detailed. Just make it:

"The Broadcom NIC driver has been upgraded to resolve the issue."

2023-09-25 20:29 UTC, hadrielk commented on docs/release_notes_128t_5.6.md
> +- **I95-53015 Highway log has large number of unnecessary INFO messages:** Resolved an issue when the `icmp unreachable action` is attempting to generate an ICMP response, but the session is destined
Too much detail, all of which is meaningless to customers.

"A previous log message of `icmp response packet failed` was incorrectly logged at `INFO` level. It is neither an error nor actually informational, and has now been downgraded to `DEBUG` level."

2023-09-26 13:18 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.6.md
> +- **I95-53000 process highway disconnected messages caused by NIC driver bug:** The DPDK driver code for the Broadcom NICs had a bug which caused the querying of the extended statistic to fail, in no
Respectfully Hadriel, Mike has asked that I provide some detail in the release notes, due to customer feedback - they want to know what was happening and how it was resolved, ostensibly to identify issues relevant to them. I do agree that less is more, and can pare this down a bit, but will keep some of the details.

2023-09-26 14:12 UTC, MichaelBaj approved these changes

2023-10-02 19:11 UTC, jeffmart-jnpr commented on docs/release_notes_128t_5.6.md
> +- **The following CVE's have been identified and addressed in this release:** I95-51431, I95-52554, I95-52644, I95-52645, I95-52956.
Tiny nit, the 6.1 release notes has:
"The following CVEs have"

This has:
"The following CVE's"

2023-10-02 19:27 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_5.6.md
> +- **The following CVE's have been identified and addressed in this release:** I95-51431, I95-52554, I95-52644, I95-52645, I95-52956.
Since CVE is a TLA for Common Vulnerabilities and Exposures, it is already plural. I'll resolve it in other release notes as I go.

2023-10-02 19:35 UTC, jeffmart-jnpr commented on docs/release_notes_128t_5.6.md
> +- **I95-51864 Ethernet Over SVR (EoSVR) Not Working:** When EoSVR traffic traverses over a dogleg path in a HA node topology, traffic failed to traverse the middle node. EoSVR packets are no longer i
resolved

2023-10-02 19:35 UTC, jeffmart-jnpr commented on docs/release_notes_128t_5.6.md
> +- **I95-52859 ENCS issue moving MPLS cable between chassis:** When swapping physical cable from active node to standby node, the customer experienced low rate packet loss on traffic-engineering enabl
resolved

2023-10-02 19:44 UTC, jeffmart-jnpr commented on docs/release_notes_128t_5.6.md
> +- **I95-52406 Add ability to download MIBs from GUI:** A button has been added to the GUI, in the Documentation pane of the About Page, to download the SNMP MIB definitions for SSR.
While true, customers may not have the ability to download MIB's that we currently ship.

2023-10-02 19:49 UTC, MichaelBaj approved these changes

2023-10-02 20:07 UTC, hadrielk commented on docs/release_notes_128t_5.6.md
> +- **I95-51181 Improve `save-tech-support-info` command:** The PCLI command save tech-support-info now has a since argument that limits log collection to only logs generated after that given point. Th
this is missing the salient point: the _default_ for saving tech support is now 1 day's worth. Previously save tech support would collect everything.

The new `since` argument allows one to override that new default.

2023-10-02 20:27 UTC, hadrielk approved these changes

2023-10-02 20:33 UTC, jeffmart-jnpr approved these changes

2023-10-02 20:38 UTC, MichaelBaj approved these changes

2023-10-02 20:40 UTC, merged