Updated NoCloud documentation to provide interface persistence details
128technology/docs pull request #617
Opened 2023-09-26 19:27 UTC by laneshields

2023-09-26 20:23 UTC, MichaelBaj commented on docs/install_qcow2_deployment.md
> +```
What is the location of this file and what is its filename?

2023-09-26 20:23 UTC, MichaelBaj commented on docs/install_qcow2_deployment.md
> +```
Is this the network-config contents?
If so (and do this for the others), add a comment at the top (because customers will cut-and-paste) that explains which file this pertains to.

2023-09-26 20:23 UTC, MichaelBaj commented on docs/install_qcow2_deployment.md
> +To create an ISO image with these configuration files and the volume label `cidata` on a Linux system, place the user-data in a file named `user-data`, the meta-data in a file named `meta-data`, and
There are two file examples here, but three are referenced in the command.

2023-10-05 18:15 UTC, iwbarker commented on docs/install_qcow2_deployment.md
> +This ISO should be attached to the SSR VM when booted. **Is this a user action or does the attachment happen as a result of creating the image??** The cloud-init process on the system will find the d
it is a user action.
the user prepares the iso as described, then attaches it to the VM ready for boot.
cloud-init will then mount the attached ISO during vm boot, and act on the data

the exact method of how to attach an ISO to the VM varies depending on the hypervisor in use

2023-10-05 18:32 UTC, laneshields commented on docs/install_qcow2_deployment.md
> +This ISO should be attached to the SSR VM when booted. **Is this a user action or does the attachment happen as a result of creating the image??** The cloud-init process on the system will find the d
yes, maybe to make that more clear add something about "consult the documentation for your particular hypervisor on how to do this?"

2023-10-05 19:53 UTC, Chr1st0ph3rTurn3r requested changes

2023-10-05 19:53 UTC, Chr1st0ph3rTurn3r commented on docs/install_qcow2_deployment.md
> +This ISO should be attached to the SSR VM when booted, please consult the documentation for your specific hypervisor for details on how to do this. The cloud-init process on the system will find the
5. Attach the ISO to the SSR VM. Please refer to your hypervisor documentation for these instructions. 
6. The cloud-init process on the system will locate the data during first boot and perform the desired actions.

2023-10-05 20:31 UTC, Chr1st0ph3rTurn3r approved these changes

2023-10-05 21:06 UTC, merged