Release notes for ipsec-client plugin version 3.6.0
128technology/docs pull request #627
Opened 2023-10-11 19:36 UTC by agrawalkaushik

DOCS-382 #time 1h

2023-10-11 20:19 UTC, Chr1st0ph3rTurn3r requested changes

2023-10-11 20:19 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +Various features introduced as part of the [3.6.0](#release-360) version require the user to enable session records on the egress tunnel services such as `ipsec-tunnel` shown above. The following sam
The following sample config shows the **recommended**

2023-10-11 20:19 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +For the ipsec plugin, several individual processes were consolidated into a single controller process providing an overall reduction in CPU and memory when the plugin is enabled on a SSR.
```suggestion
For the ipsec plugin, several individual processes were consolidated into a single controller process providing an overall reduction in CPU and memory when the plugin is enabled on **an** SSR.
```

2023-10-11 20:19 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +The new version adds support for automatically detecting egress tunnel sessions that are not able to communicate with the IPsec remote server anymore. The recovery happens in form of automatically de
```suggestion
The new version adds support for automatically detecting egress tunnel sessions that are not able to communicate with the IPsec remote server anymore. The recovery happens in **the** form of automatically deleting those session allowing new egress tunnel sessions to be formed. Please refer to the [session-record](#session-record) section on how to enable this new feature.
```

2023-10-11 23:26 UTC, BenMatase requested changes

2023-10-11 23:26 UTC, BenMatase commented on docs/plugin_ipsec_client.md
> +The new version adds support for automatically detecting egress tunnel sessions that are not able to communicate with the IPsec remote server anymore. The recovery happens in form of automatically de
Those sessions

2023-10-11 23:26 UTC, BenMatase commented on docs/plugin_ipsec_client.md
> +- **WAN-2361** Include the egress wan interface being used for ipsec tunnel for better tunnel insights
Ipsec tunnels

2023-10-12 13:38 UTC, BenMatase commented on docs/plugin_ipsec_client.md
> +The new version adds support for automatically detecting egress tunnel sessions that are not able to communicate with the IPsec remote server anymore. The recovery happens in form of automatically de
`those session` -> `those sessions` just grammar

2023-10-12 13:58 UTC, agrawalkaushik commented on docs/plugin_ipsec_client.md
> +The new version adds support for automatically detecting egress tunnel sessions that are not able to communicate with the IPsec remote server anymore. The recovery happens in form of automatically de
oh - ah got it!

2023-10-12 14:22 UTC, MichaelBaj submitted a review, later dismissed

2023-10-12 15:11 UTC, Chr1st0ph3rTurn3r submitted a review, later dismissed

2023-10-13 18:29 UTC, BenMatase approved these changes

2023-10-13 19:01 UTC, Chr1st0ph3rTurn3r approved these changes

2023-10-13 20:29 UTC, merged