5.6.12 release notes
128technology/docs pull request #631
Opened 2023-10-17 19:21 UTC by Chr1st0ph3rTurn3r

2023-10-17 20:58 UTC, MichaelBaj requested changes

2023-10-17 20:58 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-47859 3G signal strength displayed in `show lte` command:** Resolved an issue where the `show lte` command displayed the first value it encountered. The code now checks for the correct lte st
This can't be the right issue. The issue being addressed in 5.6.12 relates to startup.
Provided you a link to the issues out-of-band

2023-10-18 14:46 UTC, MichaelBaj approved these changes

2023-10-18 15:22 UTC, migolnikov commented on docs/release_notes_128t_5.6.md
> +- **I95-53833 Timeout prevents startup:** Resolved a regression introduced in 5.6.11 in the SSR reboot startup logic. If any of the processes took longer than 30 seconds to complete, the startup sequ
renders ==> rendered

2023-10-18 18:16 UTC, MichaelBaj approved these changes

2023-10-18 19:10 UTC, migolnikov approved these changes

2023-10-20 18:30 UTC, merged