Release notes for WAN Assurance 3.7.6
128technology/docs pull request #638
Opened 2023-11-15 17:01 UTC by agrawalkaushik

2023-11-15 17:12 UTC, MichaelBaj requested changes

2023-11-15 17:41 UTC, BenMatase commented on docs/release_notes_wan_assurance_plugin_3.7.md
>  ## Release 3.7.5
Need to change the heading here

2023-11-15 18:32 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +  _**Resolution:**_ When using MIST redirect onboarding for a router an additional initialization step caused the existing router to be reset causing the configuration to get wiped out. The code path
```suggestion
  _**Resolution:**_ When using MIST redirect onboarding for a router, an additional initialization step caused the existing router to be reset and the configuration removed. Conductor onboarding has been made more robust, avoiding unnecessary reinitialization.
```

2023-11-15 18:32 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +- **WAN-2545 Config wiped out after enabling WAN assurance plugin on a router**
Suggest: **WAN-2545 Router configuration reset during WAN Assurance onboarding:**

2023-11-15 18:42 UTC, MichaelBaj approved these changes

2023-11-16 12:34 UTC, gregschrock submitted a review, later dismissed

2023-11-20 18:11 UTC, MichaelBaj approved these changes

2023-11-20 18:13 UTC, BenMatase approved these changes

2023-11-20 19:50 UTC, merged