security policy best practices
128technology/docs pull request #639
Opened 2023-11-15 18:53 UTC by MichaelBaj

2023-11-16 19:53 UTC, Chr1st0ph3rTurn3r requested changes

2023-11-16 19:53 UTC, Chr1st0ph3rTurn3r commented on docs/sec_security_policy.md
> +While the SSR affords you the ability to provision a unique security policy per service, in a typical hub-and-spoke topology, a single security policy can be shared among all services, with a separat
```suggestion
The SSR affords you the ability to provision a unique security policy per service. However, in a typical hub-and-spoke topology, a single security policy can be shared among all services, with a separate security policy used for metadata encryption and authentication.
```

2023-11-16 19:53 UTC, Chr1st0ph3rTurn3r commented on docs/sec_security_policy.md
> +The best approach to making any change to a security policy is to create a new policy, with a new name, and apply it to the respective service, interface or adjacency. Doing so affords network admini
```suggestion
The best approach to making any change to a security policy is to create a new policy, with a new name, and apply it to the respective service, interface, or adjacency. This affords network administrators the ability to readily identify sessions that may not have adopted the new policy.
```

2023-11-16 19:53 UTC, Chr1st0ph3rTurn3r commented on docs/sec_security_policy.md
> +Identify the sessions traversing the service, paying particular attention to those with an uptime greater than the time of the configuration change. If sessions exist with an uptime greater than the
```suggestion
Identify the sessions traversing the service, specifically looking for those with an uptime greater than the time of the configuration change. If sessions exist with an uptime greater than the time of the `delete sessions` command, execute the `delete sessions` command again and confirm that they have been cleared.
```

2023-11-16 19:53 UTC, Chr1st0ph3rTurn3r commented on docs/sec_security_policy.md
> +`Forward Flows > Metadata Security Policy` which comes from the configuration `network-interface > adjacency > inter-router-security`, which is the metadata encryption policy<br/>
```suggestion
- `Forward Flows > Metadata Security Policy`: This comes from the configuration of `network-interface > adjacency > inter-router-security`, which is the metadata encryption policy.<br/>
```

2023-11-16 19:53 UTC, Chr1st0ph3rTurn3r commented on docs/sec_security_policy.md
> +`Payload Security Policy` which comes from the configuration `service > security-policy`, which is the payload encryption policy<br/>
```suggestion
- `Payload Security Policy`: This comes from the configuration `service > security-policy`, which is the payload encryption policy.<br/>
```

2023-11-16 19:53 UTC, Chr1st0ph3rTurn3r commented on docs/sec_security_policy.md
> +`Reverse Flows > Decrypt Security Policy` which comes from the configuration `network-interface > inter-router-security`, which is the metadata decryption policy
```suggestion
- `Reverse Flows > Decrypt Security Policy`: This comes from the configuration `network-interface > inter-router-security`, which is the metadata decryption policy.
```

2023-11-16 20:13 UTC, ayungelson commented
@MichaelBaj I am having doubts that this procedure will work. This still needs to be tested.

- [ ] verify this works

2023-12-08 00:06 UTC, ayungelson commented on docs/sec_security_policy.md
> +While the SSR affords you the ability to provision a unique security policy per service, in a typical hub-and-spoke topology, a single security policy can be shared among all services, with a separat
Maybe also mention that the best practices for inter-node policy is to leave it unencrypted? Current defaults enable it, but in reality that's what we tell people AFAIK

2023-12-08 00:06 UTC, ayungelson commented on docs/sec_security_policy.md
> +After applying the change, be sure to restart the SSR on any routers that share the same security policy to clear any active sessions. Once the sessions have been cleared, ensure that traffic is trav
Instead of `Once the sessions have been cleared`, maybe `after the ssr is back up` or something... to just make sure they don't just clear sessions...

2023-12-08 17:10 UTC, laneshields commented on docs/sec_security_policy.md
> +Metadata is encrypted and decrypted between SSR routers, but payload encryption is performed end-to-end. This is illustrated in a multi-hop router deployment by the image below.
Possibly a minor nit, but I have been told that this is not true unless the original session was using UDP or TCP. For all other transports like ICMP and ESP it is decrypted and re-encrypted hop by hop though I'd need Engineering to confirm that. Also, I have heard that if we implement inline security rekeying everything would be decrypted/re-encrytped hop by hop though that is not currently in product.

2023-12-08 17:16 UTC, laneshields commented on docs/sec_security_policy.md
> +* A security policy can be defined in `router > inter-node-security`. This security policy defines the encryption for HA interfaces used for inter node communication.
As a point of clarity, I believe this is just responsible for encrypting metadata (and hmac signing packets) through the HA interface. It is akin to the inter-router-security policy just for traffic between the two nodes of an HA router and not between two routers.

2023-12-08 17:19 UTC, laneshields commented on docs/sec_security_policy.md
> +HA interfaces between SSR nodes are directly connected between nodes and therefore pose no risk of interception. Given the additional computational cost of encrypting and decrypting traffic, it is re
Example:
`        security  encrypt-hmac-disabled
            name                 encrypt-hmac-disabled
            description          "Encryption and message authentication disabled"
            hmac-cipher          sha256
            hmac-key             (removed)
            encryption-cipher    aes-cbc-128
            encryption-key       (removed)
            encryption-iv        (removed)
            encrypt              false
            hmac-mode            disabled
            adaptive-encryption  false
        exit
`

2023-12-08 20:32 UTC, Chr1st0ph3rTurn3r approved these changes

2023-12-11 21:08 UTC, merged