creating 6.1.6 release notes
128technology/docs pull request #640
Opened 2023-11-17 20:40 UTC by Chr1st0ph3rTurn3r

2023-11-20 16:17 UTC, MichaelBaj requested changes

2023-11-20 16:17 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-53852 host-service snmp-server blocks SVR pings to network-interface owned address:** Ping traffic was hitting the generated (wildcarded) snmp-server service. The session could not setup due
"udp" should be capitalized.

2023-11-20 16:17 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-53915 Removing an X710/X722 port from SSR can cause high RX latency:** Deleting an SSR interface of an X710/722 NIC which is part of a multi-port device, introduces RX Latency into sibling po
"Latency" should not be capitalized.

2023-11-20 16:17 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-53916 Stale Teams interfaces conflict with HA interfaces:** In some cases a stale teams interface could conflict with a new configuration pushed down from MIST. Resolved an issue where the us
This statement is very confusing. If this is a Mist-managed SSR, then it should be impossible to have a "stale" teams interface as Mist is the one that generated the configuration. The PR release notes reads differently:

"Fix an issue in a MIST environment where the use of non-standard HA ports could result in non-functional HA after a factory reset."

We need clarity on what exactly is meant by a "stale interface". Is this an interface that someone created prior to having a device be Mist-managed? (i.e., conductor-managed converted to Mist-managed)

2023-11-20 16:17 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-54051 Driver causing memory corruption :** Updated the driver support for BNXT NICs.
extra space after corruption

Also, this needs to specifically call out that the driver is broadcom related

"Broadcom driver causing memory corruption, leading to system fault"

2023-11-28 14:04 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-53641 BGP between peers does not immediately transition to the Connected state:** A change has been made to reduce the time that BGP routes learned from a BGP over SVR neighbor are withdrawn
Huh? If it said "BGP things <routes, events, paths, coconuts>..." then *grammatically* it would make sense to say "do not". Based on the resolution info, should it state "BGP routes between peers do not immediately transition to the Connected state"?

2023-11-28 16:06 UTC, MichaelBaj submitted a review, later dismissed

2023-12-27 16:36 UTC, MichaelBaj requested changes

2023-12-27 16:36 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-51614 Firewall Protection Profile:** Several updates to existing functionality have been made to address firewall filtering. For additional information, see [Customizable Firewall Rules and F
I don’t believe any of these firewall features were delivered to 6.1.

2023-12-27 16:36 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-52018 Path returned contained ip-address with no escaping:** The Inspector path has been modified with the ability to escape.
Not updated per suggested change.

2023-12-27 20:13 UTC, MichaelBaj approved these changes

2024-01-02 20:34 UTC, MichaelBaj approved these changes

2024-01-02 21:28 UTC, jeffmart-jnpr approved these changes

2024-01-02 21:30 UTC, merged