creating 5.5.12 release notes
128technology/docs pull request #641
Opened 2023-11-29 19:22 UTC by Chr1st0ph3rTurn3r

2023-11-29 19:37 UTC, MichaelBaj requested changes

2023-11-29 19:37 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-51459 Logs and exception pcaps are periodically filled with error logs and truncated packets:** Resolved an issue where ICMP error respond packets for encapsulated traffic caused `PacketBuffe
"error respond packets" should be "error response packets"

2023-11-29 19:37 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-51864 Ethernet Over SVR (EoSVR) not working for multi-hop SVR scenarios:** When EoSVR traffic traverses over a dogleg path in a HA node topology, traffic failed to traverse the middle node. E
"traffic failed to traverse the middle node" should be "traffic failed to traverse intermediate nodes" as there may be more than three SVRs in a multi-hop scenario.

2023-11-29 19:56 UTC, MichaelBaj approved these changes

2023-11-30 21:19 UTC, MichaelBaj approved these changes

2024-02-20 19:37 UTC, MichaelBaj requested changes

2024-02-20 19:37 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-54155 nodeMonitor coredump on secondary node after upgrade:** During an upgrade where `deviceType` was `LTE` the attempt to get a linux interface name (not supported) failed. This issue has b
Typo on "implemting" (implementing)

2024-02-20 19:37 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **I95-54490 Permission denied when trying to open a user config file:** Resolved a permissions issue for the `connect router` command by adding ACLs for reverse SSH nodeIdentifier so that this is a
Simplify this statement to the following:

- **I95-54490 Permission denied when trying to open a user config file:** Resolved a permissions issue for the `connect router` command by adding ACLs for reverse SSH so that this is accessible for admin users.

2024-02-20 19:37 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **WAN-2486 SSR data reporting values that are unrealistically high:** When capturing application usage for application summary learned apps, we sometimes observe really high values for bandwidth an
remove "we" from the statement.

- **WAN-2486 SSR data reporting values that are unrealistically high:** When capturing application usage for application summary learned apps, sometimes very high values for bandwidth and other metrics are observed.
Resolution: The high value was due to an internal corruption when the metrics for these learned applications were removed and subsequently re-added. During such transition, it is possible to result in an incorrect high value.

2024-02-20 19:59 UTC, MichaelBaj requested changes

2024-02-20 19:59 UTC, MichaelBaj commented on docs/release_notes_128t_5.5.md
> +- **WAN-2486 SSR data reporting values that are unrealistically high:** When capturing application usage for application summary learned apps, we sometimes observe really high values for bandwidth an
Please apply this edit as well.

2024-02-20 20:05 UTC, MichaelBaj approved these changes

2024-02-22 15:53 UTC, Bhautik approved these changes

2024-02-22 20:26 UTC, merged