Static-NAT update
128technology/docs pull request #642
Opened 2023-11-29 21:24 UTC by Chr1st0ph3rTurn3r

Static-NAT update for non-svr traffic, per note from Chao

2023-11-29 21:34 UTC, MichaelBaj requested changes

2023-11-29 21:34 UTC, MichaelBaj commented on docs/config_nat.md
> +The `ingress-source-nat-pool` and the `source-nat` settings of `bidirectional-nat` are both `ingress source-nat` that are intended for SVR traffic targeted towards an inter-router peer. In this situa
I had to read the first sentence four times and I still don't think I grok it. This statement needs to be changed for readability.
Additionally, `ingress-source-nat-pool` is being referenced for the first time here. Definitions would help.

2023-11-29 21:34 UTC, MichaelBaj commented on docs/config_nat.md
> +If you want to configure `ingress source-nat` for non-SVR traffic, for example LAN-to-LAN traffic traversing a single SSR router, you can use the configuration above. However, you must also disable `
convention for referencing config path is to use a single right angle bracket between objects. e.g.
`service > source-nat`

2023-11-29 21:47 UTC, chao-128t commented on docs/config_nat.md
> +The `ingress-source-nat-pool` and the `source-nat` settings of `bidirectional-nat` are both `ingress source-nat` that are intended for SVR traffic targeted towards an inter-router peer. In this situa
@MichaelBaj below is the "annotation" for the first sentence.
Depending on when and where a packet gets source NAT'd, there are two types of source NAT - ingress and egress.

The `bidirectional-nat` config is in the form of `local-ip` and `remote-ip` pair.
- source-nat is performed for packet ingressing the interface where `bidirectional-nat` is configured.
- dest-nat is performed for packet egressing the interface where `bidirectional-nat` is configured.

In this sense, along with `ingress-source-nat-pool`, the `source-nat` part of `bidirectional-nat` falls into the ingress source-nat category and will be handled accordingly.

2023-11-30 21:25 UTC, MichaelBaj approved these changes

2023-11-30 21:26 UTC, chao-128t approved these changes

2023-11-30 21:27 UTC, merged