Firewall Certification docs
128technology/docs pull request #645
Opened 2023-12-06 15:09 UTC by Chr1st0ph3rTurn3r

2023-12-06 16:40 UTC, MichaelBaj requested changes

2023-12-06 16:40 UTC, MichaelBaj commented on docs/sec_firewall_filtering.md
> +- Berkeley Packet Filter - Identifies the filter to be applied. Validation confirms proper BPF syntax.
@ayungelson When we discussed this feature, you had mentioned that validation had not yet been added. Has that gap been closed?

2023-12-06 16:40 UTC, MichaelBaj commented on docs/sec_firewall_filtering.md
> +The number of rules and the filtering operation is resource heavy and may impact performance.
Need @ayungelson to confirm, but I might word this statement differently:

The number and complexity of rules will have an impact on forwarding performance.

2023-12-06 16:40 UTC, MichaelBaj commented on docs/sec_firewall_filtering.md
> +ICMP Echo Replies that arrive at the SSR are dropped if no corresponding request has been seen and the ICMP Aysnc Reply is set to drop. This is the new default behavior; no change in configuration is
New behavior as of when? This document should state that these features were introduced in 6.2.3-r2

2023-12-06 16:40 UTC, MichaelBaj commented on docs/sec_firewall_filtering.md
> +If you do not want any allowed options, you do not have to proceed any farther. Return to the Authority level and continue with other configuration activities.
farter = further

2023-12-06 16:40 UTC, MichaelBaj commented on docs/sec_firewall_filtering.md
> +The connection limit is configured at the router level (Authority > Router), and is unlimited by default. To set a limit, enter a numerical value in the `Half-Open Connection Limit` field in the Rout
@ayungelson It seems to me that we should add a WARNING admonition here regarding this feature.
Please correct as needed
::: warning
When the SSR reaches near its limit of half-open TCP connections, this may begin to prevent the establishment of "healthy" TCP traffic. Please ensure that this value is set appropriately for your network. Importantly, identify the devices that are creating half-open sessions.
:::

2023-12-06 16:55 UTC, ayungelson commented on docs/sec_firewall_filtering.md
> +- Berkeley Packet Filter - Identifies the filter to be applied. Validation confirms proper BPF syntax.
Yes, it has. We added config validation.

2023-12-06 16:57 UTC, ayungelson commented on docs/sec_firewall_filtering.md
> +ICMP Echo Replies that arrive at the SSR are dropped if no corresponding request has been seen and the ICMP Aysnc Reply is set to drop. This is the new default behavior; no change in configuration is
This statement isn't correct - this needs to be configured.
```
*admin@conductor.conductor# configure authority icmp-control icmp-async-reply drop
```

2023-12-06 16:59 UTC, ayungelson commented on docs/sec_firewall_filtering.md
> +The connection limit is configured at the router level (Authority > Router), and is unlimited by default. To set a limit, enter a numerical value in the `Half-Open Connection Limit` field in the Rout
I don't think this setting should ever be used. 
I recommend removing this sentence entirely: `This provides protection against SYN flood DDoS attacks.`
And furthermore, I would just recommend not enabling it.

2023-12-06 17:01 UTC, ayungelson commented on docs/sec_firewall_filtering.md
> +Packets with broadcast or multicast source L2 addresses will now be dropped by default.
It's not just L2...
so maybe 
`Packets with broadcast or multicast source addresses` - or `Packets with broadcast or multicast source IP and MAC addresses`

2023-12-07 20:05 UTC, MichaelBaj requested changes

2023-12-07 20:05 UTC, MichaelBaj commented on docs/sec_firewall_filtering.md
> +As part of the security hardening and certification process, the SSR has implemented the following firewall features to provide a more secure platform for network traffic. Steps for configuration fro
I don't think we need justification for why we developed these features. To be a player in the Secure SD-WAN Market, these features are arguably table-stakes. Suggested rewording:

The SSR has firewall capabilities which offer a more secure platform for network traffic, blending a layer 3 and layer 4 firewall with SD-WAN. Steps for configuration from both the GUI and the PCLI are provided.

2023-12-07 20:05 UTC, MichaelBaj commented on docs/sec_firewall_filtering.md
> +Additionally, if you require a limit for half-open TCP sessions, it may be helpful to consider the TCP session timeout value. The default timer is 1900000ms (roughly 31 minutes). If an application es
@ayungelson is this correct? 31 minutes for TCP initial state? That's got to be wrong. I thought TCP session timers were 30 min only upon establishment but initially very short during setup.

2023-12-14 14:30 UTC, ayungelson commented on docs/sec_firewall_filtering.md
> +Additionally, if you require a limit for half-open TCP sessions, it may be helpful to consider the TCP session timeout value. The default timer is 1900000ms (roughly 31 minutes). If an application es
Half-open connections and TCP established timers really have nothing to do with each other... The initial timeout is defaulted to 10 seconds, although it can be changed, so maybe that's what this is referring to? And if the application actually establishes a TCP socket, it doesn't matter whether it's idle or not - it has nothing to do with the `half-open` connection limit. Those are fully opened and don't count against this limit.

2023-12-14 14:36 UTC, MichaelBaj commented on docs/sec_firewall_filtering.md
> +Additionally, if you require a limit for half-open TCP sessions, it may be helpful to consider the TCP session timeout value. The default timer is 1900000ms (roughly 31 minutes). If an application es
Please correct me if I am wrong, but TCP initial timers have a direct impact on half-open connection limit.
If the initial connection timer is 10 minutes and the number of half-open connections allowed is 1000 (presuming all half-open connections are from a bad actor), then the system will not be able to handle a new TCP connection for 10 minutes.
If the initial connection timer is 10 seconds and the number of half-open connections allows is 1000 (presuming all half-open connections are from a bad actor), then the system will be able to process the next TCP session in 10 seonds.
Therefore, it is important to tune both parameters: Queue depth and Queue wait time before discard.

2023-12-14 16:36 UTC, ayungelson commented on docs/sec_firewall_filtering.md
> +Additionally, if you require a limit for half-open TCP sessions, it may be helpful to consider the TCP session timeout value. The default timer is 1900000ms (roughly 31 minutes). If an application es
@MichaelBaj yes - initial time matters of course. That's typically not tuned, and is defaulted to 10 seconds. If we wanted to mention this, then we should change the wording, something like this:
```
Additionally, if you require a limit for half-open TCP sessions, it may be helpful to consider the initial TCP session timeout value. The default timer is 10 seconds. If an application fails to establish a TCP socket, the sessions that are in that state will still remain on the SSR for that initial timeout. 
```

2023-12-15 14:41 UTC, closed without merging