Release notes for monitoring agent plugin
128technology/docs pull request #646
Opened 2023-12-07 04:45 UTC by agrawalkaushik

DOCS-395 #time 1h

2023-12-07 05:22 UTC, BenMatase commented on docs/plugin_monitoring_agent.md
> +  - **PLUGIN-2272 The `include-output` configuration causes unrelated config to be added to the generated config
Unrelated > duplicated

2023-12-07 05:22 UTC, BenMatase commented on docs/plugin_monitoring_agent.md
> +    _**Resolution**_ When an input uses multiple syslog output, the data corruption caused by message serialization code has been addressed.
Outputs

2023-12-07 14:07 UTC, Chr1st0ph3rTurn3r requested changes

2023-12-07 14:07 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_monitoring_agent.md
> +  - **PLUGIN-2274 Monitoring Agent Plugin allows `data-format` option on some inputs it shouldn't
```suggestion
  - **PLUGIN-2274 Monitoring Agent Plugin incorrectly allows the `data-format` option on some output.
```
input and output do not need to be pluralized (is that a word??) They are deemed plural by context.

2023-12-07 14:09 UTC, MichaelBaj commented on docs/plugin_monitoring_agent.md
> +The `t128_lte_collector` now includes additional information such as `carrier`, `connection-status`, `active-band-class`, `apn`, `service-mode` and `service-status`.
Does `t128_lte_collector` have any meaning to a customer? Would it be better to simply state:
Monitoring Agent now includes additional LTE information such as `carrier`, `connection-status`, `active-band-class`, `apn`, `service-mode` and `service-status`.

2023-12-08 22:11 UTC, gregschrock commented on docs/plugin_monitoring_agent.md
> +  - **PLUGIN-2274 Monitoring Agent Plugin allows `data-format` option on some inputs it shouldn't
This isn't "output" in the sense of results from a script where the entity cannot be counted. In this case, the outputs are distinct, named, and countable. I believe `outputs` is correct.

2023-12-08 22:11 UTC, gregschrock commented on docs/plugin_monitoring_agent.md
> +    _**Resolution**_ The code generation logic handles multiple `include-output` correctly and resolves the duplication in the generated config.
or instances/entries

2023-12-11 22:32 UTC, agrawalkaushik commented on docs/plugin_monitoring_agent.md
> +The `t128_lte_collector` now includes additional information such as `carrier`, `connection-status`, `active-band-class`, `apn`, `service-mode` and `service-status`.
Fair point @MichaelBaj - I'll re-word it!

2023-12-11 22:35 UTC, agrawalkaushik commented on docs/plugin_monitoring_agent.md
> +    _**Resolution**_ When an input uses multiple syslog output, the data corruption caused by message serialization code has been addressed.
> Isn't there a monitoring agent app section of release notes? Some of these should also go there?

I left the old notes there for posterity but I've stopped updating those since its a PITA.

2023-12-12 14:19 UTC, BenMatase requested changes

2023-12-12 14:19 UTC, BenMatase commented on docs/plugin_monitoring_agent.md
> +- 128T-monitoring-agent-plugin-router-1.1.9-1
This is 1.1.10-2

2023-12-12 14:19 UTC, BenMatase commented on docs/plugin_monitoring_agent.md
> +A new `timeout` argument is added for the `run-once` testing tool provided by `monitoring-agent-cli` to control how long the input waits to complete its data completion.
completion -> collection?

2023-12-13 14:08 UTC, MichaelBaj approved these changes

2023-12-13 14:17 UTC, BenMatase approved these changes

2023-12-14 13:08 UTC, Chr1st0ph3rTurn3r approved these changes

2023-12-14 13:20 UTC, merged