6.2 r2 release docs
128technology/docs pull request #647
Opened 2023-12-08 22:26 UTC by Chr1st0ph3rTurn3r

2023-12-11 12:48 UTC, jpetersonssr approved these changes

2023-12-11 18:04 UTC, MichaelBaj requested changes

2023-12-11 18:04 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-47253 Stuck Session Detection:** In situations where forward traffic is received, but there is no reverse traffic; for example, when the local IP of an interface performing source-nat changes
extra space after waypoint and will

2023-12-11 18:04 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-51614 Common Criteria Certification - Firewall Protection Profile :** Several updates to existing functionality have been made to address Common Criteria Certification. For additional informa
We can't claim certification yet. Instead, call out each of the firewall features that have been added. Add each one as a new feature, but use the same Jira ID for each. Add a brief description for each feature.

Packet Filtering
ICMP Filtering
IPv4 Option Filtering
TCP Half-Open Connection Limit

2023-12-11 18:04 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +
- [ ] TODO. Add CVEs here.

2023-12-14 15:02 UTC, MichaelBaj requested changes

2023-12-14 15:02 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-54434 MistPCAP failure - inverted commands observed by the device:** In rare cases where captures are created and deleted too quickly, a delete command may be received by the device before th
Need space after Mist

2023-12-15 13:41 UTC, MichaelBaj requested changes

2023-12-15 13:41 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-54780 Forwarding Utilization stats are missing:** This issue is the result of the fix in place for the `stats default retention short` setting was not being honored (I95-53875). This will be
Specifically passed one hour. Suggested rewording:
Forwarding Utilization stats are not retained beyond one hour:

2023-12-15 14:59 UTC, MichaelBaj requested changes

2023-12-15 14:59 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-53851 DHCP server scripts return false positive:** During the creation process, the DHCP scripts check the server name for an existing namespace. The script would return a false positive if t
Typo: substing

2023-12-15 15:11 UTC, MichaelBaj approved these changes

2023-12-15 15:56 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.2.md
> +- **I95-53896 nodeMonitor failed to get data for show platform disk:** Some of the dynamic access for smartctl objects were not protected. A check for the object existence has been added before attem
The number is inverted, this is https://128technology.atlassian.net/browse/I95-53986

2023-12-15 16:00 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.2.md
> +- **I95-51648 Application ID Database Memory Improvements:** Internal improvements have been made reduce memory consumption of the Application Identification IP database.
Recommend rewording this section:
"have been made reduce memory consumption"

to:

"have been made to reduce memory consumption"

2023-12-15 16:11 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.2.md
> +- **I95-53896 nodeMonitor failed to get data for show platform disk:** Some of the dynamic access for smartctl objects were not protected. A check for the object existence has been added before attem
This has an exclude on it - I just found it now. Unless you have objections, I will remove it.

2023-12-15 17:15 UTC, jeffmart-jnpr commented on docs/release_notes_128t_6.2.md
> +- **II95-50493 Memory calculation for alarms is confusing:** This alarm was designed to trigger when memory usage went above 90% and clear only when memory usage went below 80%, causing confusion. Th
There is a double I here

2023-12-15 18:52 UTC, MichaelBaj approved these changes

2023-12-15 18:52 UTC, jeffmart-jnpr approved these changes

2023-12-15 18:56 UTC, merged