Adding details regarding vector costs
128technology/docs pull request #648
Opened 2023-12-15 16:51 UTC by MichaelBaj

2023-12-15 16:57 UTC, laneshields commented on docs/concepts_glossary.md
> +It is possible to mix explicit vector values with implicit, ordered values, although this is not recommended. For cases where this type of configuration is necessary, the follow example illustrates t
Do we even want to open this door? I guess where would this be necessary?

2023-12-15 17:12 UTC, MichaelBaj commented on docs/concepts_glossary.md
> +It is possible to mix explicit vector values with implicit, ordered values, although this is not recommended. For cases where this type of configuration is necessary, the follow example illustrates t
I don't necessarily want to, but at the same time, we rightly got called out for not providing details for how order cost is defined. The same holds true for interspersing explicit and implicit cost. IMO, we are obligated to describe the system behavior.
Arguably all of this could have been avoided if we could just print out the generated values right from the config.

2023-12-15 17:15 UTC, Chr1st0ph3rTurn3r requested changes

2023-12-15 17:15 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_glossary.md
> +When defining vectors within a service-policy for association within a neighborhood, network-interface or service-route, each will be set with a default priority of `ordered`. The order in which they
```suggestion
When defining vectors within a service-policy for association within a neighborhood, network-interface, or service-route, each will be set with a default priority of `ordered`. The order in which they are configured define the precedence for which path should be used. The use of ordered vectors triggers the conductor to automatically generate a value for the vector cost. This numbering starts at one and increases by an order of magnitude (1, 10, 100, 1000, 10000, 100000, 999999). Ordered lists longer than six vectors will result in additional vectors autogenerated with the highest configurable cost of 999999 which would result in these vectors being considered equal cost. Therefore, for service-policies with more than six vectors it is required to manually set the cost.
```

2023-12-15 19:03 UTC, MichaelBaj commented on docs/concepts_glossary.md
> +It is possible to mix explicit vector values with implicit, ordered values, although this is not recommended. For cases where this type of configuration is necessary, the follow example illustrates t
As a compromise, we can add this content in a collapsible section so that it does not draw attention.
Attached are rendered examples of the implementation with the collapsed section closed and open:
![Screenshot 2023-12-15 at 2 01 29 PM](https://github.com/128technology/docs/assets/5543991/993003d3-3c9c-4b67-8a01-54bc8ac37122)
![Screenshot 2023-12-15 at 2 01 44 PM](https://github.com/128technology/docs/assets/5543991/a04ea500-fd5b-4fd8-bdb4-c3862ef3d06d)

2023-12-18 14:49 UTC, Chr1st0ph3rTurn3r approved these changes
I like the collapsable section. I haven't seen that in years.

2023-12-18 15:18 UTC, avinashbhat80 approved these changes

2023-12-18 15:56 UTC, merged