Add dns release notes to plugins
128technology/docs pull request #649
Opened 2023-12-18 17:11 UTC by jamesesilvia

## Description
add dns plugin release notes
also fixup DNS App ID info note endind

## Testing
<img width="1029" alt="Screenshot 2023-12-15 at 2 19 42 PM" src="https://github.com/128technology/docs/assets/1403603/3e91d2cc-19ff-42ae-b14c-17305462280e">
<img width="919" alt="Screenshot 2023-12-15 at 2 19 36 PM" src="https://github.com/128technology/docs/assets/1403603/3d02c5d6-2824-4388-9fd1-3225acf68517">

2023-12-18 17:30 UTC, agrawalkaushik commented on docs/plugin_dns_app_id.md
> +- **PLUGIN-1842** Pillar data scaling
For consistency, we've used the following for other plugins with this fix

```
#### New Features and Improvements
- **PLUGIN-1839** Reduce time to apply salt states in large scale deployments

By using Saltstack data files, the time to apply high states across all assets is significantly reduced.

```

2023-12-18 17:30 UTC, agrawalkaushik commented on docs/plugin_dns_app_id.md
> +- **PLUGIN-1842** Pillar data scaling
I think its probably best to re-use that (you can use the new JIRA).

2023-12-18 17:42 UTC, MichaelBaj requested changes

2023-12-18 17:42 UTC, MichaelBaj commented on docs/plugin_dns_app_id.md
> +**Release Date:** Dec 15, 2023
Has this plugin already been released? If not, this date is incorrect.

2023-12-18 17:42 UTC, MichaelBaj commented on docs/plugin_dns_cache.md
> +**Release Date:** Dec 15, 2023
Same comments above apply here as well.

2023-12-21 18:21 UTC, jamesesilvia commented on docs/plugin_dns_app_id.md
> +- **PLUGIN-1842** Pillar data scaling
took your suggestion and reworded a bit. please check

2023-12-21 18:21 UTC, jamesesilvia commented on docs/plugin_dns_app_id.md
> +**Release Date:** Dec 15, 2023
updated to today

2023-12-21 18:23 UTC, agrawalkaushik approved these changes

2023-12-21 18:24 UTC, MichaelBaj approved these changes

2023-12-21 22:42 UTC, jeffmart-jnpr approved these changes

2023-12-21 22:43 UTC, merged