Caveat for I95-54856
128technology/docs pull request #650
Opened 2023-12-19 15:12 UTC by Chr1st0ph3rTurn3r

2023-12-19 15:57 UTC, MichaelBaj requested changes

2023-12-19 15:57 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-54856 Rollback issue after upgrade to 6.2 from versions 6.1 or earlier:** If you upgrade from 6.1 (or older) to 6.2 and you have BGP neighbors with address family configuration, and then try
"If you upgrade" should be changed to "If the SSR is upgraded from"

* I thought that this issue only affected systems that were upgraded from 5.1 or older, not 6.1. Please confirm.

2023-12-19 15:57 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +One workaround is to copy off the `neighbor address-family` container and then delete it from the configuration before the downgrade. That configuration will need to be added back after the downgrade
Change wording to:
Workaround Options:
* Delete the `neighbor address-family` container from the configuration before the downgrade. The configuration removed will need to be added back after the downgrade.
* Explicitly configure `remove-private-as` to one of the other valid values. It is recommended to review your BGP configuration before making any of the below changes, as they may have an impact.
Valid values for `remove-private-as`:
- `all`: Remove all private AS in the AS path.
- `replace-all`: Replace all private AS with the local AS.
- `only`: Remove private AS only if the AS path contains just private AS.
- `replace-only`: Replace private AS with the local AS only if the AS path contains just private AS.

2023-12-20 13:58 UTC, MichaelBaj approved these changes

2023-12-20 14:34 UTC, jpetersonssr approved these changes

2023-12-20 14:43 UTC, merged