CC FIPS Documentation
128technology/docs pull request #651
Opened 2023-12-19 20:35 UTC by Chr1st0ph3rTurn3r

2023-12-19 21:24 UTC, MichaelBaj requested changes

2023-12-19 21:24 UTC, MichaelBaj commented on docs/cc_fips_sec_firewall_filtering.md
> +---
This document is the same that is already published correct? Rather than duplicate, please make it a module that is imported instead.

2023-12-19 21:24 UTC, MichaelBaj commented on docs/cc_fips_titlepage.md
> +This guide provides installation and configuration information for using SSR Conductors and Routers in a certified Common Criteria and FIPS environment.
While this introduction might be sufficient for those well versed in CC, this may not be sufficient for those navigating here without prior knowledge. A better introduction as to why a customer would chose to deploy in this fashion would be helpful.

2023-12-19 21:24 UTC, MichaelBaj commented on docs/cc_fips_router_install.md
> +---
This document is the same that is already published correct? Rather than duplicate, please make it a module that is imported instead.

2023-12-19 21:24 UTC, MichaelBaj commented on docs/cc_fips_config_password_policies.md
> +title: Username and Password Policies
This document is the same that is already published correct? Rather than duplicate, please make it a module that is imported instead.

2023-12-19 21:24 UTC, MichaelBaj commented on docs/cc_fips_conductor_install.md
> +---
This document is the same that is already published correct? Rather than duplicate, please make it a module that is imported instead.

2023-12-19 21:30 UTC, Chr1st0ph3rTurn3r commented on docs/cc_fips_sec_firewall_filtering.md
> +---
One of the requirements for the CC FIPS docs is that they are versioned, which would lock it. If we use the existing docs as links, then we cannot guarantee that the documentation won't change. So the individual files, specifically for this version of software are copied into the doc and not updated with the rest of the documentation. 

If we could have a separate location just for this doc, that would be better, and solve the issue of someone coming across it.

2023-12-20 19:42 UTC, MichaelBaj approved these changes

2023-12-20 19:42 UTC, MichaelBaj commented on docs/cc_fips_router_install.md
> +<!------->
Why is this here?

2023-12-20 21:31 UTC, migolnikov commented on docs/cc_fips_sec_firewall_filtering.md
> +---
Please keep in mind that CC and FIPS are completely independent of each other. The only reason FIPS is a part of this is because we require that FIPS mode is enabled on the SSR.  I would suggest renaming the PR to not include FIPS

2023-12-20 21:40 UTC, migolnikov requested changes

2023-12-20 21:40 UTC, migolnikov commented on docs/cc_fips_compliance_guidelines.md
> +- All configuration procedures must be performed from the PCLI; use of the GUI is not part of the approved use case.
the distinction is GUI is allowed during the initial setup process.

2023-12-20 21:40 UTC, migolnikov commented on docs/cc_fips_compliance_guidelines.md
> +- Traffic logging must be enabled by setting the following command to `true`:
This is a very performance affecting setting. Users should not expect to run more than a handful of sessions while traffic icsa events are being collected.

2023-12-20 21:40 UTC, migolnikov commented on docs/cc_fips_compliance_guidelines.md
> +- HTTPS/TLS, IPSec, SNMP, RADIUS.
no LDAP either. Basically nothing that uses TLS or IPSec

2023-12-20 21:40 UTC, migolnikov commented on docs/cc_fips_config_password_policies.md
> +title: Username and Password Policies
@MichaelBaj one of the requirements for this documentation is that it must be versioned. Meaning that once we get SSR CC certified with a particular version and with this specific Guidance doc, it must not be changeable. I am all for reusing this as a module, but it also must be frozen in time,

2023-12-20 21:40 UTC, migolnikov commented on docs/cc_fips_titlepage.md
> +title: SSR Common Criteria and FIPS Installation and User Guide
is this replacing our standard fips docs?

2023-12-20 21:43 UTC, Chr1st0ph3rTurn3r commented on docs/cc_fips_titlepage.md
> +title: SSR Common Criteria and FIPS Installation and User Guide
no. I was under the assumption that CC and FIPS were tied together as part of a certification, hence the doc reflects that. I am changing it all in the next push.

2023-12-21 13:47 UTC, iwbarker commented on docs/cc_fips_sec_firewall_filtering.md
> +---
> One of the requirements for the CC FIPS docs is that they are versioned

An alternative proposed by Teron is that we publish a PDF of the CC-specific doc, which is a snapshot in time of the common web-based doc content for FIPS.

That PDF can then be given a specific version number and posted as a standalone doc, along with the CC ST and guidance documents, which also must be similarly version controlled.

2023-12-21 13:51 UTC, iwbarker commented on docs/cc_fips_conductor_install.md
> +---
All CC documents must be immutable i.e. snapshot or standalone versioned documents, and cannot be updated after publishing without invalidating the CC compliance.  i.e. the exact docs used during CC verification must remain available indefinitely and unmodified, it's not permitted to reference CI/CD docs such as our online web pages.

2023-12-21 13:52 UTC, iwbarker commented on docs/cc_fips_conductor_install.md
> +#### Install via VGA Console
None of the CC certified platforms has a VGA does it?
I think we use serial console on all the qualified SSR platforms, so this can be omitted for CC.

2023-12-21 13:53 UTC, iwbarker commented on docs/cc_fips_conductor_install.md
> +## Conductor Installation
@migolnikov are we including conductor in CC?
Is conductor running on one of the CC qualified SSR platforms ?

2023-12-21 13:56 UTC, iwbarker commented on static/img/cc_fips_serial_conductor.png
This is the UEFI VGA, not the BIOS Serial.
Please replace with the 'blue' screenshot for fips serial.

2023-12-21 13:58 UTC, iwbarker commented on docs/cc_fips_compliance_guidelines.md
> +- Graphical User Interface (GUI) and Juniper MIST.
Should we also state that plugins are excluded from certification ?
In particular, FIPS/CC doesn't allow the wireshark plugin as that has uncertified crypto

2023-12-21 13:58 UTC, iwbarker commented on docs/cc_fips_compliance_guidelines.md
> +The following functionality and platforms are not supported under Common Criteria.
"not supported" -> "not permitted" ?

2023-12-21 14:02 UTC, iwbarker commented on static/img/install_serial_conductor_interactive1.png
mixed up titles for these img ?
this one is install VGA interactive, not install serial interactive

2023-12-21 14:03 UTC, iwbarker requested changes
screenshots and cc-specific details need fixing as noted inline

2023-12-21 19:33 UTC, iwbarker commented on docs/cc_fips_conductor_install.md
> +![Select Serial Install](/img/cc_fips_serial_install1.png)
I think we should remove 26..34 here, and move 34 down to after 44

2023-12-21 19:37 UTC, iwbarker commented on docs/cc_fips_router_install.md
> +
same comments as for conductor. i.e. remove the initial 'select' screen and rely on the fips section instead

2023-12-21 19:38 UTC, iwbarker commented on docs/cc_fips_router_install.md
> +Because not all hardware has video support, booting to the serial console 115200 baud is the default, and is automatically selected after 30 seconds. When using the serial console, the terminal size
can remove the reference to video as there are no VGA on any of the CC platforms

2023-12-21 19:38 UTC, iwbarker commented on docs/cc_fips_router_install.md
> +Selecting the wrong type of console (Serial or VGA) may result in garbled characters being displayed. If allowed to continue it will result in an incorrect installation. If the wrong console is selec
move this to after 45

2023-12-21 19:39 UTC, iwbarker commented on docs/cc_fips_router_install.md
> +  Both routers and conductors can consist of one node (for standalone systems) or two nodes (for highly available systems).
why are we referring to conductor here and next para, this doc section is for routers only

2023-12-21 19:41 UTC, iwbarker commented on docs/cc_fips_router_install.md
> +Selecting the wrong type of console (Serial or VGA) may result in garbled characters being displayed. If allowed to continue it will result in an incorrect installation. If the wrong console is selec
same, no vga

2023-12-21 20:05 UTC, migolnikov commented on docs/cc_fips_conductor_install.md
> +## Conductor Installation
Yes, conductor is included as a separate device. This is the distributed platform decision we made. There is no reason conductor cannot run on Juniper branded hardware.

2023-12-21 20:06 UTC, migolnikov commented on docs/cc_fips_compliance_guidelines.md
> +The following functionality and platforms are not supported under Common Criteria.
Or "not approved for common ctriteria" or "not certified"

2023-12-21 20:53 UTC, iwbarker approved these changes

2024-01-02 16:20 UTC, MichaelBaj requested changes

2024-01-02 16:20 UTC, MichaelBaj commented on docs/cc_fips_compliance_guidelines.md
> +- Except during installation, all configuration procedures must be performed from the PCLI; use of the GUI is not part of the approved use case. Configuring the router OTP Quickstart file from the Co
This statement should be reworded: "Configuring the router OTP Quickstart file" to "Configuring the router via OTP Quickstart file"

2024-01-02 16:20 UTC, MichaelBaj commented on docs/cc_fips_compliance_guidelines.md
> + This is a resource intensive setting. Not more than a few sessions are expected to run while collecting traffic events.
Does "a few sessions" here mean active PCLI sessions? Clarity is needed.

2024-03-20 20:55 UTC, MichaelBaj requested changes

2024-03-20 20:55 UTC, MichaelBaj commented on docs/cc_fips_access_mgmt.md
> +Prerequisites for installation and upgrades now include configuring a super user in /etc/sudoers that is allowed to execute Linux shell commands as root (sudo privileges).
enclose `/etc/sudoers` in back ticks

2024-03-20 20:55 UTC, MichaelBaj commented on docs/cc_fips_access_mgmt.md
> +It is recorded in /var/log/messages for the current boot:
place /var/log/messages in a code snippet

2024-03-20 20:55 UTC, MichaelBaj commented on docs/cc_fips_access_mgmt.md
> +The Kernel Known Answer Tests (KAT) for the FIPS subsystem run automatically at startup. Any failures are displayed on the system console during boot. These scroll quickly off screen, but are recorde
place /var/log/messages in a code snippet

2024-03-20 20:55 UTC, MichaelBaj commented on docs/cc_fips_config_audit_event.md
> +The Session Smart Router can be configured to maintain a history of several different class of events in the *event log* , which can subsequently be used to support compliance audits, forensics on ne
extra space after *event log*

2024-03-20 20:55 UTC, MichaelBaj commented on docs/cc_fips_config_audit_event.md
> +Traffic events are generated as sessions as created on the router. These include details such as the protocol, source address, source port, destination address and destination port. In addition, the
remove "as" after sessions

2024-03-20 20:55 UTC, MichaelBaj commented on docs/cc_fips_config_audit_event.md
> +```toml
This is not part of the 128T config. Specify the file that contains this contents.

2024-03-20 20:55 UTC, MichaelBaj commented on docs/cc_fips_config_audit_event.md
> +```toml
This is not part of the 128T config. Specify the file that contains this contents.

2024-03-20 20:55 UTC, MichaelBaj commented on docs/cc_fips_config_audit_event.md
> +[[inputs.t128_events]]
This is not part of the 128T config. Specify the file that contains this contents.

2024-03-20 20:55 UTC, MichaelBaj commented on docs/cc_fips_config_audit_event.md
> +### All Management Activities of TSF data
TSF?

2024-03-20 20:55 UTC, MichaelBaj commented on docs/cc_fips_software_upgrades.md
> +**The SSH Root login is not permitted and is not compliant with Common Criteria guidelines.** If the existing version allows SSH Root login, it will be disabled during the upgrade.
**Logging in as root is not permitted and is not compliant with Common Criteria guidelines.**

2024-03-21 15:04 UTC, Chr1st0ph3rTurn3r commented on docs/cc_fips_titlepage.md
> +| 0.1 | Initial version for 6.2.3-R2 Common Criteria | December 31, 2023 |
No, once finalized it will read only: | 1.0 | Initial version for 6.2.3-R2-14 Common Criteria | March 22, 20023 |

2024-03-21 15:32 UTC, Chr1st0ph3rTurn3r commented on docs/cc_fips_compliance_guidelines.md
> +- The `password-policy` must define the minimum password length and maximum number of permitted login attempts per user. Please refer to [Username and Password Policies](cc_fips_config_password_polic
I have not had an issue raised from Teron about it. I have to assume it is okay. I would guess that stating the requirements within the doc are what is required for CC, since there has been no comment on it.

2024-03-21 16:00 UTC, Chr1st0ph3rTurn3r commented on docs/cc_fips_intro_installation.md
> +- [Download the OTP ISO](cc_fips_downloading_iso.md)
It is stated on Line 19 - under the heading SSR Software Version.
"The SSR devices ship with an older version of SSR software that is not Common Criteria and FIPS compliant. It is required that you install SSR 6.2.3-14-R2 software on the device to configure and run Common Criteria and FIPS compliant instances."

2024-03-21 18:30 UTC, Chr1st0ph3rTurn3r commented on docs/cc_fips_config_audit_event.md
> +### All Management Activities of TSF data
Target of Evaluation (TOE) Security Functionality. Took me a long time to find that one... It now reads "All Management Activities of Security Functionality Data"

2024-03-21 19:45 UTC, MichaelBaj requested changes

2024-03-21 19:45 UTC, MichaelBaj commented on docs/cc_fips_config_audit_event.md
> +Traffic events are generated as sessions created on the router. These include details such as the protocol, source address, source port, destination address and destination port. In addition, the suc
oops, I gave incorrect advice.
Traffic events are generated as sessions are created

2024-03-21 20:11 UTC, MichaelBaj approved these changes

2024-03-22 14:55 UTC, MichaelBaj approved these changes

2024-03-22 15:01 UTC, merged