Single Router Migration per DOCS-284
128technology/docs pull request #653
Opened 2023-12-29 19:25 UTC by Chr1st0ph3rTurn3r

2023-12-29 19:58 UTC, ian-h-chamberlain approved these changes

2023-12-29 19:58 UTC, ian-h-chamberlain commented on docs/howto_router_migration.md
> +2. Run the `migrate` command as follows:
It might be good to clarify that only one of the two options is necessary. This reads to me as if you would need to do both in order.

2024-01-02 14:53 UTC, ian-h-chamberlain commented on docs/howto_router_migration.md
> +Alternatively, you can export the router configuration from the old conductor, and import and commit the router configurations to the new conductor. Or depending on the complexity of the configuratio
Hmm, this isn't quite what I had in mind. The configuration export/import is always necessary, as far as I know — but either of the two bulleted `migrate conductor` commands mentioned could be used. I'd probably write something like this:

```suggestion
1. Export the router configuration from the old conductor, and import and commit the router configurations to the new conductor. Depending on the complexity of the configuration, you may be able to simply copy and paste the router configuration to the new conductor.
2. Run either of the following `migrate` commands:
 - From the old conductor: `migrate conductor <new-address> router <router>`
 - From the router: `migrate conductor <new_address>`
```

2024-01-02 15:24 UTC, ian-h-chamberlain submitted a review, later dismissed

2024-01-02 16:47 UTC, MichaelBaj requested changes

2024-01-02 16:47 UTC, MichaelBaj commented on docs/howto_router_migration.md
> +This process is used to migrate an existing conductor-managed router to a new conductor and infrastructure. From the PCLI, the command can be run from the existing conductor to automatically migrate
"... the command can be run from the existing conductor to automatically migrate the router to the new conductor, or it can be run from the router itself"
Why the two different approaches? Why is one better than the other? Under what circumstances would you use one vs. the other? Can this be spelled out? If there is no difference, best to document a procedure using one approach only. Then add a footnote that the process can be done the other way, as needed.

2024-01-02 16:47 UTC, MichaelBaj commented on docs/howto_router_migration.md
> +1. Export the router configuration from the old conductor, and import and commit the router configurations to the new conductor. Depending on the complexity of the configuration, you may be able to s
I don't believe there is a way to export only a specific router's configuration @ian-h-chamberlain.
Can we enumerate the exact steps needed to obtain only the router's specific config?
Also, what about references to config outside of the router config model? Presumably those need to be copied over as well, else validation will fail.

2024-01-03 16:15 UTC, ian-h-chamberlain commented on docs/howto_router_migration.md
> +This process is used to migrate an existing conductor-managed router to a new conductor and infrastructure. From the PCLI, the command can be run from the existing conductor to automatically migrate
Functionally, both methods should be the same in terms of what actually happens to the router. I'd guess that driving it from the conductor is normally preferred for convenience, but if the user wanted to debug / monitor the system during migration they might want to drive it from the router (since it will at some point become inaccessible from the old conductor as part of the migration).

2024-01-03 16:34 UTC, ian-h-chamberlain commented on docs/howto_router_migration.md
> +1. Export the router configuration from the old conductor, and import and commit the router configurations to the new conductor. Depending on the complexity of the configuration, you may be able to s
That's true, and what it actually means to obtain a specific router's config probably varies per-deployment, since as you mention datamodel references to peers etc. would depend on the existing configuration. I'm not sure there's really a one-size-fits-all procedure for copying the configuration, but two options but the first thing that comes to mind would be something like this:

1. From the router PCLI (so it only includes config that applies to that router), `show config running flat > /tmp/router_config.txt`
2. Remove `conductor-address` from the config so that "import" doesn't overwrite it, and adjust any routing configuration that the router will need to be able to reach the new conductor
3. Copy `/tmp/router_config.txt` to the new conductor
4. In new conductor PCLI: `< /tmp/router_config.txt`
5. Perform migration with `migrate` command.

Step 2 is the most nebulous since it will depend on how the router reaches the new Conductor — if no special routing configuration is required then it might be trivial, but if management-over-forwarding is used or anything like that it could be more involved and deployment-specific.

2024-01-03 16:49 UTC, Chr1st0ph3rTurn3r commented on docs/howto_router_migration.md
> +1. Export the router configuration from the old conductor, and import and commit the router configurations to the new conductor. Depending on the complexity of the configuration, you may be able to s
I just did something similar to test my own theory about exporting just the router config. I opened the pcli for a router, did a show config running, and then ran 
```
admin@128t-west.128t-west# export config running west-router
✔ Exporting configuration...
Successfully exported configuration: /etc/128technology/config-exports/west-router.gz
```

2024-01-03 19:57 UTC, ian-h-chamberlain approved these changes

2024-01-03 20:26 UTC, MichaelBaj approved these changes

2024-01-03 21:48 UTC, merged