6.1.7 release notes
128technology/docs pull request #673
Opened 2024-02-13 22:39 UTC by Chr1st0ph3rTurn3r

2024-02-13 23:37 UTC, agrawalkaushik commented on docs/release_notes_128t_6.1.md
> +- **I95-54729 Marking of packets for Performance Monitoring:** Performance monitoring now prefers to mark non-metadata packets on established sessions instead of packets which already contain metadat
@Chr1st0ph3rTurn3r does this truly need a config change to work?

2024-02-13 23:37 UTC, agrawalkaushik commented on docs/release_notes_128t_6.1.md
> +- **I95-54909 Alarm when websense connection is down:** An alarm has been added to indicate that the connection to the Websense URL is down or responds with a 5xx error.
Same for this - I dont belive there is any config change needed for this.

2024-02-13 23:40 UTC, agrawalkaushik commented on docs/release_notes_128t_6.1.md
> +- **I95-55069 One HA node is missing from the Mist GUI:** REsolved an issue where a managed router had an empty product version config metadata field, which resulted in the conductor version metadata
```suggestion
- **I95-55069 One HA node is missing from the Mist GUI:** Resolved an issue where a managed router had an empty product version config metadata field, which resulted in the conductor version metadata field being cleared.
```

2024-02-14 13:54 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.1.md
> +- **I95-54729 Marking of packets for Performance Monitoring:** Performance monitoring now prefers to mark non-metadata packets on established sessions instead of packets which already contain metadat
Well, probably not, but the "Resolved Issues Requiring Configuration Changes" was the agreed upon heading for what used to be "New Features" in a point release, since we are not really supposed to be introducing new features. But this and the one below don't really seem to be "Resolved Issues" as much as new functionality.

2024-02-14 17:08 UTC, MichaelBaj requested changes

2024-02-14 17:08 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-54867 SSR 1300 baud rate set incorrectly:** Resolved an issue where the incorrect baud rate was allowed. The only allowed baud rate for the SSR is now 115200. This is the default rate.
should be a hyphen between SSR-1300

2024-02-14 17:08 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-55244 Unable to initialize DPDK:** Resolved an issue with the way the initializer identified the amount of memory in the processor. The initializer is now more NUMA aware when sizing the numb
**I95-55244 Unable to initialize DPDK; SSR does not start:

2024-02-14 20:32 UTC, MichaelBaj approved these changes

2024-02-15 00:22 UTC, Bhautik approved these changes

2024-02-17 11:49 UTC, jeffmart-jnpr approved these changes

2024-02-17 13:13 UTC, merged