6.3.0 release documentation
128technology/docs pull request #676
Opened 2024-02-21 19:10 UTC by Chr1st0ph3rTurn3r

2024-02-23 16:21 UTC, leo-128t-liu commented on docs/config_dnat.md
> +- [`remote-ip`](config_command_guide.md#configure-authority-router-node-device-interface-network-interface-dynamic-source-nat-remote-ip): For packets ingressing this interface, the IP where the `loca
Maybe worth mentioning `remote-ip` need to be `/32` prefix.

2024-02-23 16:21 UTC, leo-128t-liu commented on docs/config_dnat.md
> +title: Dynamic Source NAT
Maybe more a question for @avinashbhat80 and @MichaelBaj, shall we use `Dynamic Ingress Source NAT` to be more accurate naming for this feature?

2024-02-23 16:21 UTC, leo-128t-liu commented on docs/config_static_nat.md
> +title: Static NAT
I think this came from the func-spec. But I would like to propose this feature to be updated `Static Bidirectional NAT` because the content is referring to `bidirectional NAT` often.

2024-02-23 16:55 UTC, chao-128t reviewed
The static NAT and dynamic source NAT parts look good 👍.

2024-02-23 16:55 UTC, chao-128t commented on docs/config_static_nat.md
> +In order for non-SVR traffic (for example, LAN-to-LAN traffic traversing a single SSR) to take advantage of static-NAT addressing, you must disable egress source-nat at the service level by setting `
There are two more ways to disable egress source nat that we want to include here
- disable egress source-nat at the network-interface level by setting `network-interface > source-nat` to `false` and not configuring `network-interface > egress-source-nat-pool`
```
authority
    router SSR-router
        name SSR-router
        node SSR-node
            name SSR-node
            device-interface egress-LAN
                name egress-LAN
                network-interface egress-LAN
                    name egress-LAN
                    source-nat false
                    egress-source-nat-pool <DON'T CONFIGURE>
                exit
            exit
        exit
    exit
exit
```
- disable egress source-nat at the service-route level by not configuring `service-route > next-hop > source-nat-pool`
```
authority
    router SSR
        service-route LAN-to-LAN-route
            name LAN-to-LAN-route
            service-name LAN-to-LAN
            next-hop node egress-LAN
                node-name SSR-node
                interface egress-LAN
                source-nat-pool <DON'T CONFIGURE>
            exit
        exit
    exit
exit
```

2024-02-23 16:55 UTC, chao-128t commented on docs/config_dnat.md
> +Dynamic Source NAT may also provide solutions for IP address conflicts, but because it is not mapping NAT one-to-one, it is not required to facilitate the destination NAT mapping for network connecti
Maybe more clearer to the reader that they should not be confused or expect this to work like `bidirectional-nat`.
> Dynamic Source NAT may also provide solutions for IP address conflicts, but the IP mapping is not one-to-one and does **NOT** provide destination NAT in the reverse direction. To facilitate the destination NAT mapping for network connections from the external client to the internal client, use `bidirectional-nat` (add a link here).

2024-07-18 16:20 UTC, chao-128t commented on docs/config_source-dest_nat.md
> +The port range is not configurable and ranges between 16384 to 65534, allowing for 49,150 concurrent sessions per interface.
49151 concurrent sessions to be exact as both lower and upper ports should be included per `ip-address` per interface.

2024-07-18 16:20 UTC, chao-128t commented on docs/config_source-dest_nat.md
> +                        dhcp                    v4
A non-DHCP interface with multiple IPs statically configured is a more suitable example.
e.g.
```
...
dhcp disabled
address 192.168.1.101
    ip-address 192.168.1.101
    prefix-length 24
    gateway 192.168.1.1
exit
address 192.168.1.102
    ip-address 192.168.1.102
    prefix-length 24
    gateway 192.168.1.1
exit
...
```

2024-07-22 14:20 UTC, chao-128t commented on docs/config_static_nat.md
> +| 6.2.0   | Static NAT Feature Introduced   |
`6.3.0`?

2024-09-16 17:43 UTC, agrawalkaushik commented on docs/initialize_u-iso_device.md
> +---
@Chr1st0ph3rTurn3r either in this doc or elsewhere, we should also capture the PCLI workflow for each of these onboarding modes. It will be very helpful for the console based users.

Also I think this (and surrounding) documents mostly negates the need for `intro_installation_image` doc. The only exception I believe is the PCLI commands which I mentioned above.

2024-09-16 17:44 UTC, agrawalkaushik commented on docs/intro_upgrade_considerations.md
> +Beginning with SSR v6.3.0, the use of the interactive installer is not supported, or necessary. Software installation and upgrade upgrade activities are supported from the GUI or PCLI; rollback activ
should the `Beginning with SSR v6.3.0, the use of the interactive installer is not supported, or necessary.` be called out more explicitly as a note?

2024-09-24 20:36 UTC, agrawalkaushik commented on docs/initialize_u-iso_other.md
> +The brains behind the automated onboarding process is a json file named `onboarding-config.json`. This file contains all the configuration parameters and drives the entire onboarding process. The `on
```suggestion
The brains behind the automated onboarding process is a json file named `onboarding-config.json`. This file contains all the configuration parameters and drives the entire onboarding process. The `onboarding-config.json` can be provided from a USB, as a file placed on the SSR disk, or applied via API initialization. For virtual and cloud based deployments, the same mechanism is supported via cloud-init as well.
```

2024-09-24 20:37 UTC, agrawalkaushik commented on docs/initialize_u-iso_other.md
> +"name": "Conductor",
```suggestion
"name": "MyConductor",
```

2024-09-24 20:37 UTC, agrawalkaushik commented on docs/initialize_u-iso_other.md
> +“mode”: “conductor-managed”,
@haberkornsam Don't we need router name or asset-id in this case?

2024-09-24 20:40 UTC, agrawalkaushik commented on docs/initialize_u-iso_other.md
> +### File on Disk
This workflow also supports the pre/post scriplets so we should expand more on that in this section.

2024-09-24 20:40 UTC, agrawalkaushik commented on docs/initialize_u-iso_other.md
> +- pre-scriptlet
Also - somewhere in this doc -  we should capture the order in which we apply these scriptlets and any requiremetns we have such as root executable etc.

2024-09-25 15:15 UTC, haberkornsam commented on docs/initialize_u-iso_other.md
> +- pre-scriptlet
Scriptlets are passed the device identifier. This is usually the serial number. Ordering is
1. pre-bootstrap
2. normal bootstrapping
3. post-scriptlet
4. onboarding

2024-09-25 15:16 UTC, haberkornsam commented on docs/initialize_u-iso_other.md
> +### File on Disk
The paths for the scripts are `/etc/128T-hardware-bootstrapper/pre-bootstrap`. File must be executable.

2024-09-25 16:07 UTC, haberkornsam commented on docs/initialize_u-iso_other.md
The url of this page still says `initialize_u-iso_other` instead of the `advanced workflows name

2024-09-25 16:07 UTC, haberkornsam commented on docs/initialize_u-iso_other.md
> +	]
nit: the indentation of this isn't standard

2024-09-25 16:07 UTC, haberkornsam commented on docs/initialize_u-iso_other.md
> +3. UUID (via dmidecode)
@agrawalkaushik would the proper name for this be `DMI Decode` or just `via DMI`?

2024-09-25 16:07 UTC, haberkornsam commented on docs/initialize_u-iso_other.md
> +`/etc/128T-hardware-bootstrapper/post-bootstrap`
From the web these are not showing up on multiple lines. Not sure what needs to be done to fix that

2024-09-25 16:07 UTC, haberkornsam commented on docs/initialize_u-iso_other.md
> +3. UUID (via dmidecode)
Additionally, these defaults apply to mist managed

2024-09-25 16:07 UTC, haberkornsam commented on docs/initialize_u-iso_other.md
> +				"registration_code": "RegistrationCode",
should actually be `registration-code`

2024-09-26 01:46 UTC, MichaelBaj requested changes

2024-09-26 01:46 UTC, MichaelBaj commented on docs/release_notes_128t_6.3.md
> +- **I95-49712 Configuration validation error uniformative:** Resolved an issue that when configuring an SSR, invalid configuration parameters were returning errors that were not specific enough to al
Suggest breaking up the sentence. Add a period after validation. Start the next sentence with The messages include...

2024-09-26 01:46 UTC, MichaelBaj commented on docs/release_notes_128t_6.3.md
> +- **I95-54844 Default to Multi-threading:** New session processing rates are now increased by default when the system has sufficient CPU resources, by using multiple CPU threads.
Default to Multi-threading for session processing

2024-09-26 01:46 UTC, MichaelBaj commented on docs/release_notes_128t_6.3.md
> +- **I95-55725 Highway crashes when peer-path routers are removed:** Resolved a race condition that could cause a crash in the highway worker-core packet-processor if peer routers are removed from the
**I95-55725 Highway crashes when peer-path routers are removed:** Resolved a race condition that could cause a crash in the forwarding plane (highway) if peer routers are removed from the configuration.

2024-09-26 01:46 UTC, MichaelBaj commented on docs/release_notes_128t_6.3.md
> +- **I95-57110 Crash seen during add and delete peers while sending traffic:** A race condition has been fixed that could cause a crash in the packet-processing highway process if a peer-path is remov
could cause a crash in the forwarding plane (highway) process

2024-09-26 01:46 UTC, MichaelBaj commented on docs/release_notes_128t_6.3.md
> +<!-- markdown-link-check-disable -->
This link check disable should not be needed. This tells me that the reference to the KB article is incorrect.

2024-09-26 17:39 UTC, Chr1st0ph3rTurn3r commented on docs/config_lacp.md
> +* High Availability has not been fully tested, and may not be fully functional.
It is not fully supported. These statements are the result of a conversation with the test team (Dave F) and Jake Dionne and were added based on a request from Jeff Martin.

2024-09-26 19:08 UTC, Chr1st0ph3rTurn3r commented on docs/upgrade_ibu_conductor.md
> +**Package Based**
Because the conductor is still package based, but the conductor will store an Image based version for the routers. The example is to show them what they will see.

2024-09-26 19:33 UTC, Chr1st0ph3rTurn3r commented on docs/initialize_u-iso_device.md
> +## Initialize a Mist-Managed Router
There are three different workflows in that document. Conductor, Conductor-managed, and Mist-managed. They all originate from the same installation, which is the simplicity of the universal ISO. It made sense to me because they all start from the same location in the web interface.

2024-09-26 19:41 UTC, Chr1st0ph3rTurn3r commented on docs/install_univ_iso.md
> +Before beginning, ensure that you have an appropriate rollover cable available to connect to your computer. The SSR has a console port (CONSOLE) with an RJ-45 connector. Use the console port to conne
I don't understand this comment. How can you make selections on the boot screen if you are not connected to the SSR with a computer?

2024-09-26 19:45 UTC, MichaelBaj commented on docs/install_univ_iso.md
> +Before beginning, ensure that you have an appropriate rollover cable available to connect to your computer. The SSR has a console port (CONSOLE) with an RJ-45 connector. Use the console port to conne
Sorry, to be more clear. I mean that a customer that purchases a SSR120->SSR1500, these systems will come with SSR software already installed on them. i.e., they will start from another installation document. Make sense?

2024-09-26 20:02 UTC, Chr1st0ph3rTurn3r commented on docs/install_univ_iso.md
> +Before beginning, ensure that you have an appropriate rollover cable available to connect to your computer. The SSR has a console port (CONSOLE) with an RJ-45 connector. Use the console port to conne
never mind

2024-09-26 21:01 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.3.md
> +- **I95-28073 Support for OSPFv3:** Support for OSPF v3 routing protocol for IPv6 networks. See [OSPF](config_ospf.md) for additional information and command information.
no, apparently it was updated in 6.2.3. removing the jira from the release notes. It clearly says in the config_ospf.md file that it was updated in 6.2.3, and there are several references to the functionality in the doc.

2024-09-26 21:12 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_128t_6.3.md
> +<!-- markdown-link-check-disable -->
The link works and if i recall we had to do this because when it tried to build it would fail. We couldn't figure out why so we disabled the link. I'll investigate after the release if I don't get a chance before.

2024-09-27 08:12 UTC, Chr1st0ph3rTurn3r commented on docs/config_lacp.md
> +* High Availability has not been fully tested, and may not be fully functional.
removed

2024-09-27 17:51 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_legacy.md
> +## Installing SSR Software Versions 6.2.x and Earlier
The legacy guide and the 6.3.0 install guide overviews follow the same format. So the Installing section is laid out the same in both - this one just makes it clear that this is for versions 6.2.x and earlier. Are you suggesting that I change the heading to "Installation Process"?

2024-09-27 17:53 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_legacy.md
> +### Image-based Installation
I don't think so; the image based install is part of the legacy process for 6.0.x to 6.2.x. 6.3.0 uses the U-ISO which is different than the earlier image based install.

2024-09-27 17:56 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_legacy.md
> +### Image-based Installation
I've added this to the paragraph:
### Image-based Installation

SSR Version 6.3.0 provides support for image-based installs for both Conductor- and Mist-managed deployments. Earlier installations (6.0.x - 6.2.x) using the image-based install only support Mist-managed deployments.

2024-09-27 18:00 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_legacy.md
> +## Installing SSR Software Versions 6.2.x and Earlier
I changed the heading to Installation Process.

2024-09-30 16:36 UTC, MichaelBaj requested changes

2024-09-30 16:36 UTC, MichaelBaj commented on docs/releases.table.js
> +    url: 'release_notes_128t_6.1#release-6110-8-lts',
All of the other releases updated in the other release notes page need to be updated here as well.

2024-09-30 18:09 UTC, MichaelBaj approved these changes

2024-09-30 21:28 UTC, merged