Release notes for WAN Assurance plugin 3.7.7
128technology/docs pull request #678
Opened 2024-02-24 05:50 UTC by agrawalkaushik

DOCS-403 #time 30m

2024-02-26 15:39 UTC, MichaelBaj requested changes

2024-02-26 15:39 UTC, MichaelBaj commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +**Release Date:** TBD
- [ ] Add release date

2024-02-26 15:39 UTC, MichaelBaj commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +- **WAN-2858 LLDP client information not send for routers running version 6.2.3 software**
typo: "not sent"

2024-03-01 04:33 UTC, agrawalkaushik commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +- **WAN-2858 LLDP client information not send for routers running version 6.2.3 software**
done

2024-03-01 13:19 UTC, MichaelBaj requested changes
Release state missing

2024-03-01 13:30 UTC, Chr1st0ph3rTurn3r approved these changes

2024-03-08 14:09 UTC, MichaelBaj approved these changes

2024-03-18 13:37 UTC, Chr1st0ph3rTurn3r requested changes

2024-03-18 13:37 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +- **WAN-2240 WAN bandwidth graph is blank after the user adds new WAN interfaces: oc-stats from the SSR is missing some interfaces**
```suggestion
- **WAN-2240 WAN bandwidth graph is blank after the user adds new WAN interfaces: `oc-stats` from the SSR is missing some interfaces**
```

2024-03-18 13:37 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +- **WAN-2478 Disabling WAN Assurance plugin does not stop the mist-agent service**
```suggestion
- **WAN-2478 Disabling the WAN Assurance plugin does not stop the mist-agent service**
```

2024-03-18 13:37 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +  _**Resolution**_ The runtime par file corruption of monitoring-agent package is being addressed by adopting a better packaging approach.
```suggestion
  _**Resolution**_ The runtime par file corruption of the monitoring-agent package has been addressed by adopting a better packaging approach.
```
Also, is the "runtime par file" correct? I've not heard of a "par" file. Just verifying that it's not a typo.

2024-03-18 13:37 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +- **WAN-2696 Client information displays user as `Anonymous` **
```suggestion
- **WAN-2696 Client information displays user as `Anonymous`**
```

2024-03-18 13:37 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_wan_assurance_plugin_3.7.md
> +- **WAN-2897 Router not reporting CPU, memory and port metrics**
```suggestion
- **WAN-2897 Router not reporting CPU, memory, and port metrics**
```

2024-03-29 01:50 UTC, Chr1st0ph3rTurn3r approved these changes

2024-03-29 14:33 UTC, merged