PAYG MIST managed Azure instructions
128technology/docs pull request #682
Opened 2024-03-13 21:21 UTC by agrawalkaushik

2024-03-13 21:47 UTC, MichaelBaj requested changes

2024-03-13 21:47 UTC, MichaelBaj commented on docs/intro_installation_azure.md
> +Mist-managed SSR installations are now available through Azure. **However, SSR Version 6.x installed as an Azure image will only support Mist-managed routers. It will not support a conductor-managed
recommended rewording of 2nd sentence:
**SSR software versions 6.x and greater are only supported for Mist-managed deployments and not supported for conductor-based deployments.**

2024-03-13 21:47 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +![Plans](/img/platforms_azure_plans.png)
Are these a new or pre-existing images?

2024-03-13 21:47 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +Proceed to the next section [Selecting the Azure plan"](#selecting-the-azure-plan).
This is unnecessary since it is literally jumping you to the next line.

2024-03-13 21:47 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +* Hourly Plan: This provides a free trial period for 30 days and an hourly software cost after the trial expires. This plan is recommended for Proof of Concepts and Trials only. Software upgrades and
"The software can not be purchased via the marketplace"
cannot is one word

This is also a confusing statement since the software is being purchased, albeit hourly. What do you mean exactly that the software can't be purchased?

2024-03-13 21:47 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +* The version of the Session Smart Networking software. Your Juniper Sales representative will assist you if you don't know the version you need for your deployment.
The "desired version"

2024-03-13 21:47 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +3. Wait for the confirmation from your Juniper Sales representative to confirm that your Azure Subscription has been allowlisted and therefore access has been granted.
"allowlisted" on word? Is this an Azure term?

2024-03-13 21:47 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +Once you have selected the plan that better suits the needs of your deployment, proceed to the section [Session Smart Conductor Deployment](#session-smart-conductor-deployment) to deploy a Session Sm
If this guide is specifically for Mist, can we please separate this document into two, one for Mist and one for conductor?

2024-03-13 21:47 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +If the validation process fails with the error shown below, please make sure you are deploying the version of the software Juniper has allowlisted to your Subscription ID and try again later. If the
move to a troubleshooting section?

2024-03-13 21:47 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +If the validation process fails with the error shown below, please make sure you are deploying the version of the software Juniper has allowlisted to your Subscription ID and try again later. If the
troubleshooting section

2024-03-13 21:47 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +If the device does not show up in the Mist org after 5 minutes, ssh into the instance.
troubleshooting

2024-03-13 21:47 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +  * If there is an existing Session Smart Conductor in the network and the intent is to perform a non interactive installation of an SSR (for example a ZTP installation) please make sure the certific
Does this belong in a Mist install guide?

2024-03-13 23:07 UTC, agrawalkaushik commented on docs/intro_installation_azure.md
> +Mist-managed SSR installations are now available through Azure. **However, SSR Version 6.x installed as an Azure image will only support Mist-managed routers. It will not support a conductor-managed
I took this verbatim from the AWS doc and this came from @Chr1st0ph3rTurn3r FWIW

2024-03-13 23:07 UTC, agrawalkaushik commented on docs/intro_installation_azure_mist.md
> +![Plans](/img/platforms_azure_plans.png)
pre-existing

2024-03-13 23:08 UTC, agrawalkaushik commented on docs/intro_installation_azure_mist.md
> +Proceed to the next section [Selecting the Azure plan"](#selecting-the-azure-plan).
I mostly just copy/pasted this from the exisitng Azure doc. Once new images are published I'll go back and clean up the docs but for now I hope its okay to keep this as is. I want to also get better screenshots coz these word instructions are actually very confusing. I wont have time to do that for this doc for now though.

2024-03-13 23:09 UTC, agrawalkaushik commented on docs/intro_installation_azure_mist.md
> +* Hourly Plan: This provides a free trial period for 30 days and an hourly software cost after the trial expires. This plan is recommended for Proof of Concepts and Trials only. Software upgrades and
not sure - this is exactly copy/pasted from existing docs - https://docs.128technology.com/docs/intro_installation_azure - which is already published.

2024-03-13 23:11 UTC, agrawalkaushik commented on docs/intro_installation_azure_mist.md
> +  * If there is an existing Session Smart Conductor in the network and the intent is to perform a non interactive installation of an SSR (for example a ZTP installation) please make sure the certific
it does not - I'll remove it - the base document was copied from https://docs.128technology.com/docs/intro_installation_azure so this was a left over. Good catch.

2024-03-13 23:13 UTC, agrawalkaushik commented on docs/intro_installation_azure_mist.md
> +If the validation process fails with the error shown below, please make sure you are deploying the version of the software Juniper has allowlisted to your Subscription ID and try again later. If the
this is how we structured the AWS doc - so following the same format

2024-03-13 23:15 UTC, agrawalkaushik commented on docs/intro_installation_azure_mist.md
> +3. Wait for the confirmation from your Juniper Sales representative to confirm that your Azure Subscription has been allowlisted and therefore access has been granted.
no idea - its taken from https://docs.128technology.com/docs/intro_installation_azure - probably worth asking Tony Sanchez to re-review this once published. I dont know if the process has changed at all since we last captured these docs.

2024-03-13 23:20 UTC, agrawalkaushik commented
@MichaelBaj I've removed all the incorrect "conductor" references. I unfortunately wont have the bandwidth to true up the rest of the doc since its just copy/pasted from existing docs. We can hopefully come back to that in the future to take another pass of cleanup for all of them.

2024-03-14 00:09 UTC, MichaelBaj requested changes

2024-03-14 00:09 UTC, MichaelBaj commented on docs/intro_installation_azure.md
> +:::important
It would make more sense to point to the conductor azure onboarding guide rather than include that information here.

2024-03-14 00:09 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +This section describes how to fill out and launch the template using either the AWS marketplace or programmatically to deploy a Session Smart Router.
AWS -> Azure

2024-03-14 13:32 UTC, agrawalkaushik commented on docs/intro_installation_azure.md
> +:::important
The existing doc is meant for conductor but I agree. @Chr1st0ph3rTurn3r can we do a 2nd pass of restructuring the docs?

2024-03-14 13:36 UTC, agrawalkaushik commented on docs/intro_installation_azure_mist.md
> +This section describes how to fill out and launch the template using either the AWS marketplace or programmatically to deploy a Session Smart Router.
good catch ... done

2024-03-14 15:23 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_azure.md
> +Mist-managed SSR installations are now available through Azure. **However, SSR Version 6.x installed as an Azure image will only support Mist-managed routers. It will not support a conductor-managed
According to the responses I got while writing the AWS guide, virtual installs of 6.x and greater on AWS and Azure will only support Mist-managed routers. Since you can install 6.x on a conductor and router, and have a conductor managed deployment, this note is specific to virtual images.

2024-03-14 15:34 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_azure_mist.md
> +3. Wait for the confirmation from your Juniper Sales representative to confirm that your Azure Subscription has been allowlisted and therefore access has been granted.
It is a term that I believe is used in their documentation - I am fairly sure I verified it in the Azure docs/installation earlier, but I will verify.

2024-03-14 15:37 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +Proceed to the next section [Selecting the Azure plan"](#selecting-the-azure-plan).
```suggestion
```

2024-03-14 15:38 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_azure_mist.md
> +* Hourly Plan: This provides a free trial period for 30 days and an hourly software cost after the trial expires. This plan is recommended for Proof of Concepts and Trials only. Software upgrades and
It's referring to on prem software being purchased through Azure. That is extremely confusing and id not necessary. I'll remove in both locations.

2024-03-14 15:38 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +* Hourly Plan: This provides a free trial period for 30 days and an hourly software cost after the trial expires. This plan is recommended for Proof of Concepts and Trials only. Software upgrades and
```suggestion
* Hourly Plan: This provides a free trial period for 30 days and an hourly software cost after the trial expires. This plan is recommended for Proof of Concepts and Trials only. Software upgrades and deployments outside of the cloud, (on premises) require a token. The software cannot be purchased via the marketplace. Select the Hourly plan of the [Session Smart Networking Platform](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/juniper-networks.session-smart-networking-payg?tab=Overview) offering.
```

2024-03-14 15:39 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +Once you have selected the plan that better suits the needs of your deployment, proceed to the [Session Smart Router Deployment](#session-smart-router) to deploy a Session Smart Router.
```suggestion
Once you have selected the plan that best suits the needs of your deployment, proceed to the [Session Smart Router Deployment](#session-smart-router) to deploy a Session Smart Router.
```

2024-03-14 15:40 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +There is no software cost associated with deploying the Private image, the cost of running the VM is the only cost (Azure compute cost). Please also note that software upgrades and deployments **outs
```suggestion
There is no software cost associated with deploying the Private image, the cost of running the VM is the only cost (i.e., Azure compute cost). Please also note that software upgrades and deployments **outside** of the cloud (e.g., on premises) will not be possible without a software access token.
```

2024-03-14 15:41 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +* The version of the Session Smart Networking software. Your Juniper Sales representative will assist you if you don't know the version you need for your deployment.
```suggestion
* The version of the Session Smart Networking software. Your Juniper Sales representative will assist you if you do not know the desired version needed for your deployment.
```

2024-03-14 15:48 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +Provide it in the "Instance Name" field (for example: 128TRouter).
```suggestion
Provide it in the "Instance Name" field (for example: `128TRouter`).
```

2024-03-14 15:49 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +  * Provide the name of the VNet in the "Virtual Network Name" field (for example: 128T-VNet).
```suggestion
  * Provide the name of the VNet in the "Virtual Network Name" field (for example: `128T-VNet`).
```

2024-03-14 15:49 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +  * Provide the name of the availability set in the "Availability Set Name" field (for example: 128TRouterSet).
```suggestion
  * Provide the name of the availability set in the "Availability Set Name" field (for example: `128TRouterSet`).
```

2024-03-14 15:49 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +Provide an username (for example: t128) and the content of your public SSH key in the "Admin Username" and "Admin Public Key Data" fields respectively.
```suggestion
Provide an username (for example: `t128`) and the content of your public SSH key in the "Admin Username" and "Admin Public Key Data" fields respectively.
```

2024-03-14 15:51 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +* If the **Session Smart Networking Platform** offering selected for the deployment is a **Private image**, the non-interactive, Zero Touch Provisioning (ZTP) method is triggered. After the VM is dep
```suggestion
* If the **Session Smart Networking Platform** offering selected for the deployment is a **Private image**, the non-interactive, Zero Touch Provisioning (ZTP) method is triggered. After the VM is deployed, it will take an additional 2-3 minutes for the ZTP process to complete. When the ZTP process concludes, there will be an asset in the Mist inventory to be associated with the router configuration.
```

2024-03-14 15:54 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +If the device does not show up in the Mist org after 5 minutes, ssh into the instance.
```suggestion
```

2024-03-14 15:54 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +- Log into the pcli, run `su admin` and then `show mist`.
```suggestion
```

2024-03-14 15:54 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +- If that does not show the device, drop back to the linux shell and look at the journal for the bootstrapper:
```suggestion
```

2024-03-14 15:54 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> + - `journalctl -u 128T-hardware-bootstrapper`
```suggestion
```

2024-03-14 15:56 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> + And the Mist agent:
```suggestion
```

2024-03-14 15:56 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> + - `journalctl -u 128T-mist-agent`
```suggestion
```

2024-03-14 15:57 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +Click on the "Launch" link of the "Juniper Session Smart Router" template that better suits your needs.
```suggestion
Click on the "Launch" link of the "Juniper Session Smart Router" template that best suits your needs.
```

2024-03-14 15:57 UTC, MichaelBaj commented on docs/intro_installation_azure_mist.md
> +:::
```suggestion
:::

## Troubleshooting

### Device Does Not Exist In Mist after ZTP
If the device does not show up in the Mist org after 5 minutes, ssh into the instance through the Azure portal.
- Log into the pcli, run `su admin` and then `show mist`.

- If the status and action necessary is not obvious, drop back to the linux shell and look at the journal for the bootstrapper:
 - `journalctl -u 128T-hardware-bootstrapper`

 And the Mist agent:
 - `journalctl -u 128T-mist-agent`
```

2024-03-14 20:56 UTC, BenMatase approved these changes

2024-03-14 20:56 UTC, BenMatase commented on docs/intro_installation_azure_mist.md
> +| registration-code | The Mist registration used for adoption of the EC2 instance to a Mist org. |
not ec2. I'd search for ec2 elsewhere in this doc or any other aws specific terminology

2024-03-14 21:18 UTC, MichaelBaj approved these changes

2024-03-14 21:19 UTC, Chr1st0ph3rTurn3r approved these changes

2024-03-14 21:31 UTC, MichaelBaj approved these changes

2024-03-14 21:42 UTC, merged