6.2.4 r2 release notes
128technology/docs pull request #697
Opened 2024-03-28 19:25 UTC by Chr1st0ph3rTurn3r

2024-03-28 21:57 UTC, MichaelBaj requested changes

2024-03-28 21:57 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-54780 Forwarding CPU utilization metrics missing:** Updated the retention policy for forwarding CPU utilization and other metrics.
**I95-54780 Forwarding CPU utilization metrics missing for duration greater than 1 hour:** Updated the retention policy for forwarding CPU utilization and other metrics.

2024-03-28 21:57 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-54808 Ingress VLAN tag getting stripped:** Updated the DPDK, which adds measures to prevent the vlan reinsert flag from being reset.
- **I95-54808 Ingress VLAN tag getting stripped:** Added measures to prevent the vlan reinsert flag from being reset.

2024-03-28 21:57 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-54841 NoServicePathsAvailable on RP after all receivers leave the stream:** The PIM Register State would time out at the RP due to the First-Hop router (FHR) not correctly processing the PIM
NoServicePathsAvailable = `No Service Paths Available`

2024-03-28 21:57 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-55208 SSR `state.apply` holds process lock:** Added a timeout value for processes in highstate, allowing the process to time out.
- **I95-55208 Asset fails to transition state:** In certain cases when the RPM database is corrupted or another process holds its lock indefinitely, the highstate can block forever running `rpm -q`. Since other highstate attempts see an existing highstate job, they don't try to do anything else and the asset stays stuck like that forever without manual intervention.

2024-03-28 21:57 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-55416 Dynamic reconfig of the PCI address of a bond member breaks connectivity:** Added an identifier to the bond member, enabling the proper handling of the member whenever the PCI address i
bond members = LAG memebers

2024-03-28 21:57 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-55454 Dropped packets in correctly listed as a result of Firewall filter rule:** Firewall filter rules on the network interface can be configured to drop non-ip packets. The non-ip packets we
in correctly = incorrectly

2024-03-28 21:57 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-55586 `IsActive `incorrectly returns true if the `device-interface` is `vrrp_standby`:** The `router-peer-path` setting now returns the correct value when in `vrrp-standby`.
- **I95-55586 GraphQL API returns`IsActive` incorrectly if the `device-interface` is `vrrp_standby`:** The `router-peer-path` setting now returns the correct value when in `vrrp-standby`.

2024-03-28 21:57 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95 55804 After node restart, stream is lost for approximately 2 minutes on HA router:** During restart the multicast state is relearned by the routing engine. To prevent data loss the routing en
I95-55804

2024-03-28 21:57 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-55903 Memory alarm persists in LAG/HA/VRRP configuration:** The `Memory exceeded 90%` alarm appears and persists in an HA configuration, due to multiple database connections being made and no
configuration, due
comma unnecessary

2024-03-28 21:57 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-55948 Unable to login to SSR using remote radius authentication:** Resolved an issue where the Radius `add user` hook incorrectly aliased users, based on a search pattern.
radius = RADIUS

2024-03-28 21:57 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **WAN-2753 IDP Engine Failed to Start:** Resolved an issue where an umnanaged podd may cause a rebuild failure, preventing the IDP engine from starting.
- **WAN-2753 IDP Engine Failed to Start:** Resolved an issue that prevented IDP from starting if its configuration had changed.

2024-03-29 12:47 UTC, MichaelBaj commented on docs/config_radius.md
> +Additionally, RADIUS has the concept of a Vendor Specific Attribute (VSA). This allows the administrator to configure their RADIUS server to include that VSA. The VSA is then configured with a group
As per https://www.juniper.net/documentation/us/en/software/junos/user-access/topics/topic-map/user-access-radius-authentication.html#id-juniper-networks-vendor-specific-radius-attributes
The actual VSA number has to be specified. I'm not sure if it is the same `2636`. Please confirm and add.

2024-03-29 12:48 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-53878 New LACP protocol stats added:** LACP related counters are now available at a per-bond-member resolution. For more information, see [show stats interface received lacp](cli_stats_refere
There is a broken link somewhere related to these stats references. You will need to track them down and correct.

2024-03-29 13:35 UTC, MichaelBaj requested changes

2024-03-29 13:35 UTC, MichaelBaj commented on docs/config_radius.md
> +LDAP server is disabled but an entry exists for them in the user datastore.
Is this output correct? This example is intended to illustrate RADIUS, but the detailed user output mentions LDAP?

2024-03-29 13:35 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-55672 MSDP Alarms for Peer State Change:** MSDP Alarms have been added for peer state change. For more information, see **MSDP Alarms** (add link here)
- [ ] To do: Add information here.

2024-03-29 13:35 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-51663 TCP port reuse causing application steering crashes:** Resolved an issue where backwards state transitions was causing an issue with the TCP client reusing ports.
I don't understand what TCP port reuse means. I looked through the code and don't understand. Please ask Anya.
This has to do with `transport-state-enforcement`, which should be mentioned here.

2024-03-29 13:35 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-51787 SNMP alarms generation process updated:** SNMP now uses the SHA1 algorithm to identify a specific instance of an alarm. After upgrading to this release, you will see different values fo
My interpretation of this issue is as follows:
- **I95-51787 SNMP alarms generation is not FIPS compliant:** SNMP now uses the SHA1 algorithm to identify a specific instance of an alarm. After upgrading to this release, you will see different values for these instance IDs. These values are defined as "opaque" and are intentionally not guaranteed to be consistent from release to release.

2024-03-29 13:35 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-52250 Security Package Update:** Updates have been made to Intrusion Detection and Prevention (IDP)
- **I95-52250 Security Package Update:** Intrusion Detection and Prevention (IDP) signatures have been updated.

2024-03-29 13:35 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-52500 SVR Multi Hop Failover:** Added a session lookup by session-ID to resolve a situation where sessions failing between multi-hop SVR and direct SVR connections may lead to duplicate flow
- **I95-52500 SVR multi-hop failover causes traffic to drop when using outbound-only:** Added a session lookup by session-ID to resolve a situation where sessions failing between multi-hop SVR and direct SVR connections may lead to duplicate flow exceptions and dropped traffic.

2024-03-29 13:35 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-53523 LAG interface cleanup following shutdown of the 128T service:** The order in which a LAG interface is broken down and cleaned up after shutdown has been optimixed and errors resolved.
typo: optimized
heading should read:
I95-53523 LAG interface unbind errors following shutdown of the 128T service:

2024-03-29 13:35 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-53920 Password expiration being applied to users managed through external user databases (such as LDAP or RADIUS):** Resolved an issue that incorrectly enforced password expiration (`configur
- **I95-53920 Password expiration incorrectly applied to users managed through external user databases (such as LDAP or RADIUS):** Resolved an issue that incorrectly enforced password expiration (`configure authority password-policy lifetime`) to RADIUS users.

2024-03-29 13:35 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-54189 Application mapping does not correctly match services:** Resolved an issue where the application director was misclassifying sessions due to IP overlap; this is a valid configuration, w
- **I95-54189 Application classification mapping does not correctly match configured services:** Resolved an issue where DPI was misclassifying sessions due to IP overlap. When services use an IP address with different ports assigned to different services, the SSR now recognizes these different port configurations.

2024-03-29 13:35 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-54340 Hub-to-spoke sessions fail during failover from outbound-only path:** When a session modify occurs due to an ingress change (inter-node -> inter-router) AND an egress change is also det
extra space after was

2024-03-29 13:35 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-54471 `ServiceAreaGatewayLookupFailed` exceptions:** When the egress interface has no gateway, the original packet dest IP was used for gateway lookup. Oftentimes, the original packet dest IP
Heading should read:
I95-54471 LAN-to-LAN traffic with Destination NAT without a gateway configured for either subnet results in dropped traffic and the error log:`ServiceAreaGatewayLookupFailed` exceptions:

2024-03-29 14:03 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-54808 Ingress VLAN tag getting stripped:** Added measures to prevent the vlan reinsert flag from being reset.
- **I95-54808 Ingress VLAN tag getting stripped for vSSR with SR-IOV:** Added measures to prevent the VLAN reinsert flag from being reset.

2024-03-29 14:06 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-54909 Generate an Alarm when Websense is down:** Implemented an alarm when the connection to the Websense server is down or responds with a 5xx error.
- **I95-54909 Alarm not generated when Websense is down:** Implemented an alarm when the connection to the Websense server is down or responds with a 5xx error.

2024-03-29 14:12 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-55261 Only run `validate` for plugins on the Conductor:** Resolved an issue where the plugin validator was running on routers.
- **I95-55261 Config validation incorrectly being run on router:** Resolved an issue where the plugin validator was running on routers. Validate is now correctly run only on the conductor.

2024-03-29 14:18 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-55948 Unable to login to SSR using remote RADIUS authentication:** Resolved an issue where the Radius `add user` hook incorrectly aliased users, based on a search pattern.
This should be removed. It is a found and fixed during development of the RADIUS feature.

2024-03-29 15:38 UTC, ecarson commented on docs/config_radius.md
> +RADIUS and LDAP remote authentication can be configured on a system. RADIUS will take precedence over LDAP, and is the first authorization request sent out. If RADIUS authentication is rejected or if
We should update this, it's not actually possible to configure both and this will be reported as a validation error now. Should be:
```
Either RADIUS and LDAP remote authentication can be configured on a system.
```
and delete
```
RADIUS will take precedence over LDAP, and is the first authorization request sent out.
```

2024-03-29 15:38 UTC, ecarson commented on docs/config_radius.md
> +It is also possible to configure only RADIUS authentication.
It is either/or

2024-03-29 15:42 UTC, ecarson commented on docs/config_radius.md
> +When authenticating from a RADIUS server, user authentication and local access is now configurable from the RADIUS server. Users are added and identified on the server, and each user account is creat
How about this:
```
When authenticating from a RADIUS server, the user is authenticated on the RADIUS server against the configured credentials. When account-creation is set to automatic, users are added and identified on the server, and each user account is created automatically when they authenticate successfully from a local device. This provides a simple method for managing user accounts connected to a single authentication server, with devices deployed over a wide geography.
```

2024-03-29 15:43 UTC, ecarson commented on docs/config_radius.md
> +Users are configured on the RADIUS server using the RADIUS Vendor Specific Attribute (VSA). Automatic account creation is enabled on the SSR, and user accounts are created on first login to the SSR.
```
If automatic account creation is enabled, users are configured on the RADIUS server using a RADIUS Vendor Specific Attribute (VSA) and user accounts are created on first login to the SSR based on the role specified in the VSA.
```

2024-03-29 15:45 UTC, ecarson commented on docs/config_radius.md
> +Using the RADIUS Vendor Specific Attribute (VSA) allows the administrator to identify users and assign them to a user role. The VSA Vendor ID indicates a Juniper system; the Juniper vendor ID is 2636
It might be good to identify the specific VSA by name (Juniper-Local-User-Name, which is type 1). Also it would be worth noting that this is currently the only Juniper VSA supported by the SSR as there are others that users might already be familiar with that we _don't_ support in SSR:
https://www.juniper.net/documentation/us/en/software/junos/user-access/topics/topic-map/user-access-radius-authentication.html

2024-03-29 15:46 UTC, MichaelBaj requested changes

2024-03-29 15:46 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-54189 I95-54189 Application classification mapping does not correctly match configured services:** Resolved an issue where DPI was misclassifying sessions due to IP overlap. When services use
duplicate Jira ID

2024-03-29 15:47 UTC, ecarson commented on docs/config_radius.md
> +The first successful login to the SSR triggers the account creation, and then requires the user to login a second time to complete the process.
Maybe?:
```
The first successful login to the SSR triggers the account creation, and after initial account creation the user session is terminated and the user will need to login again. Once a local account has been created on an SSR subsequent logins will function as normal.
```
```

2024-03-29 15:48 UTC, ecarson commented on docs/config_radius.md
> +The manual operation is still available by default, and requires the previous configuration process where `create user` must be run with `authentication-type` set to `remote`.
Not sure if it is worth noting but it is also possible for both models to co-exist.

2024-03-29 15:48 UTC, ecarson approved these changes

2024-03-29 17:09 UTC, MichaelBaj approved these changes

2024-03-29 17:40 UTC, Bhautik approved these changes

2024-03-29 18:16 UTC, merged