Madrid port issue
128technology/docs pull request #701
Opened 2024-04-08 20:29 UTC by Chr1st0ph3rTurn3r

2024-04-09 11:17 UTC, MichaelBaj requested changes

2024-04-09 11:17 UTC, MichaelBaj commented on docs/hdwr_whitebox_port_layout.md
> +In some cases, the Silicom Madrid 90500-0151-G61 has been found to have variations in port layout. This is likely due to changing manufacturing requirements. Users should be aware that while these va
What does some investigation mean?
Please identify the exact steps

2024-04-09 15:37 UTC, BenMatase approved these changes

2024-04-10 13:00 UTC, MichaelBaj submitted a review, later dismissed

2024-04-16 13:58 UTC, BenMatase commented on docs/hdwr_whitebox_port_layout.md
> +1.  Connect port 1 `ge0/0/1` (WAN) to a network providing DHCP address assignment, and outbound connectivity to Mist. If you are adopting using the PCLI `adopt` command, proceed to [PCLI Adoption.](i
This should be 6 based on your diagram

2024-04-16 13:58 UTC, BenMatase commented on docs/hdwr_whitebox_port_layout.md
> +2. Connect port 4 `ge0/0/4` (LAN) to your laptop, and statically assign your laptop port address 192.168.3.10.
This should be 3 based on your diagram

2024-04-16 15:02 UTC, MichaelBaj approved these changes

2024-04-16 15:13 UTC, merged