Update documentation for http probe plugin SLA support
128technology/docs pull request #705
Opened 2024-04-18 18:21 UTC by jiangsunan

Update documentation for http probe plugin SLA support

2024-04-18 18:25 UTC, jamesesilvia commented
- [ ] wait

2024-04-18 18:46 UTC, Chr1st0ph3rTurn3r requested changes

2024-04-18 18:46 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_http_probe.md
> +The plugin allows Users to configure the following SLA settings: max-loss, max-jitter, average-rtt. These are considered in probe success criteria. Additionally, these values are available thorugh me
```suggestion
The plugin allows Users to configure the following SLA settings: max-loss, max-jitter, average-rtt. These settings are considered as part of the probe success criteria. Additionally, these values are available through metrics. 
```

2024-04-19 03:58 UTC, jiangsunan commented
@Chr1st0ph3rTurn3r Thanks for the review!!

2024-04-19 12:39 UTC, Chr1st0ph3rTurn3r approved these changes

2024-04-19 12:58 UTC, MichaelBaj approved these changes

2024-08-20 16:13 UTC, agrawalkaushik commented on docs/plugin_http_probe.md
> +Based on the configuration, every test runs five probe attempts. Each attempt runs with a two second hard timeout, calculated by the `probe-duration` divided by the `number-of-attempts`. Each probe m
this feels like its missing a word here

> status will remain (up?/down?) until the end of the next test.

2024-08-20 16:15 UTC, agrawalkaushik commented on docs/plugin_http_probe.md
> +**Release Date:** Aug 19, 2024
```suggestion
**Release Date:** Aug 20, 2024
```

2024-08-20 17:26 UTC, agrawalkaushik commented on docs/plugin_http_probe.md
> +Based on the configuration, every test runs five probe attempts. Each attempt runs with a two second hard timeout, calculated by the `probe-duration` divided by the `number-of-attempts`. Each probe m
```suggestion
Based on the configuration, every test runs five probe attempts. Each attempt runs with a two second hard timeout, calculated by the `probe-duration` divided by the `number-of-attempts`. Each probe may fail due to a request failure, timeout reached, or an invalid response code. Service path status is determined at the end of the probe duration and the current status will remain until the end of the next test.
```

2024-08-20 17:26 UTC, agrawalkaushik approved these changes

2024-08-22 13:04 UTC, Chr1st0ph3rTurn3r approved these changes

2024-08-22 13:04 UTC, merged