6.1.8 release notes
128technology/docs pull request #709
Opened 2024-05-02 15:31 UTC by Chr1st0ph3rTurn3r

2024-05-02 16:23 UTC, MichaelBaj requested changes

2024-05-02 16:23 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-54541 Device interfaces on Azure VMs with a 2K or greater MTU fail to initialize:** Resolved an issue where device-interfaces configured in an Azure VM fail during initialization, and the por
Let's set a new precedent for tying release notes into the KB and vice versa.
Please update the KB article https://docs.128technology.com/kb/I95-54541 to point to this release notes section and have this release note item point to the KB for more information.

2024-05-02 16:23 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-55226 Validation allows a network interface to be used as both DHCP relay and server:** The vaildation process has been updated to include several checks against DHCP relays, clients, servers
For clarity, this would read better if it stated:
Validation incorrectly allows a network interface to be used as both DHCP relay and server:** The vaildation process has been updated to include several checks against DHCP relays, clients, servers, and access-policies.

2024-05-02 16:23 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-55467 Incorrect VLAN Tagging in Azure HCI Stack with Hyper-V Hypervisor:** When using VLANs on Azure HCI Stack with Hyper-V, bit shifting occurs resulting in incorrect VLAN tags. This has bee
How we fixed the problem in this case is not material to the issue. Remove "updating the DPDK and"

2024-05-02 16:23 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-55850 Changing the name of a `bond-interface` fails:** Resolved an issue where changing the name of a `bond-interface`required a restart to take effect.
space needed after 2nd `bond-interface`

2024-05-02 20:51 UTC, MichaelBaj approved these changes

2024-05-03 12:59 UTC, MichaelBaj submitted a review, later dismissed

2024-05-03 15:40 UTC, MichaelBaj submitted a review, later dismissed

2024-05-03 16:17 UTC, MichaelBaj submitted a review, later dismissed

2024-05-03 16:26 UTC, MichaelBaj requested changes

2024-05-03 16:26 UTC, MichaelBaj commented on docs/release_notes_128t_6.1.md
> +- **I95-55904 No service-paths seen after upgrade:** Resolved an issue where adding services with overlapping address prefixes prevented the configuration from being applied. For additional details,
There is also the directive <!-- markdown-link-check-disable-next-line --> that can be used in this context to avoid having to disable and enable.

2024-05-03 18:42 UTC, MichaelBaj submitted a review, later dismissed

2024-05-03 19:22 UTC, jeffmart-jnpr commented on docs/about_releases.mdx
> +| Release 6.1 | [6.1.0](release_notes_128t_6.1.md#release-610-55) | April 14, 2023 | [6.1.8](release_notes_128t_6.1.md#release-618-15) | September 22, 2025 | June 22, 2026 |
Need to change this date to today

2024-05-03 20:34 UTC, MichaelBaj approved these changes

2024-05-03 20:46 UTC, merged