5.6.14 release notes
128technology/docs pull request #711
Opened 2024-05-07 13:50 UTC by Chr1st0ph3rTurn3r

2024-05-07 15:19 UTC, MichaelBaj requested changes

2024-05-07 15:19 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-55848 / I95-56403 Service `webEx-Calling` dropping calls frequently since implementing best-path-criteria vector:** Resolved an issue where an outbound-only session with a `nat-keep-alive` mo
- **I95-55848 / I95-56403 Session traffic is black-holed during path failover when `nat-keep-alive` is in use:** Resolved an issue where an outbound-only session with a `nat-keep-alive` moved from a dogleg path to a direct inter-router path. This causes repeated session modifications on the hub side and drops reverse traffic.

2024-05-08 15:38 UTC, MichaelBaj submitted a review, later dismissed

2024-05-13 14:14 UTC, MichaelBaj requested changes

2024-05-13 14:14 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +**Release Date:** May 13, 2024
I believe we are looking to publish tomorrow.

2024-05-13 14:14 UTC, MichaelBaj commented on docs/releases.table.js
> +    releaseDate: 'May 13, 2024',
This should be the 14th.

2024-05-13 14:14 UTC, MichaelBaj commented on docs/releases.table.js
> +    url:'/docs/release_notes_128t_5.6#release-5614-7',
Leading `/docs/` should not be present.

2024-05-13 18:05 UTC, MichaelBaj approved these changes

2024-05-14 23:10 UTC, jeffmart-jnpr approved these changes

2024-05-14 23:10 UTC, merged