IPSec Client Documentation
128technology/docs pull request #715
Opened 2024-05-10 21:44 UTC by jiangsunan

2024-05-10 21:46 UTC, jamesesilvia commented
- [ ] no merge.

we'll be using this documentation to handover to Teron.

2024-05-10 21:47 UTC, jamesesilvia commented on docs/plugin_ipsec_client.md
> +The `router > ipsec-profile`'s are reusable IPsec settings that can be used across multiple nodes in a router and multiple IPsec endpoint `remote`s. The examples below shows two examples of ipsec pro
`The examples below show two IPSec profiles that are mutually exclusive; ...`

2024-05-10 21:48 UTC, jamesesilvia commented on docs/plugin_ipsec_client.md
> +This plugin can only connect to IPsec endpoints that support pre-shared key or X.509 certificate.
maybe change `endpoints` to `servers`

2024-05-13 13:12 UTC, MichaelBaj requested changes

2024-05-13 13:12 UTC, MichaelBaj commented on docs/plugin_ipsec_client.md
> +- **/I95-51716** Common Criteria Certification - VPN Protection Profile
leading forward slash needs to be removed.

2024-05-13 16:21 UTC, Chr1st0ph3rTurn3r requested changes

2024-05-13 16:21 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +The `private-key` is used for pkc12 certification creation which will be used for tunnel authentication. Wrongly configured private key may prevent IPSec tunnel from establishing successfully.
```suggestion
The `private-key` is used to create the pkc12 certificate for tunnel authentication. A wrongly configured private key may prevent an IPSec tunnel from being established successfully. 
```

2024-05-13 16:21 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +The user could enable X.509 certificate type for tunnel authenticate by configuring valid [`private-key`](#private-key), [`client-certificate`](config_command_guide.md#configure-authority-client-cert
```suggestion
### Configure X.509 Certificate-type for Tunnel Authentication

The IPsec plugin requires users to generate/acquire their private key, a CA certificate file, and user certificate file. This must be signed by the CA certificate offline by utilities mentioned in Libreswan document (or other reliable sources such as openssl). Refer to the public [HOWTO:_Using_NSS_with_libreswan document](https://libreswan.org/wiki/HOWTO:_Using_NSS_with_libreswan) for additional information. Note that the IPsec plugin will take over the configuration mentioned in `Importing third-party files into NSS` in the Libreswan document. 

Use the following steps to create the X.509 certificate-type for Tunnel Authentication. 

1. Configure the [`private-key`](#private-key).
2. Configure the [`client-certificate`](config_command_guide.md#configure-authority-client-certificate).
3. Configure the [`trusted-ca-certificate`](config_command_guide.md#configure-authority-trusted-ca-certificate).
4. Enter the key names for each of these items in their respective fields in the [`ipsec-profile`](#profiles).

This information is used to generate the PKCS12 file. The IPsec NSS database stores the generated PKCS12 file for tunnel authentication. 
```

2024-05-13 18:33 UTC, jiangsunan commented on docs/plugin_ipsec_client.md
> +- **/I95-51716** Common Criteria Certification - VPN Protection Profile
done

2024-05-13 18:33 UTC, jiangsunan commented on docs/plugin_ipsec_client.md
> +The `router > ipsec-profile`'s are reusable IPsec settings that can be used across multiple nodes in a router and multiple IPsec endpoint `remote`s. The examples below shows two examples of ipsec pro
Added

2024-05-13 20:49 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +The `router > ipsec-profile`'s are reusable IPsec settings that can be used across multiple nodes in a router and multiple IPsec endpoint `remote`s. The examples below shows two examples of ipsec pro
```suggestion
The `router > ipsec-profile`'s are reusable IPsec settings that can be used across multiple nodes in a router and multiple IPsec endpoint `remote`s. The examples below shows two examples of ipsec profiles that are mutually exclusive; one using pre-shared keys, and one using certificate based authentication. The examples below show two IPSec profiles that are mutually exclusive.
```

2024-05-13 20:51 UTC, Chr1st0ph3rTurn3r requested changes
Just the one new change everything else looks good.

2024-05-14 12:57 UTC, MichaelBaj requested changes

2024-05-14 12:57 UTC, MichaelBaj commented on docs/plugin_ipsec_client.md
> +The `router > ipsec-profile`'s are reusable IPsec settings that can be used across multiple nodes in a router and multiple IPsec endpoint `remote`s. The examples below shows two examples of ipsec pro
The last sentence is a repeat and should be removed.
"The examples below show two IPSec profiles that are mutually exclusive."

2024-05-14 12:57 UTC, MichaelBaj commented on docs/plugin_ipsec_client.md
>  ### Configure X.509 Certificates Type For Tunnel Authentication
Looks like this header was not removed:
"### Configure X.509 Certificates Type For Tunnel Authentication"

2024-05-14 14:41 UTC, jiangsunan commented on docs/plugin_ipsec_client.md
>  ### Configure X.509 Certificates Type For Tunnel Authentication
Fixed

2024-05-14 14:44 UTC, jiangsunan commented on docs/plugin_ipsec_client.md
> +The `router > ipsec-profile`'s are reusable IPsec settings that can be used across multiple nodes in a router and multiple IPsec endpoint `remote`s. The examples below shows two examples of ipsec pro
Previous comments are misunderstood. Fixed.

2024-05-14 14:51 UTC, MichaelBaj submitted a review, later dismissed

2024-05-14 15:06 UTC, Chr1st0ph3rTurn3r submitted a review, later dismissed

2025-01-15 16:01 UTC, closed without merging