dns-cache-4.0.0 release changes
128technology/docs pull request #717
Opened 2024-05-14 20:55 UTC by mdzwil-JNPR

Changes related to the `dns-cache-4.0.0` release with plugin `api-2.0` and `api-3.0` versions.

2024-05-15 13:15 UTC, Chr1st0ph3rTurn3r approved these changes

2024-08-02 14:30 UTC, agrawalkaushik commented on docs/plugin_dns_cache.md
> +**Release Date:** May 15, 2024
- [ ] update

2024-08-02 14:31 UTC, agrawalkaushik requested changes

2024-08-02 14:31 UTC, agrawalkaushik commented on docs/plugin_dns_cache.md
> +The conductor and router(s) install the same dns-cache rpm to improve release tracking and functionality.
I guess this will be the same text we put up for all api-3.0 RPMs. So lets re-word it. I dont view this as a new feature that customers would care about. We can figure out a better way to capture this.

2024-10-04 14:52 UTC, closed without merging