Adding clarification to since command for rate stats
128technology/docs pull request #719
Opened 2024-05-21 21:03 UTC by MichaelBaj

DOCS-405 #time 30min

2024-05-22 12:25 UTC, Chr1st0ph3rTurn3r requested changes

2024-05-22 12:25 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_metrics.md
> +The since argument is a general utility which performs a delta between the two values supplied by the arguments. The primary use is for cumulative metrics - ones that keep incrementing. Some stats ar
```suggestion
The `since` argument is a general utility which performs a delta between the two values supplied by the arguments. The primary use is for cumulative metrics - ones that keep incrementing. Some stats are stored as a rate, which is a per 5 second view of the stat. A rate value in the past may be higher than the current rate (or rate at the selected time) and therefore a negative value may be returned.
```

2024-05-22 16:42 UTC, Chr1st0ph3rTurn3r approved these changes

2024-05-29 12:34 UTC, merged

2024-05-29 15:15 UTC, gregschrock commented on docs/concepts_metrics.md
> +The `since` argument is a general utility which performs a delta between the two values supplied by the arguments. The primary use is for cumulative metrics - ones that keep incrementing. Some stats
The description is accurate, but I'm confused by the location.
1. I would not expect the since command to show up here as it is least relevant for the in memory metrics. They do not have history, so they should only really have a caveat saying they'll only show the current value when used with `since`.
2. Rate metrics and in memory metrics are not related, so the section header makes this out of place.

It seems like we should have a section just for the `show since` command where we can put these caveats.

2024-05-29 15:24 UTC, MichaelBaj commented on docs/concepts_metrics.md
> +The `since` argument is a general utility which performs a delta between the two values supplied by the arguments. The primary use is for cumulative metrics - ones that keep incrementing. Some stats
Appreciate the input. Put up PR https://github.com/128technology/docs/pull/721 to provide this correct. Additional input is requested.