Added release notes for ipsec-client plugin 3.6.1
128technology/docs pull request #720
Opened 2024-05-28 14:37 UTC by BenMatase

2024-05-28 15:56 UTC, Chr1st0ph3rTurn3r requested changes

2024-05-28 15:56 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +- **PLUGIN-2232** Enabled and configured tunnels remain down.
```suggestion
- **PLUGIN-2232** Configured and enabled tunnels remain down.
```
From a logical perspective, I'm thinking you configure a tunnel and then enable it. Unless the flow is different than that, which it may be.

2024-05-28 15:56 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +  _**Resolution:**_ The plugin now handles file corruption better so that it does not get in this state.
```suggestion
  _**Resolution:**_ File corruption is now handled more gracefully, preventing IPSEC tunnels from going down.
```

2024-05-28 15:56 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_ipsec_client.md
> +  _**Resolution:**_ If any FQDNs are defined in the `ipsec-client` > `remote` > `host` fields, the plugin will not start the tunnels if the FQDNs of the tunnels are unresolvable.
```suggestion
  _**Resolution:**_ When FQDNs are defined in the `ipsec-client` > `remote` > `host` fields, the plugin will not start the tunnels if the FQDNs of the tunnels are unresolvable.
```

2024-05-28 17:35 UTC, BenMatase commented on docs/plugin_ipsec_client.md
> +- **WAN-2994** Port 500 session were stuck even with session deletion feature.
```suggestion
- **WAN-2994** Port 500 sessions were stuck even with session deletion feature.
```

2024-05-28 17:38 UTC, MichaelBaj approved these changes

2024-05-28 20:22 UTC, agrawalkaushik approved these changes

2024-05-29 13:22 UTC, Chr1st0ph3rTurn3r approved these changes

2024-05-29 14:23 UTC, merged