Add KB for AD high memory
128technology/docs pull request #722
Opened 2024-05-29 15:44 UTC by jamesesilvia

## Description
^

## Testing
<img width="1031" alt="Screenshot 2024-05-29 at 11 44 17 AM" src="https://github.com/128technology/docs/assets/1403603/419aedf6-1418-4a79-9d99-6904796ee139">

<img width="1024" alt="Screenshot 2024-05-29 at 11 43 29 AM" src="https://github.com/128technology/docs/assets/1403603/33ac1cca-8f25-4dd1-aa97-141e565592a5">

2024-05-29 15:49 UTC, MichaelBaj requested changes

2024-05-29 15:51 UTC, Chr1st0ph3rTurn3r requested changes

2024-05-29 15:51 UTC, Chr1st0ph3rTurn3r commented on kb/2024-05-29-I95-56484.md
> +It is possible that stale connections are left around to a database that will utilize excessive memory over a long duration (application-director uptime).
```suggestion
It is possible that stale connections to a database will utilize excessive memory over a long duration (application-director uptime).
```

2024-05-29 15:51 UTC, Chr1st0ph3rTurn3r commented on kb/2024-05-29-I95-56484.md
> +If the `application-director` is increasing memory over time, the service can be restarted on the offending device using `systemctl restart application-director` as a priviledged User.
```suggestion
If the `application-director` is increasing memory over time, the service can be restarted on the offending device using `systemctl restart application-director` as a privileged User.
```

2024-05-29 15:55 UTC, jamesesilvia commented on kb/2024-05-29-I95-56484.md
> +### Workaround
Yeah. I can add some details. There are per-process memory metrics so through graphs the User should see the memory increase over time for this service.

2024-05-29 16:23 UTC, agrawalkaushik commented on kb/2024-05-29-I95-56484.md
> +**Introduced in SSR Version:** 6.2.3
6.2.3 or 6.2.4?

2024-05-29 16:24 UTC, agrawalkaushik commented on kb/2024-05-29-I95-56484.md
> +The application-director has a race condition that can occur during app-id module updates, app-id database reloads, and MIST configuration changes.
Why just MIST config changes? The timex system we saw this on was not WAN 2.0.

2024-05-29 16:25 UTC, agrawalkaushik commented on kb/2024-05-29-I95-56484.md
> +### Workaround
we should include the `show stats...` command down to the name of the process in this case.

2024-05-29 17:41 UTC, jamesesilvia commented on kb/2024-05-29-I95-56484.md
> +The application-director has a race condition that can occur during app-id module updates, app-id database reloads, and MIST configuration changes.
mist config changes inject apps into the AD which also causes a database reload. i can just reword to `configuration changes`

2024-05-29 17:42 UTC, jamesesilvia commented on kb/2024-05-29-I95-56484.md
> +**Introduced in SSR Version:** 6.2.3
this was caused by the sqllite changes we made in 6.2.3. one fix made it into 6.2.4 and one into 6.2.5.

2024-05-30 21:09 UTC, jamesesilvia commented on kb/2024-05-29-I95-56484.md
> +The application-director has a race condition that can occur during app-id module updates, app-id database reloads, and MIST configuration changes.
done

2024-05-31 10:27 UTC, MichaelBaj approved these changes

2024-05-31 12:28 UTC, Chr1st0ph3rTurn3r approved these changes

2024-05-31 15:08 UTC, merged