5.6.16 release notes
128technology/docs pull request #745
Opened 2024-07-25 14:17 UTC by Chr1st0ph3rTurn3r

2024-07-25 17:04 UTC, MichaelBaj requested changes

2024-08-06 15:15 UTC, MichaelBaj approved these changes

2024-08-19 14:07 UTC, MichaelBaj approved these changes

2024-11-18 15:01 UTC, MichaelBaj requested changes

2024-11-18 15:01 UTC, MichaelBaj commented on docs/release_notes_128t_5.6.md
> +- **I95-58528 SSR OS renaming:** The SSR OS has been renamed/rebranded from CentOS7 to SSR OS to acknowledge CentOS 7 is no longer supported. All internal naming has been updated.
Suggested rewording:

- **I95-58528 SSR OS renaming:** The SSR OS has been renamed/rebranded from "CentOS7" to "SSR OS" to more accurately reflect its customized Linux distribution. All internal naming has been updated.

2024-11-18 20:51 UTC, MichaelBaj requested changes

2024-11-18 20:51 UTC, MichaelBaj commented on docs/releases.table.js
> +    version: '6.1.3'
how is this working with the comma removed? This needs to be added back in.

2024-11-19 14:14 UTC, MichaelBaj approved these changes

2024-11-19 15:11 UTC, MichaelBaj approved these changes

2024-11-25 17:51 UTC, MichaelBaj approved these changes

2024-11-25 18:16 UTC, jeffmart-jnpr approved these changes

2024-11-25 22:39 UTC, merged