Add release notes and KB for ipsec restart issue
128technology/docs pull request #747
Opened 2024-08-05 17:14 UTC by agrawalkaushik

2024-08-05 19:27 UTC, Chr1st0ph3rTurn3r approved these changes

2024-08-06 15:13 UTC, MichaelBaj requested changes

2024-08-06 15:13 UTC, MichaelBaj commented on kb/2024-08-05-PLUGIN-2550.md
> +The IPSec client plugin (3.6.1) attempted to correct a run time race condition between IPSec tunnel starting before DNS was fully operational in the IPSec namespace. Two changes we made to resolve th
"Two changes were made to resolve ..."

2024-08-06 15:13 UTC, MichaelBaj commented on kb/2024-08-05-PLUGIN-2550.md
> +running
"running" should be removed.

2024-08-07 14:47 UTC, Chr1st0ph3rTurn3r approved these changes

2024-08-07 14:49 UTC, merged