6.2.6 release notes
128technology/docs pull request #750
Opened 2024-08-26 18:26 UTC by Chr1st0ph3rTurn3r

Waiting on text for WAN 3027

2024-08-26 18:47 UTC, agrawalkaushik commented
@Chr1st0ph3rTurn3r 

> Waiting on text for WAN 3027

This is a WAN Assurance JIRA and not applicable to 6.2.6.

2024-08-26 20:16 UTC, MichaelBaj requested changes

2024-08-26 20:16 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-55965 IDP engine not starting due to invalid environmental conditions:** In cases where a container/csrx does not shut down cleanly, the IDP engine does not start. These conditions are now de
Too many internal details:

- **I95-55965 IDP engine not starting due to invalid environmental conditions:** In cases where the IDP engine does not shut down cleanly, the IDP engine will fail to restart. These conditions are now detected and handled correctly.

2024-08-26 20:16 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-55982 X722 interfaces overwritten when upgrading an SSR1300/SSR1400:** Identified an issue where the firmware for the x722 interfaces was not waiting long enough for the device to complete re
- **I95-55982 X722 interface MAC being set to `00:00:00:00:00:00` on SSR1300/SSR1400:** Identified an issue the MAC address would change during a power cycle. Another power cycle can restore the MAC to its previous value. An upgrade to the X722 firmware addresses this issue. NOTE: A power cycle is required as part of the firmware flashing sequence. All power feeds must be manually disconnected and reconnected to cycle it correctly.

2024-08-26 20:16 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-56345 Multiple reboots of the same node of a dual node router causes the stream to stopped:** Resolved an issue where multiple reboots of an HA node did not allow traffic to pass. Now in this
- **I95-56345 Multiple reboots of the same node of a dual node router causes multicast stream to stop:** Resolved an issue where multiple reboots of an HA node did not allow traffic to pass. Now in this scenario an exception is thrown, which allows the session to rebuild once the internode link comes up.

2024-08-26 20:16 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-57099 BFD Session timeout discovered:** Resolved an issue where BFD sessions were deleted prematurely.
- **I95-57099 Race condition causing crash in highway process when peer path timers expire:** Resolved an issue with handling BFD timers in multi-threaded environments.

2024-08-26 20:16 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **WAN-3027 ARV events for peers with hostnames are delayed:**
incomplete statement.

2024-08-27 15:17 UTC, MichaelBaj submitted a review, later dismissed
Approved, but waiting on confirmation regarding OSPF GR configuration.

2024-09-05 13:09 UTC, MichaelBaj approved these changes

2024-09-06 13:39 UTC, MichaelBaj requested changes

2024-09-06 15:30 UTC, MichaelBaj approved these changes

2024-09-06 19:28 UTC, Bhautik approved these changes

2024-09-06 19:45 UTC, MichaelBaj approved these changes

2024-09-06 20:33 UTC, merged