Add BYOL release notes
128technology/docs pull request #757
Opened 2024-09-16 17:28 UTC by agrawalkaushik

2024-09-16 17:36 UTC, MichaelBaj commented on docs/intro_installation_byol_azure_mist.md
> +## Release Notes
You are adopting the plugin release notes model wherein the guide has a trailing release notes section.
What does 1.1.0 refer to in this regard? Is this the BYOL image? How does a customer understand what version they are running?
IMO, we should have a separate release notes category for BYOL and list this information there instead. The configuration guides should be separate from the release notes.
@Chr1st0ph3rTurn3r This is consistent with our migration to the Juniper docs format, correct?

2024-09-16 18:02 UTC, Chr1st0ph3rTurn3r requested changes

2024-09-16 18:02 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_byol_azure_mist.md
> +- **I95-48255** BYOL Support for Mist Managed router
Put everything in one entry:
- **I95-48255 BYOL Support for Mist Managed router:** Created a new BYOL offering in Azure, to provide seamless onboarding for MIST managed Session Smart Routers. The offer enables various modes of operation using ARM templates, image-based, cloud-init based, and manual onboarding modes to best fit the end user workfow.

2024-09-16 18:02 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_quickstart_byol_mist_aws.md
> +- **I95-48255** BYOL Support for Mist Managed router
Put everything in one entry:

- **I95-48255 BYOL Support for Mist Managed router:** Created a new BYOL offering in AWS, to provide seamless onboarding for MIST managed Session Smart Routers. The offer enables various modes of operation using CloudFormation templates, AMI-based, cloud-init based, and manual onboarding modes to best fit the end user workfow.

2024-09-16 19:23 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_byol_azure_mist.md
> +## Release Notes
It is, and I thought about suggesting a release notes section for AWS and Azure, since they have separate "guides" in the docs now, and will be getting more with the 6.3 release (BYOL for conductor). Then I thought if there was a need to get it out right away, I would let it go as is for now and reformat the docs after this goes out as part of the 6.3 release. If Kaushik has the cycles and wants to do it now, that is fine with me. If not, I will get it reformatted over the next week or so.

2024-09-17 13:29 UTC, agrawalkaushik commented on docs/intro_installation_byol_azure_mist.md
> +## Release Notes
> What does 1.1.0 refer to in this regard? Is this the BYOL image? How does a customer understand what version they are running?

Yes. The version is visible on AWS. For Azure, its what they would by default pick the latest but for some reason if they needed/wanted to stick to an older version, they would get them via API and use in their templates.

2024-09-17 13:43 UTC, agrawalkaushik commented on docs/intro_installation_byol_azure_mist.md
> +## Release Notes
I'll update it to add a new sidebar for BYOL.

2024-09-17 15:52 UTC, merged