Add release note for Http Probe
128technology/docs pull request #766
Opened 2024-09-25 03:02 UTC by sunanj-JNPR

2024-09-26 14:58 UTC, Chr1st0ph3rTurn3r requested changes

2024-09-26 14:58 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_http_probe.md
> +- **PLUGIN-2629** The command "show stats http-probe" is not working in the SSR.
```suggestion
- **PLUGIN-2629** The command `show stats http-probe` is not working in the SSR.
```

2024-09-26 14:58 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_http_probe.md
> +  _**Resolution:**_ Replace incompatible parameter referred in stats data model with local leaf definition
```suggestion
  _**Resolution:**_ Replace incompatible parameter referenced in the stats data model with local leaf definition.
```

2024-09-27 13:13 UTC, Chr1st0ph3rTurn3r approved these changes

2024-09-27 13:21 UTC, MichaelBaj approved these changes

2024-10-17 19:11 UTC, jamesesilvia commented
Closing due ot stale and that we released this already with IBU

2024-10-17 19:11 UTC, closed without merging