generating 6.2.7 release notes
128technology/docs pull request #771
Opened 2024-10-02 15:54 UTC by Chr1st0ph3rTurn3r

2024-10-02 15:59 UTC, MichaelBaj requested changes

2024-10-02 15:59 UTC, MichaelBaj commented on docs/release_notes_128t_6.2.md
> +- **I95-53274 PIM scaling above 1500 (Source,Group) sessions:** Resolved an issue where the SSR could not maintain more than 1400 active (Source,Group) sessions. In deployments with a high number of
- **I95-53274 PIM scaling above 1500 multicast routes:** Resolved an issue where the SSR could not maintain more than 1400 active sessions.

2024-10-02 17:26 UTC, MichaelBaj approved these changes

2024-10-03 14:56 UTC, MichaelBaj approved these changes

2024-10-03 15:05 UTC, MichaelBaj approved these changes

2024-10-03 15:05 UTC, jeffmart-jnpr approved these changes

2024-10-03 15:25 UTC, merged