http-probe-2.1.0 documentation
128technology/docs pull request #772
Opened 2024-10-04 14:52 UTC by mdzwil-JNPR

Documentation for the `up-delay-timer` feature for the `http-probe-2.1.0` release

2024-10-04 14:54 UTC, jamesesilvia commented
- [ ] 10/10 release

2024-10-04 14:55 UTC, jamesesilvia commented on docs/plugin_http_probe.md
> +| up-delay-timer | uint32 | default: 0 | The duration (in seconds) a probe is held down before it comes up when the previous state was down |
.. a probe is held down before transitioning from down to up state

2024-10-04 14:56 UTC, jamesesilvia commented on docs/plugin_http_probe.md
> +The plugin allows users to configure the following SLA settings: max-loss, max-jitter, average-rtt. These settings are considered as part of the probe success criteria. Additionally, these values are
we sure we dont want Users?

2024-10-04 14:59 UTC, mdzwil-JNPR commented on docs/plugin_http_probe.md
> +The plugin allows users to configure the following SLA settings: max-loss, max-jitter, average-rtt. These settings are considered as part of the probe success criteria. Additionally, these values are
I do not think that grammatically makes sense, but I could be wrong

2024-10-04 15:02 UTC, mdzwil-JNPR commented on docs/plugin_http_probe.md
> +| up-delay-timer | uint32 | default: 0 | The duration (in seconds) a probe is held down before it comes up when the previous state was down |
Updated

2024-10-04 15:45 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_http_probe.md
> +The plugin allows users to configure the following SLA settings: max-loss, max-jitter, average-rtt. These settings are considered as part of the probe success criteria. Additionally, these values are
you are correct - lower case "u".

2024-10-04 15:52 UTC, Chr1st0ph3rTurn3r requested changes

2024-10-04 15:52 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_http_probe.md
> +It is recommended that a probe's `up-delay-timer` has a value greater than the `probe-interval` field. This configuration allows the probe to run atleast one more time while the timer is active. A wa
```suggestion
It is recommended that a probe's `up-delay-timer` has a value greater than the `probe-interval` field. This configuration allows the probe to run at least one more time while the timer is active. A warning will be produced if a probe is configured with an `up-delay-timer` value less than the `probe-interval`. If a configuration reload occurs while a probe timer is active, the timer is honored with the previous config.
```

2024-10-04 15:52 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_http_probe.md
> +The plugin allows users to configure an up-delay-timer which holds a probe down for a set duration before bringing the probe up.
```suggestion
The plugin allows users to configure an `up-delay-timer` which holds a probe down for a set duration before bringing the probe up.
```

2024-10-04 15:57 UTC, mdzwil-JNPR commented on docs/plugin_http_probe.md
> +The plugin allows users to configure an up-delay-timer which holds a probe down for a set duration before bringing the probe up.
The reason I did not make this change is because in the other sections of `Release Notes` we did not do this for other configurable fields. For example `max-loss`, `max-jitter`, `average-rtt` in the SLA section for release `1.2.0`

2024-10-04 15:58 UTC, mdzwil-JNPR commented on docs/plugin_http_probe.md
> +It is recommended that a probe's `up-delay-timer` has a value greater than the `probe-interval` field. This configuration allows the probe to run atleast one more time while the timer is active. A wa
Fixed.

2024-10-04 16:36 UTC, Chr1st0ph3rTurn3r commented on docs/plugin_http_probe.md
> +The plugin allows users to configure an up-delay-timer which holds a probe down for a set duration before bringing the probe up.
okay - good call, consistency matters.

2024-10-04 16:36 UTC, Chr1st0ph3rTurn3r approved these changes

2024-10-04 16:50 UTC, MichaelBaj requested changes

2024-10-04 16:50 UTC, MichaelBaj commented on docs/plugin_http_probe.md
> +        up-delay-timer      15
Is there a default value for `up-delay-timer`? Is it 0? If 0, does that mean it is disabled?
Is there a logical validator that ensures up-delay-timer is greater than probe-interval?

2024-10-04 17:04 UTC, mdzwil-JNPR commented on docs/plugin_http_probe.md
> +        up-delay-timer      15
Yes, the default value is 0 which is listed in the `HTTP Probe Profile configuration` section. With this value, it means that the probe would act as if the timer is disabled. 

We do not enforce the `up-delay-timer` to be greater than the `probe-interval`, but have a validation warning if config is trying to be committed that does not adhere by this. This is explained in the `Up Delay Timer` section

2024-10-04 17:08 UTC, MichaelBaj commented on docs/plugin_http_probe.md
> +        up-delay-timer      15
Please state that the default value of 0 means disabled.

2024-10-04 18:32 UTC, mdzwil-JNPR commented on docs/plugin_http_probe.md
> +        up-delay-timer      15
Fixed.

2024-10-31 14:24 UTC, jamesesilvia commented
Thanks @mdzwil-JNPR ; since this is getting grouped into other plugin release; I have cherry-picked your commits into a seperate branch

2024-10-31 14:25 UTC, closed without merging

2024-10-31 14:25 UTC, jamesesilvia commented
https://github.com/128technology/docs/pull/791