Added clarity around the use and need of max-way-points
128technology/docs pull request #776
Opened 2024-10-10 19:37 UTC by MichaelBaj

2024-10-10 19:39 UTC, avinashbhat80 approved these changes

2024-10-10 19:43 UTC, Chr1st0ph3rTurn3r requested changes

2024-10-10 19:43 UTC, Chr1st0ph3rTurn3r commented on docs/concepts_waypoint_ports.md
> +It is important to note that despite the configured [port-range](config_reference_guide.md#port-range), the SSR will at most use 50K of those ports by default. The configuration [max-way-points](conf
```suggestion
It is important to note that despite the configured [port-range](config_reference_guide.md#port-range), the SSR will at most use 50,000 of those ports by default. The configuration [max-way-points](config_reference_guide.md#max-way-points) allows the SSR software to scale respective to the platform and the administrator's needs. A `max-way-points` setting that is smaller than the number of sessions traversing a peer path will result in port exhaustion. A `max-way-points` setting that is too large will result in wasted system resources. Best practice is to tune both the `port-range` and `max-way-points` to a factor of 1.5x of the max number of sessions traversing a peer path.
```

2024-10-10 20:47 UTC, chao-128t commented on docs/concepts_waypoint_ports.md
> +Limiting this range will make your firewall team happy without putting too much of a crimp in your ability to SVR sessions. In fact, we have some customers that have limited their waypoint port alloc
- The default **local** port range is 16384 ~ 65534, 49151 ports in total, not 49148.

> the default value of ports (49,148 ports)

- The default **remote** port range is 16385 ~ 65533, 49149 ports in total.

- When (remote) port-range is not configured, local ports are even, remote ports are odd, the total combination is 24576 (even local ports) * 24575 (odd remote ports) = 603,955,200
- When (remote) port-range is configured, local ports are continuous within that 16384 ~ 65534 range, remote ports are also continuous within the configured range, so the total combination is 49151 * `num of ports within the range`. In the doc's example, the total combination is 49151 * 10 = 491,510.

2024-10-10 21:00 UTC, MichaelBaj commented on docs/concepts_waypoint_ports.md
> +Limiting this range will make your firewall team happy without putting too much of a crimp in your ability to SVR sessions. In fact, we have some customers that have limited their waypoint port alloc
What do you mean by "local" vs "remote" port ranges? Are the settings per neighborhood, and therefore shared by both nodes? Or is that not the case and for any given neighborhood, there is both a local and remote, because the setting applies to that device specifically?

2024-10-10 22:54 UTC, chao-128t commented on docs/concepts_waypoint_ports.md
> +Limiting this range will make your firewall team happy without putting too much of a crimp in your ability to SVR sessions. In fact, we have some customers that have limited their waypoint port alloc
For a given SVR session, waypoint ports are allocated by the ingress router. So, the notion of local vs. remote is from the ingress router's perspective. The local port does not have a configurable range only the remote port does. It tells the ingress router what ports are opened on the egress router for SVR sessions.

The port range is per neighborhood per network-interface and only shared across an HA pair if the interface is redundant.

The `neighborhood->port-range` on the hub is propagated to `adjacency->port-range` on the branch through adjacency generation by the conductor.

2024-10-11 17:01 UTC, Chr1st0ph3rTurn3r approved these changes

2024-10-11 17:36 UTC, chao-128t approved these changes

2024-10-11 17:44 UTC, merged