Conductor-Managed BYOL
128technology/docs pull request #785
Opened 2024-10-25 22:26 UTC by haberkornsam

2024-10-28 12:09 UTC, MichaelBaj submitted a review, later dismissed

2024-10-28 12:11 UTC, MichaelBaj commented
These links appear to no longer be valid. Please replace with current equivalent or rework documentation.
```
ERROR: 2 dead links found!
[✖] https://docs.saltstack.com/en/latest/ref/states/top.html → Status: 404
[✖] https://docs.saltstack.com/en/latest/topics/tutorials/pillar.html → Status: 404
```

2024-10-28 15:53 UTC, Chr1st0ph3rTurn3r requested changes
Sam, I had several edits in the intro_installation_quickstart_byol_conductor_aws.md topic - most were purely editorial. However I added comments in the doc itself for clarification of two steps in two procedures - steps 16 and 22. They call out mist managed devices, and then reference config templates. Please take a look at them and if you have questions, let me know. Thanks.

2024-10-28 15:53 UTC, Chr1st0ph3rTurn3r commented on docs/intro_installation_quickstart_byol_mist_aws.md
> +22. If an onboarding configuration was not provided in step 16, follow the manual steps to in the [Manual Onboarding](#manual-onboarding) section.
```suggestion
22. If an onboarding configuration was not provided in step 16, follow the steps in the [Manual Onboarding](#manual-onboarding) section.
```

2024-10-28 20:39 UTC, agrawalkaushik commented on docs/intro_installation_quickstart_byol_conductor_aws.md
> +## Session Smart Router Deployment
can we call this `Session Smart Conductor Managed Router` isntead?

2024-10-28 20:40 UTC, agrawalkaushik approved these changes

2024-10-29 12:52 UTC, Chr1st0ph3rTurn3r requested changes
I have to check a couple things in the intro_installation topic as well, because I'm not seeing changes I made directly to the doc.

2024-10-29 12:52 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_byol_2.0.md
> +- **I95-58706 Whitelist AWS cXa instance types:** Added support for AWS cXa instance types such as c7a. These instnace types utilize varius AMD processors. More information can be found in the [AWS d
```suggestion
- **I95-58706 Whitelist AWS cXa instance types:** Added support for AWS cXa instance types such as c7a. These instance types utilize various AMD processors. For more information, please see the [AWS documentation](https://aws.amazon.com/ec2/instance-types/#Compute_Optimized).
```

2024-10-29 12:52 UTC, Chr1st0ph3rTurn3r commented on docs/release_notes_byol_2.0.md
> +- **I95-58549 Azure and AWS instances can sometimes fail to successfully connect to Mist:** On first boot the system can sometimes fail to connect to Mist before timing out. This causes the SSR softw
```suggestion
- **I95-58549 Azure and AWS instances can sometimes fail to successfully connect to Mist:** On first boot the system can sometimes fail to connect to Mist before timing out. This causes the SSR software to not be installed. The timeout has been increased.
```

2024-10-29 14:26 UTC, Chr1st0ph3rTurn3r approved these changes

2024-10-29 14:54 UTC, merged