updates to supported platforms and portfolio
128technology/docs pull request #786
Opened 2024-10-28 21:03 UTC by Chr1st0ph3rTurn3r

2024-10-29 14:58 UTC, MichaelBaj requested changes

2024-10-29 14:58 UTC, MichaelBaj commented on docs/about_certified_platforms.mdx
> +    mem : "128-192GB",
A range for memory is strange. If our min requirements are 128GB, we should state 128GB. A customer can always add more memory if required. If the min required is 192, we should state as such.

2024-10-29 14:58 UTC, MichaelBaj commented on docs/about_certified_platforms.mdx
>  export const certifiedPlatforms = {
Can we get the storage details added to these tables as well?

2024-10-29 14:58 UTC, MichaelBaj commented on docs/about_certified_platforms.mdx
> +    lannernca1515a : {
Extra leading spacing

2024-10-29 14:58 UTC, MichaelBaj commented on docs/about_certified_platforms.mdx
> +    lannernca1515alte : {
Extra leading spacing

2024-10-29 14:58 UTC, MichaelBaj commented on docs/about_certified_platforms.mdx
> +The following devices are Certified Platforms for small to medium deployments. Models vary out of the box. Only the SKUs listed are Certified.
"Models vary out of the box." is a strange statement.
Recommended rewording:

The following devices are Certified Platforms for small to medium deployments. Only the SKUs listed are Certified. The platform model alone does not guarantee conformance to software requirements.

2024-10-29 14:58 UTC, MichaelBaj commented on docs/about_certified_platforms.mdx
> +The following devices are Certified Platforms for medium to large deployments. Models vary out of the box. Only the SKUs listed are Certified.
Recommended rewording:

The following devices are Certified Platforms for medium to large deployments. Only the SKUs listed are Certified. The platform model alone does not guarantee conformance to software requirements.

2024-10-29 14:58 UTC, MichaelBaj commented on docs/about_supported_platforms.md
> +The SSR Certification program provides a designation of Certified for certain platforms. CCertified platforms within the portfolio have the following characteristics:
Typo: Certified

2024-10-29 14:58 UTC, MichaelBaj commented on docs/about_supported_platforms.md
> +--->
Why is this arrow here?

2024-11-06 19:38 UTC, MichaelBaj submitted a review, later dismissed

2024-11-13 20:03 UTC, MichaelBaj submitted a review, later dismissed

2024-11-14 17:21 UTC, avijitvjuniper commented on docs/intro_system_reqs.md
>  The Session Smart Networking Platform runs on both bare metal servers and as a virtual machine within hypervisor environments. For virtual environments the same CPU, memory, and storage specification
> For virtual environments the same CPU, memory, and storage specifications are required for comparable throughput.

I don't think this is true. We should rephrase this and remove the comparable throughput part

2024-11-14 20:02 UTC, MichaelBaj submitted a review, later dismissed

2024-11-14 20:03 UTC, avijitvjuniper submitted a review, later dismissed

2024-11-14 20:26 UTC, MichaelBaj approved these changes

2024-11-14 20:36 UTC, merged