adding x722 bios upgrade info
128technology/docs pull request #788
Opened 2024-10-29 15:30 UTC by Chr1st0ph3rTurn3r

2024-10-29 16:17 UTC, MichaelBaj requested changes

2024-10-29 16:17 UTC, MichaelBaj commented on docs/howto_update_bios.md
> +title: BIOS Upgrade for x722
I think the title should include SSR1400 and SSR1500.
If you were browsing the sidebar, you wouldn't know that either of these platforms had a x722 NIC, or even what it was.

2024-10-29 16:17 UTC, MichaelBaj commented on docs/howto_update_bios.md
> +Juniper SSR1300 and SSR1400 routers are manufactured to support x722 NICs. To support the LLDP feature available in SSR releases 6.1 and greater, a BIOS upgrade to version 4.09 is required. This BIOS
Juniper SSR1300 and SSR1400 routers are platforms that have Intel x722 NICs.

It is also important to add as a closing sentence to this paragraph in what SSR version this BIOS upgrade is no longer manually required.

2024-10-29 16:17 UTC, MichaelBaj commented on docs/howto_update_bios.md
> +- An automated power off/power on that is automatically performed after the firmware update has completed.
"automatically" seems redundant

2024-10-29 16:17 UTC, MichaelBaj commented on docs/howto_update_bios.md
> +### Online Installation from the SSR Repository
I thought this was all going to be bundled and automated as part of SSR firmware

2024-10-29 16:17 UTC, MichaelBaj commented on docs/howto_update_bios.md
> +### Sample Upgrade Output
Is there a tool/script that can be used to check what version is currently installed?

2024-10-30 17:44 UTC, iwbarker commented on docs/howto_update_bios.md
> +Juniper SSR1300 and SSR1400 devices are manufactured to support x722 NICs. To support the LLDP feature available in SSR releases 6.1 and greater, a BIOS upgrade to version 4.09 is required. This BIOS
are manufactured to support x722 NICs
->
incorporate Intel x722 NICs

2024-10-30 17:46 UTC, iwbarker commented on docs/howto_update_bios.md
> +Juniper SSR1300 and SSR1400 devices are manufactured to support x722 NICs. To support the LLDP feature available in SSR releases 6.1 and greater, a BIOS upgrade to version 4.09 is required. This BIOS
contains X722 firmware version 6.5
->
contains updated Intel Management Engine (ME) and X722 NIC firmware

2024-10-30 17:48 UTC, iwbarker commented on docs/howto_update_bios.md
> +In order to fully integrate the new Intel ME firmware delivered by the BIOS, there are two mandatory steps to be performed:
why "two steps"?

the s/w will shut down the system after firmware update, and the user must power it back on
so the user only has one action...

2024-10-30 17:50 UTC, iwbarker commented on docs/howto_update_bios.md
> +### Online Installation from the SSR Repository
The automatic update was removed, because it does a power down after flashing, which we cannot avoid. 
So it was decided it must be a manual upgrade for those users who need to use the LLDP feature.

2024-10-30 17:51 UTC, iwbarker commented on docs/howto_update_bios.md
> +  `sudo dnf install -y afulnx-5.16.02.0111-3`
nit: no need to specify the full package version here, just afulnx should be sufficient

2024-10-30 17:53 UTC, iwbarker commented on docs/howto_update_bios.md
> +### Sample Upgrade Output
dmidecode displays the bios version (it's in TSI also), and ethtool / dmesg display the NIC firmware

2024-10-30 17:54 UTC, iwbarker requested changes
suggested updates noted inline

2024-10-30 20:16 UTC, iwbarker commented on docs/howto_update_bios.md
> +title: BIOS Upgrade for x722
@MichaelBaj  SSR1500 doesn't use X722

2024-10-30 20:37 UTC, MichaelBaj approved these changes

2024-10-30 20:40 UTC, iwbarker commented on docs/howto_update_bios.md
> +In the example above, the X722 firmware version is `firmware-version: 6.20 0x80004200 1.3353.0`.
this quote doesn't match the above output. I think you used the dmesg dump but quoted the ethtool output?

2024-10-30 20:43 UTC, iwbarker commented on docs/howto_update_bios.md
> +In the example above, the X722 firmware version is `firmware-version: 6.20 0x80004200 1.3353.0`.
can probably just say:
In the example above, the X722 firmware version is 6.20

2024-10-30 20:47 UTC, iwbarker commented on docs/howto_update_bios.md
> +```
maybe add: The last 3 digits are the BIOS version, e.g. 4.08 in this example.

2024-10-31 13:13 UTC, iwbarker submitted a review, later dismissed

2024-10-31 13:14 UTC, MichaelBaj approved these changes

2024-10-31 13:44 UTC, jeffmart-jnpr commented on docs/howto_update_bios.md
> +title: SSR1300 and SSR1400 BIOS Upgrade for X722
I think we should call out "Intel X722 ..." in this , the next line and on line 6 where we can say (which will be refered to X722 NIC further in the doc.)

2024-10-31 13:56 UTC, jeffmart-jnpr commented on docs/howto_update_bios.md
> +In order to fully integrate the new Intel ME firmware delivered by the BIOS, the software powers down the system after the firmware upgrade, and the user must manually power the system back up.
I would capitalize the word "MUST" in the user MUST ... Also this should be changed, to the following:

The power cables NUST be removed for 30 seconds, then power connected back up and system turned on. (This is how I understood this was supposed to work).

2024-10-31 14:34 UTC, Chr1st0ph3rTurn3r commented on docs/howto_update_bios.md
> +In order to fully integrate the new Intel ME firmware delivered by the BIOS, the software powers down the system after the firmware upgrade, and the user must manually power the system back up.
I will capitalize must. The full process is covered in step 3 of the Upgrading the BIOS and X722 Firmware procedure.

2024-10-31 14:41 UTC, jeffmart-jnpr commented on docs/howto_update_bios.md
> +Although the update procedure can be initiated remotely over ssh, personnel must be available **ON SITE** to perform the mandatory post-update power cycle.
Can we link to the "manditory post-update power cycle" section.

2024-10-31 14:42 UTC, jeffmart-jnpr commented on docs/howto_update_bios.md
> +- Personnel available on site to perform power cycle
update with:

"post-update power cycle"

2024-10-31 14:43 UTC, jeffmart-jnpr commented on docs/howto_update_bios.md
> +In this example, the BIOS version of the SSR1300 is `4.08`.
Where did this "4.08" number come from?

Current shipping is 4.05, and the upgrade installs 4.09

2024-10-31 14:45 UTC, jeffmart-jnpr commented on docs/howto_update_bios.md
> +[    5.373011] i40e 0000:6a:00.0: fw 5.6.74624 api 1.12 nvm 6.20 0x80004200 1.3353.0
This is the firmware that the system will be updated to with the BIOS update, is this expected to provide the details of the old firmware that does not support LLDP? If yes we should have the old version here and the new version after the update.

2024-10-31 14:53 UTC, jeffmart-jnpr commented on docs/howto_update_bios.md
> +[root@PERF-SSR1300-AR49230058 t128]# ethtool -i xe-0-0
Same as previous section, we should be pointing to the version that is the intent of the section this is for. If after the upgrade then the below information. If before the upgrade

2024-10-31 14:56 UTC, migolnikov approved these changes

2024-10-31 14:58 UTC, jeffmart-jnpr commented on docs/howto_update_bios.md
> +[root@PERF-SSR1300-AR49230058 t128]# ethtool -i xe-0-0
This is the output of the shipping version today:

# ethtool -i xe-0-0
driver: i40e
version: 2.16.11
firmware-version: 3.31 0x80000d00 1.1766.0
expansion-rom-version: 
bus-info: 0000:6a:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2024-10-31 14:59 UTC, jeffmart-jnpr commented on docs/howto_update_bios.md
> +[t128@PERF-SSR1300-AR49230058 ~]$ lspci | grep X722
Please remove the host details, aka:

"t128@PERF-SSR1300-AR49230058"

2024-10-31 15:00 UTC, jeffmart-jnpr commented on docs/howto_update_bios.md
> +[root@as43220096]# /usr/libexec/update_bios.sh
Please remove the host details from this line (and others like it:

aka: "[root@as43220096]"

2024-10-31 15:01 UTC, jeffmart-jnpr requested changes
Additional comments added with details to replace them with.

2024-10-31 15:13 UTC, jeffmart-jnpr commented on docs/howto_update_bios.md
> +$ dmidecode -s bios-version
Use this instead, this is the current shipping version:

# dmidecode -s bios-version
SSR1300V405


And this is the updated version:

# dmidecode -s bios-version
SSR1300V409

and if this is on the SSR1400 it would be

SSR1400V405 or SSR1400V409

2024-10-31 15:56 UTC, MichaelBaj approved these changes

2024-10-31 16:15 UTC, jeffmart-jnpr approved these changes

2024-10-31 17:47 UTC, merged