Create a KB for the salt grain issue
128technology/docs pull request #792
Opened 2024-11-06 21:51 UTC by agrawalkaushik

2024-11-06 22:14 UTC, jamesesilvia commented on kb/2024-11-06-PLUGIN-2776.md
> +tags: ['salt-stack, sip-alg']
oneword saltstack unless its tagged in other KBs this way

2024-11-06 22:21 UTC, jamesesilvia commented on kb/2024-11-06-PLUGIN-2776.md
> +Salt states can potentially fail to apply on certain routers post upgrade to 5.6.16, 6.1.12 or above
Salt states that rely on `CentOS` name to detect or conditionally perform operations on SSR hosts will be impacted.

2024-11-06 22:23 UTC, jamesesilvia commented on kb/2024-11-06-PLUGIN-2776.md
> +Salt states can potentially fail to apply on certain routers post upgrade to 5.6.16, 6.1.12 or above
sample for top.sls that would be impacted

````
base:
  '*':
    - dummy

  'os:CentOS':
    - match: grain
 ```

2024-11-07 07:33 UTC, MichaelBaj requested changes

2024-11-07 07:33 UTC, MichaelBaj commented on kb/2024-11-06-PLUGIN-2776.md
> +**Introduced in SSR Version:** 5.6.16, 6.1.12
Won't this be an issue with 6.2 versions as well? Perhaps when 6.2.8 is released? Should this document be updated at that time?

2024-11-07 07:33 UTC, MichaelBaj commented on kb/2024-11-06-PLUGIN-2776.md
> +SSR is migrating its underlying Linux distribution in an effort to remain agile and to reduce the surface area of CVEs. This change has an impact on certain packages that have an OS dependency such a
Per Jame's comment earlier, should "salt stack" be "saltstack"?

2024-11-07 07:33 UTC, MichaelBaj commented on kb/2024-11-06-PLUGIN-2776.md
> +Similar to custom salt states, the SIP ALG plugin was also leveraging the same feature. Any version of the 128T-sip-alg plugin 4.0.1 or below will face this issue when the router is upgraded to 5.6.1
Reworded paragraph:

Version 4.0.1 or earlier of the 128T-SIP-ALG plugin is impacted by this issue once the router is upgraded to 5.6.16+ or 6.1.12+. In order to address this issue with the SIP ALG plugin, the plugin must first be upgraded to 4.0.2 prior to the upgrade.

Similar to the SIP ALG plugin, custom salt states may also be impacted in the same way. Please see the [workaround](#workaround) section for steps to identify if your environment is impacted.

2024-11-07 07:33 UTC, MichaelBaj commented on kb/2024-11-06-PLUGIN-2776.md
> +TBD
12T-SIP-ALG-4.0.2 ???

2024-11-07 07:33 UTC, MichaelBaj commented on kb/2024-11-06-PLUGIN-2776.md
> +SSR
SSR conductor, right?

2024-11-07 07:33 UTC, MichaelBaj commented on kb/2024-11-06-PLUGIN-2776.md
> +For customer that implement custom salt states, they should follow the procedure below to scan their salt states to identify any potential problems they could run into during upgrades.
(There should be a paragraph prior section that talks about what custom salt states are and how to identify if a customer has them. Keep in mind, a network operator may be taking over support of an environment and is not familiar with all of the specifics.)

For customers that implement custom salt states, follow the procedure below to scan all salt states to identify any potential problems they could run into during upgrades.

2024-11-07 07:33 UTC, MichaelBaj commented on kb/2024-11-06-PLUGIN-2776.md
> +1. Scan the custom salt states for Centos 7 by doing `grep -riE 'cent[-]?os' /srv/salt`
"by doing" = "by running ..."

There should be a step 1 prior that states that the user must first login to the conductor CLI with the admin user and then drop to the Linux shell.

2024-11-07 07:33 UTC, MichaelBaj commented on kb/2024-11-06-PLUGIN-2776.md
> +:::note
::: warn
There exists a possibility that a custom salt state is impacted despite the scan returning an empty result. In this case, please contact your Juniper support representative for support on the matter.
:::

(If this happens, we need to update this KB article to close this gap in the workaround section.

2024-11-07 07:33 UTC, MichaelBaj commented on kb/2024-11-06-PLUGIN-2776.md
> +3. If the above command results in hits, please remediate the salt states to be OS agnostic. Here's an example of one possible remediation stragety. Please note, the exact changes would depend on the
3. If the above command results in non-empty output, please remediate the salt states to be OS agnostic. Please note, the exact changes depend on the business logic of the salt state and customers should work with their subject matter experts to properly remediate and test their changes.

#### Example Remediation

2024-11-07 07:33 UTC, MichaelBaj commented on kb/2024-11-06-PLUGIN-2776.md
> +The remediated version look as follows in this instance
Remediated salt state

2024-11-07 07:33 UTC, MichaelBaj commented
How did you make this PR a draft?

2024-11-07 21:08 UTC, MichaelBaj requested changes

2024-11-07 21:08 UTC, MichaelBaj commented on kb/2024-11-06-PLUGIN-2776.md
> +**Salt states are derived from ancient deposits of Himalayan Sea Salt found in the mountains of Tibet. They represent intricate rituals performed by ones and zeros to duplicate the formation of the s
Is that where they come from? No wonder why they are so valuable...

2024-11-07 22:07 UTC, agrawalkaushik commented
> How did you make this PR a draft?

Purely based on this comment
> Kaushik, a draft will have to be put forth to Chris for him to wordsmith

2024-11-13 14:07 UTC, ecarson commented on kb/2024-11-06-PLUGIN-2776.md
> +**Introduced in SSR Version:** 5.6.16, 6.1.12
6.3.3-r2 also (or whatever 6.3.x-r2 is released as).

2024-11-13 14:10 UTC, agrawalkaushik commented on kb/2024-11-06-PLUGIN-2776.md
> +SSR
no since the salt states run on the routers - it will actually impact the routers not the conductor.

2024-11-13 14:11 UTC, agrawalkaushik commented on kb/2024-11-06-PLUGIN-2776.md
> +TBD
```suggestion
128T-sip-alg-4.0.2
```

2024-11-13 14:12 UTC, ecarson submitted a review, later dismissed

2024-11-13 15:18 UTC, Chr1st0ph3rTurn3r approved these changes

2024-11-13 16:57 UTC, MichaelBaj approved these changes

2024-11-13 17:01 UTC, jamesesilvia approved these changes

2024-11-14 14:19 UTC, merged