Add instructions on IP config for UISO
128technology/docs pull request #799
Opened 2024-12-05 20:58 UTC by agrawalkaushik

2024-12-06 13:40 UTC, MichaelBaj commented on docs/initialize_u-iso_adv_workflow.md
> +For non console access you can connect your laptop or other device to any of the designated LAN port and connect to 192.168.128.1 to connect to SSR PCLI and/or shell.
The other document specifies connecting to http://192.168.128.1. Should this be the same?

2024-12-06 13:42 UTC, MichaelBaj requested changes

2024-12-06 13:42 UTC, MichaelBaj commented on docs/initialize_u-iso_device.md
> +As a first step, connect your laptop or other device to any of the designated LAN port and connect to http://192.168.128.1 to connect to SSR onboarding UI
you will have to add the directives:

<!-- markdown-link-check-disable -->
<!-- markdown-link-check-enable -->

Around this line as the broken link checker is going to try to validate http://192.168.128.1.

You received the following build error:
[✖] http://192.168.128.1/ → Status: 0 Error: ETIMED

2024-12-06 18:40 UTC, agrawalkaushik commented on docs/initialize_u-iso_adv_workflow.md
> +For non console access you can connect your laptop or other device to any of the designated LAN port and connect to 192.168.128.1 to connect to SSR PCLI and/or shell.
The other document is for web but this one is for PCLI and API based workflow.

2024-12-06 18:41 UTC, agrawalkaushik commented on docs/initialize_u-iso_device.md
> +As a first step, connect your laptop or other device to any of the designated LAN port and connect to http://192.168.128.1 to connect to SSR onboarding UI
bummer - I was hoping to keep it a hyperlink. Is there a special directive for this to allow both i.e. skip the check but keep it a hyperlink?

2024-12-06 18:43 UTC, MichaelBaj commented on docs/initialize_u-iso_adv_workflow.md
> +For non console access you can connect your laptop or other device to any of the designated LAN port and connect to 192.168.128.1 to connect to SSR PCLI and/or shell.
Perhaps change the wording then to state SSH to 192.168.128.1 to be more explicit?

2024-12-06 18:44 UTC, MichaelBaj commented on docs/initialize_u-iso_device.md
> +As a first step, connect your laptop or other device to any of the designated LAN port and connect to http://192.168.128.1 to connect to SSR onboarding UI
Adding the directives (which were removed from the comments....) will preserve the hyperlink,

2024-12-06 18:51 UTC, agrawalkaushik commented on docs/initialize_u-iso_device.md
> +As a first step, connect your laptop or other device to any of the designated LAN port and connect to http://192.168.128.1 to connect to SSR onboarding UI
Thanks - I was able to see it now!

2024-12-06 18:51 UTC, agrawalkaushik commented on docs/initialize_u-iso_adv_workflow.md
> +For non console access you can connect your laptop or other device to any of the designated LAN port and connect to 192.168.128.1 to connect to SSR PCLI and/or shell.
the same address can be used for API calls to FWIW but I'll add some language to be clear.

2024-12-06 19:00 UTC, MichaelBaj approved these changes

2024-12-06 19:30 UTC, Chr1st0ph3rTurn3r requested changes

2024-12-06 19:30 UTC, Chr1st0ph3rTurn3r commented on docs/initialize_u-iso_device.md
> +As a first step, connect your laptop or other device to any of the designated LAN port and connect to https://192.168.128.1 to access the SSR onboarding UI
```suggestion
As a first step, connect your laptop or other device to any of the designated LAN ports and connect to https://192.168.128.1 to access the SSR onboarding UI.
```

2024-12-06 19:30 UTC, Chr1st0ph3rTurn3r commented on docs/initialize_u-iso_device.md
> +The laptop or other client device must be assigned a static IP address within the range of `192.168.128.2` to `192.168.128.254` along with a subnet mask of `/24` or `255.255.255.0`
```suggestion
The laptop or other client device must be assigned a static IP address within the range of `192.168.128.2` to `192.168.128.254` along with a subnet mask of `/24` or `255.255.255.0`.
```

2024-12-18 21:13 UTC, Chr1st0ph3rTurn3r approved these changes

2024-12-19 16:17 UTC, merged