6.3.3 r1 release docs
128technology/docs pull request #800
Opened 2024-12-06 18:36 UTC by Chr1st0ph3rTurn3r

2024-12-06 20:11 UTC, MichaelBaj requested changes

2024-12-06 20:11 UTC, MichaelBaj commented on docs/release_notes_128t_6.3.md
> +- **I95-57471 Allow Radius configuration per router:** Radius servers can now be configured at the router level. The servers can continue to be configured at the Authority level. If configured in bot
"the combination of both configured servers will be used."
I don't believe this is an accurate statement. I believe this has to do with order of precedence.
If a radius server is configured at the authority, but not the router, then the authority value will be used. If it is configured at the authority and the router, the router value will be used.

2024-12-17 14:14 UTC, jamesesilvia commented on docs/sec-config-antivirus.md
> +SSR Anti-Virus uses the Sophos anti-virus engine and includes a self signing certificate for simplified, secure connection. Similar to IDP, Anti-Virus is configurable directly on the hub and spokes o
We support spoke-side DPI / IDP / AV only. Hub didn't make it in time

2024-12-17 14:15 UTC, jamesesilvia commented on docs/sec-config-antivirus.md
> +            anti-virus-profile          custom-profile
missing a top-level item here in config snippet

```
anti-virus-profile  custom-profile
    name custom-profile
    url-allowlist ...
exit
```

2024-12-17 14:17 UTC, jamesesilvia commented on docs/sec-config-antivirus.md
> +- Anti-virus server is down: An alarm is triggered and an error logged.
capitalizing `virus` was done throughout but not here; nit for consistency

2024-12-17 17:02 UTC, MichaelBaj requested changes

2024-12-17 19:40 UTC, eleung128 commented on docs/sec-disable-console-output.md
> +2. Use the following config example to configure `serial-console-enabled false`.
May want to mention that `serial-console-enabled` only show in advanced user mode.

2024-12-17 20:28 UTC, migolnikov requested changes

2024-12-17 20:28 UTC, migolnikov commented on docs/sec-disable-console-output.md
> +After disabling the serial console output (setting to `false`), the setting **will** perpetuate after an upgrade, but the router must be restarted after the upgrade to maintain the `false` setting.
I am not sure what this means for "false:". From my understanding this feature is not dynamically reconfigurable whether it is turned on or off, so in all cases it required a reboot. @eleung128 please confirm

2024-12-17 20:33 UTC, migolnikov commented on docs/sec-disable-console-output.md
> +After disabling the serial console output (setting to `false`), the setting **will** perpetuate after an upgrade, but the router must be restarted after the upgrade to maintain the `false` setting.
We should also discuss that this does not apply to system startup. Console gets turned off once kernel starts up, so it is still available for both input and output during bootup.

2024-12-17 20:38 UTC, migolnikov commented on docs/sec-usb-security.md
> +This document provides guidance on disabling USB booting and storage in the SSR BIOS, and disabling USB storage in the Operating System.
I see the instructions below for BIOS changes, but I do not see them for disabling " disabling USB storage in the Operating System." via the config.

2024-12-18 21:42 UTC, Chr1st0ph3rTurn3r commented on docs/sec-disable-console-output.md
> +After disabling the serial console output (setting to `false`), the setting **will** perpetuate after an upgrade, but the router must be restarted after the upgrade to maintain the `false` setting.
@migolnikov  Max, I'm going to need a little more info on this - I'm  not quite clear on what you mean.

2024-12-20 19:16 UTC, MichaelBaj commented on docs/sec-disable-console-output.md
> +:::note
This note appears twice in this document.

2024-12-20 19:37 UTC, Chr1st0ph3rTurn3r commented on docs/sec-disable-console-output.md
> +:::note
That is intentional, once in the cli instructions and once in the GUI instructions. Just in case they don't see it in the section they are not using.

2025-01-07 21:49 UTC, MichaelBaj submitted a review, later dismissed

2025-01-08 17:05 UTC, jamesesilvia commented on docs/release_notes_128t_6.3.md
> +## Release 6.3.3-36r2
do we usualyl include the release number? i think its 40 now

2025-01-08 17:05 UTC, jamesesilvia commented on docs/sec-config-antivirus.md
> +The SSR provides Anti-Virus protection on spoke and hub devices, and is configurable on a per-application basis. SSR Anti-Virus runs with or without IDP configuration, reports metrics to the User Int
spoke* devices. Hube support didnt make 6.3.3 R2

2025-01-09 17:07 UTC, jamesesilvia approved these changes

2025-01-09 19:46 UTC, MichaelBaj requested changes

2025-01-09 19:46 UTC, MichaelBaj commented on docs/release_notes_128t_6.3.md
> +- **I95-58539 The `validate` command does not check or test for router `applies-to` config:** Resolved an issue where the DHCP relay inspector rule that validates whether an interface is not being us
possible better rephrasing:

- **I95-58539 The `validate` command does not check or test for router `applies-to` config:** Resolved an issue whereby the DHCP relay inspector rule was not honoring router-based services for interfaces without DHCP relay. Errors from this rule are now warnings.

2025-01-09 19:46 UTC, MichaelBaj commented on docs/release_notes_128t_6.3.md
> +- **I95-59146 BGP confederation member-as modify path incorrect:** Resolved an issue where modifications to `bgp confederation member-as` were not comparing and validating the changes correctly.
- **I95-59146 BGP confederation member-as not dynamically reconfigurable:** Resolved an issue where modifications to `bgp confederation member-as` were not comparing and validating the changes correctly.

2025-01-09 20:22 UTC, MichaelBaj approved these changes

2025-01-10 00:24 UTC, migolnikov approved these changes

2025-01-10 00:24 UTC, merged