Add a KB article for deprecating certain weak ipsec ciphers
128technology/docs pull request #802
Opened 2024-12-12 22:39 UTC by agrawalkaushik

2024-12-13 15:12 UTC, agrawalkaushik commented on kb/2024-12-12-PLUGIN-2835.md
> +1. While running the existing plugin version, replace the weak cipher with a stronger one from the supported list. **(where can they find the list?)**
> **(where can they find the list?)**

The list is visible in config UI and PCLI. There are a couple of different config elements - one for IKE and one for IPsec. Do you think just listing the config path is sufficient?

2024-12-13 15:12 UTC, agrawalkaushik commented on kb/2024-12-12-PLUGIN-2835.md
> + - Restart the **service/SSR/tunnels??**
The restart will happen automatically as part of the config change.

2024-12-18 16:44 UTC, MichaelBaj requested changes

2024-12-18 16:44 UTC, MichaelBaj commented on kb/2024-12-12-PLUGIN-2835.md
> +1. While running the existing plugin version, replace the weak cipher with a stronger one from the supported list. **(where can they find the list?)**
"**(where can they find the list?)**" needs to be addressed.

2024-12-18 16:58 UTC, MichaelBaj approved these changes

2024-12-18 21:17 UTC, Chr1st0ph3rTurn3r approved these changes

2024-12-18 22:41 UTC, merged